import type { CategoryQuestion } from "./categoriesAgrupment";

export const peliculas: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/9IYyCLf5NNAQFK9pNtqzEU9HWzM.jpg", answer: "Brazil" },
    { image: "https://image.tmdb.org/t/p/original/ApB0mF2d5Oqioi3yxjuogiotSLI.jpg", answer: "Eraserhead" },
    { image: "https://image.tmdb.org/t/p/original/vhu2Nscn4HTi5gwYBRXU3OJqVCo.jpg", answer: "Christiane F." },
    { image: "https://image.tmdb.org/t/p/original/3Na31ta8vDuKOgQuPLdSZLs8bCB.jpg", answer: "Come and See" },
    { image: "https://image.tmdb.org/t/p/original/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg", answer: "The Notebook" },
    { image: "https://image.tmdb.org/t/p/original/gTghF8ardwJ48XLHkiapWk3ZmSo.jpg", answer: "Snatch" },
    { image: "https://image.tmdb.org/t/p/original/ow2boWFZWza7D4qDvJohg9GJVoH.jpg", answer: "Thirteen" },
    { image: "https://image.tmdb.org/t/p/original/t3HVA7XdVnQneMjI5hYjEhXmHY3.jpg", answer: "Matilda" },
    { image: "https://image.tmdb.org/t/p/original/75UPGUm2Zm6M60szq1gQisDF4g.jpg", answer: "The Butterfly Effect" },
    { image: "https://image.tmdb.org/t/p/original/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg", answer: "The Hangover" },
    { image: "https://image.tmdb.org/t/p/original/qA2TyqPldTtoTVY3LKrNIG5g6bH.jpg", answer: "Before Sunrise" },
    { image: "https://image.tmdb.org/t/p/original/tcZi0LQc5iu2u6i5aOWyj9NBBvl.jpg", answer: "Before Sunset" },
    { image: "https://image.tmdb.org/t/p/original/m5dA4JZsj78EBTa2D6imWOAebwB.jpg", answer: "Scary Movie" },
    { image: "https://image.tmdb.org/t/p/original/cjSB3ZjaMpaa9oHFyeYha3KG0mp.jpg", answer: "Scary Movie 2" },
    { image: "https://image.tmdb.org/t/p/original/q8GwhIAttJwqmjDtbLW8JvEMMdw.jpg", answer: "Punch-Drunk Love" },
    { image: "https://image.tmdb.org/t/p/original/atoIgfAk2Ig2HFJLD0VUnjiPWEz.jpg", answer: "Charlie and the Chocolate Factory" },
    { image: "https://image.tmdb.org/t/p/original/hi3lxLd93iKwCmVAfhMV9m1k2jr.jpg", answer: "The Machinist" },
    { image: "https://image.tmdb.org/t/p/original/x903dx8Km6XNLFEmvbXc98vePSV.jpg", answer: "Yi Yi" },
    { image: "https://image.tmdb.org/t/p/original/dF6GNQ0TnZkr1t4wBt36Xc0Pccd.jpg", answer: "Hostel" },
    { image: "https://image.tmdb.org/t/p/original/ckTh7Ej33m9O4eiKDQ1u91Opd9N.jpg", answer: "Leaving Las Vegas" },
    { image: "https://image.tmdb.org/t/p/original/tEhvOU8nJp4v9goYwrJTASJJD3C.jpg", answer: "The Piano Teacher" },
    { image: "https://image.tmdb.org/t/p/original/s9Bn7Mx4U9cWOR1WdFZjU1DTAkh.jpg", answer: "Zathura: A Space Adventure" },
    { image: "https://image.tmdb.org/t/p/original/vxvzf0cGtFY2Vpw5ULWumCIW6Ri.jpg", answer: "Dancer in the Dark" },
    { image: "https://image.tmdb.org/t/p/original/tgRQsrjBKdic7llxhI7pqLJb8kS.jpg", answer: "Rounders" },
    { image: "https://image.tmdb.org/t/p/original/yCtgdv7TfgZLHj6R9IQKD5TjljP.jpg", answer: "The Celebration" },
    { image: "https://image.tmdb.org/t/p/original/qJaR9AZx2Qq2oJ3krnSO0Z5ne5I.jpg", answer: "Fear and Loathing in Las Vegas" },
    { image: "https://image.tmdb.org/t/p/original/nY2faCdUVHzuH6FmDI6QsAURE68.jpg", answer: "Breaking the Waves" },
    { image: "https://image.tmdb.org/t/p/original/qQNGhBijPIBlFkGwjtQk6sflml9.jpg", answer: "The Adventures of Sharkboy and Lavagirl" },
    { image: "https://image.tmdb.org/t/p/original/6qHI1IYj7QlLSCwHRzkL62X175s.jpg", answer: "American History X" },
    { image: "https://image.tmdb.org/t/p/original/yvPbncYhMu9FfTjDhq0N5lgnVkO.jpg", answer: "10 Things I Hate About You" },
    { image: "https://image.tmdb.org/t/p/original/amGU1FpELmenVvNmPShW58Orepy.jpg", answer: "Twin Peaks: Fire Walk with Me" },
    { image: "https://image.tmdb.org/t/p/original/msCHK5Kh1YbdZ0zPJ2nzPUhhSN9.jpg", answer: "Donnie Darko" },
    { image: "https://image.tmdb.org/t/p/original/iTkxwBriD9YKg4Q35qWEIlLXd6e.jpg", answer: "Amores Perros" },
    { image: "https://image.tmdb.org/t/p/original/aM6E4DBP6588q3tEr9hz41ls80q.jpg", answer: "The Perks of Being a Wallflower" },
    { image: "https://image.tmdb.org/t/p/original/s0OrExdg7i3RLR7oqzHRk4q2kL4.jpg", answer: "Birdman or (The Unexpected Virtue of Ignorance)" },
    { image: "https://image.tmdb.org/t/p/original/vyrCniZsrXZAW08eECKIp1BMLPh.jpg", answer: "Crazy, Stupid, Love." },
    { image: "https://image.tmdb.org/t/p/original/cUqXHZtnptgvyAE1hN47Wsf3ami.jpg", answer: "Project X" },
    { image: "https://image.tmdb.org/t/p/original/rgNzvSagnlc32TuMEBa529QFIig.jpg", answer: "Chronicle" },
    { image: "https://image.tmdb.org/t/p/original/cvGE73s935bXEAVt2W0zADPPegG.jpg", answer: "Coherence" },
    { image: "https://image.tmdb.org/t/p/original/aPSGg0ZGirS0sSxGlwTGTAo0ruV.jpg", answer: "Before Midnight" },
    { image: "https://image.tmdb.org/t/p/original/3WK7p9EdZmmvB1IbB2Vw9Rf4lXH.jpg", answer: "Me Before You" },
    { image: "https://image.tmdb.org/t/p/original/3tkDMNfM2YuIAJlvGO6rfIzAnfG.jpg", answer: "The Platform" },
    { image: "https://image.tmdb.org/t/p/original/qVGpxnjrGlHaSTCqTQI6viBDSfp.jpg", answer: "It" },
    { image: "https://image.tmdb.org/t/p/original/hkAVgWvAMmM8tj9CDEvGqMdNQBE.jpg", answer: "Ted" },
    { image: "https://image.tmdb.org/t/p/original/6UFnKzVzFqKDjs4iCVLJdneK3ch.jpg", answer: "Pixels" },
    { image: "https://image.tmdb.org/t/p/original/ivJ5UzT6IzucLVfbZwCCwiJJoBz.jpg", answer: "Portrait of a Lady on Fire" },
    { image: "https://image.tmdb.org/t/p/original/6CLNOzMXO9bvapDD8gsdwkJU4wN.jpg", answer: "Godzilla" },
    { image: "https://image.tmdb.org/t/p/original/wWqTMWkEw6HouLd1zPZbZWxtAPr.jpg", answer: "Godzilla vs. Kong" },
    { image: "https://image.tmdb.org/t/p/original/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg", answer: "Avengers: Age of Ultron" },
    { image: "https://image.tmdb.org/t/p/original/9WoLTsRgrupkvCgs3bhsl2EjLhs.jpg", answer: "Zack Snyder's Justice League" },
    { image: "https://image.tmdb.org/t/p/original/eHaazLxM5LRMh0ySkVy7SK6wUWt.jpg", answer: "The Hunger Games: Catching Fire" },
    { image: "https://image.tmdb.org/t/p/original/lV1P1Q5gLDXVG1ZYCxZHStkcQC3.jpg", answer: "The Hunger Games: Mockingjay - Part 1" },
    { image: "https://image.tmdb.org/t/p/original/qVgLMRVNB5bHU0inmRa0ueShacN.jpg", answer: "The Hunger Games: Mockingjay - Part 2" },
    { image: "https://image.tmdb.org/t/p/original/cwytQHRHSrMnsSEowcY4Z6jIEeb.jpg", answer: "Inherent Vice" },
    { image: "https://image.tmdb.org/t/p/original/einbto9qLXFx9QXxEHylaxDbKPx.jpg", answer: "About Time" },
    { image: "https://image.tmdb.org/t/p/original/qzrS5ShZZPsPdhM5ZbcQKG7fwFo.jpg", answer: "Melancholia" },
    { image: "https://image.tmdb.org/t/p/original/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg", answer: "Cruella" },
    { image: "https://image.tmdb.org/t/p/original/nAxGnGHOsfzufThz20zgmRwKur3.jpg", answer: "Sinners" },
    { image: "https://image.tmdb.org/t/p/original/u5NWHVhZ6HWc1fXnqn82cMar5St.jpg", answer: "Train Dreams" },
    { image: "https://image.tmdb.org/t/p/original/dDYpjrwh1wNVQk0rEpc9P81wQt4.jpg", answer: "A Star Is Born" },
    { image: "https://image.tmdb.org/t/p/original/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg", answer: "Backrooms" },
    { image: "https://image.tmdb.org/t/p/original/aKPCZwkSZy2ASLo0QKeYmcoplfA.jpg", answer: "Game Night" },
    { image: "https://image.tmdb.org/t/p/original/w7Z4BVMin49voNN61IUWyN9DopV.jpg", answer: "Amour" },
    { image: "https://image.tmdb.org/t/p/original/b7t3r39Oll5qPxBKzLZ8eHMBD7l.jpg", answer: "Digger" },
    { image: "https://image.tmdb.org/t/p/original/oUVd42KgJWW6YnZLfzI7SDTdcPL.jpg", answer: "Frances Ha" },
    { image: "https://image.tmdb.org/t/p/original/ikpwuaK0yzNhXO24OeB7cKulhZE.jpg", answer: "Pinocchio" },
    { image: "https://image.tmdb.org/t/p/original/yGgEg4yimYQJLZrZg3Qhogp2raQ.jpg", answer: "Lady and the Tramp" },
    { image: "https://image.tmdb.org/t/p/original/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg", answer: "Toy Story" },
    { image: "https://image.tmdb.org/t/p/original/vABOhCPfvm1g0cKNzQXwK8EyQ5z.jpg", answer: "Cars" },
    { image: "https://image.tmdb.org/t/p/original/robYRZk9LxJTwD7GlZCginji5k.jpg", answer: "Cars 2" },
    { image: "https://image.tmdb.org/t/p/original/4mlS1MitcOqdPLhxEFyk9Qwf5rr.jpg", answer: "Cars 3" },
    { image: "https://image.tmdb.org/t/p/original/hGGC9gKo7CFE3fW07RA587e5kol.jpg", answer: "Up" },
    { image: "https://image.tmdb.org/t/p/original/nYs4ZwnJBK4AgljhvzwNz7fpr3E.jpg", answer: "WALL·E" },
    { image: "https://image.tmdb.org/t/p/original/AsWuvFnzgmG6kZMIpJO7HZpvYRB.jpg", answer: "Meet the Robinsons" },
    { image: "https://image.tmdb.org/t/p/original/reK7SgAFlyxg3s9R7neh6M970kh.jpg", answer: "Over the Hedge" },
    { image: "https://image.tmdb.org/t/p/original/doNIj6jX27hhfcbD6GEb22ydLSF.jpg", answer: "Cloudy with a Chance of Meatballs" },
    { image: "https://image.tmdb.org/t/p/original/zWqxBc6pdSIjklqWfZ70l5ce28P.jpg", answer: "Bolt" },
    { image: "https://image.tmdb.org/t/p/original/h5Bwxe6dTVFtAFkybkd1EAB4yUW.jpg", answer: "Chicken Little" },
    { image: "https://image.tmdb.org/t/p/original/7xQk3HdCvkNmk3gblDGn9fVnbsT.jpg", answer: "Flushed Away" },
    { image: "https://image.tmdb.org/t/p/original/8ln5VUVk7gnNGIb2VNgw8nICDVt.jpg", answer: "The Simpsons Movie" },
    { image: "https://image.tmdb.org/t/p/original/xRxSLhhjPG2D8l0BXi0KdN4IvPt.jpg", answer: "Fantastic Mr. Fox" },
    { image: "https://image.tmdb.org/t/p/original/8UxYHvKBNFnoyfHjgjMwzj4zOuy.jpg", answer: "Mary and Max" },
    { image: "https://image.tmdb.org/t/p/original/irpJXGiVr539uuspcQcNdkhS2lq.jpg", answer: "Megamind" },
    { image: "https://image.tmdb.org/t/p/original/2XSeKDmIa2KxaiJy4J9e8FrIZhk.jpg", answer: "Despicable Me" },
    { image: "https://image.tmdb.org/t/p/original/c5MCkebYhFuhmi32x760HfcvLIO.jpg", answer: "Puss in Boots" },
    { image: "https://image.tmdb.org/t/p/original/3vxlXdwBKztOJdgiZ2Qwasl9FY4.jpg", answer: "Rio" },
    { image: "https://image.tmdb.org/t/p/original/qx9ts2hBYJrkIQxhryitxnLlm2u.jpg", answer: "Brave" },
    { image: "https://image.tmdb.org/t/p/original/9UZnCIeUVHzZQLDXN7lht2T4ndB.jpg", answer: "The Pirates! In an Adventure with Scientists!" },
    { image: "https://image.tmdb.org/t/p/original/5rARlA8beRAVXPYzSaF2NoS8Ry5.jpg", answer: "Hotel Transylvania" },
    { image: "https://image.tmdb.org/t/p/original/3dLjNqylxtfgKelBJse5OWqhggf.jpg", answer: "Rise of the Guardians" },
    { image: "https://image.tmdb.org/t/p/original/rA9QYI7yTV2F2AvaqBcq1vL3MOr.jpg", answer: "It's Such a Beautiful Day" },
    { image: "https://image.tmdb.org/t/p/original/3qfiZd8ETMk9MQsmhbOB5QAAx0l.jpg", answer: "Turbo" },
    { image: "https://image.tmdb.org/t/p/original/b6usdEMEOX5pcVpXrS32z0NOwGc.jpg", answer: "Underdogs" },
    { image: "https://image.tmdb.org/t/p/original/6gI1dAkOaUQ6659OdRPsTLlsem5.jpg", answer: "The Lego Movie" },
    { image: "https://image.tmdb.org/t/p/original/An1FS6Baec7uogTcQyEYqruYAtM.jpg", answer: "Regular Show: The Movie" },
    { image: "https://image.tmdb.org/t/p/original/9tOkjBEiiGcaClgJFtwocStZvIT.jpg", answer: "Zootopia" },
    { image: "https://image.tmdb.org/t/p/original/c1Ywtvlqls6tPBZ3BqbPtBwHyng.jpg", answer: "The Secret Life of Pets" },
    { image: "https://image.tmdb.org/t/p/original/5ceIqlRzWH4x1IPU9OfjXHO2Kz6.jpg", answer: "Captain Underpants: The First Epic Movie" },
    { image: "https://image.tmdb.org/t/p/original/goMGTcitprGu7YD6VZS4lUUwzRA.jpg", answer: "Isle of Dogs" },
    { image: "https://image.tmdb.org/t/p/original/5lWIYxYEqWi8j3ZloxXntw3ImBo.jpg", answer: "The Grinch" },
    { image: "https://image.tmdb.org/t/p/original/6FTc6G8gwawItBqGQd7sYtf6s3f.jpg", answer: "Teen Titans Go! To the Movies" },
    { image: "https://image.tmdb.org/t/p/original/6OTRuxpwUUGbmCX3MKP25dOmo59.jpg", answer: "Dragon Ball Super: Broly" },
    { image: "https://image.tmdb.org/t/p/original/felXFRjJXF40NPzK1IPib8ojF2X.jpg", answer: "Dragon Ball Z: Battle of Gods" },
    { image: "https://image.tmdb.org/t/p/original/usrUizny0dLNJTrrJSxsvu5V0z0.jpg", answer: "Dragon Ball Z: Resurrection 'F'" },
    { image: "https://image.tmdb.org/t/p/original/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg", answer: "The Super Mario Bros. Movie" },
];
