import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const actores: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/eEHCjqKMWSvQU4bmwhLMsg4RtEr.jpg", answer: "Marlon Brando" },
    { image: "https://image.tmdb.org/t/p/original/m8HAAjq1T75JypKk0v1FFQn4ysZ.jpg", answer: "Al Pacino" },
    { image: "https://image.tmdb.org/t/p/original/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg", answer: "Robert De Niro" },
    { image: "https://image.tmdb.org/t/p/original/hBHcQIEa6P48HQAlLZkh0eKSSkG.jpg", answer: "Jack Nicholson" },
    { image: "https://image.tmdb.org/t/p/original/iaf7SHSkGDpnyrDh1Jolilwk2TD.jpg", answer: "Anthony Hopkins" },
    { image: "https://image.tmdb.org/t/p/original/jPsLqiYGSofU4s6BjrxnefMfabb.jpg", answer: "Morgan Freeman" },
    { image: "https://image.tmdb.org/t/p/original/yxNGnTiou25c3zjppT5dW2eWAve.jpg", answer: "Dustin Hoffman" },
    { image: "https://image.tmdb.org/t/p/original/wN8brfOI8AjngGchkQtFqfEPam5.jpg", answer: "Gene Hackman" },
    { image: "https://image.tmdb.org/t/p/original/8TwdCfeOZH7ucRlfLZ6wObxa7cO.jpg", answer: "Clint Eastwood" },
    { image: "https://image.tmdb.org/t/p/original/bP2fByqNR7BorsUNuD6nSm0u2vJ.jpg", answer: "Paul Newman" },
    { image: "https://image.tmdb.org/t/p/original/mhHk4NRPXEJLL0SySheXZAArp5w.jpg", answer: "Steve McQueen" },
    { image: "https://image.tmdb.org/t/p/original/jam9DRhOuKomlr0vUXTamPoxPdk.jpg", answer: "James Stewart" },
    { image: "https://image.tmdb.org/t/p/original/rUaQTKw7hNcEvZyFaahIpqiiiWv.jpg", answer: "Cary Grant" },
    { image: "https://image.tmdb.org/t/p/original/2Ojm5IwpTF5qdMTjEmdBh8UZM6K.jpg", answer: "Gregory Peck" },
    { image: "https://image.tmdb.org/t/p/original/mJabHWZrjlFiF8U8Bbr8lSFtLX6.jpg", answer: "Charlton Heston" },
    { image: "https://image.tmdb.org/t/p/original/2F15qrkiDp4qhYJnXuFqINIBsHp.jpg", answer: "Peter O'Toole" },
    { image: "https://image.tmdb.org/t/p/original/hbB676mW62gjsh0f51ICYE11niG.jpg", answer: "Sean Connery" },
    { image: "https://image.tmdb.org/t/p/original/bVZRMlpjTAO2pJK6v90buFgVbSW.jpg", answer: "Michael Caine" },
    { image: "https://image.tmdb.org/t/p/original/j8yRSo6S2bnYubKZTBUvD7fuOyX.jpg", answer: "Richard Burton" },
    { image: "https://image.tmdb.org/t/p/original/kziWbtgEJB0dFZA6kPyzoaYEyQ5.jpg", answer: "Laurence Olivier" },
    { image: "https://image.tmdb.org/t/p/original/mkdRcVIQl4WZhDf1vXKWTD7HZrZ.jpg", answer: "Leonardo DiCaprio" },
    { image: "https://image.tmdb.org/t/p/original/oFvZoKI6lvU03n4YoNGAll9rkas.jpg", answer: "Tom Hanks" },
    { image: "https://image.tmdb.org/t/p/original/m09Y1YfPPeNYYUSHnnVqahkrC1o.jpg", answer: "Brad Pitt" },
    { image: "https://image.tmdb.org/t/p/original/k2xt6EUxQDwYRKIyI4IBdZxfs8n.jpg", answer: "Johnny Depp" },
    { image: "https://image.tmdb.org/t/p/original/7Pxez9J8fuPd2Mn9kex13YALrCQ.jpg", answer: "Christian Bale" },
    { image: "https://image.tmdb.org/t/p/original/aCvBXTAR9B1qRjIRzMBYhhbm1fR.jpg", answer: "Matt Damon" },
    { image: "https://image.tmdb.org/t/p/original/aTcqu8cI4wMohU17xTdqmXKTGrw.jpg", answer: "Ben Affleck" },
    { image: "https://image.tmdb.org/t/p/original/8RZLOyYGsoRe9p44q3xin9QkMHv.jpg", answer: "Keanu Reeves" },
    { image: "https://image.tmdb.org/t/p/original/u38k3hQBDwNX0VA22aQceDp9Iyv.jpg", answer: "Joaquin Phoenix" },
    { image: "https://image.tmdb.org/t/p/original/3mShHjSQR7NXOVbdTu5rT2Qd0MN.jpg", answer: "Tom Cruise" },
    { image: "https://image.tmdb.org/t/p/original/8TlKqbXYgHmmaEoPBJ7djJ8Rxxa.jpg", answer: "Will Smith" },
    { image: "https://image.tmdb.org/t/p/original/jj2Gcobpopokal0YstuCQW0ldJ4.jpg", answer: "Denzel Washington" },
    { image: "https://image.tmdb.org/t/p/original/uxiXuVH4vNWrKlJMVVPG1sxAJFe.jpg", answer: "Russell Crowe" },
    { image: "https://image.tmdb.org/t/p/original/4Xujtewxqt6aU0Y81tsS9gkjizk.jpg", answer: "Hugh Jackman" },
    { image: "https://image.tmdb.org/t/p/original/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg", answer: "Ryan Gosling" },
    { image: "https://image.tmdb.org/t/p/original/trzgptffGvAlAT6MEu01fz47cLW.jpg", answer: "Ryan Reynolds" },
    { image: "https://image.tmdb.org/t/p/original/j2Yahha9C0zN5DRaTDzYA7WtdOT.jpg", answer: "Jake Gyllenhaal" },
    { image: "https://image.tmdb.org/t/p/original/lCySuYjhXix3FzQdS4oceDDrXKI.jpg", answer: "Matthew McConaughey" },
    { image: "https://image.tmdb.org/t/p/original/2lKs67r7FI4bPu0AXxMUJZxmUXn.jpg", answer: "Cillian Murphy" },
    { image: "https://image.tmdb.org/t/p/original/8nytsqL59SFJTVYVrN72k6qkGgJ.jpg", answer: "Edward Norton" },
    { image: "https://image.tmdb.org/t/p/original/qBc7ahQrpVpcllaZ5hkivsOEb3C.jpg", answer: "Adrien Brody" },
    { image: "https://image.tmdb.org/t/p/original/3kNA9VcmymoEwT0btQ4bvMYxzcP.jpg", answer: "Daniel Day-Lewis" },
    { image: "https://image.tmdb.org/t/p/original/tJr9GcmGNHhLVVEH3i7QYbj6hBi.jpg", answer: "Ralph Fiennes" },
    { image: "https://image.tmdb.org/t/p/original/oojD9jSshvUT4t6AUySsBxoekHk.jpg", answer: "Ethan Hawke" },
    { image: "https://image.tmdb.org/t/p/original/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg", answer: "Willem Dafoe" },
    { image: "https://image.tmdb.org/t/p/original/5GilHMOt5PAQh6rlUKZzGmaKEI7.jpg", answer: "Mark Ruffalo" },
    { image: "https://image.tmdb.org/t/p/original/3bOGNsHlrswhyW79uvIHH1V43JI.jpg", answer: "Chris Evans" },
    { image: "https://image.tmdb.org/t/p/original/piQGdoIQOF3C1EI5cbYZLAW1gfj.jpg", answer: "Chris Hemsworth" },
    { image: "https://image.tmdb.org/t/p/original/872Hzdq95gsbMRabsColTW3TLrD.jpg", answer: "Chris Pratt" },
    { image: "https://image.tmdb.org/t/p/original/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg", answer: "Robert Downey Jr." },
    { image: "https://image.tmdb.org/t/p/original/wz3MRiMmoz6b5X3oSzMRC9nLxY1.jpg", answer: "Benedict Cumberbatch" },
    { image: "https://image.tmdb.org/t/p/original/AiAYAqwpM5xmiFrAIeQvUXDCVvo.jpg", answer: "Samuel L. Jackson" },
    { image: "https://image.tmdb.org/t/p/original/dFxpwRpmzpVfP1zjluH68DeQhyj.jpg", answer: "Timothée Chalamet" },
    { image: "https://image.tmdb.org/t/p/original/hPcyXGZ0qNL9Sm2LKlDzO54Pa8g.jpg", answer: "Paul Mescal" },
    { image: "https://image.tmdb.org/t/p/original/oKcMbVn0NJTNzQt0ClKKvVXkm60.jpg", answer: "Pedro Pascal" },
    { image: "https://image.tmdb.org/t/p/original/dW5U5yrIIPmMjRThR9KT2xH6nTz.jpg", answer: "Oscar Isaac" },
    { image: "https://image.tmdb.org/t/p/original/b5w381C8Z33D1iF30KT4k8tJNsk.jpg", answer: "Adam Driver" },
    { image: "https://image.tmdb.org/t/p/original/xvbnUiB2ZBR3QIt595OzNy657Vw.jpg", answer: "Michael Fassbender" },
    { image: "https://image.tmdb.org/t/p/original/5FdalJbrbZ5UCsED5rFrXpvbqJa.jpg", answer: "Colin Farrell" },
    { image: "https://image.tmdb.org/t/p/original/tFj5PaWWQbb8rHBBhu1EHklznph.jpg", answer: "Brendan Fraser" },
    { image: "https://image.tmdb.org/t/p/original/g5cVxQBAQ3AXt3LhdBXtbbN47Uc.jpg", answer: "Meryl Streep" },
    { image: "https://image.tmdb.org/t/p/original/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg", answer: "Cate Blanchett" },
    { image: "https://image.tmdb.org/t/p/original/4KSQDodyBtTDMaREYgMdWD1LbH1.jpg", answer: "Nicole Kidman" },
    { image: "https://image.tmdb.org/t/p/original/fQacAdIa1WUNChQ6FgEko13eqOA.jpg", answer: "Julia Roberts" },
    { image: "https://image.tmdb.org/t/p/original/iYk1dueFEQpJwriOgMdnhyDDeDz.jpg", answer: "Sandra Bullock" },
    { image: "https://image.tmdb.org/t/p/original/5emVgsLFlU6SmeBIFsF2Y7aqwtG.jpg", answer: "Jodie Foster" },
    { image: "https://image.tmdb.org/t/p/original/edPU5HxncLWa1YkgRPNkSd68ONG.jpg", answer: "Natalie Portman" },
    { image: "https://image.tmdb.org/t/p/original/druW5adKddizHNSoPbI0q7Mvn0K.jpg", answer: "Scarlett Johansson" },
    { image: "https://image.tmdb.org/t/p/original/t7EYLBMWQiIDtCoOYZjvqXV84S5.jpg", answer: "Emma Stone" },
    { image: "https://image.tmdb.org/t/p/original/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg", answer: "Emma Watson" },
    { image: "https://image.tmdb.org/t/p/original/mDKMsjOMytyBiy7MHNZTa7gp7wj.jpg", answer: "Jennifer Lawrence" },
    { image: "https://image.tmdb.org/t/p/original/au6Hq8nQXJD67mDtl34ZOm8DXrh.jpg", answer: "Margot Robbie" },
    { image: "https://image.tmdb.org/t/p/original/gd7ShD0yt4bsR2STeQ19KQ6hvXL.jpg", answer: "Charlize Theron" },
    { image: "https://image.tmdb.org/t/p/original/nbccV2pMoyLTCeg5DQip24Eq0Jp.jpg", answer: "Anne Hathaway" },
    { image: "https://image.tmdb.org/t/p/original/bXNxIKcJ5cNNW8QFrBPWcfTSu9x.jpg", answer: "Angelina Jolie" },
    { image: "https://image.tmdb.org/t/p/original/e3tdop3WhseRnn8KwMVLAV25Ybv.jpg", answer: "Kate Winslet" },
    { image: "https://image.tmdb.org/t/p/original/hJMbNSPJ2PCahsP3rNEU39C8GWU.jpg", answer: "Helena Bonham Carter" },
    { image: "https://image.tmdb.org/t/p/original/wTSnfktNBLd6kwQxgvkqYw6vEon.jpg", answer: "Sigourney Weaver" },
    { image: "https://image.tmdb.org/t/p/original/hlYG0MC6im0MHNq1xixxVilfwyR.jpg", answer: "Uma Thurman" },
    { image: "https://image.tmdb.org/t/p/original/xDssw6vpYNRjsybvMPRE30e0dPN.jpg", answer: "Viola Davis" },
    { image: "https://image.tmdb.org/t/p/original/qYNofOjlRke2MlJVihmJmEdQI4v.jpg", answer: "Anya Taylor-Joy" },
    { image: "https://image.tmdb.org/t/p/original/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg", answer: "Florence Pugh" },
    { image: "https://image.tmdb.org/t/p/original/yCpzzMJ9gS7Rp7xgrVOsntW1m7D.jpg", answer: "Zendaya" },
    { image: "https://image.tmdb.org/t/p/original/371WiQYe2mGlsZj5f7AZHSGgnFV.jpg", answer: "Mia Goth" },
    { image: "https://image.tmdb.org/t/p/original/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg", answer: "Sydney Sweeney" },
    { image: "https://image.tmdb.org/t/p/original/dQb6COORkv8liT5FMtXdHuvjUsb.jpg", answer: "Jenna Ortega" },
    { image: "https://image.tmdb.org/t/p/original/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg", answer: "Steven Spielberg" },
    { image: "https://image.tmdb.org/t/p/original/g3DjfKsgZQWZiw30I20hZVk1oMX.jpg", answer: "Martin Scorsese" },
    { image: "https://image.tmdb.org/t/p/original/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg", answer: "Christopher Nolan" },
    { image: "https://image.tmdb.org/t/p/original/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg", answer: "Quentin Tarantino" },
    { image: "https://image.tmdb.org/t/p/original/tpEczFclQZeKAiCeKZZ0adRvtfz.jpg", answer: "David Fincher" },
    { image: "https://image.tmdb.org/t/p/original/IwGgkmW6IoJ9vuNF0T9CU3FYUX.jpg", answer: "Francis Ford Coppola" },
    { image: "https://image.tmdb.org/t/p/original/exfQ6vXXq7rMS5YWb3B88PK39a1.jpg", answer: "Stanley Kubrick" },
    { image: "https://image.tmdb.org/t/p/original/108fiNM6poRieMg7RIqLJRxdAwG.jpg", answer: "Alfred Hitchcock" },
    { image: "https://image.tmdb.org/t/p/original/97SO7H0UlS3racqjeW5JTy8c6GM.jpg", answer: "Ridley Scott" },
    { image: "https://image.tmdb.org/t/p/original/9NAZnTjBQ9WcXAQEzZpKy4vdQto.jpg", answer: "James Cameron" },
    { image: "https://image.tmdb.org/t/p/original/wwBzRDoIW6Ld64h6OkQ6ImCZKsR.jpg", answer: "David Lynch" },
    { image: "https://image.tmdb.org/t/p/original/zdDx9Xs93UIrJFWYApYR28J8M6b.jpg", answer: "Denis Villeneuve" },
    { image: "https://image.tmdb.org/t/p/original/wcjuY5vD1nlfwWNbvvTGg5dGoRR.jpg", answer: "Tim Burton" },
    { image: "https://image.tmdb.org/t/p/original/bNc908d59Ba8VDNr4eCcm4G1cR.jpg", answer: "Peter Jackson" },
    { image: "https://image.tmdb.org/t/p/original/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg", answer: "George Lucas" },
    { image: "https://image.tmdb.org/t/p/original/2576qoW8l9Z1nKGM10ar60aIwUu.jpg", answer: "Sergio Leone" },
    { image: "https://image.tmdb.org/t/p/original/g2iwSho2vJxVz7cbD1FAKAmPD6A.jpg", answer: "Akira Kurosawa" },
    { image: "https://image.tmdb.org/t/p/original/ouhjt9KugzhWtdEyBPipihB3ic8.jpg", answer: "Hayao Miyazaki" },
    { image: "https://image.tmdb.org/t/p/original/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg", answer: "Guillermo del Toro" },
    { image: "https://image.tmdb.org/t/p/original/stwnTvZAoD8gEJEDHpDQyLCyDy5.jpg", answer: "Bong Joon Ho" },
    { image: "https://image.tmdb.org/t/p/original/msp2p1lFpbsQ3Ntpdh1sbryIZBR.jpg", answer: "Wong Kar-Wai" },
    { image: "https://image.tmdb.org/t/p/original/a1zVySI0Yqqf3ORegQ1icMfvhAa.jpg", answer: "Lars von Trier" },
    { image: "https://image.tmdb.org/t/p/original/r0GTpMWUrxgPRbMmv38mNggOBvA.jpg", answer: "Federico Fellini" },
    { image: "https://image.tmdb.org/t/p/original/60UYC6apdoC8VBh62WCkZ2LPGPk.jpg", answer: "Roman Polanski" },
    { image: "https://image.tmdb.org/t/p/original/bWjOPDt8HRww5VAtpZ5FiCxpIxu.jpg", answer: "Brian De Palma" },
    { image: "https://image.tmdb.org/t/p/original/3Qp0mg61u1qSZNJh30BFEUZrIMG.jpg", answer: "John Carpenter" },
    { image: "https://image.tmdb.org/t/p/original/s03CeUeC5yAXyB1acqP0zGNo2SC.jpg", answer: "Wes Anderson" },
    { image: "https://image.tmdb.org/t/p/original/kFUKn5g3ebpyZ3CSZZZo2HFWRNQ.jpg", answer: "Jordan Peele" },
    { image: "https://image.tmdb.org/t/p/original/14kRZ3XxNMyBv717YQSXr3wCucy.jpg", answer: "Damien Chazelle" },
    { image: "https://image.tmdb.org/t/p/original/dxKAhpkz4XNwmRzMG5QOpXjPZ1N.jpg", answer: "Greta Gerwig" },
    { image: "https://image.tmdb.org/t/p/original/v9ukVIUGT1vQ3KuPVLSua7FfS9s.jpg", answer: "Robert Eggers" },
    { image: "https://image.tmdb.org/t/p/original/45lOHyHwdMgyKm6u3jwLtyfwOjc.jpg", answer: "Ari Aster" },
    { image: "https://image.tmdb.org/t/p/original/dvtv8eV1O8Fl385ctOu3sqO2PbD.jpg", answer: "Yorgos Lanthimos" },
    { image: "https://image.tmdb.org/t/p/original/5z89X9rB76JDblqMQ52fviwXxAN.jpg", answer: "Sam Mendes" },
    { image: "https://image.tmdb.org/t/p/original/g3n8qduLaPO2l4kJZsV6xNMXozn.jpg", answer: "Ron Howard" },
    { image: "https://image.tmdb.org/t/p/original/8TwdCfeOZH7ucRlfLZ6wObxa7cO.jpg", answer: "Clint Eastwood" },
    { image: "https://image.tmdb.org/t/p/original/jnqHMaOslt8cef2atSmOpGRvNla.jpg", answer: "Mel Gibson" },
    { image: "https://image.tmdb.org/t/p/original/wP7gyISMcsXLJoInWTjncqhrsAT.jpg", answer: "Ricardo Darín" },
    { image: "https://image.tmdb.org/t/p/original/tqHvc1MaEzZHp52EeOagmBzaTn8.jpg", answer: "Guillermo Francella" },
    { image: "https://image.tmdb.org/t/p/original/honq5g3GPjaCBoiik4uU7va0OJf.jpg", answer: "Diego Peretti" },
    { image: "https://image.tmdb.org/t/p/original/dGW0WpAgEfExaMdt63sQ3r21HAG.jpg", answer: "Luis Brandoni" },
    { image: "https://image.tmdb.org/t/p/original/wwK95YtxNd1VuaUncPO5qvZq1L2.jpg", answer: "Héctor Alterio" },
    { image: "https://image.tmdb.org/t/p/original/fRezPzJO3rGaO2JZZsghEVhjvaa.jpg", answer: "Norma Aleandro" },
    { image: "https://image.tmdb.org/t/p/original/4icHsZvHy0ZnDGF2kovjNLuDQEM.jpg", answer: "Cecilia Roth" },
    { image: "https://image.tmdb.org/t/p/original/2r5QQeumzXWoSma6RQrLjiNhHdu.jpg", answer: "Mercedes Morán" },
    { image: "https://image.tmdb.org/t/p/original/8WqQnJJ30fJkFZAnmndjfhsT41k.jpg", answer: "Érica Rivas" },
    { image: "https://image.tmdb.org/t/p/original/leG6cjuFtfBwSHt2c9PeJdIdX12.jpg", answer: "China Zorrilla" },
    { image: "https://image.tmdb.org/t/p/original/gDjw5xPPlqOtD8hXCvSQilWBJ1Q.jpg", answer: "Soledad Villamil" },
    { image: "https://image.tmdb.org/t/p/original/zCC1SUcjoDuJui9qgFjJIgr6kDq.jpg", answer: "Damián Szifron" },
    { image: "https://image.tmdb.org/t/p/original/vnZ69dnDx9tnAkW9wicO9wHRQdx.jpg", answer: "Juan José Campanella" },
    { image: "https://image.tmdb.org/t/p/original/e70SUgZRzx5fFZ49zgn2uCqw8Jm.jpg", answer: "Lucrecia Martel" },
    { image: "https://image.tmdb.org/t/p/original/mw0EZJYz3kiFq9fNxsML773gotF.jpg", answer: "Jean Reno" },
    { image: "https://image.tmdb.org/t/p/original/cibkIAJN6ctlqHohhdDEcfbiCAL.jpg", answer: "Gérard Depardieu" },
    { image: "https://image.tmdb.org/t/p/original/biitzOF0GffIqFYLyOPkoiaOngQ.jpg", answer: "Marion Cotillard" },
    { image: "https://image.tmdb.org/t/p/original/ivUQfhn5olOmR5hthN8C8GThBV4.jpg", answer: "Vincent Cassel" },
    { image: "https://image.tmdb.org/t/p/original/ftoP3CMC4ob8VJAu1gEHSC714K5.jpg", answer: "Omar Sy" },
    { image: "https://image.tmdb.org/t/p/original/8R8WVggSEKxxT4n2HRKHjxHrIQZ.jpg", answer: "Louis de Funès" },
    { image: "https://image.tmdb.org/t/p/original/fce7zl6elUzsv7wudHFc7RgFtjD.jpg", answer: "Antonio Banderas" },
    { image: "https://image.tmdb.org/t/p/original/p5xjCovj1uzvA2SXrWLH78Nh1Jf.jpg", answer: "Javier Bardem" },
    { image: "https://image.tmdb.org/t/p/original/n5SFgmvJSENQt8poE4qYacUnKOi.jpg", answer: "Penélope Cruz" },
    { image: "https://image.tmdb.org/t/p/original/dKlaXJk3NLcsC1CKMx6xmyW5BZD.jpg", answer: "Pedro Almodóvar" },
    { image: "https://image.tmdb.org/t/p/original/ba1Sg02XxCphu6E1dWDMAH1GzeE.jpg", answer: "Roberto Benigni" },
    { image: "https://image.tmdb.org/t/p/original/lxhkn933v8EuBHvfTWSS5SQQnJ4.jpg", answer: "Sophia Loren" },
    { image: "https://image.tmdb.org/t/p/original/bfLnFfNfMC73Q7WW90xQy2PvRZm.jpg", answer: "Marcello Mastroianni" },
    { image: "https://image.tmdb.org/t/p/original/7g3k3u2gZpE7XU8GRYwHDuN1jlM.jpg", answer: "Monica Bellucci" },
    { image: "https://image.tmdb.org/t/p/original/jMvLGCVXLaBqjRLf5olyvEucZob.jpg", answer: "Christoph Waltz" },
    { image: "https://image.tmdb.org/t/p/original/o5gVowcjVw4ThYi0L3883Y4X7kH.jpg", answer: "Diane Kruger" },
    { image: "https://image.tmdb.org/t/p/original/9wDbsPQ5lu9A04FJ1pVi9y1dRjn.jpg", answer: "Michael Haneke" },
    { image: "https://image.tmdb.org/t/p/original/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg", answer: "Jackie Chan" },
    { image: "https://image.tmdb.org/t/p/original/uUC3N3sIuFLD0ZpNyc58NxW1Pzf.jpg", answer: "Bruce Lee" },
    { image: "https://image.tmdb.org/t/p/original/c4s8INzU0ZAujCQ1YmphCmcsNzl.jpg", answer: "Jet Li" },
    { image: "https://image.tmdb.org/t/p/original/hTlhrrZMj8hZVvD17j4KyAFWBHc.jpg", answer: "Donnie Yen" },
    { image: "https://image.tmdb.org/t/p/original/hre6xmoDbh67YN7wR5nhUazPTlb.jpg", answer: "Maggie Cheung" },
    { image: "https://image.tmdb.org/t/p/original/i6fHvGt7Rb8oVyjjdQVV6vEHB94.jpg", answer: "Michelle Yeoh" },
    { image: "https://image.tmdb.org/t/p/original/2Jybmz4PSuilsSnmQ4tYWXykPjC.jpg", answer: "Chow Yun-Fat" },
    { image: "https://image.tmdb.org/t/p/original/6pnXXkCx8wkCHvOrcWjaY58KA7k.jpg", answer: "Takeshi Kitano" },
    { image: "https://image.tmdb.org/t/p/original/cZ5ybA7cDA0EBMaM5jX2f7RNBVb.jpg", answer: "Toshirō Mifune" },
    { image: "https://image.tmdb.org/t/p/original/kBM9UTPYXUA2RNk210DXhztLFns.jpg", answer: "Song Kang-ho" },
    { image: "https://image.tmdb.org/t/p/original/j7SUd9Qi8iOxgrQGb3nQyEYcXur.jpg", answer: "Lee Byung-hun" },
    { image: "https://image.tmdb.org/t/p/original/gc3Ul6EtVYKgjBuYAaD8U2qIcSl.jpg", answer: "Shah Rukh Khan" },
    { image: "https://image.tmdb.org/t/p/original/6uiZSwi2kvd1jZ7X7Xz9W9VGuV4.jpg", answer: "Aamir Khan" },
    { image: "https://image.tmdb.org/t/p/original/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg", answer: "Salman Khan" },
    { image: "https://image.tmdb.org/t/p/original/rzvvBQ0r6oiqDdzcsdTRB7jN4Rx.jpg", answer: "Deepika Padukone" },
    { image: "https://image.tmdb.org/t/p/original/9n2n3fUFI553HKH0CEAb2TPLtCx.jpg", answer: "Priyanka Chopra Jonas" },
    { image: "https://image.tmdb.org/t/p/original/7uEO29wtdyY9bjt2JN43gVpE6vt.jpg", answer: "Gael García Bernal" },
    { image: "https://image.tmdb.org/t/p/original/qwbjcyDN37OHiln4a6P4LP31o7F.jpg", answer: "Diego Luna" },
    { image: "https://image.tmdb.org/t/p/original/1qfYF7NGRObmeKR7IVXUFVIC0CN.jpg", answer: "Salma Hayek Pinault" },
    { image: "https://image.tmdb.org/t/p/original/gaHhrzPfxfc3cbQLkDt54gtP3n1.jpg", answer: "Alfonso Cuarón" },
    { image: "https://image.tmdb.org/t/p/original/5Mx0RilUcVjXzmeKYAZJJ0WXZMQ.jpg", answer: "Alejandro G. Iñárritu" },
    { image: "https://image.tmdb.org/t/p/original/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg", answer: "Guillermo del Toro" },
    { image: "https://image.tmdb.org/t/p/original/53IbAed4t1dOWxY3iygbRYZBBnm.jpg", answer: "Wagner Moura" },
    { image: "https://image.tmdb.org/t/p/original/8NqF8pH836rfSlcI4ipmPH1NL2g.jpg", answer: "Sonia Braga" },
    { image: "https://image.tmdb.org/t/p/original/uxiXuVH4vNWrKlJMVVPG1sxAJFe.jpg", answer: "Russell Crowe" },
    { image: "https://image.tmdb.org/t/p/original/4KSQDodyBtTDMaREYgMdWD1LbH1.jpg", answer: "Nicole Kidman" },
    { image: "https://image.tmdb.org/t/p/original/4Xujtewxqt6aU0Y81tsS9gkjizk.jpg", answer: "Hugh Jackman" },
    { image: "https://image.tmdb.org/t/p/original/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg", answer: "Cate Blanchett" },
    { image: "https://image.tmdb.org/t/p/original/piQGdoIQOF3C1EI5cbYZLAW1gfj.jpg", answer: "Chris Hemsworth" },
    { image: "https://image.tmdb.org/t/p/original/au6Hq8nQXJD67mDtl34ZOm8DXrh.jpg", answer: "Margot Robbie" },
    { image: "https://image.tmdb.org/t/p/original/iIfuxalf37xUayuGyK0zG7z6WEZ.jpg", answer: "Sam Neill" },
    { image: "https://image.tmdb.org/t/p/original/y3U9QfPN6sJaGl6l68xjwWj28ig.jpg", answer: "Jim Carrey" },
    { image: "https://image.tmdb.org/t/p/original/iYdeP6K0qz44Wg2Nw9LPJGMBkQ5.jpg", answer: "Robin Williams" },
    { image: "https://image.tmdb.org/t/p/original/iTMnXrPfC1rmom6a9q4hy6YSJWG.jpg", answer: "Adam Sandler" },
    { image: "https://image.tmdb.org/t/p/original/cS7Cbyff6wFVfUGem497vy9LS7A.jpg", answer: "Steve Carell" },
    { image: "https://image.tmdb.org/t/p/original/gdiN2zLjC3Mnfrp7hM3TXVJjWJv.jpg", answer: "Rowan Atkinson" },
    { image: "https://image.tmdb.org/t/p/original/bGzXHu8zwWqUY5gEExSh3deQd2j.jpg", answer: "Sacha Baron Cohen" },
    { image: "https://image.tmdb.org/t/p/original/scgpxhI05JpdNXXfmpK6z0rPOWN.jpg", answer: "Ben Stiller" },
    { image: "https://image.tmdb.org/t/p/original/5A46lNOwmpX77jAdhyKxU7e2Hub.jpg", answer: "Owen Wilson" },
    { image: "https://image.tmdb.org/t/p/original/59IhgCtiWI5yTfzPhsjzg7GjCjm.jpg", answer: "Jack Black" },
    { image: "https://image.tmdb.org/t/p/original/nnCsJc9x3ZiG3AFyiyc3FPehppy.jpg", answer: "Bill Murray" },
];
