import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const synonymQuestions: CategoryQuestion[] = [
  { text: "Feliz → Sinónimo", answer: "Alegre", possibleAnswers: ["Contento", "Dichoso"] },
  { text: "Triste → Sinónimo", answer: "Apenado", possibleAnswers: ["Melancólico", "Deprimido"] },
  { text: "Grande → Sinónimo", answer: "Enorme", possibleAnswers: ["Gigante", "Inmenso"] },
  { text: "Pequeño → Sinónimo", answer: "Chico", possibleAnswers: ["Reducido", "Diminuto"] },
  { text: "Rápido → Sinónimo", answer: "Veloz", possibleAnswers: ["Ágil"] },
  { text: "Lento → Sinónimo", answer: "Pausado", possibleAnswers: ["Despacio"] },
  { text: "Bonito → Sinónimo", answer: "Hermoso", possibleAnswers: ["Lindo", "Bello"] },
  { text: "Feo → Sinónimo", answer: "Horrible", possibleAnswers: ["Desagradable"] },
  { text: "Fácil → Sinónimo", answer: "Sencillo", possibleAnswers: ["Simple"] },
  { text: "Difícil → Sinónimo", answer: "Complicado", possibleAnswers: ["Complejo"] },

  { text: "Empezar → Sinónimo", answer: "Comenzar", possibleAnswers: ["Iniciar"] },
  { text: "Terminar → Sinónimo", answer: "Finalizar", possibleAnswers: ["Concluir"] },
  { text: "Mirar → Sinónimo", answer: "Observar", possibleAnswers: ["Ver"] },
  { text: "Hablar → Sinónimo", answer: "Conversar", possibleAnswers: ["Dialogar"] },
  { text: "Callar → Sinónimo", answer: "Silenciar", possibleAnswers: ["Enmudecer"] },
  { text: "Comprar → Sinónimo", answer: "Adquirir", possibleAnswers: [] },
  { text: "Vender → Sinónimo", answer: "Comercializar", possibleAnswers: [] },
  { text: "Ayudar → Sinónimo", answer: "Asistir", possibleAnswers: ["Socorrer"] },
  { text: "Buscar → Sinónimo", answer: "Procurar", possibleAnswers: ["Explorar"] },
  { text: "Encontrar → Sinónimo", answer: "Hallar", possibleAnswers: [] },

  { text: "Caminar → Sinónimo", answer: "Andar", possibleAnswers: [] },
  { text: "Correr → Sinónimo", answer: "Trotar", possibleAnswers: [] },
  { text: "Saltar → Sinónimo", answer: "Brincar", possibleAnswers: [] },
  { text: "Caer → Sinónimo", answer: "Desplomarse", possibleAnswers: [] },
  { text: "Subir → Sinónimo", answer: "Ascender", possibleAnswers: [] },
  { text: "Bajar → Sinónimo", answer: "Descender", possibleAnswers: [] },
  { text: "Romper → Sinónimo", answer: "Quebrar", possibleAnswers: [] },
  { text: "Arreglar → Sinónimo", answer: "Reparar", possibleAnswers: [] },
  { text: "Crear → Sinónimo", answer: "Fabricar", possibleAnswers: ["Construir"] },
  { text: "Destruir → Sinónimo", answer: "Demoler", possibleAnswers: [] },

  { text: "Casa → Sinónimo", answer: "Hogar", possibleAnswers: ["Vivienda"] },
  { text: "Auto → Sinónimo", answer: "Coche", possibleAnswers: ["Automóvil", "Carro"] },
  { text: "Trabajo → Sinónimo", answer: "Empleo", possibleAnswers: ["Labor"] },
  { text: "Dinero → Sinónimo", answer: "Plata", possibleAnswers: ["Capital"] },
  { text: "Amigo → Sinónimo", answer: "Compañero", possibleAnswers: [] },
  { text: "Enemigo → Sinónimo", answer: "Adversario", possibleAnswers: ["Rival"] },
  { text: "Error → Sinónimo", answer: "Equivocación", possibleAnswers: ["Fallo"] },
  { text: "Problema → Sinónimo", answer: "Inconveniente", possibleAnswers: ["Dificultad"] },
  { text: "Respuesta → Sinónimo", answer: "Contestación", possibleAnswers: [] },
  { text: "Pregunta → Sinónimo", answer: "Interrogante", possibleAnswers: ["Cuestión"] },

  { text: "Inteligente → Sinónimo", answer: "Listo", possibleAnswers: ["Brillante"] },
  { text: "Tonto → Sinónimo", answer: "Necio", possibleAnswers: ["Ignorante"] },
  { text: "Valiente → Sinónimo", answer: "Intrépido", possibleAnswers: ["Audaz"] },
  { text: "Cobarde → Sinónimo", answer: "Miedoso", possibleAnswers: ["Temeroso"] },
  { text: "Fuerte → Sinónimo", answer: "Robusto", possibleAnswers: ["Resistente"] },
  { text: "Débil → Sinónimo", answer: "Frágil", possibleAnswers: [] },
  { text: "Rico → Sinónimo", answer: "Adinerado", possibleAnswers: ["Acaudalado"] },
  { text: "Pobre → Sinónimo", answer: "Necesitado", possibleAnswers: [] },
  { text: "Viejo → Sinónimo", answer: "Anciano", possibleAnswers: [] },
  { text: "Joven → Sinónimo", answer: "Muchacho", possibleAnswers: [] },

  { text: "Contento → Sinónimo", answer: "Feliz", possibleAnswers: ["Alegre"] },
  { text: "Asustado → Sinónimo", answer: "Aterrado", possibleAnswers: ["Temeroso"] },
  { text: "Enojado → Sinónimo", answer: "Furioso", possibleAnswers: ["Irritado"] },
  { text: "Cansado → Sinónimo", answer: "Fatigado", possibleAnswers: ["Agotado"] },
  { text: "Sorprendido → Sinónimo", answer: "Asombrado", possibleAnswers: [] },
  { text: "Aburrido → Sinónimo", answer: "Fastidiado", possibleAnswers: [] },
  { text: "Hermoso → Sinónimo", answer: "Bello", possibleAnswers: ["Lindo"] },
  { text: "Oscuro → Sinónimo", answer: "Sombrío", possibleAnswers: [] },
  { text: "Claro → Sinónimo", answer: "Luminoso", possibleAnswers: [] },
  { text: "Silencio → Sinónimo", answer: "Calma", possibleAnswers: ["Quietud"] },

  { text: "Rápidamente → Sinónimo", answer: "Velozmente", possibleAnswers: [] },
  { text: "Siempre → Sinónimo", answer: "Constantemente", possibleAnswers: [] },
  { text: "Jamás → Sinónimo", answer: "Nunca", possibleAnswers: [] },
  { text: "Quizás → Sinónimo", answer: "Tal vez", possibleAnswers: ["Acaso"] },
  { text: "Además → Sinónimo", answer: "También", possibleAnswers: [] },
  { text: "Luego → Sinónimo", answer: "Después", possibleAnswers: [] },
  { text: "Antes → Sinónimo", answer: "Previamente", possibleAnswers: [] },
  { text: "Cerca → Sinónimo", answer: "Próximo", possibleAnswers: [] },
  { text: "Lejos → Sinónimo", answer: "Distante", possibleAnswers: [] },
  { text: "Pronto → Sinónimo", answer: "Rápidamente", possibleAnswers: [] },

  { text: "Elegir → Sinónimo", answer: "Escoger", possibleAnswers: ["Seleccionar"] },
  { text: "Guardar → Sinónimo", answer: "Conservar", possibleAnswers: ["Almacenar"] },
  { text: "Lanzar → Sinónimo", answer: "Arrojar", possibleAnswers: ["Tirar"] },
  { text: "Levantar → Sinónimo", answer: "Alzar", possibleAnswers: [] },
  { text: "Empujar → Sinónimo", answer: "Impulsar", possibleAnswers: [] },
  { text: "Tirar → Sinónimo", answer: "Jalar", possibleAnswers: [] },
  { text: "Explicar → Sinónimo", answer: "Aclarar", possibleAnswers: [] },
  { text: "Aprender → Sinónimo", answer: "Estudiar", possibleAnswers: ["Asimilar"] },
  { text: "Enseñar → Sinónimo", answer: "Educar", possibleAnswers: ["Instruir"] },
  { text: "Pensar → Sinónimo", answer: "Reflexionar", possibleAnswers: [] },

  { text: "Recordar → Sinónimo", answer: "Rememorar", possibleAnswers: ["Evocar"] },
  { text: "Olvidar → Sinónimo", answer: "Omitir", possibleAnswers: [] },
  { text: "Aceptar → Sinónimo", answer: "Admitir", possibleAnswers: [] },
  { text: "Rechazar → Sinónimo", answer: "Negar", possibleAnswers: [] },
  { text: "Permitir → Sinónimo", answer: "Autorizar", possibleAnswers: [] },
  { text: "Prohibir → Sinónimo", answer: "Impedir", possibleAnswers: ["Vetar"] },
  { text: "Mostrar → Sinónimo", answer: "Exhibir", possibleAnswers: [] },
  { text: "Ocultar → Sinónimo", answer: "Esconder", possibleAnswers: [] },
  { text: "Llenar → Sinónimo", answer: "Completar", possibleAnswers: ["Colmar"] },
  { text: "Vaciar → Sinónimo", answer: "Desocupar", possibleAnswers: [] },

  { text: "Paz → Sinónimo", answer: "Tranquilidad", possibleAnswers: ["Calma"] },
  { text: "Guerra → Sinónimo", answer: "Conflicto", possibleAnswers: [] },
  { text: "Meta → Sinónimo", answer: "Objetivo", possibleAnswers: ["Propósito"] },
  { text: "Camino → Sinónimo", answer: "Sendero", possibleAnswers: ["Ruta"] },
  { text: "Ciudad → Sinónimo", answer: "Urbe", possibleAnswers: [] },
  { text: "Campo → Sinónimo", answer: "Pradera", possibleAnswers: [] },
  { text: "Bosque → Sinónimo", answer: "Selva", possibleAnswers: [] },
  { text: "Mar → Sinónimo", answer: "Océano", possibleAnswers: [] },
  { text: "Montaña → Sinónimo", answer: "Monte", possibleAnswers: [] },
  { text: "Final → Sinónimo", answer: "Conclusión", possibleAnswers: ["Fin"] },
  { text: "Feliz → Antónimo", answer: "Triste", possibleAnswers: ["Infeliz"] },
  { text: "Triste → Antónimo", answer: "Feliz", possibleAnswers: ["Alegre", "Contento"] },
  { text: "Grande → Antónimo", answer: "Pequeño", possibleAnswers: ["Chico"] },
  { text: "Pequeño → Antónimo", answer: "Grande", possibleAnswers: ["Enorme"] },
  { text: "Alto → Antónimo", answer: "Bajo", possibleAnswers: [] },
  { text: "Bajo → Antónimo", answer: "Alto", possibleAnswers: [] },
  { text: "Largo → Antónimo", answer: "Corto", possibleAnswers: [] },
  { text: "Corto → Antónimo", answer: "Largo", possibleAnswers: [] },
  { text: "Ancho → Antónimo", answer: "Angosto", possibleAnswers: ["Estrecho"] },
  { text: "Angosto → Antónimo", answer: "Ancho", possibleAnswers: [] },

  { text: "Rápido → Antónimo", answer: "Lento", possibleAnswers: [] },
  { text: "Lento → Antónimo", answer: "Rápido", possibleAnswers: ["Veloz"] },
  { text: "Fácil → Antónimo", answer: "Difícil", possibleAnswers: ["Complicado"] },
  { text: "Difícil → Antónimo", answer: "Fácil", possibleAnswers: ["Simple"] },
  { text: "Claro → Antónimo", answer: "Oscuro", possibleAnswers: [] },
  { text: "Oscuro → Antónimo", answer: "Claro", possibleAnswers: [] },
  { text: "Limpio → Antónimo", answer: "Sucio", possibleAnswers: [] },
  { text: "Sucio → Antónimo", answer: "Limpio", possibleAnswers: [] },
  { text: "Seco → Antónimo", answer: "Mojado", possibleAnswers: ["Húmedo"] },
  { text: "Mojado → Antónimo", answer: "Seco", possibleAnswers: [] },

  { text: "Caliente → Antónimo", answer: "Frío", possibleAnswers: [] },
  { text: "Frío → Antónimo", answer: "Caliente", possibleAnswers: [] },
  { text: "Nuevo → Antónimo", answer: "Viejo", possibleAnswers: ["Usado"] },
  { text: "Viejo → Antónimo", answer: "Nuevo", possibleAnswers: [] },
  { text: "Joven → Antónimo", answer: "Anciano", possibleAnswers: ["Viejo"] },
  { text: "Anciano → Antónimo", answer: "Joven", possibleAnswers: [] },
  { text: "Fuerte → Antónimo", answer: "Débil", possibleAnswers: [] },
  { text: "Débil → Antónimo", answer: "Fuerte", possibleAnswers: [] },
  { text: "Pesado → Antónimo", answer: "Liviano", possibleAnswers: ["Ligero"] },
  { text: "Liviano → Antónimo", answer: "Pesado", possibleAnswers: [] },

  { text: "Lleno → Antónimo", answer: "Vacío", possibleAnswers: [] },
  { text: "Vacío → Antónimo", answer: "Lleno", possibleAnswers: [] },
  { text: "Abierto → Antónimo", answer: "Cerrado", possibleAnswers: [] },
  { text: "Cerrado → Antónimo", answer: "Abierto", possibleAnswers: [] },
  { text: "Encendido → Antónimo", answer: "Apagado", possibleAnswers: [] },
  { text: "Apagado → Antónimo", answer: "Encendido", possibleAnswers: [] },
  { text: "Verdadero → Antónimo", answer: "Falso", possibleAnswers: [] },
  { text: "Falso → Antónimo", answer: "Verdadero", possibleAnswers: [] },
  { text: "Correcto → Antónimo", answer: "Incorrecto", possibleAnswers: [] },
  { text: "Incorrecto → Antónimo", answer: "Correcto", possibleAnswers: [] },

  { text: "Entrar → Antónimo", answer: "Salir", possibleAnswers: [] },
  { text: "Salir → Antónimo", answer: "Entrar", possibleAnswers: [] },
  { text: "Subir → Antónimo", answer: "Bajar", possibleAnswers: [] },
  { text: "Bajar → Antónimo", answer: "Subir", possibleAnswers: [] },
  { text: "Comprar → Antónimo", answer: "Vender", possibleAnswers: [] },
  { text: "Vender → Antónimo", answer: "Comprar", possibleAnswers: [] },
  { text: "Aceptar → Antónimo", answer: "Rechazar", possibleAnswers: [] },
  { text: "Rechazar → Antónimo", answer: "Aceptar", possibleAnswers: [] },
  { text: "Permitir → Antónimo", answer: "Prohibir", possibleAnswers: [] },
  { text: "Prohibir → Antónimo", answer: "Permitir", possibleAnswers: [] },

  { text: "Recordar → Antónimo", answer: "Olvidar", possibleAnswers: [] },
  { text: "Olvidar → Antónimo", answer: "Recordar", possibleAnswers: [] },
  { text: "Encontrar → Antónimo", answer: "Perder", possibleAnswers: [] },
  { text: "Perder → Antónimo", answer: "Encontrar", possibleAnswers: [] },
  { text: "Ganar → Antónimo", answer: "Perder", possibleAnswers: [] },
  { text: "Romper → Antónimo", answer: "Arreglar", possibleAnswers: ["Reparar"] },
  { text: "Arreglar → Antónimo", answer: "Romper", possibleAnswers: [] },
  { text: "Crear → Antónimo", answer: "Destruir", possibleAnswers: [] },
  { text: "Destruir → Antónimo", answer: "Crear", possibleAnswers: [] },
  { text: "Construir → Antónimo", answer: "Demoler", possibleAnswers: ["Destruir"] },

  { text: "Amigo → Antónimo", answer: "Enemigo", possibleAnswers: ["Rival"] },
  { text: "Enemigo → Antónimo", answer: "Amigo", possibleAnswers: [] },
  { text: "Paz → Antónimo", answer: "Guerra", possibleAnswers: [] },
  { text: "Guerra → Antónimo", answer: "Paz", possibleAnswers: [] },
  { text: "Éxito → Antónimo", answer: "Fracaso", possibleAnswers: [] },
  { text: "Fracaso → Antónimo", answer: "Éxito", possibleAnswers: [] },
  { text: "Rico → Antónimo", answer: "Pobre", possibleAnswers: [] },
  { text: "Pobre → Antónimo", answer: "Rico", possibleAnswers: ["Adinerado"] },
  { text: "Principio → Antónimo", answer: "Final", possibleAnswers: ["Fin"] },
  { text: "Final → Antónimo", answer: "Principio", possibleAnswers: ["Inicio"] },

  { text: "Día → Antónimo", answer: "Noche", possibleAnswers: [] },
  { text: "Noche → Antónimo", answer: "Día", possibleAnswers: [] },
  { text: "Interior → Antónimo", answer: "Exterior", possibleAnswers: [] },
  { text: "Exterior → Antónimo", answer: "Interior", possibleAnswers: [] },
  { text: "Cerca → Antónimo", answer: "Lejos", possibleAnswers: [] },
  { text: "Lejos → Antónimo", answer: "Cerca", possibleAnswers: [] },
  { text: "Arriba → Antónimo", answer: "Abajo", possibleAnswers: [] },
  { text: "Abajo → Antónimo", answer: "Arriba", possibleAnswers: [] },
  { text: "Dentro → Antónimo", answer: "Fuera", possibleAnswers: [] },
  { text: "Fuera → Antónimo", answer: "Dentro", possibleAnswers: [] },

  { text: "Inicio → Antónimo", answer: "Final", possibleAnswers: ["Fin"] },
  { text: "Silencio → Antónimo", answer: "Ruido", possibleAnswers: [] },
  { text: "Ruido → Antónimo", answer: "Silencio", possibleAnswers: [] },
  { text: "Orden → Antónimo", answer: "Caos", possibleAnswers: ["Desorden"] },
  { text: "Caos → Antónimo", answer: "Orden", possibleAnswers: [] },
  { text: "Valiente → Antónimo", answer: "Cobarde", possibleAnswers: ["Miedoso"] },
  { text: "Cobarde → Antónimo", answer: "Valiente", possibleAnswers: ["Audaz"] },
  { text: "Generoso → Antónimo", answer: "Tacaño", possibleAnswers: [] },
  { text: "Tacaño → Antónimo", answer: "Generoso", possibleAnswers: [] },
  { text: "Humilde → Antónimo", answer: "Orgulloso", possibleAnswers: ["Soberbio"] },

  { text: "Orgulloso → Antónimo", answer: "Humilde", possibleAnswers: [] },
  { text: "Paciente → Antónimo", answer: "Impaciente", possibleAnswers: [] },
  { text: "Impaciente → Antónimo", answer: "Paciente", possibleAnswers: [] },
  { text: "Optimista → Antónimo", answer: "Pesimista", possibleAnswers: [] },
  { text: "Pesimista → Antónimo", answer: "Optimista", possibleAnswers: [] },
  { text: "Legal → Antónimo", answer: "Ilegal", possibleAnswers: [] },
  { text: "Ilegal → Antónimo", answer: "Legal", possibleAnswers: [] },
  { text: "Positivo → Antónimo", answer: "Negativo", possibleAnswers: [] },
  { text: "Negativo → Antónimo", answer: "Positivo", possibleAnswers: [] },
  { text: "Visible → Antónimo", answer: "Invisible", possibleAnswers: [] }

];