import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const flags: CategoryQuestion[] = [
    { image: "https://flagcdn.com/h240/af.png", answer: "Afganistán" },
    { image: "https://flagcdn.com/h240/al.png", answer: "Albania" },
    { image: "https://flagcdn.com/h240/de.png", answer: "Alemania" },
    { image: "https://flagcdn.com/h240/ad.png", answer: "Andorra" },
    { image: "https://flagcdn.com/h240/ao.png", answer: "Angola" },
    { image: "https://flagcdn.com/h240/ag.png", answer: "Antigua y Barbuda" },
    { image: "https://flagcdn.com/h240/sa.png", answer: "Arabia Saudita" },
    { image: "https://flagcdn.com/h240/dz.png", answer: "Argelia" },
    { image: "https://flagcdn.com/h240/ar.png", answer: "Argentina" },
    { image: "https://flagcdn.com/h240/am.png", answer: "Armenia" },
    { image: "https://flagcdn.com/h240/au.png", answer: "Australia" },
    { image: "https://flagcdn.com/h240/at.png", answer: "Austria" },
    { image: "https://flagcdn.com/h240/az.png", answer: "Azerbaiyán" },
    { image: "https://flagcdn.com/h240/bs.png", answer: "Bahamas" },
    { image: "https://flagcdn.com/h240/bh.png", answer: "Baréin" },
    { image: "https://flagcdn.com/h240/bd.png", answer: "Bangladés" },
    { image: "https://flagcdn.com/h240/bb.png", answer: "Barbados" },
    { image: "https://flagcdn.com/h240/be.png", answer: "Bélgica" },
    { image: "https://flagcdn.com/h240/bz.png", answer: "Belice" },
    { image: "https://flagcdn.com/h240/bj.png", answer: "Benín" },
    { image: "https://flagcdn.com/h240/by.png", answer: "Bielorrusia" },
    { image: "https://flagcdn.com/h240/bo.png", answer: "Bolivia" },
    { image: "https://flagcdn.com/h240/ba.png", answer: "Bosnia y Herzegovina" },
    { image: "https://flagcdn.com/h240/bw.png", answer: "Botsuana" },
    { image: "https://flagcdn.com/h240/br.png", answer: "Brasil" },
    { image: "https://flagcdn.com/h240/bn.png", answer: "Brunéi" },
    { image: "https://flagcdn.com/h240/bg.png", answer: "Bulgaria" },
    { image: "https://flagcdn.com/h240/bf.png", answer: "Burkina Faso" },
    { image: "https://flagcdn.com/h240/bi.png", answer: "Burundi" },
    { image: "https://flagcdn.com/h240/bt.png", answer: "Bután" },
    { image: "https://flagcdn.com/h240/cv.png", answer: "Cabo Verde" },
    { image: "https://flagcdn.com/h240/kh.png", answer: "Camboya" },
    { image: "https://flagcdn.com/h240/cm.png", answer: "Camerún" },
    { image: "https://flagcdn.com/h240/ca.png", answer: "Canadá" },
    { image: "https://flagcdn.com/h240/qa.png", answer: "Catar" },
    { image: "https://flagcdn.com/h240/td.png", answer: "Chad" },
    { image: "https://flagcdn.com/h240/cl.png", answer: "Chile" },
    { image: "https://flagcdn.com/h240/cn.png", answer: "China" },
    { image: "https://flagcdn.com/h240/cy.png", answer: "Chipre" },
    { image: "https://flagcdn.com/h240/va.png", answer: "Ciudad del Vaticano" },
    { image: "https://flagcdn.com/h240/co.png", answer: "Colombia" },
    { image: "https://flagcdn.com/h240/km.png", answer: "Comoras" },
    { image: "https://flagcdn.com/h240/cg.png", answer: "Congo" },
    { image: "https://flagcdn.com/h240/cd.png", answer: "Congo (RDC)" },
    { image: "https://flagcdn.com/h240/kp.png", answer: "Corea del Norte" },
    { image: "https://flagcdn.com/h240/kr.png", answer: "Corea del Sur" },
    { image: "https://flagcdn.com/h240/cr.png", answer: "Costa Rica" },
    { image: "https://flagcdn.com/h240/ci.png", answer: "Costa de Marfil" },
    { image: "https://flagcdn.com/h240/hr.png", answer: "Croacia" },
    { image: "https://flagcdn.com/h240/cu.png", answer: "Cuba" },
    { image: "https://flagcdn.com/h240/dk.png", answer: "Dinamarca" },
    { image: "https://flagcdn.com/h240/dj.png", answer: "Yibuti" },
    { image: "https://flagcdn.com/h240/dm.png", answer: "Dominica" },
    { image: "https://flagcdn.com/h240/ec.png", answer: "Ecuador" },
    { image: "https://flagcdn.com/h240/eg.png", answer: "Egipto" },
    { image: "https://flagcdn.com/h240/sv.png", answer: "El Salvador" },
    { image: "https://flagcdn.com/h240/ae.png", answer: "Emiratos Árabes Unidos" },
    { image: "https://flagcdn.com/h240/er.png", answer: "Eritrea" },
    { image: "https://flagcdn.com/h240/sk.png", answer: "Eslovaquia" },
    { image: "https://flagcdn.com/h240/si.png", answer: "Eslovenia" },
    { image: "https://flagcdn.com/h240/es.png", answer: "España" },
    { image: "https://flagcdn.com/h240/us.png", answer: "Estados Unidos" },
    { image: "https://flagcdn.com/h240/ee.png", answer: "Estonia" },
    { image: "https://flagcdn.com/h240/et.png", answer: "Etiopía" },
    { image: "https://flagcdn.com/h240/ph.png", answer: "Filipinas" },
    { image: "https://flagcdn.com/h240/fi.png", answer: "Finlandia" },
    { image: "https://flagcdn.com/h240/fj.png", answer: "Fiyi" },
    { image: "https://flagcdn.com/h240/fr.png", answer: "Francia" },
    { image: "https://flagcdn.com/h240/ga.png", answer: "Gabón" },
    { image: "https://flagcdn.com/h240/gm.png", answer: "Gambia" },
    { image: "https://flagcdn.com/h240/ge.png", answer: "Georgia" },
    { image: "https://flagcdn.com/h240/gh.png", answer: "Ghana" },
    { image: "https://flagcdn.com/h240/gd.png", answer: "Granada" },
    { image: "https://flagcdn.com/h240/gr.png", answer: "Grecia" },
    { image: "https://flagcdn.com/h240/gt.png", answer: "Guatemala" },
    { image: "https://flagcdn.com/h240/gn.png", answer: "Guinea" },
    { image: "https://flagcdn.com/h240/gq.png", answer: "Guinea Ecuatorial" },
    { image: "https://flagcdn.com/h240/gw.png", answer: "Guinea-Bisáu" },
    { image: "https://flagcdn.com/h240/gy.png", answer: "Guyana" },
    { image: "https://flagcdn.com/h240/ht.png", answer: "Haití" },
    { image: "https://flagcdn.com/h240/hn.png", answer: "Honduras" },
    { image: "https://flagcdn.com/h240/hu.png", answer: "Hungría" },
    { image: "https://flagcdn.com/h240/in.png", answer: "India" },
    { image: "https://flagcdn.com/h240/id.png", answer: "Indonesia" },
    { image: "https://flagcdn.com/h240/iq.png", answer: "Irak" },
    { image: "https://flagcdn.com/h240/ir.png", answer: "Irán" },
    { image: "https://flagcdn.com/h240/ie.png", answer: "Irlanda" },
    { image: "https://flagcdn.com/h240/is.png", answer: "Islandia" },
    { image: "https://flagcdn.com/h240/il.png", answer: "Israel" },
    { image: "https://flagcdn.com/h240/it.png", answer: "Italia" },
    { image: "https://flagcdn.com/h240/jm.png", answer: "Jamaica" },
    { image: "https://flagcdn.com/h240/jp.png", answer: "Japón" },
    { image: "https://flagcdn.com/h240/jo.png", answer: "Jordania" },
    { image: "https://flagcdn.com/h240/kz.png", answer: "Kazajistán" },
    { image: "https://flagcdn.com/h240/ke.png", answer: "Kenia" },
    { image: "https://flagcdn.com/h240/kg.png", answer: "Kirguistán" },
    { image: "https://flagcdn.com/h240/ki.png", answer: "Kiribati" },
    { image: "https://flagcdn.com/h240/kw.png", answer: "Kuwait" },
    { image: "https://flagcdn.com/h240/la.png", answer: "Laos" },
    { image: "https://flagcdn.com/h240/ls.png", answer: "Lesoto" },
    { image: "https://flagcdn.com/h240/lv.png", answer: "Letonia" },
    { image: "https://flagcdn.com/h240/lb.png", answer: "Líbano" },
    { image: "https://flagcdn.com/h240/lr.png", answer: "Liberia" },
    { image: "https://flagcdn.com/h240/ly.png", answer: "Libia" },
    { image: "https://flagcdn.com/h240/li.png", answer: "Liechtenstein" },
    { image: "https://flagcdn.com/h240/lt.png", answer: "Lituania" },
    { image: "https://flagcdn.com/h240/lu.png", answer: "Luxemburgo" },
    { image: "https://flagcdn.com/h240/mk.png", answer: "Macedonia del Norte" },
    { image: "https://flagcdn.com/h240/mg.png", answer: "Madagascar" },
    { image: "https://flagcdn.com/h240/my.png", answer: "Malasia" },
    { image: "https://flagcdn.com/h240/mw.png", answer: "Malaui" },
    { image: "https://flagcdn.com/h240/mv.png", answer: "Maldivas" },
    { image: "https://flagcdn.com/h240/ml.png", answer: "Malí" },
    { image: "https://flagcdn.com/h240/mt.png", answer: "Malta" },
    { image: "https://flagcdn.com/h240/ma.png", answer: "Marruecos" },
    { image: "https://flagcdn.com/h240/mh.png", answer: "Islas Marshall" },
    { image: "https://flagcdn.com/h240/mr.png", answer: "Mauritania" },
    { image: "https://flagcdn.com/h240/mu.png", answer: "Mauricio" },
    { image: "https://flagcdn.com/h240/mx.png", answer: "México" },
    { image: "https://flagcdn.com/h240/fm.png", answer: "Micronesia" },
    { image: "https://flagcdn.com/h240/md.png", answer: "Moldavia" },
    { image: "https://flagcdn.com/h240/mc.png", answer: "Mónaco" },
    { image: "https://flagcdn.com/h240/mn.png", answer: "Mongolia" },
    { image: "https://flagcdn.com/h240/me.png", answer: "Montenegro" },
    { image: "https://flagcdn.com/h240/mz.png", answer: "Mozambique" },
    { image: "https://flagcdn.com/h240/mm.png", answer: "Myanmar" },
    { image: "https://flagcdn.com/h240/na.png", answer: "Namibia" },
    { image: "https://flagcdn.com/h240/nr.png", answer: "Nauru" },
    { image: "https://flagcdn.com/h240/np.png", answer: "Nepal" },
    { image: "https://flagcdn.com/h240/ni.png", answer: "Nicaragua" },
    { image: "https://flagcdn.com/h240/ne.png", answer: "Níger" },
    { image: "https://flagcdn.com/h240/ng.png", answer: "Nigeria" },
    { image: "https://flagcdn.com/h240/no.png", answer: "Noruega" },
    { image: "https://flagcdn.com/h240/nz.png", answer: "Nueva Zelanda" },
    { image: "https://flagcdn.com/h240/om.png", answer: "Omán" },
    { image: "https://flagcdn.com/h240/nl.png", answer: "Países Bajos" },
    { image: "https://flagcdn.com/h240/pk.png", answer: "Pakistán" },
    { image: "https://flagcdn.com/h240/pw.png", answer: "Palaos" },
    { image: "https://flagcdn.com/h240/pa.png", answer: "Panamá" },
    { image: "https://flagcdn.com/h240/pg.png", answer: "Papúa Nueva Guinea" },
    { image: "https://flagcdn.com/h240/py.png", answer: "Paraguay" },
    { image: "https://flagcdn.com/h240/pe.png", answer: "Perú" },
    { image: "https://flagcdn.com/h240/pl.png", answer: "Polonia" },
    { image: "https://flagcdn.com/h240/pt.png", answer: "Portugal" },
    { image: "https://flagcdn.com/h240/gb.png", answer: "Reino Unido" },
    { image: "https://flagcdn.com/h240/cf.png", answer: "República Centroafricana" },
    { image: "https://flagcdn.com/h240/cz.png", answer: "República Checa" },
    { image: "https://flagcdn.com/h240/do.png", answer: "República Dominicana" },
    { image: "https://flagcdn.com/h240/ro.png", answer: "Rumanía" },
    { image: "https://flagcdn.com/h240/rw.png", answer: "Ruanda" },
    { image: "https://flagcdn.com/h240/ru.png", answer: "Rusia" },
    { image: "https://flagcdn.com/h240/ws.png", answer: "Samoa" },
    { image: "https://flagcdn.com/h240/kn.png", answer: "San Cristóbal y Nieves" },
    { image: "https://flagcdn.com/h240/sm.png", answer: "San Marino" },
    { image: "https://flagcdn.com/h240/vc.png", answer: "San Vicente y las Granadinas" },
    { image: "https://flagcdn.com/h240/lc.png", answer: "Santa Lucía" },
    { image: "https://flagcdn.com/h240/st.png", answer: "Santo Tomé y Príncipe" },
    { image: "https://flagcdn.com/h240/sn.png", answer: "Senegal" },
    { image: "https://flagcdn.com/h240/rs.png", answer: "Serbia" },
    { image: "https://flagcdn.com/h240/sc.png", answer: "Seychelles" },
    { image: "https://flagcdn.com/h240/sl.png", answer: "Sierra Leona" },
    { image: "https://flagcdn.com/h240/sg.png", answer: "Singapur" },
    { image: "https://flagcdn.com/h240/sy.png", answer: "Siria" },
    { image: "https://flagcdn.com/h240/so.png", answer: "Somalia" },
    { image: "https://flagcdn.com/h240/lk.png", answer: "Sri Lanka" },
    { image: "https://flagcdn.com/h240/sz.png", answer: "Suazilandia" },
    { image: "https://flagcdn.com/h240/za.png", answer: "Sudáfrica" },
    { image: "https://flagcdn.com/h240/sd.png", answer: "Sudán" },
    { image: "https://flagcdn.com/h240/ss.png", answer: "Sudán del Sur" },
    { image: "https://flagcdn.com/h240/se.png", answer: "Suecia" },
    { image: "https://flagcdn.com/h240/ch.png", answer: "Suiza" },
    { image: "https://flagcdn.com/h240/sr.png", answer: "Surinam" },
    { image: "https://flagcdn.com/h240/th.png", answer: "Tailandia" },
    { image: "https://flagcdn.com/h240/tz.png", answer: "Tanzania" },
    { image: "https://flagcdn.com/h240/tj.png", answer: "Tayikistán" },
    { image: "https://flagcdn.com/h240/tl.png", answer: "Timor Oriental" },
    { image: "https://flagcdn.com/h240/tg.png", answer: "Togo" },
    { image: "https://flagcdn.com/h240/to.png", answer: "Tonga" },
    { image: "https://flagcdn.com/h240/tt.png", answer: "Trinidad y Tobago" },
    { image: "https://flagcdn.com/h240/tn.png", answer: "Túnez" },
    { image: "https://flagcdn.com/h240/tm.png", answer: "Turkmenistán" },
    { image: "https://flagcdn.com/h240/tr.png", answer: "Turquía" },
    { image: "https://flagcdn.com/h240/tv.png", answer: "Tuvalu" },
    { image: "https://flagcdn.com/h240/ua.png", answer: "Ucrania" },
    { image: "https://flagcdn.com/h240/ug.png", answer: "Uganda" },
    { image: "https://flagcdn.com/h240/uy.png", answer: "Uruguay" },
    { image: "https://flagcdn.com/h240/uz.png", answer: "Uzbekistán" },
    { image: "https://flagcdn.com/h240/vu.png", answer: "Vanuatu" },
    { image: "https://flagcdn.com/h240/ve.png", answer: "Venezuela" },
    { image: "https://flagcdn.com/h240/vn.png", answer: "Vietnam" },
    { image: "https://flagcdn.com/h240/ye.png", answer: "Yemen" },
    { image: "https://flagcdn.com/h240/dz.png", answer: "Argelia" },
    { image: "https://flagcdn.com/h240/zm.png", answer: "Zambia" },
    { image: "https://flagcdn.com/h240/zw.png", answer: "Zimbabue" },
];
