export interface CapitalQuestion {
    image?: string;
    text?: string;
    answer: string;
}

export const cantantes: CapitalQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Michael_Jackson_1983_%283x4_cropped%29_%28contrast%29.jpg", answer: "Michael Jackson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg", answer: "Elvis Presley" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg", answer: "Freddie Mercury" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/David-Bowie_Chicago_2002-08-08_photoby_Adam-Bielawski-cropped.jpg", answer: "David Bowie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/85/John_Lennon_%22Walls_and_Bridges%22_1974_press_photo_2_%28color%29_%28cropped%29.jpg", answer: "John Lennon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/MaccaLyricsRFH051121_%2815_of_18%29_%28updated%29_%28cropped%29.jpg", answer: "Paul McCartney" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/DylanYoungKilkenny140719v2_%2850_of_52%29_%2852246124397%29_%28cropped%29.jpg", answer: "Bob Dylan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Prince_William_attends_Holocaust_Memorial_Day_%2854290704867%29%28cropped_3%29.jpg", answer: "Prince" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Frank_Sinatra_1961.jpg", answer: "Frank Sinatra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Monroecirca1953.jpg", answer: "Marilyn Monroe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/94/Whitney_Houston_by_Richard_Avedon_color_%28cropped%29.jpg", answer: "Whitney Houston" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Aretha_Franklin_1968.jpg", answer: "Aretha Franklin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/SWonderBSTHyde060719-72_%28cropped%29.jpg", answer: "Stevie Wonder" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Ray_Charles_classic_piano_pose.jpg", answer: "Ray Charles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/James_Brown_1996_%28HQ%29.jpg", answer: "James Brown" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Tina_Turner_1985_%28cropped%29.jpg", answer: "Tina Turner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/92/Janis_Joplin_1970.JPG", answer: "Janis Joplin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/37/Nirvana_around_1992_%28cropped%29.jpg", answer: "Kurt Cobain" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Amy_Winehouse_f4962007_crop.jpg", answer: "Amy Winehouse" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Britney_Spears_2013_%28Straighten_Crop%29.jpg", answer: "Britney Spears" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/MadonnaO2171023_%2897_of_133%29_%2853269593787%29_%28cropped%29.jpg", answer: "Madonna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Lady_Gaga_at_Joe_Biden%27s_inauguration_%28cropped_5%29.jpg", answer: "Lady Gaga" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg", answer: "Beyoncé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Rihanna_Fenty_2018.png", answer: "Rihanna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Adele_2016.jpg", answer: "Adele" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png", answer: "Taylor Swift" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg", answer: "Billie Eilish" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Ariana_Grande_promoting_Wicked_%282024%29.jpg", answer: "Ariana Grande" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Dua_Lipa-69798_%28cropped%29.jpg", answer: "Dua Lipa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Miley_Cyrus_Primavera19_-226_%2848986293772%29_%28cropped%29.jpg", answer: "Miley Cyrus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_10_%28cropped%29.jpg", answer: "Selena Gomez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/KatyPerryWestminst111224_%2881_of_95%29_%2854206733094%29_%28cropped_2%29.jpg", answer: "Katy Perry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/2023-11-16_Gala_de_los_Latin_Grammy%2C_03_%28cropped%2902.jpg", answer: "Shakira" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Jennifer_Lopez_at_the_2025_Sundance_Film_Festival_%28cropped_3%29.jpg", answer: "Jennifer Lopez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Christina_Aguilera_2019_Disney_Legends_Awards_Ceremony_D23_EXPO_2019_%2851440742748%29_%28cropped3%29.jpg", answer: "Christina Aguilera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/C%C3%A9line_Dion_2012.jpg", answer: "Celine Dion" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Luis_miguel_328_%28cropped%29_%282%29.jpg", answer: "Luis Miguel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Juan_Gabriel_---_Pepsi_Center_---_09.26.14_%28cropped_2%29.jpg", answer: "Juan Gabriel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/14/Vicente_Fern%C3%A1ndez_-_Pepsi_Center_-_06.11.11.jpg", answer: "Vicente Fernández" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Jos%C3%A9_Jos%C3%A9_y_Lee_Taylor_en_1970_%28cropped%29.webp", answer: "José José" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Julio_Iglesias09.jpg", answer: "Julio Iglesias" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Enrique_Iglesias_2011%2C_2.jpg", answer: "Enrique Iglesias" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Ricky_Martin_Golden_Globe_Awards_2018.jpg", answer: "Ricky Martin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Bad_Bunny_2019_by_Glenn_Francis_%28cropped%29.jpg", answer: "Bad Bunny" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg", answer: "Freddie Mercury" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/94/Bono_singing_in_Indianapolis_on_Joshua_Tree_Tour_2017_9-10-17.jpg", answer: "Bono" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/55/Jay-Z_meets_with_New_York_Senate_Majority_Leader_in_Albany_%28cropped%29.webp", answer: "Jay-Z" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Ed_Sheeran-6886_%28cropped%29.jpg", answer: "Ed Sheeran" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/191125_Shawn_Mendes_at_the_2019_American_Music_Awards.png", answer: "Shawn Mendes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d0/LanaDRPrimavera310524_%2832_of_147%29_%2853765476960%29_%28cropped%29.jpg", answer: "Lana Del Rey" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Glasto2025-546_%28cropped%29_%282%29.jpg", answer: "Olivia Rodrigo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/MIYAVI_from_%22American_Airlines%22_at_Opening_Ceremony_of_the_Tokyo_International_Film_Festival_2019_%2849013361203%29.jpg/3840px-MIYAVI_from_%22American_Airlines%22_at_Opening_Ceremony_of_the_Tokyo_International_Film_Festival_2019_%2849013361203%29.jpg", answer: "Miyavi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Hikaru_Utada_at_Spotify_Tokyo.png", answer: "Hikaru Utada" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/21/G-Dragon_in_October_2025.jpg", answer: "G-Dragon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/PSY_EMTV_logo_27_%288198008711%29.jpg", answer: "Psy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Jung_Kook_of_BTS%2C_February_12%2C_2026_%281%29.png", answer: "Jung Kook" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg", answer: "BTS" },
{ image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Chayanne_-_Chicago_2010-11-24.jpg", answer: "Chayanne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Interview_with_Marc_Anthony_%28cropped%29.png", answer: "Marc Anthony" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Daddy_Yankee_-_The_Kingdom_%28Official_Q_%26_A%29.png", answer: "Daddy Yankee" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/J_Balvin%2C_Noisey_Meets%3B_Oct_2018.jpg", answer: "J Balvin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/2023-11-16_Gala_de_los_Latin_Grammy%2C_20_%28Maluma%29.jpg", answer: "Maluma" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/2023-11-16_Gala_de_los_Latin_Grammy%2C_15.jpg/1920px-2023-11-16_Gala_de_los_Latin_Grammy%2C_15.jpg", answer: "Karol G" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Anuel_AA_in_2022.png", answer: "Anuel AA" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Ozuna-2019.jpg", answer: "Ozuna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/08/Romeo_Santos_y_Juan_Luis_Guerra_%28cropped%29.jpg", answer: "Romeo Santos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Don_Omar_-_The_Kingdom_%28Official_Q_%26_A%29.png", answer: "Don Omar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Nicki_Minaj_2025_%283x4_cropped%29.jpg", answer: "Nicki Minaj" },
{ image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Wisin_-_Tony_Dandrades_interview_-_2021.png", answer: "Wisin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Yandel_-_Como_Si_El_Mundo_Se_Fuera_A_Acabar_-_Behind_to_Scenes.png", answer: "Yandel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Carlos_gardel_en_su_casa_1933.jpg", answer: "Carlos Gardel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Mercedes_Sosa%2C_by_Annemarie_Heinrich.jpg", answer: "Mercedes Sosa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Gustavo_Cerati%2C_Madrid%2C_2006.10.10_retouched.jpg", answer: "Gustavo Cerati" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Charly_Garc%C3%ADa_%26_the_Prostitution_at_Cosqu%C3%ADn_Rock_12.02.2011_%285449800300%29.jpg", answer: "Charly García" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/Homenaje_Gustavo_Cerati_%2815528982867%29_%28cropped%29.jpg", answer: "Fito Páez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Andr%C3%A9s_Calamaro-Razzmatazz-03.jpg", answer: "Andrés Calamaro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Spinetta%2C_1969.jpg", answer: "Luis Alberto Spinetta" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/68/Banda_Mecano_1.png", answer: "Mecano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Joan_Manuel_Serrat_-_Gira_100x100_Serrat.jpg", answer: "Joan Manuel Serrat" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/BrunoMars24KMagicWorldTourLive_%28cropped%29.jpg", answer: "Bruno Mars" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Justin_Bieber_in_2015.jpg", answer: "Justin Bieber" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/HarryStylesWembley170623_%2865_of_93%29_%2852982678051%29_%28cropped_2%29.jpg", answer: "Harry Styles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/The_Weeknd_Portrait_by_Brian_Ziff.jpg", answer: "The Weeknd" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/SamSmith-byPhilipRomano.jpg/3840px-SamSmith-byPhilipRomano.jpg", answer: "Sam Smith" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Post_Malone_July_2021_%28cropped%29.jpg", answer: "Post Malone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Ozzy_Osbourne_in_1970_%28medium-sized_crop%29.jpg", answer: "Ozzy Osbourne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Rob_Halford.jpg", answer: "Rob Halford" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/James_Hetfield_2025_Marvel_Stadium_%288%29.jpg", answer: "James Hetfield" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Lars_Ulrich_2025_Marvel_Stadium_%285%29.jpg", answer: "Lars Ulrich" },
{ image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/RStonesHydePark030722_%2849_of_125%29_%2852193656268%29_%28cropped%29.jpg", answer: "Mick Jagger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Steven_Tyler_by_Gage_Skidmore_3.jpg", answer: "Steven Tyler" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Glasto2023_%28239_of_468%29_%2853009325175%29_%28cropped%29.jpg", answer: "Axl Rose" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Eddie_Vedder_2018_-2.jpg", answer: "Eddie Vedder" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Linkin_Park-Rock_im_Park_2014-_by_2eight_3SC0327.jpg", answer: "Chester Bennington" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/03/FoosDublin210819-6_%2848620330261%29_%28cropped%29.jpg", answer: "Dave Grohl" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/05/OasisCardiff040725-88_-_54640244776_%28landscape_crop%29_%28cropped%29.jpg", answer: "Liam Gallagher" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Noel_Gallagher_Glastonbury_2022_%28cropped%29.jpg", answer: "Noel Gallagher" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Kanye_West_at_the_2009_Tribeca_Film_Festival_%28crop_2%29.jpg", answer: "Kanye West" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Eminem_2021_Color_Corrected.jpg", answer: "Eminem" },
{ image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Snoop_Dogg_2023_%2853775197331%29_%28cropped%29_%28cropped%29.jpg", answer: "Snoop Dogg" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Tupac_Shakur_in_1995.jpg", answer: "Tupac Shakur" },
    { image: "https://upload.wikimedia.org/wikipedia/en/8/8c/Biggie_Smalls_1997.jpg", answer: "The Notorious B.I.G." },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Curtis_%2250_Cent%22_Jackson_visits_Barksdale_AFB_%285%29_%28cropped%29.jpg", answer: "50 Cent" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Ice_Cube_September_2025.png", answer: "Ice Cube" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Cardi_B_March_2024.png", answer: "Cardi B" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/18/KendrickSZASPurs230725-144_%28cropped%29_desaturated.jpg", answer: "Kendrick Lamar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/96/2025-0120_Cole_Gahagan_Michael_Rubin_Travis_Scott_%28cropped%29.jpg", answer: "Travis Scott" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Sia_%28cropped_2%29.jpg", answer: "Sia" },]