export interface CapitalQuestion {
    text: string;
    answer: string;
}

export const capitals: CapitalQuestion[] = [
    { text: "Argentina", answer: "Buenos Aires" },
    { text: "Brasil", answer: "Brasilia" },
    { text: "Chile", answer: "Santiago" },
    { text: "Uruguay", answer: "Montevideo" },
    { text: "Paraguay", answer: "Asunción" },
    { text: "Bolivia", answer: "Sucre" },
    { text: "Perú", answer: "Lima" },
    { text: "Ecuador", answer: "Quito" },
    { text: "Colombia", answer: "Bogotá" },
    { text: "Venezuela", answer: "Caracas" },

    { text: "Guyana", answer: "Georgetown" },
    { text: "Surinam", answer: "Paramaribo" },
    { text: "México", answer: "Ciudad de México" },
    { text: "Guatemala", answer: "Ciudad de Guatemala" },
    { text: "Belice", answer: "Belmopán" },
    { text: "Honduras", answer: "Tegucigalpa" },
    { text: "El Salvador", answer: "San Salvador" },
    { text: "Nicaragua", answer: "Managua" },
    { text: "Costa Rica", answer: "San José" },
    { text: "Panamá", answer: "Ciudad de Panamá" },

    { text: "Cuba", answer: "La Habana" },
    { text: "República Dominicana", answer: "Santo Domingo" },
    { text: "Haití", answer: "Puerto Príncipe" },
    { text: "Jamaica", answer: "Kingston" },
    { text: "Bahamas", answer: "Nassau" },

    { text: "Estados Unidos", answer: "Washington D. C." },
    { text: "Canadá", answer: "Ottawa" },

    { text: "España", answer: "Madrid" },
    { text: "Portugal", answer: "Lisboa" },
    { text: "Francia", answer: "París" },
    { text: "Alemania", answer: "Berlín" },
    { text: "Italia", answer: "Roma" },
    { text: "Reino Unido", answer: "Londres" },
    { text: "Irlanda", answer: "Dublín" },
    { text: "Países Bajos", answer: "Ámsterdam" },
    { text: "Bélgica", answer: "Bruselas" },
    { text: "Luxemburgo", answer: "Luxemburgo" },

    { text: "Suiza", answer: "Berna" },
    { text: "Austria", answer: "Viena" },
    { text: "Polonia", answer: "Varsovia" },
    { text: "Chequia", answer: "Praga" },
    { text: "Eslovaquia", answer: "Bratislava" },
    { text: "Hungría", answer: "Budapest" },
    { text: "Rumania", answer: "Bucarest" },
    { text: "Bulgaria", answer: "Sofía" },
    { text: "Grecia", answer: "Atenas" },
    { text: "Croacia", answer: "Zagreb" },

    { text: "Serbia", answer: "Belgrado" },
    { text: "Bosnia y Herzegovina", answer: "Sarajevo" },
    { text: "Eslovenia", answer: "Liubliana" },
    { text: "Albania", answer: "Tirana" },
    { text: "Macedonia del Norte", answer: "Skopie" },
    { text: "Montenegro", answer: "Podgorica" },
    { text: "Noruega", answer: "Oslo" },
    { text: "Suecia", answer: "Estocolmo" },
    { text: "Finlandia", answer: "Helsinki" },
    { text: "Dinamarca", answer: "Copenhague" },

    { text: "Islandia", answer: "Reikiavik" },
    { text: "Estonia", answer: "Tallin" },
    { text: "Letonia", answer: "Riga" },
    { text: "Lituania", answer: "Vilna" },
    { text: "Ucrania", answer: "Kiev" },
    { text: "Moldavia", answer: "Chisináu" },
    { text: "Bielorrusia", answer: "Minsk" },
    { text: "Rusia", answer: "Moscú" },

    { text: "Turquía", answer: "Ankara" },
    { text: "Georgia", answer: "Tiflis" },
    { text: "Armenia", answer: "Ereván" },
    { text: "Azerbaiyán", answer: "Bakú" },

    { text: "China", answer: "Pekín" },
    { text: "Japón", answer: "Tokio" },
    { text: "Corea del Sur", answer: "Seúl" },
    { text: "Corea del Norte", answer: "Pionyang" },
    { text: "India", answer: "Nueva Delhi" },
    { text: "Pakistán", answer: "Islamabad" },
    { text: "Bangladés", answer: "Daca" },
    { text: "Nepal", answer: "Katmandú" },
    { text: "Bután", answer: "Timbu" },
    { text: "Sri Lanka", answer: "Sri Jayawardenapura Kotte" },

    { text: "Myanmar", answer: "Naipyidó" },
    { text: "Tailandia", answer: "Bangkok" },
    { text: "Vietnam", answer: "Hanói" },
    { text: "Camboya", answer: "Nom Pen" },
    { text: "Laos", answer: "Vientián" },
    { text: "Malasia", answer: "Kuala Lumpur" },
    { text: "Singapur", answer: "Singapur" },
    { text: "Indonesia", answer: "Yakarta" },
    { text: "Filipinas", answer: "Manila" },

    { text: "Australia", answer: "Canberra" },
    { text: "Nueva Zelanda", answer: "Wellington" },

    { text: "Egipto", answer: "El Cairo" },
    { text: "Marruecos", answer: "Rabat" },
    { text: "Argelia", answer: "Argel" },
    { text: "Túnez", answer: "Túnez" },
    { text: "Libia", answer: "Trípoli" },

    { text: "Nigeria", answer: "Abuya" },
    { text: "Etiopía", answer: "Adís Abeba" },
    { text: "Kenia", answer: "Nairobi" },
    { text: "Sudáfrica", answer: "Pretoria" },
    { text: "Ghana", answer: "Acra" },
    { text: "Angola", answer: "Luanda" },
    { text: "Tanzania", answer: "Dodoma" },
    { text: "Uganda", answer: "Kampala" }
];