import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const cientificosInventores: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Bernardo_Alberto_Houssay.jpg", answer: "Bernardo Houssay" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Luis_Federico_Leloir_-_young.jpg", answer: "Luis Federico Leloir" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Milstein_lnp_restauraci%C3%B3n.jpg", answer: "César Milstein" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Rene_Favaloro.JPG", answer: "René Favaloro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Photo_of_Juan_Vucetich.jpg", answer: "Juan Vucetich" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Florentino_Ameghino_portrait.png", answer: "Florentino Ameghino" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Salvador_Mazza.JPG", answer: "Salvador Mazza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Domingo_Liotta.jpg", answer: "Domingo Liotta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/94/Eduardo_Holmberg.JPG", answer: "Eduardo Ladislao Holmberg" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Alberto-granado-scaled.JPG", answer: "Alberto Granado" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/3840px-Albert_Einstein_Head_cleaned.jpg", answer: "Albert Einstein" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Portrait_of_Sir_Isaac_Newton%2C_1689_%28brightened%29.jpg", answer: "Isaac Newton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff/lossy-page1-1920px-Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff.jpg", answer: "Galileo Galilei" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Tesla_circa_1890.jpeg", answer: "Nikola Tesla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Thomas_Edison2.jpg", answer: "Thomas Edison" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/James-Clerk-Maxwell-1831-1879.jpg", answer: "James Clerk Maxwell" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Michael_Faraday_sitting_crop.jpg", answer: "Michael Faraday" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Niels_Bohr.jpg", answer: "Niels Bohr" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Max_Planck_by_Hugo_Erfurth_1938cr_-_restoration1.jpg", answer: "Max Planck" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/42/Richard_Feynman_Nobel.jpg", answer: "Richard Feynman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Erwin_Schr%C3%B6dinger_-_Narodowe_Archiwum_Cyfrowe_%281-E-939%29.jpg", answer: "Erwin Schrödinger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Werner_Heisenberg_Portrait_%283x4_cropped%29.jpg", answer: "Werner Heisenberg" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Paul_Dirac%2C_1933.jpg", answer: "Paul Dirac" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Stephen_Hawking.StarChild.jpg", answer: "Stephen Hawking" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Charles_Darwin_seated_crop.jpg", answer: "Charles Darwin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Gregor_Mendel_2.jpg", answer: "Gregor Mendel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Louis_Pasteur%2C_foto_av_Paul_Nadar%2C_Crisco_edit.jpg", answer: "Louis Pasteur" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Synthetic_Production_of_Penicillin_TR1468.jpg", answer: "Alexander Fleming" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/RobertKoch_cropped.jpg", answer: "Robert Koch" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Edward_Jenner.jpg", answer: "Edward Jenner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/James_D._Watson_LCCN2007680359.jpg/3840px-James_D._Watson_LCCN2007680359.jpg", answer: "James Watson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Francis_Crick_crop.jpg", answer: "Francis Crick" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Rosalind_Franklin_%28retouched%29.jpg", answer: "Rosalind Franklin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Carl_von_Linn%C3%A9%2C_1707-1778%2C_botanist%2C_professor_%28Alexander_Roslin%29_-_Nationalmuseum_-_15723_%28cropped%29.tif/lossy-page1-1920px-Carl_von_Linn%C3%A9%2C_1707-1778%2C_botanist%2C_professor_%28Alexander_Roslin%29_-_Nationalmuseum_-_15723_%28cropped%29.tif.jpg", answer: "Carl Linnaeus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Ivan_Pavlov_NLM3.jpg", answer: "Ivan Pavlov" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Alan_turing_header.jpg", answer: "Alan Turing" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Tim_Berners-Lee_at_the_2025_Web_Summit_%28Cropped%29.jpg", answer: "Tim Berners-Lee" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/JohnvonNeumann-LosAlamos.gif", answer: "John von Neumann" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/C.E._Shannon._Tekniska_museet_43069_%282x3_crop%29.jpg", answer: "Claude Shannon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/23/Dennis_Ritchie_2011.jpg", answer: "Dennis Ritchie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Ken_Thompson%2C_2019.jpg", answer: "Ken Thompson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/LinuxCon_Europe_Linus_Torvalds_03_%28cropped%29.jpg", answer: "Linus Torvalds" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Donald_Ervin_Knuth_%28cropped%29.jpg", answer: "Donald Knuth" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/58/Edgar_F_Codd.jpg", answer: "Edgar F. Codd" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Dr_Vint_Cerf_ForMemRS_%28cropped%29.jpg", answer: "Vint Cerf" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Larry_Page_in_the_European_Parliament%2C_17.06.2009_%28cropped_2%29.jpg", answer: "Larry Page" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Sergey_Brin_Ted_2010_%28cropped%29.jpg", answer: "Sergey Brin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Bill_Gates_at_the_European_Commission_-_P067383-987995_%28cropped%29_5.jpg", answer: "Bill Gates" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/51/Steve_Jobs_Headshot_2010_%28cropped_4%29.jpg", answer: "Steve Jobs" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Steve_Wozniak_by_Gage_Skidmore_3_%28cropped%29.jpg", answer: "Steve Wozniak" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Elon_Musk_-_54820081119_%28cropped%29.jpg", answer: "Elon Musk" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/260202-D-PM193-2205_SECWAR_Arsenal_of_Freedom_Tour_-_Florida_%283x4_cropped_on_Bezos_and_rotated%29.jpg", answer: "Jeff Bezos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/F20250904AH-2824_%2854778373111%29_%283x4_cropped_on_Zuckerberg_following_the_rule_of_thirds%29.jpg", answer: "Mark Zuckerberg" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg", answer: "Warren Buffett" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Charlie_Munger_%28cropped%29.jpg", answer: "Charlie Munger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/MS-Exec-Nadella-Satya-2017-08-31-22_%28cropped%29.jpg", answer: "Satya Nadella" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Sundar_Pichai_-_2023_%28cropped%29.jpg", answer: "Sundar Pichai" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Tim_Cook_March_2026_%28cropped_2%29.jpg", answer: "Tim Cook" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/00/Larry_Ellison_picture.png", answer: "Larry Ellison" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Jack_Dorsey_in_Washington_D.C._-_2018_%2844538272181%29_%28cropped%29.jpg", answer: "Jack Dorsey" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Re_publica_2015_-_Tag_1_%2817381870955%29_%28cropped%29.jpg", answer: "Reed Hastings" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Marc_Andreessen-9_%28cropped%29.jpg", answer: "Marc Andreessen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Peter_Thiel_by_Gage_Skidmore.jpg", answer: "Peter Thiel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Meeting_with_Masayoshi_Son_and_Sam_Altman_%28February_3%2C_2025%29_%283x4_cropped_on_Altman%29.jpg", answer: "Sam Altman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Jen-Hsun_Huang_2025.jpg", answer: "Jensen Huang" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Andrew_Ng_at_TechCrunch_Disrupt_SF_2017.jpg", answer: "Andrew Ng" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Demis_Hassabis%2C_2024_Nobel_Prize_Laureate_in_Chemistry_7_%28cropped%29.jpg", answer: "Demis Hassabis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Orville_Wright_1905-crop.jpg", answer: "Wright brothers" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Watt_James_von_Breda.jpg", answer: "James Watt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/George_Stephenson_-_Project_Gutenberg_etext_13103.jpg", answer: "George Stephenson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Carl_Benz_circa_1920.jpg", answer: "Carl Benz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Henry_Ford_portrait_1915_original_%283x4_cropped%29.png", answer: "Henry Ford" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Guglielmo_Marconi.jpg", answer: "Guglielmo Marconi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Alexander_Graham_Bell_1895_NPG_77_363.jpg/3840px-Alexander_Graham_Bell_1895_NPG_77_363.jpg", answer: "Alexander Graham Bell" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Mainz_Gutenbergdenkmal_2016_%28cropped%29.jpg", answer: "Johannes Gutenberg" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Alessandro_Volta.jpeg", answer: "Alessandro Volta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Ampere_Andre_1825.jpg", answer: "André-Marie Ampère" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/16/Newcomen_atmospheric_engine_animation.gif", answer: "Thomas Newcomen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Rudolf_Diesel2.jpg", answer: "Rudolf Diesel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Sikorsky%2C_Igor.jpg", answer: "Igor Sikorsky" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Dr._Robert_H._Goddard_-_GPN-2002-000131.jpg", answer: "Robert H. Goddard" },
];
