import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const ciudades: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Puerto_Madero%2C_Buenos_Aires_%2840689219792%29_%28cropped%29.jpg", answer: "Buenos Aires" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/J30_869_Rosario.jpg/3840px-J30_869_Rosario.jpg", answer: "Rosario" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Palacio_Municipal_de_La_Plata_20..JPG/3840px-Palacio_Municipal_de_La_Plata_20..JPG", answer: "La Plata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/PT_TORREON3.jpg", answer: "Mar del Plata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Tucuman_San_Miguel_ciudad_capital_vista_de_noche_contexto_srl_revista_gonzaloluciani.jpg/3840px-Tucuman_San_Miguel_ciudad_capital_vista_de_noche_contexto_srl_revista_gonzaloluciani.jpg", answer: "San Miguel de Tucumán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/54/Panor%C3%A1mica_Ciudad_de_Salta.jpg", answer: "Salta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/SSDJ_Montage.jpg", answer: "San Salvador de Jujuy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Puente_General_Manuel_Belgrano.jpg", answer: "Corrientes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Landform_of_Formosa.png", answer: "Formosa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_La_Rioja_%28with_coat_of_arms%29.svg/960px-Flag_of_La_Rioja_%28with_coat_of_arms%29.svg.png", answer: "La Rioja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Santiago_del_Estero.jpg/3840px-Santiago_del_Estero.jpg", answer: "Santiago del Estero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Vista_a%C3%A9rea_Viedma_-_Carmen_de_Patagones.jpg", answer: "Viedma, Río Negro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/BancoNaci%C3%B3n_Trelew2008.JPG", answer: "Trelew" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Vista_de_Puerto_Madryn%2C_Argentina.jpg/3840px-Vista_de_Puerto_Madryn%2C_Argentina.jpg", answer: "Puerto Madryn" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Comodoro_Rivadavia.jpg", answer: "Comodoro Rivadavia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Rio_Gallegos_Montaje.jpg", answer: "Río Gallegos, Santa Cruz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ushuaia_aerial_panorama.jpg/3840px-Ushuaia_aerial_panorama.jpg", answer: "Ushuaia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/El_Calafate_%2825825005237%29.jpg/3840px-El_Calafate_%2825825005237%29.jpg", answer: "El Calafate" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/47/El_Chalt%C3%A9n.jpg", answer: "El Chaltén" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Catedral_desde_el_Lago_Nahuel_Huapi_-_panoramio.jpg/3840px-Catedral_desde_el_Lago_Nahuel_Huapi_-_panoramio.jpg", answer: "Bariloche" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Villa_Carlos_Paz_desde_el_Cerro_de_la_Cruz.jpg", answer: "Villa Carlos Paz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Villa_General_Belgrano.jpg", answer: "Villa General Belgrano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Tandil_desde_La_Movediza_2.JPG", answer: "Tandil" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Ski_ola.JPG", answer: "Olavarría, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Vistas_de_Bahia_Blanca_%2824%29.jpg/3840px-Vistas_de_Bahia_Blanca_%2824%29.jpg", answer: "Bahía Blanca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/31/CPCpanoramica2.JPG", answer: "San Martín de los Andes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Villa_La_Angostura_Montaje.jpg", answer: "Villa La Angostura" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Esquel_desde_Trochita.jpg", answer: "Esquel, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Downtown_Puerto_Iguazu%2C_Misiones%2C_Argentina%2C_6th._Jan._2011_-_Flickr_-_PhillipC.jpg/3840px-Downtown_Puerto_Iguazu%2C_Misiones%2C_Argentina%2C_6th._Jan._2011_-_Flickr_-_PhillipC.jpg", answer: "Puerto Iguazú" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/06/Pinamar061.JPG", answer: "Pinamar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Villa_Gesell_-_panoramio_-_VANT_Vistas_A%C3%A9reas_%2812%29.jpg/3840px-Villa_Gesell_-_panoramio_-_VANT_Vistas_A%C3%A9reas_%2812%29.jpg", answer: "Villa Gesell" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Puerto_Madero%2C_Buenos_Aires_%2840689219792%29_%28cropped%29.jpg", answer: "Buenos Aires" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Puente_General_Manuel_Belgrano.jpg", answer: "Corrientes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Landform_of_Formosa.png", answer: "Formosa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/SSDJ_Montage.jpg", answer: "San Salvador de Jujuy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Parque_Nacional_Lihu%C3%A9_Calel.jpg/3840px-Parque_Nacional_Lihu%C3%A9_Calel.jpg", answer: "La Pampa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_La_Rioja_%28with_coat_of_arms%29.svg/960px-Flag_of_La_Rioja_%28with_coat_of_arms%29.svg.png", answer: "La Rioja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Misiones_-_Parque_provincial_Salto_Encantado_desde_ruta_7.jpg/3840px-Misiones_-_Parque_provincial_Salto_Encantado_desde_ruta_7.jpg", answer: "Misiones" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/54/Panor%C3%A1mica_Ciudad_de_Salta.jpg", answer: "Salta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Santiago_del_Estero.jpg/3840px-Santiago_del_Estero.jpg", answer: "Santiago del Estero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/62/NASA_Tierra_del_Fuego_image.jpg", answer: "Tierra del Fuego" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tafi_del_Valle_-_postal.jpg/3840px-Tafi_del_Valle_-_postal.jpg", answer: "Tucumán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Marginal_Pinheiros_e_Jockey_Club.jpg", answer: "São Paulo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Cidade_Maravilhosa.jpg", answer: "Río de Janeiro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Planalto_Central_%28cropped%29.jpg", answer: "Brasília" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Palacio_de_La_Moneda_-_miguelreflex.jpg/3840px-Palacio_de_La_Moneda_-_miguelreflex.jpg", answer: "Santiago" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Historic_Quarter_of_the_Seaport_City_of_Valpara%C3%ADso_04.jpg", answer: "Valparaíso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/59/PALACIO_LEGISLATIVO_01.JPG", answer: "Montevideo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Palacio_de_Gobierno2.jpg", answer: "Asunción" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Bas%C3%ADlica_Catedral_Metropolitana_de_Lima_%28cropped%29.jpg", answer: "Lima" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Vista_Calle_Suecia.jpg/3840px-Vista_Calle_Suecia.jpg", answer: "Cusco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg/3840px-FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg", answer: "Quito" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Faro_de_Guayaquil.jpg", answer: "Guayaquil" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Bogota%2C_Colombia_%2836668708290%29.jpg", answer: "Bogotá" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/El_Poblado_Medell%C3%ADn.jpg", answer: "Medellín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Caracas_desde_el_%C3%A1vila.jpg", answer: "Caracas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Panama_Papers_%28148830809%29.jpeg", answer: "Ciudad de Panamá" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/12/DJI_0197_crp_wiki.jpg", answer: "La Habana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/SantoDomingoedit.JPG", answer: "Santo Domingo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Sobrevuelos_CDMX_HJ2A4913_%2825514321687%29_%28cropped%29.jpg/3840px-Sobrevuelos_CDMX_HJ2A4913_%2825514321687%29_%28cropped%29.jpg", answer: "Ciudad de México" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cancun_Strand_Luftbild_%2822143397586%29.jpg/3840px-Cancun_Strand_Luftbild_%2822143397586%29.jpg", answer: "Cancún" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Panor%C3%A1mica_Guadalajara_desde_edificio_Bansi_hacia_norte_%28cropped%29.jpg", answer: "Guadalajara" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/View_of_Monterrey_%282015%29.jpg/3840px-View_of_Monterrey_%282015%29.jpg", answer: "Monterrey" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/3840px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg", answer: "Nueva York" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Chicago_River_ferry_b.jpg", answer: "Chicago" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Las_Vegas_from_above_%2840064746644%29.jpg/3840px-Las_Vegas_from_above_%2840064746644%29.jpg", answer: "Las Vegas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Villa_Vizcaya_20110228.jpg", answer: "Miami" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/San_Francisco_Downtown_Aerial%2C_August_2025.jpg", answer: "San Francisco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/12-07-13-washington-by-RalfR-08.jpg", answer: "Washington, D.C." },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/96/ISH_WC_Boston4.jpg", answer: "Boston" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Seattle_Center_as_night_falls.jpg", answer: "Seattle" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Toronto_Skyline_from_Olympic_Island%2C_June_20_2026_%285-3_cropped%29.jpg/3840px-Toronto_Skyline_from_Olympic_Island%2C_June_20_2026_%285-3_cropped%29.jpg", answer: "Toronto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Montreal%2C_Quebec_skyline.jpg/3840px-Montreal%2C_Quebec_skyline.jpg", answer: "Montreal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Skyline_of_Vancouver%2C_Canada.jpg/3840px-Skyline_of_Vancouver%2C_Canada.jpg", answer: "Vancouver" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/3840px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg", answer: "París" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Plaza_Mayor_De_Madrid_%28215862629%29_edited.jpeg", answer: "Madrid" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Evening_light_over_Barcelona.jpg/3840px-Evening_light_over_Barcelona.jpg", answer: "Barcelona" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Milan_-_Scala_-_Facade.jpg/3840px-Milan_-_Scala_-_Facade.jpg", answer: "Milán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Berlin_collage.png", answer: "Berlín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/3840px-Stadtbild_M%C3%BCnchen.jpg", answer: "Múnich" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png", answer: "Ámsterdam" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Grand_Place_Bruselas_2.jpg", answer: "Bruselas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Lisboa_-_Portugal_%2852597836992%29.jpg", answer: "Lisboa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Puente_Don_Luis_I%2C_Oporto%2C_Portugal%2C_2012-05-09%2C_DD_13.JPG/3840px-Puente_Don_Luis_I%2C_Oporto%2C_Portugal%2C_2012-05-09%2C_DD_13.JPG", answer: "Oporto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Dublin_-_aerial_-_2025-07-07_01.jpg/3840px-Dublin_-_aerial_-_2025-07-07_01.jpg", answer: "Dublín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Skyline_of_Edinburgh.jpg/3840px-Skyline_of_Edinburgh.jpg", answer: "Edimburgo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ulica_Z%C4%85bkowska_przy_Targowej_2020.jpg/3840px-Ulica_Z%C4%85bkowska_przy_Targowej_2020.jpg", answer: "Praga" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/View_from_Gell%C3%A9rt_Hill_to_the_Danube%2C_Hungary_-_Budapest_%2828493220635%29.jpg", answer: "Budapest" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Iglesia_Atenas.jpg/3840px-Iglesia_Atenas.jpg", answer: "Atenas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Saint_Basil%27s_Cathedral_and_the_Red_Square.jpg", answer: "Moscú" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/%D0%91%D1%83%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA_%D0%B7_%D1%85%D0%B8%D0%BC%D0%B5%D1%80%D0%B0%D0%BC%D0%B8%2C_%D1%81%D0%B5%D1%80%D0%BF%D0%B5%D0%BD%D1%8C_2019.jpg/3840px-%D0%91%D1%83%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA_%D0%B7_%D1%85%D0%B8%D0%BC%D0%B5%D1%80%D0%B0%D0%BC%D0%B8%2C_%D1%81%D0%B5%D1%80%D0%BF%D0%B5%D0%BD%D1%8C_2019.jpg", answer: "Kiev" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/2018_-_Christiansborg_from_the_Marble_Bridge.jpg/3840px-2018_-_Christiansborg_from_the_Marble_Bridge.jpg", answer: "Copenhague" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/3a/Estocolmo-identidad-perdida-2.jpg", answer: "Estocolmo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Nationaltheatret_evening.jpg/3840px-Nationaltheatret_evening.jpg", answer: "Oslo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Suomenlinna_%28cropped%29.jpg", answer: "Helsinki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Osaka_Castle_02bs3200.jpg/3840px-Osaka_Castle_02bs3200.jpg", answer: "Osaka" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/960px-Flag_of_Hong_Kong.svg.png", answer: "Hong Kong" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/4Y1A1159_Bangkok_%2833536795515%29.jpg", answer: "Bangkok" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/960px-Flag_of_Singapore.svg.png", answer: "Singapur" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Abu_dhabi_skylines_2014.jpg/3840px-Abu_dhabi_skylines_2014.jpg", answer: "Abu Dhabi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/The_Pearl_Marina_in_Nov_2013.jpg", answer: "Doha" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sarona_CBD_01_%28cropped%29.jpg/3840px-Sarona_CBD_01_%28cropped%29.jpg", answer: "Tel Aviv" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Colombia_-_Valle_del_Cauca_-_El_Cairo.svg/1280px-Colombia_-_Valle_del_Cauca_-_El_Cairo.svg.png", answer: "El Cairo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Casa_finance_city_6_%28cropped%29.jpg", answer: "Casablanca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/18/Morocco_-_Rabat_%2831387775324%29.jpg", answer: "Rabat" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/46/Dakar-Ind%C3%A9pendance.jpg", answer: "Dakar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Tafa_Balewa_Square_%28Onikan%29_in_Lagos._Nigeria.jpg", answer: "Lagos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Melbourne_skyline_sor.jpg", answer: "Melbourne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg/3840px-Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg", answer: "Brisbane" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Perth_CBD_skyline_from_State_War_Memorial_Lookout%2C_2023%2C_04_b.jpg/3840px-Perth_CBD_skyline_from_State_War_Memorial_Lookout%2C_2023%2C_04_b.jpg", answer: "Perth" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Canberra_panorama_from_Mount_Ainslie.jpg/3840px-Canberra_panorama_from_Mount_Ainslie.jpg", answer: "Canberra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Auckland_skyline_-_May_2024_%282%29.jpg/3840px-Auckland_skyline_-_May_2024_%282%29.jpg", answer: "Auckland" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Seddon_Statue_in_Parliament_Grounds.jpg", answer: "Wellington" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_California.svg/960px-Flag_of_California.svg.png", answer: "California" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Texas.svg/960px-Flag_of_Texas.svg.png", answer: "Texas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Florida.svg/3840px-Flag_of_Florida.svg.png", answer: "Florida" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/1920px-Flag_of_Alaska.svg.png", answer: "Alaska" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Hawaii.svg/1280px-Flag_of_Hawaii.svg.png", answer: "Hawái" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_Andaluc%C3%ADa.svg/960px-Flag_of_Andaluc%C3%ADa.svg.png", answer: "Andalucía" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Catalonia.svg/960px-Flag_of_Catalonia.svg.png", answer: "Cataluña" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Sicily_in_Italy.svg/1280px-Sicily_in_Italy.svg.png", answer: "Sicilia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tuscany_in_Italy.svg/1280px-Tuscany_in_Italy.svg.png", answer: "Toscana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/Cathedral_Main_Square.jpg", answer: "Córdoba, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/Downtown_Mendoza.jpg", answer: "Mendoza, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Collage_Ciudad_de_San_Juan.jpg", answer: "San Juan, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Ciudad_de_San_Luis%2C_provincia_de_San_Luis%2C_Argentina.jpg/3840px-Ciudad_de_San_Luis%2C_provincia_de_San_Luis%2C_Argentina.jpg", answer: "San Luis, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Santa_Fe%2C_Argentina_2019_%28letras%29.jpg/3840px-Santa_Fe%2C_Argentina_2019_%28letras%29.jpg", answer: "Santa Fe, Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Panor%C3%A1mica_de_Paran%C3%A1%2C_Entre_R%C3%ADos.jpg/3840px-Panor%C3%A1mica_de_Paran%C3%A1%2C_Entre_R%C3%ADos.jpg", answer: "Paraná, Entre Ríos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Posadas_Montage.jpg", answer: "Posadas, Misiones" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Resistencia_Montage.jpg", answer: "Resistencia, Chaco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Casa_de_Gobierno_del_Chubut.jpg", answer: "Rawson, Chubut" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/San_Rafael%2C_Mendoza_27.jpg", answer: "San Rafael, Mendoza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/CATAMARCA_318_%282%29.jpg/3840px-CATAMARCA_318_%282%29.jpg", answer: "Catamarca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/R%C3%ADo_negro_%28Chaco%2C_Argentina%29_in_Villa_Fabiana.JPG", answer: "Chaco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Villa_Lago_Rivadavia_y_cordillera_de_los_Andes.JPG/3840px-Villa_Lago_Rivadavia_y_cordillera_de_los_Andes.JPG", answer: "Chubut" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Parana%2C_Entre_Rios%2C_Argentina_-_panoramio_%281001%29.jpg", answer: "Entre Ríos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Aconcagua_%28aerial%29.jpg", answer: "Mendoza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Lanin_%283275580393%29.jpg", answer: "Neuquén" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/92/View_from_the_Golf_course_at_Llao_Llao.jpg", answer: "Río Negro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Atardecer_con_el_Cerro_Negro.JPG", answer: "San Luis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/National_Flag_Memorial.jpg/3840px-National_Flag_Memorial.jpg", answer: "Santa Fe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/30/Museo_Naval_del_Caribe.JPG", answer: "Cartagena, Colombia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Ciudad_de_San_Jos%C3%A9.png", answer: "San José, Costa Rica" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hollywood_sign_%288485145044%29.jpg/3840px-Hollywood_sign_%288485145044%29.jpg", answer: "Los Ángeles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/67/London_Skyline_%28125508655%29.jpeg", answer: "Londres" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Trevi_Fountain%2C_Rome%2C_Italy_2_-_May_2007.jpg", answer: "Roma" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Venezia_aerial_view.jpg/3840px-Venezia_aerial_view.jpg", answer: "Venecia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Firenze_-_Piazzale_Michelangelo%2C_Firenze%2C_Italy_-_April_6%2C_2015_02.jpg/3840px-Firenze_-_Piazzale_Michelangelo%2C_Firenze%2C_Italy_-_April_6%2C_2015_02.jpg", answer: "Florencia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Hamburg%2C_Landungsbr%C3%BCcken_--_2016_--_3131-7.jpg/3840px-Hamburg%2C_Landungsbr%C3%BCcken_--_2016_--_3131-7.jpg", answer: "Hamburgo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Schoenbrunn_philharmoniker_2012.jpg/3840px-Schoenbrunn_philharmoniker_2012.jpg", answer: "Viena" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/35/Aleja_Niepdleglosci_Warsaw_2022_aerial_%28cropped%29.jpg", answer: "Varsovia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Krakow_Rynek_Glowny_panorama_2.jpg/3840px-Krakow_Rynek_Glowny_panorama_2.jpg", answer: "Cracovia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Historical_peninsula_and_modern_skyline_of_Istanbul.jpg", answer: "Estambul" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Spb_06-2017_img20_StMichael_Castle_%28cropped%29.jpg/3840px-Spb_06-2017_img20_StMichael_Castle_%28cropped%29.jpg", answer: "San Petersburgo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Altstadt_Z%C3%BCrich_2015.jpg/3840px-Altstadt_Z%C3%BCrich_2015.jpg", answer: "Zúrich" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Geneve_2005_001_Ork.ch.jpg", answer: "Ginebra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg", answer: "Tokio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Skyline_of_Beijing_CBD_with_B-5906_approaching_%2820211016171955%29_%281%29.jpg/3840px-Skyline_of_Beijing_CBD_with_B-5906_approaching_%2820211016171955%29_%281%29.jpg", answer: "Pekín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Huangpu_Park_20124-Shanghai_%2832208802494%29.jpg", answer: "Shanghái" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg/3840px-%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg", answer: "Seúl" },
    { image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Burj_Khalifa_2021.jpg/3840px-Burj_Khalifa_2021.jpg", answer: "Dubái" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Dome_of_the_Rock_seen_from_the_Mount_of_Olives_%2812395649153%29_%28cropped%29.jpg", answer: "Jerusalén" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Forecourt%2C_Rashtrapati_Bhavan_-_1.jpg/3840px-Forecourt%2C_Rashtrapati_Bhavan_-_1.jpg", answer: "Nueva Delhi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Botanical_Garden_Hamma.jpg/3840px-Botanical_Garden_Hamma.jpg", answer: "Argel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Minaret_et_patio_de_la_mosqu%C3%A9e_Zitouna_au_centre_de_la_M%C3%A9dina_de_Tunis.jpg/3840px-Minaret_et_patio_de_la_mosqu%C3%A9e_Zitouna_au_centre_de_la_M%C3%A9dina_de_Tunis.jpg", answer: "Túnez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Camps_bay_%2853460319478%29_%28cropped%29.jpg/3840px-Camps_bay_%2853460319478%29_%28cropped%29.jpg", answer: "Ciudad del Cabo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg/3840px-Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg", answer: "Sídney" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_Bavaria_%28lozengy%29.svg/1280px-Flag_of_Bavaria_%28lozengy%29.svg.png", answer: "Baviera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Galicia_in_Spain_%28including_Canarias%29.svg/1280px-Galicia_in_Spain_%28including_Canarias%29.svg.png", answer: "Galicia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_Scotland.svg/1280px-Flag_of_Scotland.svg.png", answer: "Escocia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/960px-Flag_of_Wales.svg.png", answer: "Gales" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Normandie.svg/960px-Flag_of_Normandie.svg.png", answer: "Normandía" },
];
