import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const comidas: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Asado_2005.jpg", answer: "Asado" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Choripan.jpg", answer: "Choripán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/18/Milanesa_con_fritas.png", answer: "Milanesa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Tapa_de_empanadillitas.JPG", answer: "Empanada" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/22/Locro_argentino.jpg", answer: "Locro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Humitas.jpg", answer: "Humita" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Tamale_Oaxaque%C3%B1o.jpg", answer: "Tamale" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Puchero2.jpg", answer: "Puchero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Matambrerelleno.JPG", answer: "Matambre" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/3840px-Pizza-3007395.jpg", answer: "Pizza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/RedDot_Burger.jpg/3840px-RedDot_Burger.jpg", answer: "Hamburger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/94/S%C3%A1ndwich_de_milanesa_tucumano.jpg", answer: "Milanesa sandwich" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Factura_membrillo.jpg", answer: "Facturas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Lasagne_-_stonesoup.jpg", answer: "Lasagna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Espaguetis_carbonara.jpg", answer: "Carbonara" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Tagliatelle_al_rag%C3%B9_%28image_modified%29.jpg", answer: "Bolognese sauce" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Risotto_with_speck_and_goat_cheese_%286101067436%29.jpg", answer: "Risotto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Gnocchi_di_ricotta_burro_e_salvia.jpg", answer: "Gnocchi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Focaccia_with_Crumb.jpg", answer: "Focaccia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/2014_Bruschetta_The_Larder_Chiang_Mai.jpg", answer: "Bruschetta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Wikimania_2016_Deryck_day_0_-_07_calzone.jpg/3840px-Wikimania_2016_Deryck_day_0_-_07_calzone.jpg", answer: "Calzone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/80/Panna_Cotta_with_cream_and_garnish.jpg", answer: "Panna cotta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Cannoli_siciliani_al_Caff%C3%A8_Impero%2C_ad_Alcamo.jpg", answer: "Cannoli" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ed/01_Paella_Valenciana_original.jpg", answer: "Paella" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Gazpacho_Malague%C3%B1o_con_su_%E2%80%9Cpica%C3%ADto%E2%80%9D_-_Moreno%2C_Playa_Burriana_%28cropped%29.jpg", answer: "Gazpacho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Croquetas_Caseras_%287068664101%29.jpg", answer: "Croquette" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Jamon_iberico_de_bellota_2_%28cinco_jotas%29.jpg/3840px-Jamon_iberico_de_bellota_2_%28cinco_jotas%29.jpg", answer: "Jamón ibérico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Chocolate_con_churros_%2827343655726%29.jpg", answer: "Churro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Polbo_a_feira.jpg", answer: "Polbo á feira" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tortilla_de_patata_-_San_Sebasti%C3%A1n.jpg/3840px-Tortilla_de_patata_-_San_Sebasti%C3%A1n.jpg", answer: "Spanish omelette" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Croissant-Petr_Kratochvil.jpg", answer: "Croissant" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Baguettes%2C_Paris%2C_France_-_panoramio.jpg", answer: "Baguette" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Quiche_de_Lorraine.jpg", answer: "Quiche Lorraine" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/37/Ratatouille_home_cooked.jpg", answer: "Ratatouille" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Gourmet_coq_au_vin.jpg", answer: "Coq au vin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/Crepes_dsc07085.jpg", answer: "Crêpe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Bacon_and_Cheddar_Cheese_Souffl%C3%A9.jpg/3840px-Bacon_and_Cheddar_Cheese_Souffl%C3%A9.jpg", answer: "Soufflé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Fondue_dish.jpg", answer: "Fondue" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Wiener-Schnitzel02.jpg", answer: "Wiener schnitzel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/German_Bratw%C3%BCrste.jpg", answer: "Bratwurst" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Gulyas080.jpg", answer: "Goulash" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Pierogi_z_mas%C5%82em_-_2023.03.31.jpg/3840px-Pierogi_z_mas%C5%82em_-_2023.03.31.jpg", answer: "Pierogi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/MussakasMeMelitsanesKePatates01.JPG", answer: "Moussaka" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Pita_giros.JPG", answer: "Gyros" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Souvlaki_in_Athens.JPG", answer: "Souvlaki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Baklava%281%29.png", answer: "Baklava" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Lula_kebab_2.jpg/3840px-Lula_kebab_2.jpg", answer: "Kebab" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Falafels_2.jpg/3840px-Falafels_2.jpg", answer: "Falafel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/%D0%A8%D0%B0%D1%83%D1%80%D0%BC%D0%B0_6.jpg/3840px-%D0%A8%D0%B0%D1%83%D1%80%D0%BC%D0%B0_6.jpg", answer: "Shawarma" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Lebanese_style_hummus.jpg", answer: "Hummus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Tabouleh_1.JPG", answer: "Tabbouleh" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Baba_Ganoush_05of05_%288735238183%29.jpg", answer: "Baba ghanoush" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg", answer: "Couscous" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Tajine-marocain-un-plat-varie-et-sain_%28cropped%29.jpg", answer: "Tagine" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Chinese_DimSum_%289023590541%29.jpg/3840px-Chinese_DimSum_%289023590541%29.jpg", answer: "Dim sum" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg", answer: "Sushi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/241109_Shigaraki_ware_Koga_Shiga_pref_Japan01s3.jpg/3840px-241109_Shigaraki_ware_Koga_Shiga_pref_Japan01s3.jpg", answer: "Sashimi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg", answer: "Ramen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Tempura_01.jpg", answer: "Tempura" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/97/Kakeudon.jpg", answer: "Udon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Cooking_yakitori.jpg", answer: "Yakitori" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Takoyaki.jpg", answer: "Takoyaki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Okonomiyaki_001.jpg/3840px-Okonomiyaki_001.jpg", answer: "Okonomiyaki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/%E5%B0%8F%E6%96%99%E7%90%86%E3%83%90%E3%83%AB%E3%81%95%E3%81%8F%E3%82%89_%E7%89%B9%E8%A3%BD%E3%81%8A%E3%81%AB%E3%81%8E%E3%82%8A.jpg", answer: "Onigiri" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/%22Amai-Yuwaku%22_Special_Loin_Pork_Cutlet1.jpg/3840px-%22Amai-Yuwaku%22_Special_Loin_Pork_Cutlet1.jpg", answer: "Tonkatsu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Miso_Soup_001.jpg", answer: "Miso soup" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Various_kimchi.jpg", answer: "Kimchi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/3840px-Dolsot-bibimbap.jpg", answer: "Bibimbap" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Bulgogi_2.jpg", answer: "Bulgogi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Polish_Korean_Cuisine_and_Culture_Exchanges_Gradmother%E2%80%99s_Recipes_05.jpg/3840px-Polish_Korean_Cuisine_and_Culture_Exchanges_Gradmother%E2%80%99s_Recipes_05.jpg", answer: "Japchae" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Tteokbokki.JPG/3840px-Tteokbokki.JPG", answer: "Tteokbokki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Phat_Thai_kung_Chang_Khien_street_stall.jpg", answer: "Pad thai" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tom_yam_kung_maenam.jpg", answer: "Tom yum" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Kaeng_phet_mu.jpg", answer: "Red curry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bowl_of_Meatball_pho.jpg/3840px-Bowl_of_Meatball_pho.jpg", answer: "Pho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_n%C6%B0%E1%BB%9Bng.png", answer: "Bánh mì" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Nasi_Goreng_Kampung_%2811967588375%29.jpg", answer: "Nasi goreng" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Sate_Udang.JPG", answer: "Satay" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/41/Butter_Chicken_%26_Butter_Naan_-_Home_-_Chandigarh_-_India_-_0006.jpg", answer: "Butter chicken" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/00/Chicken_tikka_masala_%28cropped%29.jpg", answer: "Chicken tikka masala" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/3840px-%22Hyderabadi_Dum_Biryani%22.jpg", answer: "Biryani" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg/3840px-Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg", answer: "Samosa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Annapurna_Naan.jpg", answer: "Naan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Palakpaneer_Rayagada_Odisha_0009.jpg", answer: "Palak paneer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/67/Rogan_Josh_Kashmiri.jpg", answer: "Rogan josh" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Beef_Vindaloo_-_Chilli_Mama%2C_Chadstone_%283014236693%29.jpg", answer: "Vindaloo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/3840px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg", answer: "Taco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Burrito.JPG", answer: "Burrito" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Empanada_flor_de_Calabaza.jpg", answer: "Quesadilla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Enchilada_Rice_Beans.jpg", answer: "Enchilada" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Nachos-cheese.jpg", answer: "Nachos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Guacamole_IMGP1271.jpg/3840px-Guacamole_IMGP1271.jpg", answer: "Guacamole" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Green_pozole%2C_dressed_%2829161841908%29_%28cropped%29.jpg", answer: "Pozole" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Tamale_Oaxaque%C3%B1o.jpg", answer: "Tamale" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Cebiche_de_corvina.JPG", answer: "Ceviche" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/80/Lomo_Saltado_-_Lima%2C_Peru_Miraflores_%28Tiendecita_Blanca%29.jpg", answer: "Lomo saltado" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Arepitas_Food_Macro.jpg", answer: "Arepa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bandeja_paisa%2C_plato_Colombiano.jpg/3840px-Bandeja_paisa%2C_plato_Colombiano.jpg", answer: "Bandeja paisa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Sancocho_de_espinazo_de_cerdo.jpg", answer: "Sancocho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Feijoada_%C3%A0_transmontada.jpg", answer: "Feijoada" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Cheesebread.jpg", answer: "Pão de queijo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Moqueca.jpg", answer: "Moqueca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Cheeseburger.jpg", answer: "Cheeseburger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Hot_dog_with_mustard.png", answer: "Hot dog" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/51/Buffalo_wings-01.jpg", answer: "Buffalo wing" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Original_Mac_n_Cheese_.jpg", answer: "Macaroni and cheese" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Quail_07_bg_041506.jpg", answer: "Clam chowder" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Food_at_WIkimanian_2017_02.jpg", answer: "Poutine" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Lattice_apple_pie.png", answer: "Apple pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Pecan_pie%2C_November_2010.jpg", answer: "Pecan pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Pumpkin-Pie-Whole-Slice.jpg/3840px-Pumpkin-Pie-Whole-Slice.jpg", answer: "Pumpkin pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg", answer: "Pancake" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Bagel_with_sesame_3.jpg/3840px-Bagel_with_sesame_3.jpg", answer: "Bagel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/30/BrezelnSalz02_%28cropped%29.JPG", answer: "Pretzel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Rib_cage.gif", answer: "Rib cage" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/eb/OnionRings.JPG", answer: "Onion ring" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Fish_and_chips_blackpool.jpg/3840px-Fish_and_chips_blackpool.jpg", answer: "Fish and chips" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg", answer: "Shepherd's pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Full_English_breakfast_%28cropped%29.jpg", answer: "Full breakfast" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Three_Bars_%281%29.jpg/3840px-Three_Bars_%281%29.jpg", answer: "Chocolate" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Carrot_cake_at_America_Graffiti_%28cropped%29.jpg", answer: "Carrot cake" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Banoffeepie.jpg", answer: "Banoffee pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/47/CafeMia.jpg", answer: "Gelato" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/45/French_fry_frozen_yoghurt.jpg", answer: "Frozen yogurt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Turr%C3%B3n_de_Alicante_%28Casa_Mira%29.jpg/3840px-Turr%C3%B3n_de_Alicante_%28Casa_Mira%29.jpg", answer: "Turrón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Rolling_out_the_marzipan_%2811029638025%29.jpg/3840px-Rolling_out_the_marzipan_%2811029638025%29.jpg", answer: "Marzipan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Nougat.jpg", answer: "Nougat" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/Crepes_dsc07085.jpg", answer: "Crêpe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Waffles_with_Strawberries.jpg", answer: "Waffle" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Lemon_tart_-_star5112.jpg/3840px-Lemon_tart_-_star5112.jpg", answer: "Lemon tart" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg", answer: "Cheesecake" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Nuremberg_chronicles_-_BVJA.png", answer: "Buda" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/02116jfMuffins_in_Philippinesfvf_02.jpg/3840px-02116jfMuffins_in_Philippinesfvf_02.jpg", answer: "Muffin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Cupcakes%2C_chocolate_and_strawberry_flavour.jpg", answer: "Cupcake" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Choco_chip_cookie.png", answer: "Cookie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/DonasTowe.jpg", answer: "Donas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Tiramisu_-_Raffaele_Diomede.jpg", answer: "Tiramisu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg", answer: "Crème brûlée" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Paris_2e_-_Rue_Vivienne_-_Restaurant_Le_Vaudeville_-_Profiteroles_au_chocolat.jpg/3840px-Paris_2e_-_Rue_Vivienne_-_Restaurant_Le_Vaudeville_-_Profiteroles_au_chocolat.jpg", answer: "Profiterole" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Two_Safeway_Chocolate_Eclairs_%2819043880936%29.jpg", answer: "Éclair" },
];