import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const cuerpo: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/VolRenderShearWarp.gif", answer: "Cráneo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Mandible_bone_-_animation_02.gif", answer: "Mandíbula" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Maxilla_anterior.png", answer: "Maxilar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Male_forehead-01_ies.jpg", answer: "Frente" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Philae_temple_at_night.jpg", answer: "Sien" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Geisha-kyoto-2004-11-21.jpg", answer: "Nuca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Neck.png", answer: "Cuello" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Structure_of_Adam%27s_apple.png", answer: "Nuez de Adán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/06/Crane3chin.png", answer: "Mentón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Cheek.jpg", answer: "Mejilla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Zygomatic_bone_anterior.png", answer: "Hueso cigomático" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Canine_Nose_Macro_Photo.png", answer: "Nariz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Gray854.png", answer: "Tabique nasal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Human_Nostrils_01.JPG", answer: "Fosa nasal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Human_right_ear_%28cropped%29.jpg", answer: "Oreja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Gray904.png", answer: "Lóbulo de la oreja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Blausen_0328_EarAnatomy.png", answer: "Tímpano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Krilleyekils.jpg", answer: "Ojo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Closed_human_eye%2C_superior_view.jpg", answer: "Párpado" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Human_eyelashes.jpg", answer: "Pestaña" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Jeremy_Cadot%27s_eyebrow.jpg", answer: "Ceja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Eye_iris.jpg", answer: "Pupila" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Human_eye_cross-sectional_view_grayscale.png", answer: "Retina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/61/Cornea.png", answer: "Córnea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Double-lens_burning_apparatus%2C_Ehrenfried_Walther_von_Tschirnhaus%2C_Kieslingswalde_%28today_Slawonice%2C_Poland%29%2C_c._1690_-_Mathematisch-Physikalischer_Salon%2C_Dresden_-_DSC08133.JPG", answer: "Cristalino" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/%D8%B2%D8%A8%D8%A7%D9%86_tongue.jpg", answer: "Lengua" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Close_up_-_chimpanzee_teeth.png", answer: "Diente" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Lower_wisdom_tooth.jpg", answer: "Muela" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Gray1003.png", answer: "Incisivo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Illu01_head_neck.jpg", answer: "Paladar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Lips_2023.jpg", answer: "Labio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Lips_2023.jpg", answer: "Labio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Blausen_0863_ToothAnatomy_02.png", answer: "Encías" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Tonsils_diagram.jpg", answer: "Amígdala" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Illu01_head_neck.jpg", answer: "Faringe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Larynx_external_en.svg/1280px-Larynx_external_en.svg.png", answer: "Laringe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Illu_conducting_passages.svg/330px-Illu_conducting_passages.svg.png", answer: "Tráquea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Tractus_intestinalis_esophagus.svg/960px-Tractus_intestinalis_esophagus.svg.png", answer: "Esófago" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Clavicle_-_anterior_view.png/3840px-Clavicle_-_anterior_view.png", answer: "Clavícula" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Pectoral_girdle_front_diagram.svg/960px-Pectoral_girdle_front_diagram.svg.png", answer: "Escápula" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Pectoral_girdle_front_diagram.svg/960px-Pectoral_girdle_front_diagram.svg.png", answer: "Escápula" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Sternum_composition.png/3840px-Sternum_composition.png", answer: "Esternón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Rib_cage.gif", answer: "Caja torácica" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cervical_vertebrae_lateral2.png/3840px-Cervical_vertebrae_lateral2.png", answer: "Vértebras cervicales" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Thoracic_vertebrae_back5.png", answer: "Vértebras torácicas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Lumbar_vertebrae_anterior.png/3840px-Lumbar_vertebrae_anterior.png", answer: "Vértebras lumbares" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Sacrum_-_anterior_view04.png", answer: "Sacro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Coccyx_-_anterior_view02.png", answer: "Cóccix" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/Chest.jpg", answer: "Tórax" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/Chest.jpg", answer: "Tórax" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Posterior_view_of_human_female_and_male_backs_%28cropped%29.jpg", answer: "Espalda" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Waist.svg/960px-Waist.svg.png", answer: "Cintura" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Abdomen-periumbilical_region.png", answer: "Abdomen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Human_navel%2C_female.jpg", answer: "Ombligo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Gray241.png", answer: "Pelvis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Hip.jpg", answer: "Cadera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Dr_Bock_plate11a.jpg", answer: "Ingle" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Human_buttocks.jpg", answer: "Glúteos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Left_shoulder.jpg/3840px-Left_shoulder.jpg", answer: "Hombro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/ArmpitHair2.jpg/3840px-ArmpitHair2.jpg", answer: "Axila" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Extended_arm.jpg/3840px-Extended_arm.jpg", answer: "Brazo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/1120_Muscles_that_Move_the_Forearm_Humerus_Flex_Sin.png", answer: "Bíceps" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/83/Triceps_brachii.png", answer: "Tríceps" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/93/Deltoideus.png", answer: "Músculo deltoides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Circle-withsegments.svg/960px-Circle-withsegments.svg.png", answer: "Radio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Ulna_-_anterior_view.png/3840px-Ulna_-_anterior_view.png", answer: "Cúbito" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Elbow_on_gray_background.jpg/3840px-Elbow_on_gray_background.jpg", answer: "Codo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Nadgarstek_%28ubt%29.jpeg", answer: "Muñeca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Liam_Thumb.jpg", answer: "Pulgar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Index_finger_%3D_to_attention.JPG", answer: "Dedo índice" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Hand_-_Middle_finger.jpg", answer: "Dedo medio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Ring_Finger_Kian.jpg/1920px-Ring_Finger_Kian.jpg", answer: "Dedo anular" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Little_finger.jpg", answer: "Dedo meñique" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Nail_svg_hariadhi.svg/960px-Nail_svg_hariadhi.svg.png", answer: "Uña" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Thigh.jpg", answer: "Muslo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Quadriceps_3D.gif", answer: "Cuádriceps" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Hamstrings.gif", answer: "Isquiotibiales" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Human_knees.jpg", answer: "Rodilla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Knee_diagram.svg/960px-Knee_diagram.svg.png", answer: "Rótula" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Gastrocnemius_muscle_by_Sanjoy_Sanyal_2018-06-02.webm/960px--Gastrocnemius_muscle_by_Sanjoy_Sanyal_2018-06-02.webm.jpg", answer: "Músculo gastrocnemio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Tibia_-_frontal_view.png/3840px-Tibia_-_frontal_view.png", answer: "Tibia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Fibula_-_anterior_view.png/3840px-Fibula_-_anterior_view.png", answer: "Peroné" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Ankle.jpg", answer: "Tobillo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Girls_heel.jpg", answer: "Talón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Foot_on_white_background.jpg/3840px-Foot_on_white_background.jpg", answer: "Pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Foot_on_white_background.jpg/3840px-Foot_on_white_background.jpg", answer: "Pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Gray290.png", answer: "Arco del pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Toes.png", answer: "Dedo del pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Toes.png", answer: "Dedo del pie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Trapezius.png", answer: "Trapecio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Gray410.png", answer: "Pectoral mayor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Pectoralis_minor.svg/500px-Pectoralis_minor.svg.png", answer: "Pectoral menor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Latissimus.jpg", answer: "Dorsal ancho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Rhomboidei.PNG", answer: "Músculos romboides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/SerratusMagnus.jpg", answer: "Serrato anterior" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Rectus_abdominis.png", answer: "Recto abdominal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Illu_trunk_muscles.jpg", answer: "Oblicuo externo del abdomen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Gray395.png", answer: "Oblicuo interno del abdomen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Illu_trunk_muscles.jpg", answer: "Transverso del abdomen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Gray389_-_Erector_spinae.png", answer: "Músculos erectores de la columna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Gluteus_maximus_3D.gif", answer: "Glúteo mayor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Gluteus_medius_muscle08.png/3840px-Gluteus_medius_muscle08.png", answer: "Glúteo medio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Gluteus_minimus_muscle07.png/3840px-Gluteus_minimus_muscle07.png", answer: "Glúteo menor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Gray430_with_TensorFasciaLata-en.svg/960px-Gray430_with_TensorFasciaLata-en.svg.png", answer: "Tensor de la fascia lata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/SoleusAndArch.jpg", answer: "Sóleo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Tibialis.png", answer: "Tibial anterior" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Gray417_color.PNG", answer: "Braquiorradial" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/CroquisSupinadorCorto.jpg", answer: "Músculo supinador" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Gray417_color.PNG", answer: "Compartimento anterior del antebrazo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Gray378_%28masseter_highlight%29.png", answer: "Músculo masetero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Gray382.png", answer: "Músculo temporal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Sternocleidomastoideus.png", answer: "Esternocleidomastoideo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Humerus_-_anterior_view.png/3840px-Humerus_-_anterior_view.png", answer: "Húmero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Femur_-_anterior_view2.png/3840px-Femur_-_anterior_view2.png", answer: "Fémur" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Pelvic_girdle_illustration.svg/960px-Pelvic_girdle_illustration.svg.png", answer: "Isquion" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Pelvic_girdle_illustration.svg/960px-Pelvic_girdle_illustration.svg.png", answer: "Pubis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/3D_Medical_Animation_Human_Wrist.jpg", answer: "Huesos del carpo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Metacarpal_bones_%28left_hand%29_01_palmar_view_with_label.png/3840px-Metacarpal_bones_%28left_hand%29_01_palmar_view_with_label.png", answer: "Huesos metacarpianos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Tarsus2.png", answer: "Tarso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Metatarsal_bones01_-_superior_view.png/3840px-Metatarsal_bones01_-_superior_view.png", answer: "Huesos metatarsianos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scheme_human_hand_bones-en.svg/500px-Scheme_human_hand_bones-en.svg.png", answer: "Falange" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Occipital_bone_lateral2.png", answer: "Hueso occipital" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Parietal_bone_posterior2.png", answer: "Hueso parietal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Frontal_bone_lateral3.png/3840px-Frontal_bone_lateral3.png", answer: "Hueso frontal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Temporal_bone_lateral5.png/3840px-Temporal_bone_lateral5.png", answer: "Hueso temporal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Sphenoid_bone_-_lateral_view.png", answer: "Hueso esfenoides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Orbital_bones.png", answer: "Hueso etmoides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Illu_facial_bones.jpg", answer: "Vómer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/83/712_Hyoid_Bone.jpg", answer: "Hueso hioides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/14/Chimp_Brain_in_a_jar.jpg", answer: "Cerebro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Gehirn%2C_lateral_-_Lobi_%2B_Stammhirn_%2B_Cerebellum_eng.svg/960px-Gehirn%2C_lateral_-_Lobi_%2B_Stammhirn_%2B_Cerebellum_eng.svg.png", answer: "Cerebelo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Hypothalamus.jpg", answer: "Hipotálamo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Hypophyse.png", answer: "Glándula pituitaria" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Heart_anterior_exterior_view.png", answer: "Corazón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Lungs_diagram_detailed.svg/960px-Lungs_diagram_detailed.svg.png", answer: "Pulmón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Anatomy_Abdomen_Tiesworks.jpg", answer: "Hígado" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Gallbladder_%28organ%29.png", answer: "Vesícula biliar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Gray1046.svg/1280px-Gray1046.svg.png", answer: "Estómago" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Blausen_0699_PancreasAnatomy2.png", answer: "Páncreas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Diagram_showing_the_position_of_the_spleen_CRUK_417.svg/500px-Diagram_showing_the_position_of_the_spleen_CRUK_417.svg.png", answer: "Bazo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Tractus_intestinalis_intestinum_tenue.svg/500px-Tractus_intestinalis_intestinum_tenue.svg.png", answer: "Intestino delgado" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Tractus_intestinalis_intestinum_crassum.svg/500px-Tractus_intestinalis_intestinum_crassum.svg.png", answer: "Intestino grueso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Rectum_anatomy_en.svg/960px-Rectum_anatomy_en.svg.png", answer: "Recto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Dog%E2%80%99s_anus.jpg", answer: "Ano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Blausen_0592_KidneyAnatomy_01.png", answer: "Riñón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Urinary_system.svg/960px-Urinary_system.svg.png", answer: "Uréter" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Urinary_system.svg/960px-Urinary_system.svg.png", answer: "Vejiga" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Female_and_Male_Urethra.jpg", answer: "Uretra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Anterior_thyroid.jpg", answer: "Tiroides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Illu_thyroid_parathyroid.jpg", answer: "Glándula paratiroides" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Illu_thymus.jpg", answer: "Timo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Adrenal_Gland_detail_-_English.png", answer: "Glándula suprarrenal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Aorta_segments.svg/960px-Aorta_segments.svg.png", answer: "Aorta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/54/Sobo_1909_573-574.png", answer: "Arteria femoral" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Diagram_of_the_human_heart_%28cropped%29.svg/960px-Diagram_of_the_human_heart_%28cropped%29.svg.png", answer: "Arteria pulmonar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Diagram_of_the_human_heart_%28cropped%29.svg/960px-Diagram_of_the_human_heart_%28cropped%29.svg.png", answer: "Venas cavas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Gray558.png", answer: "Vena yugular" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Capillary.svg/500px-Capillary.svg.png", answer: "Capilar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/14/Blausen_0822_SpinalCord.png", answer: "Médula espinal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Sciatic_nerve2.jpg", answer: "Nervio ciático" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Gray773.png", answer: "Nervio óptico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Cranial_nerve_VII.svg/500px-Cranial_nerve_VII.svg.png", answer: "Nervio facial" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/TE-Nervous_system_diagram.svg/960px-TE-Nervous_system_diagram.svg.png", answer: "Sistema nervioso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/3D_Medical_Animation_Bronchus_Description.jpg", answer: "Bronquio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/Alveoli_diagram.png", answer: "Bronquiolo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Tractus_intestinalis_duodenum.svg/500px-Tractus_intestinalis_duodenum.svg.png", answer: "Duodeno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Illu_small_intestine.jpg", answer: "Yeyuno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Illu_small_intestine.jpg", answer: "Íleon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Tractus_intestinalis_cecum.svg/500px-Tractus_intestinalis_cecum.svg.png", answer: "Ciego" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/ColonAscendente.png", answer: "Colon ascendente" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/ColonTrasverso.png", answer: "Colon transverso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/ColonDiscendente.png", answer: "Colon descendente" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/eb/ColonSigmoideo.png", answer: "Colon sigmoide" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Illu_cervix.svg/3840px-Illu_cervix.svg.png", answer: "Útero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Ovary.png", answer: "Ovario" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Basic_Female_Reproductive_System_%28English%29.svg/960px-Basic_Female_Reproductive_System_%28English%29.svg.png", answer: "Trompa de Falopio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Vaginal_Canal_Normal_vs._Menopause.png", answer: "Vagina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Cervix_svg_hariadhi.svg/960px-Cervix_svg_hariadhi.svg.png", answer: "Cuello uterino" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Penis_asiatischer_Elefant.JPG", answer: "Pene" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Testicle_hariadhi.svg/960px-Testicle_hariadhi.svg.png", answer: "Testículo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Prostatelead.jpg", answer: "Próstata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Relaxed_and_contracted_male_scrotum.jpg", answer: "Escroto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Elephant_skin_%283689577529%29.jpg", answer: "Piel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Skin.png", answer: "Dermis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/84/Epidermis-delimited.JPG", answer: "Epidermis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Skin.png", answer: "Tejido subcutáneo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Hair_follicle-en.svg/500px-Hair_follicle-en.svg.png", answer: "Folículo piloso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Gray945.png", answer: "Cabello" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Androgenic_hair.svg/960px-Androgenic_hair.svg.png", answer: "Vello corporal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Human_skin_structure.svg/1920px-Human_skin_structure.svg.png", answer: "Glándula sudorípara" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Hair_follicle-en.svg/500px-Hair_follicle-en.svg.png", answer: "Glándula sebácea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Hypertrophic_Zone_of_Epiphyseal_Plate.jpg", answer: "Cartílago" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Tendon_-_add_-_high_mag.jpg/3840px-Tendon_-_add_-_high_mag.jpg", answer: "Tendón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Knee_diagram.svg/960px-Knee_diagram.svg.png", answer: "Ligamento cruzado anterior" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Knee_diagram.svg/960px-Knee_diagram.svg.png", answer: "Ligamento cruzado posterior" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/1123_Muscles_of_the_Leg_that_Move_the_Foot_and_Toes_b.png", answer: "Tendón de Aquiles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/716_Intervertebral_Disk.svg/960px-716_Intervertebral_Disk.svg.png", answer: "Disco intervertebral" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Joint.svg/960px-Joint.svg.png", answer: "Membrana sinovial" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Venous_and_arterial_blood.jpg", answer: "Sangre" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/FreshFrozenPlasma.JPG", answer: "Plasma sanguíneo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Blausen_0761_RedBloodCells.png", answer: "Glóbulo rojo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Blausen_0909_WhiteBloodCells.png", answer: "Glóbulo blanco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/51/Platelets2.JPG", answer: "Plaqueta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Section_of_bone_marrow_tissue_%28Prussian_blue_stain%29.jpg", answer: "Médula ósea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/1402_The_Tongue.jpg", answer: "Papila gustativa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Cochlea-crosssection.svg/960px-Cochlea-crosssection.svg.png", answer: "Cóclea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Vertigo.png", answer: "Sistema vestibular" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Vertigo.png", answer: "Canales semicirculares" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Gray395.png", answer: "Fascia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Illu_lymph_capillary.png", answer: "Linfa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Schematic_of_lymph_node_showing_lymph_sinuses.svg/960px-Schematic_of_lymph_node_showing_lymph_sinuses.svg.png", answer: "Ganglio linfático" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Illu_lymph_capillary.png", answer: "Vaso linfático" },
];
