import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const deportistas: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Fangio_in_1955_%28cropped%29.jpg", answer: "Juan Manuel Fangio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Ayrton_Senna_9_%28cropped%29.jpg", answer: "Ayrton Senna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/A%C3%A9cio_Neves%2C_Michael_Schumacher_e_Didi_%28Cropped%29.jpg", answer: "Michael Schumacher" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg", answer: "Lewis Hamilton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg", answer: "Max Verstappen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3978_by_Stepro_%28cropped2%29.jpg", answer: "Charles Leclerc" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3968_by_Stepro_%28cropped2%29.jpg", answer: "Lando Norris" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Formula1Gabelhofen2022_%2804%29_%28cropped2%29.jpg", answer: "Carlos Sainz Jr." },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Franco_Colapinto_at_the_Melbourne_Walk_during_the_2026_Australian_Grand_Prix_%28028A8704%29_%28cropped%29.jpg", answer: "Franco Colapinto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Roger_Federer_2015_%28cropped%29.jpg", answer: "Roger Federer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/71/Rafael_Nadal_en_2024_%28cropped%29.jpg", answer: "Rafael Nadal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Novak_Djokovic_Paris_2024_Olympic_Games_%28cropped%29.jpg", answer: "Novak Djokovic" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/2015_Australian_Open_-_Andy_Murray_12_%28cropped%29.jpg", answer: "Andy Murray" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Pete_Sampras_Champions_Shootout_2.jpg", answer: "Pete Sampras" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/93/Andre_Agassi_%282011%29.jpg", answer: "Andre Agassi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Bjorn_Borg_en_2014.jpg", answer: "Björn Borg" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/John_McEnroe_005.png", answer: "John McEnroe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/97/Jimmy_Conners_1994.jpg", answer: "Jimmy Connors" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Tennis_%27great%27%2C_Rod_Laver_%28cropped%29.jpg", answer: "Rod Laver" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Steffi_Graf_in_Hamburg_2010_%28cropped%29.jpg", answer: "Steffi Graf" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Guests_at_the_2026_Met_Gala_209_%28cropped%29.jpg", answer: "Serena Williams" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Venus_Williams_%282025_DC_Open%29_crop.jpg", answer: "Venus Williams" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Martina_Navratilova_Eastbourne_2011.jpg", answer: "Martina Navratilova" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/21/Chris_Evert.jpg", answer: "Chris Evert" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/08/Monica_Seles_1999.jpg", answer: "Monica Seles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Margaret_Court.png", answer: "Margaret Court" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Billie_Jean_King_at_the_2026_Sundance_Film_Festival_02_%28crop_2%29.jpg", answer: "Billie Jean King" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Carlos_Alcaraz_-_240422_192324_%28cropped%29.jpg", answer: "Carlos Alcaraz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Jannik_Sinner_2025_US_Open.jpg", answer: "Jannik Sinner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Aryna_Sabalenka_%282024_DC_Open%29_06.jpg", answer: "Aryna Sabalenka" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Del_Potro_en_Indian_Wells_2018.jpg", answer: "Juan Martín del Potro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Vilas-1975.jpg", answer: "Guillermo Vilas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Gabriela_Sabatini_US_Embassy_in_Argentina_cropped.jpg", answer: "Gabriela Sabatini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/David_Nalbandian_Boodles.jpg", answer: "David Nalbandian" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/80/Gast%C3%B3n_Gaudio_2018_%28cropped%29.jpg", answer: "Gastón Gaudio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Guillermo_Coria_2018_%28cropped%29.jpg", answer: "Guillermo Coria" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Schwartzman_WM19_%2824%29_%2848521748281%29.jpg", answer: "Diego Schwartzman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg", answer: "Michael Jordan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg", answer: "LeBron James" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Kobe_Bryant_Dec_2014.jpg", answer: "Kobe Bryant" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Magic_Johnson_at_SXSW_2022_%2851958828669%29_%28cropped%29.jpg", answer: "Magic Johnson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Larrybird.jpg", answer: "Larry Bird" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/TechCrunch_Disrupt_2023_-_Day_1_%28cropped%29.jpg", answer: "Shaquille O'Neal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Tim_Duncan_Walks_Verizon_Center%27s_Floor_%28cropped%29_%28cropped%29.jpg", answer: "Tim Duncan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg", answer: "Stephen Curry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg", answer: "Kevin Durant" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Wilt_Chamberlain_1960_%28cropped%29_%28cropped%29.jpg", answer: "Wilt Chamberlain" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Kareem_Abdul-Jabbar_May_2014.jpg", answer: "Kareem Abdul-Jabbar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Bill_russell_dribbling_%28cropped%29.jpg", answer: "Bill Russell" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Oscar_Robertson_2024.jpg", answer: "Oscar Robertson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Dirk_Nowitzki_2_%28cropped%29.jpg", answer: "Dirk Nowitzki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Nikola_Jokic_free_throw_%28cropped%29.jpg", answer: "Nikola Jokić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Luka_Doncic_%2851914951721%29_%28cropped1%29.jpg", answer: "Luka Dončić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg", answer: "Giannis Antetokounmpo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Manu_Ginobili_Spurs-Magic011_%28cropped%29.jpg", answer: "Manu Ginóbili" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/10/Luis_Scola_Italy_%28cropped%29.jpg", answer: "Luis Scola" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Andres_Nocioni_2013.jpg", answer: "Andrés Nocioni" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Facundo_Campazzo_7_Real_Madrid_Baloncesto_Euroleague_20250206_%286%29_%28cropped%29.jpg", answer: "Facundo Campazzo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/PauCaptura.jpg", answer: "Pau Gasol" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Marc_Gasol-jul_2018.jpg", answer: "Marc Gasol" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Yao_Ming_in_2014_%28cropped%29.jpg", answer: "Yao Ming" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Muhammad_Ali_NYWTS.jpg", answer: "Muhammad Ali" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg", answer: "Mike Tyson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Floyd_Mayweather_Jr_2011.jpg", answer: "Floyd Mayweather Jr." },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Former_senator_Manny_Pacquiao_speaks_in_event_%2810-01-2025%29_%28cropped%29.jpg", answer: "Manny Pacquiao" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Sugar_Ray_Leonard.jpg", answer: "Sugar Ray Leonard" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Joe_Frazier_reading_newspaper_cropped.jpg", answer: "Joe Frazier" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/George_Foreman_%281973%29.jpg", answer: "George Foreman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Rocky_Marciano_%28cropped%29.jpg", answer: "Rocky Marciano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/16/Julio_C%C3%A9sar_Ch%C3%A1vez_2017.png", answer: "Julio César Chávez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/82/Sa%C3%BAl_%C3%81lvarez.png", answer: "Canelo Álvarez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Tyson_Fury_at_Place_Bell%2C_Laval_Quebec%2C_Canada_-_Dec_16_2017_%28cropped%29.jpg", answer: "Tyson Fury" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/2022_-_Centre_Stage_EN1_4500_%2852471602047%29_%28cropped%29.jpg", answer: "Oleksandr Usyk" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/37/Locche_retrato_mosteirin.jpg", answer: "Nicolino Locche" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/93/Carlos_monzon_1974.jpg", answer: "Carlos Monzón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/be/El_Chino_Maidana_pre-fight_Sep_2011.jpg", answer: "Marcos Maidana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Oscar_de_la_Hoya_2014_%28cropped%29.jpg", answer: "Oscar De La Hoya" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Conor_McGregor_2025.jpeg", answer: "Conor McGregor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Khabib_nurmagomedov.jpg", answer: "Khabib Nurmagomedov" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Alex_Pereira_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg", answer: "Alex Pereira" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Charles_Oliveira_do_Bronxs.jpg", answer: "Charles Oliveira" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Usain_Bolt_smiling_Berlin_2009.JPG", answer: "Usain Bolt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Carl_Lewis_%28cropped%29.jpg", answer: "Carl Lewis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Jesse_Owens_1936.jpg", answer: "Jesse Owens" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Michael_Phelps_Rio_Olympics_2016.jpg", answer: "Michael Phelps" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/18/Katie_Ledecky_at_the_2023_Golden_Goggle_Awards.jpg", answer: "Katie Ledecky" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Mark_Spitz.jpg", answer: "Mark Spitz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Luciana_Aymar.jpg", answer: "Luciana Aymar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Agust%C3%ADn_Pichot_-_En_Casa_Rosada_-_08FEB07_-presidencia-govar.jpg", answer: "Agustín Pichot" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Felipe_Contepomi_Stade_francais_training_2012-03-03.jpg", answer: "Felipe Contepomi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Juan_Martin_Hernandez_2012_%28cropped%29.jpg", answer: "Juan Martín Hernández" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg", answer: "Tom Brady" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Patrick_Mahomes_%2851615475056%29.jpg/3840px-Patrick_Mahomes_%2851615475056%29.jpg", answer: "Patrick Mahomes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Joe_Montana_Super_Bowl_50_%28cropped%29.jpg", answer: "Joe Montana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Peyton_Manning_%2851665689271%29.jpg/3840px-Peyton_Manning_%2851665689271%29.jpg", answer: "Peyton Manning" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/AaronRodgersSteelers_%28cropped%29.jpg", answer: "Aaron Rodgers" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Brett_Favre_Super_Bowl_50.jpg", answer: "Brett Favre" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Super_Bowl_44_Miami_Florida_NFL_Network_South_Beach_Set_Deon_Sanders_interviews_Jerry_Rice_%284331549867%29_%28cropped%29_-_Jerry_Rice.jpg", answer: "Jerry Rice" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Lawrence_Taylor_in_2025_%28cropped%29.jpg", answer: "Lawrence Taylor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Randy_Moss_2016.jpg", answer: "Randy Moss" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Travis_Kelce_in_the_Oval_Office_of_the_White_House_on_June_5%2C_2023_-_P20230605AS-0902_%28cropped%29.jpg", answer: "Travis Kelce" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/President_Donald_Trump_hosts_a_reception_honoring_Black_History_Month_%2854341713089%29_%28cropped%29.jpg", answer: "Tiger Woods" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Jack_Nicklaus_2019_Jenkins_Medal_Awards_%28cropped%29.jpg", answer: "Jack Nicklaus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d8/YN3ArnoldPalmer.jpg", answer: "Arnold Palmer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Rory_McIlroy_Ryder_Cup_2025-195_%28cropped%29.jpg", answer: "Rory McIlroy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Garri_Kasparow_%2818776605665%29_%28cropped%29_2.jpg", answer: "Garry Kasparov" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Magnus_Carlsen_in_2025.jpg", answer: "Magnus Carlsen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Bobby_Fischer_1972.jpg", answer: "Bobby Fischer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Anatoly_Karpov_2017_april.jpg", answer: "Anatoly Karpov" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Jos%C3%A9_Ra%C3%BAl_Capablanca_1931.jpg", answer: "José Raúl Capablanca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Viswanathan_Anand_%282016%29_%28cropped%29.jpeg", answer: "Viswanathan Anand" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Nakamura_Hikaru_%2829290269410%29_%28cropped%29_%28cropped%29.jpg", answer: "Hikaru Nakamura" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Arnold_Schwarzenegger_-_Austrian_World_Summit_2026_BHO-2906.jpg", answer: "Arnold Schwarzenegger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Ronnie_Coleman_Invited_Guest.jpg", answer: "Ronnie Coleman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Philheath.jpg", answer: "Phil Heath" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c5/JayCutlergfdl_%28cropped%29.JPG", answer: "Jay Cutler" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Chris_Bumstead_on_Gymshark.jpg", answer: "Chris Bumstead" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Bruce_Lee_as_Chen_Zhen_%284x5_cropped%29.jpg", answer: "Bruce Lee" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Chuck_Norris%2C_The_Delta_Force_1986_%28slight_cropped%29.jpg/3840px-Chuck_Norris%2C_The_Delta_Force_1986_%28slight_cropped%29.jpg", answer: "Chuck Norris" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Teddy_Riner_Cannes_2016.jpg", answer: "Teddy Riner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/71/Ryoko_Tani.jpg", answer: "Ryoko Tani" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/31/Bela_Campe%C3%B3n_del_Mundo.jpg", answer: "Fernando Belasteguín" },
];
