import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const deportistas: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg", answer: "Lionel Messi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Argentina_celebrando_copa_%28cropped%29.jpg", answer: "Diego Maradona" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg", answer: "Cristiano Ronaldo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pele_con_brasil_%28cropped%29.jpg", answer: "Pelé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Neymar_at_2026_FIFA_World_Cup_by_YantsImages_%28cropped%29.jpg", answer: "Neymar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg", answer: "Kylian Mbappé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg", answer: "Zinedine Zidane" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Ronaldinho_in_2019.jpg", answer: "Ronaldinho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Ronaldo_Lu%C3%ADs_Naz%C3%A1rio_de_Lima_2019_%283x4_cropped%29.jpg", answer: "Ronaldo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Johan_Cruijff_%281974%29.jpg", answer: "Johan Cruyff" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Franz_Beckenbauer_%281975%29.jpg", answer: "Franz Beckenbauer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Michel_Platini_2010_%28cropped%29.jpg", answer: "Michel Platini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Andr%C3%A9s_Iniesta_2019.jpg", answer: "Andrés Iniesta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Xavi%2C_Persepolis_vs._Al_Sadd%2C_20190520_02_%28cropped%29.jpg", answer: "Xavi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Sergio_Ramos_Interview_2021_%28cropped%29.jpg", answer: "Sergio Ramos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Iker-Casillas-SportsTrade-2021-cropped.jpg", answer: "Iker Casillas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg", answer: "Gianluigi Buffon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Paolo_Maldini_AC_Milan_Technical_director_2018.jpg", answer: "Paolo Maldini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/LS3_1288_%2853332367864%29_%28cropped%29.jpg", answer: "Roberto Carlos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/14_06_2019_Abertura_da_Copa_Am%C3%A9rica_Brasil_2019_%2848064408836%29_%28cropped%29.jpg", answer: "Cafu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Thierry_Henry_%2851649035951%29_%28cropped%29.jpg", answer: "Thierry Henry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Didier_Drogba_%282019%29_%28cropped2%29.jpg", answer: "Didier Drogba" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Samuel_2011.jpg", answer: "Samuel Eto'o" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mohamed_Salah_2018.jpg", answer: "Mohamed Salah" },
        { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg", answer: "Erling Haaland" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg", answer: "Robert Lewandowski" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Karim_Benzema_Pick.jpg", answer: "Karim Benzema" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Ofrenda_de_la_Liga_y_la_Champions-57-L.Mill%C3%A1n_%2852109310843%29_%28Luka_Modri%C4%87%29.jpg", answer: "Luka Modrić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Toni_Kroos_Real_Madrid_2021.jpg", answer: "Toni Kroos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg", answer: "Kevin De Bruyne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg", answer: "Virgil van Dijk" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Harry_Kane_on_October_10%2C_2023.jpg", answer: "Harry Kane" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg", answer: "Son Heung-min" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/David_Beckham_UNICEF_%28cropped2%29.jpg", answer: "David Beckham" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wayne_Rooney_%2850121495731%29_%28cropped%29.jpg", answer: "Wayne Rooney" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/Zlatan_Ibrahimovi%C4%87_June_2018.jpg", answer: "Zlatan Ibrahimović" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Luis_Su%C3%A1rez_2026_%28cropped%29.jpg", answer: "Luis Suárez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Edinson_Cavani_2018_%28cropped%29.jpg", answer: "Edinson Cavani" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/NIG-ARG_%285%29.jpg", answer: "Ángel Di María" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Ag%C3%BCero_in_2018.jpg", answer: "Sergio Agüero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/31/Carlos_Tevez_with_Argentina_November_2014_%28cropped%29.jpg", answer: "Carlos Tevez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Juan_Rom%C3%A1n_Riquelme_-_2019.jpg", answer: "Juan Román Riquelme" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Metalist-Inter_%282%29.jpg", answer: "Javier Zanetti" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Everton_-_Uni%C3%B3n_Espa%C3%B1ola%2C_2018-04-28_-_Mart%C3%ADn_Palermo_-_01_%28cropped%29.jpg", answer: "Martín Palermo" },
        { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Enzo_Fern%C3%A1ndez_2025_FIFA_Club_World_Cup_Final.jpg", answer: "Enzo Fernández" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Rodrigo_De_Paul_NYCFC_Miami_24_Sep_2025-018_%28cropped%29.jpg", answer: "Rodrigo De Paul" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Argentina_national_football_team_-_2_-_2022_%28Juli%C3%A1n_%C3%81lvarez%29.jpg", answer: "Julián Alvarez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg", answer: "Michael Jordan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg", answer: "LeBron James" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Kobe_Bryant_Dec_2014.jpg", answer: "Kobe Bryant" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/TechCrunch_Disrupt_2023_-_Day_1_%28cropped%29.jpg", answer: "Shaquille O'Neal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg", answer: "Stephen Curry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg", answer: "Kevin Durant" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Magic_Johnson_at_SXSW_2022_%2851958828669%29_%28cropped%29.jpg", answer: "Magic Johnson" },
        { image: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Larrybird.jpg", answer: "Larry Bird" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Kareem_Abdul-Jabbar_May_2014.jpg", answer: "Kareem Abdul-Jabbar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Tim_Duncan_Walks_Verizon_Center%27s_Floor_%28cropped%29_%28cropped%29.jpg", answer: "Tim Duncan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg", answer: "Giannis Antetokounmpo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Nikola_Jokic_free_throw_%28cropped%29.jpg", answer: "Nikola Jokić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/21/Allen_Iverson_headshot.jpg", answer: "Allen Iverson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Roger_Federer_2015_%28cropped%29.jpg", answer: "Roger Federer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/71/Rafael_Nadal_en_2024_%28cropped%29.jpg", answer: "Rafael Nadal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Novak_Djokovic_Paris_2024_Olympic_Games_%28cropped%29.jpg", answer: "Novak Djokovic" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Guests_at_the_2026_Met_Gala_209_%28cropped%29.jpg", answer: "Serena Williams" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Venus_Williams_%282025_DC_Open%29_crop.jpg", answer: "Venus Williams" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Collision_2024_-_VR7_1035_%2853801820852%29_%28cropped%29.jpg", answer: "Maria Sharapova" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/2015_Australian_Open_-_Andy_Murray_12_%28cropped%29.jpg", answer: "Andy Murray" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Carlos_Alcaraz_-_240422_192324_%28cropped%29.jpg", answer: "Carlos Alcaraz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Iga_Swiatek_2023_Cropped_%2B_Retouched.jpg", answer: "Iga Świątek" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Usain_Bolt_smiling_Berlin_2009.JPG", answer: "Usain Bolt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Michael_Phelps_Rio_Olympics_2016.jpg", answer: "Michael Phelps" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Simone_Biles_National_Team_2024.jpg", answer: "Simone Biles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Carl_Lewis_%28cropped%29.jpg", answer: "Carl Lewis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Floyd_Mayweather_Jr_2011.jpg", answer: "Floyd Mayweather Jr." },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg", answer: "Mike Tyson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Muhammad_Ali_NYWTS.jpg", answer: "Muhammad Ali" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Former_senator_Manny_Pacquiao_speaks_in_event_%2810-01-2025%29_%28cropped%29.jpg", answer: "Manny Pacquiao" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Conor_McGregor_2025.jpeg", answer: "Conor McGregor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Rousey_HOF_2018_%28cropped%29.jpg", answer: "Ronda Rousey" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg", answer: "Lewis Hamilton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/A%C3%A9cio_Neves%2C_Michael_Schumacher_e_Didi_%28Cropped%29.jpg", answer: "Michael Schumacher" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Ayrton_Senna_9_%28cropped%29.jpg", answer: "Ayrton Senna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg", answer: "Max Verstappen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/97/Alonso-68_%2824710447098%29.jpg", answer: "Fernando Alonso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Sebastian_Vettel_-_2022236172324_2022-08-24_Champions_for_Charity_-_Sven_-_1D_X_MK_II_-_0418_-_B70I2428_%28cropped%29.jpg", answer: "Sebastian Vettel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg", answer: "Tom Brady" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Peyton_Manning_%2851665689271%29.jpg/3840px-Peyton_Manning_%2851665689271%29.jpg", answer: "Peyton Manning" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Patrick_Mahomes_%2851615475056%29.jpg/3840px-Patrick_Mahomes_%2851615475056%29.jpg", answer: "Patrick Mahomes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Super_Bowl_44_Miami_Florida_NFL_Network_South_Beach_Set_Deon_Sanders_interviews_Jerry_Rice_%284331549867%29_%28cropped%29_-_Jerry_Rice.jpg", answer: "Jerry Rice" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Diego_Simeone_-_240422_192621-2_%28cropped%29.jpg", answer: "Diego Simeone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Josep_Guardiola_2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2797_%28cropped%29.jpg", answer: "Pep Guardiola" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Jos%C3%A9_Mourinho_20250206_%281%29.jpg/3840px-Jos%C3%A9_Mourinho_20250206_%281%29.jpg", answer: "José Mourinho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/J%C3%BCrgen_Klopp%2C_Liverpool_vs._Chelsea%2C_UEFA_Super_Cup_2019-08-14_04.jpg", answer: "Jürgen Klopp" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Pizarrointermiami.jpg", answer: "Rodolfo Pizarro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Manu_Ginobili_Spurs-Magic011_%28cropped%29.jpg", answer: "Manu Ginóbili" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/10/Luis_Scola_Italy_%28cropped%29.jpg", answer: "Luis Scola" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Manu_Ginobili_Spurs-Magic011_%28cropped%29.jpg", answer: "Manu Ginóbili" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Facundo_Campazzo_7_Real_Madrid_Baloncesto_Euroleague_20250206_%286%29_%28cropped%29.jpg", answer: "Facundo Campazzo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Magnus_Carlsen_in_2025.jpg", answer: "Magnus Carlsen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/FaustinoOroTata2025_%28cropped%29.jpg", answer: "Faustino Oro" },







];