import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const frasesConocidas: CategoryQuestion[] = [
    { text: "Más vale pájaro en mano...", answer: "que cien volando" },
    { text: "A caballo regalado...", answer: "no se le miran los dientes" },
    { text: "No por mucho madrugar...", answer: "amanece más temprano" },
    { text: "En casa de herrero...", answer: "cuchillo de palo" },
    { text: "Dime con quién andas...", answer: "y te diré quién eres" },
    { text: "El que ríe último...", answer: "ríe mejor" },
    { text: "Ojos que no ven...", answer: "corazón que no siente" },
    { text: "Al mal tiempo...", answer: "buena cara" },
    { text: "Cría cuervos...", answer: "y te sacarán los ojos" },
    { text: "No hay mal que dure...", answer: "cien años" },
    { text: "A palabras necias...", answer: "oídos sordos" },
    { text: "El hábito no hace...", answer: "al monje" },
    { text: "Perro que ladra...", answer: "no muerde" },
    { text: "Barriga llena...", answer: "corazón contento" },
    { text: "El que mucho abarca...", answer: "poco aprieta" },
    { text: "Al que madruga...", answer: "Dios lo ayuda" },
    { text: "Donde hubo fuego...", answer: "cenizas quedan" },
    { text: "La unión hace...", answer: "la fuerza" },
    { text: "Lo prometido es...", answer: "deuda" },
    { text: "Nunca es tarde...", answer: "si la dicha es buena" },

    { text: "Pienso, luego...", answer: "existo" },
    { text: "Solo sé que...", answer: "no sé nada" },
    { text: "El hombre es la medida...", answer: "de todas las cosas" },
    { text: "Conócete a ti...", answer: "mismo" },
    { text: "El conocimiento es...", answer: "poder" },
    { text: "La vida examinada no merece...", answer: "ser vivida" },
    { text: "El fin justifica...", answer: "los medios" },
    { text: "Divide y...", answer: "vencerás" },
    { text: "El hombre es un lobo...", answer: "para el hombre" },
    { text: "La religión es el opio...", answer: "del pueblo" },
    { text: "Dios ha...", answer: "muerto" },
    { text: "Lo que no me mata...", answer: "me hace más fuerte" },
    { text: "Piensa diferente...", answer: "para ver diferente" },
    { text: "La imaginación es más importante...", answer: "que el conocimiento" },
    { text: "La educación es el arma más poderosa...", answer: "para cambiar el mundo" },

    { text: "Tengo un sueño...", answer: "que un día esta nación se levantará" },
    { text: "Un pequeño paso para el hombre...", answer: "un gran salto para la humanidad" },
    { text: "Vine, vi...", answer: "y vencí" },
    { text: "La suerte favorece...", answer: "a los audaces" },
    { text: "La historia la escriben...", answer: "los vencedores" },
    { text: "Sé el cambio...", answer: "que quieres ver en el mundo" },
    { text: "Prefiero morir de pie...", answer: "que vivir arrodillado" },
    { text: "El gobierno del pueblo, por el pueblo...", answer: "y para el pueblo" },
    { text: "Sí se puede...", answer: "si se intenta" },
    { text: "La libertad no es nada...", answer: "si no incluye la libertad de equivocarse" },
    { text: "La vida es aquello que pasa...", answer: "mientras haces otros planes" },
    { text: "El tiempo es...", answer: "oro" },
    { text: "Nunca interrumpas a tu enemigo...", answer: "cuando está cometiendo un error" },
    { text: "La victoria tiene cien padres...", answer: "pero la derrota es huérfana" },
    { text: "El conocimiento habla...", answer: "pero la sabiduría escucha" },

    { text: "Hasta el infinito...", answer: "y más allá" },
    { text: "Que la fuerza...", answer: "te acompañe" },
    { text: "Yo soy...", answer: "tu padre" },
    { text: "Elemental, mi querido...", answer: "Watson" },
    { text: "Houston, tenemos...", answer: "un problema" },
    { text: "No hay lugar como...", answer: "el hogar" },
    { text: "Hakuna...", answer: "Matata" },
    { text: "Algunas personas valen...", answer: "la pena derretirse por ellas" },
    { text: "Con gran poder...", answer: "viene una gran responsabilidad" },
    { text: "Que empiecen los...", answer: "juegos" },
    { text: "La vida es como una caja...", answer: "de bombones" },
    { text: "No puedes manejar...", answer: "la verdad" },
    { text: "Siempre nos quedará...", answer: "París" },
    { text: "Bond, James...", answer: "Bond" },
    { text: "Que coman...", answer: "pastel" },

    { text: "Nunca dejes para mañana...", answer: "lo que puedas hacer hoy" },
    { text: "El saber no ocupa...", answer: "lugar" },
    { text: "La práctica hace...", answer: "al maestro" },
    { text: "El que busca...", answer: "encuentra" },
    { text: "Quien calla...", answer: "otorga" },
    { text: "Después de la tormenta...", answer: "llega la calma" },
    { text: "No todo lo que brilla...", answer: "es oro" },
    { text: "El que espera...", answer: "desespera" },
    { text: "La curiosidad mató...", answer: "al gato" },
    { text: "Cada maestrito...", answer: "con su librito" },
    { text: "Roma no se hizo...", answer: "en un día" },
    { text: "El pez por la boca...", answer: "muere" },
    { text: "La ocasión hace...", answer: "al ladrón" },
    { text: "El que avisa...", answer: "no traiciona" },
    { text: "A buen entendedor...", answer: "pocas palabras" },

    { text: "I have...", answer: "a dream" },
    { text: "To be or not...", answer: "to be" },
    { text: "May the Force...", answer: "be with you" },
    { text: "Winter is...", answer: "coming" },
    { text: "Just do...", answer: "it" },
    { text: "Think...", answer: "different" },
    { text: "I'm loving...", answer: "it" },
    { text: "Impossible is...", answer: "nothing" },
    { text: "The truth is...", answer: "out there" },
    { text: "Keep calm and...", answer: "carry on" },

    { text: "No se trata de cuánto golpeas...", answer: "sino de cuánto aguantas" },
    { text: "La fortuna sonríe...", answer: "a los valientes" },
    { text: "El éxito es ir de fracaso...", answer: "en fracaso sin perder el entusiasmo" },
    { text: "Nunca, nunca, nunca...", answer: "te rindas" },
    { text: "La mejor venganza...", answer: "es el éxito masivo" },
    { text: "Si puedes soñarlo...", answer: "puedes hacerlo" },
    { text: "Hazlo o no lo hagas...", answer: "pero no lo intentes" },
    { text: "La disciplina tarde o temprano...", answer: "vence a la inteligencia" },
    { text: "El éxito depende...", answer: "de la preparación previa" },
    { text: "El genio es uno por ciento inspiración...", answer: "y noventa y nueve por ciento transpiración" },

    { text: "No preguntes qué puede hacer tu país por ti...", answer: "pregunta qué puedes hacer tú por tu país" },
    { text: "El único límite...", answer: "es el que te impones a ti mismo" },
    { text: "Quien tiene un porqué para vivir...", answer: "puede soportar casi cualquier cómo" },
    { text: "La duda es uno de los nombres...", answer: "de la inteligencia" },
    { text: "La paz comienza...", answer: "con una sonrisa" },
    { text: "El futuro pertenece...", answer: "a quienes creen en sus sueños" },
    { text: "La creatividad es la inteligencia...", answer: "divirtiéndose" },
    { text: "La simplicidad es la máxima...", answer: "sofisticación" },
    { text: "La mejor manera de predecir el futuro...", answer: "es crearlo" },
    { text: "El secreto para salir adelante...", answer: "es comenzar" },

    { text: "Nunca discutas con un idiota...", answer: "te arrastrará a su nivel" },
    { text: "La experiencia es el nombre...", answer: "que damos a nuestros errores" },
    { text: "La paciencia es amarga...", answer: "pero su fruto es dulce" },
    { text: "La suerte es lo que sucede...", answer: "cuando la preparación encuentra la oportunidad" },
    { text: "No cuentes los días...", answer: "haz que los días cuenten" },
    { text: "La felicidad depende...", answer: "de nosotros mismos" },
    { text: "La esperanza es lo último...", answer: "que se pierde" },
    { text: "El miedo llama a la puerta...", answer: "la confianza abre y no hay nadie" },
    { text: "La vida comienza...", answer: "donde termina tu zona de confort" },
    { text: "Todo parece imposible...", answer: "hasta que se hace" },

    { text: "Más sabe el diablo...", answer: "por viejo que por diablo" },
    { text: "El que tiene boca...", answer: "se equivoca" },
    { text: "No hay rosa...", answer: "sin espinas" },
    { text: "A mal entendedor...", answer: "peor respuesta" },
    { text: "Quien mucho duerme...", answer: "poco aprende" },
    { text: "Agua que no has de beber...", answer: "déjala correr" },
    { text: "Del dicho al hecho...", answer: "hay mucho trecho" },
    { text: "No dejes que el árbol...", answer: "te impida ver el bosque" },
    { text: "El camino al infierno...", answer: "está empedrado de buenas intenciones" },
    { text: "La avaricia rompe...", answer: "el saco" }
];