import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const futbolistasActuales: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg", answer: "Lionel Messi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Julian_Alvarez_Argentina_v_Egypt_7_July_2026-056.jpg", answer: "Julián Alvarez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Lautaro_Martinez_ARGENTINA_VS_VENEZUELA_2017.jpg", answer: "Lautaro Martínez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Rodrigo_De_Paul_NYCFC_Miami_24_Sep_2025-018_%28cropped%29.jpg", answer: "Rodrigo De Paul" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Enzo_Fernandez_Argentina_v_Egypt_7_July_2026-127.jpg", answer: "Enzo Fernández" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/41/St._Louis_City_vs_Aston_Villa_%28Jul_2025%29_14_%28Emiliano_Mart%C3%ADnez%29.jpg", answer: "Emiliano Martínez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Cristian_Gabriel_Romero_%28cropped_2%29.png", answer: "Cristian Romero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Argentina_team_in_St._Petersburg_%28cropped%29_Otamendi.jpg", answer: "Nicolás Otamendi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/83/Alexis_Mac_Allister_04012026_%283%29.jpg", answer: "Alexis Mac Allister" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/25/2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3705_by_Stepro.jpg", answer: "Giovani Lo Celso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg", answer: "Neymar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Lamine_Yamal_a_Xina_%282025%29.png", answer: "Lamine Yamal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_108_%28cropped%29.jpg", answer: "Mikel Oyarzabal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Spain_football_team_in_202_%28Marc_Cucurella%29.jpg", answer: "Marc Cucurella" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg", answer: "Kylian Mbappé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Michael_Olise_France_v_Senegal_16_June_2026-307_%28cropped%29.jpg", answer: "Michael Olise" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/23/Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg", answer: "Jude Bellingham" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg", answer: "Cristiano Ronaldo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg", answer: "Erling Haaland" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Leandro_Paredes_2018_%28cropped%29.jpg", answer: "Leandro Paredes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Marcos_acuna_vs_mexico_2022.jpg", answer: "Marcos Acuña" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Universidad_Cat%C3%B3lica_-_Rosario_Central_20190313_04.jpg", answer: "Nahuel Molina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Germ%C3%A1n_Pezzella_%28cropped%29.jpg", answer: "Germán Pezzella" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/61/Lisandro_Martinez_2022.jpg", answer: "Lisandro Martínez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Exequiel_Palacios%2C_2022-07-31%2C_Saisoner%C3%B6ffnung_Bayer_04%2C_Leverkusen_%281%29.jpg", answer: "Exequiel Palacios" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Almada_asse_ol_2425.png", answer: "Thiago Almada" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Valentin_Carboni_%28cropped%29.jpg", answer: "Valentín Carboni" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Alejandro_Garnacho_7_August_2022_%28cropped%29.jpg", answer: "Alejandro Garnacho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/00/Franco_Mastantuono_in_2025_%28cropped%29.jpg", answer: "Franco Mastantuono" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/Giuliano_Simeone%2C_FC_Salzburg_vs._Atletico_Madrid_%282025-01-29_UEFA_Championsleague%29_53_%28cropped%29.jpg", answer: "Giuliano Simeone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/%D0%9C%D0%B0%D1%82%D1%87_%C2%AB%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%BE%C2%BB_-_%C2%AB%D0%AE%D0%B2%D0%B5%D0%BD%D1%82%D1%83%D1%81%C2%BB_0-2._20_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8F_2020_%D0%B3%D0%BE%D0%B4%D0%B0_%E2%80%94_1153905_%28cropped%29.jpg", answer: "Paulo Dybala" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Argentina_national_football_team_-_2_-_2022_%28%C3%81ngel_Correa%29.jpg", answer: "Ángel Correa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Argentina_national_football_team_-_2_-_2022_%28Guido_Rodr%C3%ADguez%29.jpg", answer: "Guido Rodríguez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Nicolas_Tagliafico_Argentina_v_Egypt_7_July_2026-126_%28cropped%29.jpg", answer: "Nicolás Tagliafico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Juan_Foyth_2017.jpg", answer: "Juan Foyth" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Gonzalo_Montiel_Argentina_v_Egypt_7_July_2026-298_%28cropped%29.jpg", answer: "Gonzalo Montiel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/87/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Gabriel_Jesus_850_1688.jpg", answer: "Gabriel Jesus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Cole_Palmer_2025_FIFA_Club_World_Cup_Final.jpg", answer: "Cole Palmer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/ManCity20240722-017_%28cropped%29.jpg", answer: "Jack Grealish" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Marcus_Rashford_England_v_Panama_27_June_26-047.jpg", answer: "Marcus Rashford" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Trent_Alexander-Arnold_2018_%28cropped%29.jpg", answer: "Trent Alexander-Arnold" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/John_Stones_England_v_Ghana_23_June_2026-038.jpg", answer: "John Stones" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Kyle_Walker.jpg", answer: "Kyle Walker" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Kobbie_Mainoo_England_v_Ghana_23_June_2026-042.jpg", answer: "Kobbie Mainoo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Reece_James_England_v_Ghana_23_June_2026-248_%28cropped%29.jpg", answer: "Reece James" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Levi_Colwill_FIFA_Club_World_Cup_final_extraction.jpg", answer: "Levi Colwill" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/RafaelLe%C3%A3oPortugal23.jpg", answer: "Rafael Leão" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/55/Jo%C3%A3o_F%C3%A9lix_USMNT_v_Portugal_Mar_31_2026-22_%28cropped%29.jpg", answer: "João Félix" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Gon%C3%A7alo_Ramos_USMNT_v_Portugal_Mar_31_2026-32_%28cropped%29.jpg", answer: "Gonçalo Ramos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Vitinha_USMNT_v_Portugal_Mar_31_2026-50_%28cropped%29.jpg", answer: "Vitinha" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Pedro_Neto_Croatia_v_Portugal_2_July_2026-113.jpg", answer: "Pedro Neto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/2019-03-09_Fu%C3%9Fball%2C_M%C3%A4nner%2C_1._Bundesliga%2C_FC_Bayern_M%C3%BCnchen_-_VfL_Wolfsburg_StP_2722_by_Stepro_%28cropped%29.jpg", answer: "Renato Sanches" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Jamal_Musiala_Ecuador_v_Germany_25_June_2026-174_%28cropped%29.jpg", answer: "Jamal Musiala" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Florian_Wirtz_Ecuador_v_Germany_25_June_2026-181_%28cropped%29.jpg", answer: "Florian Wirtz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Kai_Havertz_Ecuador_v_Germany_25_June_2026-118.jpg", answer: "Kai Havertz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Facundo_Pellistri_WC2022.jpg", answer: "Facundo Pellistri" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Nicol%C3%A1s_de_la_Cruz.jpg", answer: "Nicolás de la Cruz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/20171114_AUT_URU_4518_-_Rodrigo_Bentancur_%28cropped%29_2.jpg", answer: "Rodrigo Bentancur" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Sergio_Rochet_%282022%29.jpg", answer: "Sergio Rochet" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Math%C3%ADas_Olivera_WC2022.jpg", answer: "Mathías Olivera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/James_Rodriguez_2018.jpg", answer: "James Rodríguez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Alex_Iwobi.jpg", answer: "Alex Iwobi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Martin_Odegaard_France_v_Norway_26_June_26-014.jpg", answer: "Martin Ødegaard" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Alexander_Sorloth_France_v_Norway_26_June_26-048.jpg", answer: "Alexander Sørloth" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg", answer: "Robert Lewandowski" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Piotr_Zielinski_2018_%28cropped%29.jpg", answer: "Piotr Zieliński" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/FC_Salzburg_gegen_AS_Roma_%28UEFA_Euroleague_play-off%2C_2023-02-16%29_14_%28cropped%29.jpg", answer: "Nicola Zalewski" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Incontro_con_le_squadre_finaliste_della_Coppa_Italia_di_calcio_Frecciarossa_Atalanta_-_Juventus_05_%28Du%C5%A1an_Vlahovi%C4%87%29.jpg", answer: "Dušan Vlahović" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Aleksandar_Mitrovi%C4%87_2018_%28cropped%29.jpg", answer: "Aleksandar Mitrović" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Milinkovi%C4%87-Savi%C4%87_2018.jpg", answer: "Sergej Milinković-Savić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Granit_Xhaka_%28cropped%29.jpg", answer: "Granit Xhaka" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Soul%C3%A9_ASRoma_2025_%28cropped%29.jpeg/960px-Soul%C3%A9_ASRoma_2025_%28cropped%29.jpeg", answer: "Matías Soulé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/10/Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg", answer: "Vinícius Júnior" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/05/Rodrygo_2023_%28cropped%29.jpg", answer: "Rodrygo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Team_Brazil_at_2026_FIFA_World_Cup_by_YantsImages_%28Endrick%29.jpg", answer: "Endrick" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Casemiro_Brazil_V_Morocco_13_June_2026-76_%28cropped%29.jpg", answer: "Casemiro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Bruno_Guimaraes_Brazil_V_Morocco_13_June_2026-78_%28cropped%29.jpg", answer: "Bruno Guimarães" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Raphinha_Brazil_V_Morocco_13_June_2026-133_%28cropped%29.jpg", answer: "Raphinha" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Eder_Militao_2021.jpg", answer: "Éder Militão" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Marquinhos_Brazil_V_Morocco_13_June_2026-153_%28cropped%29.jpg", answer: "Marquinhos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_%28cropped%29.jpg", answer: "Alisson Becker" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Pedri.jpg", answer: "Pedri" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/62/%C3%81lvaro_Morata_in_2025.jpg", answer: "Álvaro Morata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/ATHLETIC-OSASUNA_SEMIFINAL._MAIDER_GOIKOETXEA_%28168%29_%28cropped%29.jpg", answer: "Nico Williams" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Dani_Olmo_2022.jpg", answer: "Dani Olmo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Ruiz_asse_psg_2425.png", answer: "Fabián Ruiz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/16/%C3%81lex_Baena_2019.jpg", answer: "Álex Baena" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Robin_Le_Normand_2122.jpg", answer: "Robin Le Normand" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Unai_Sim%C3%B3n_2025_%28cropped%29.jpg", answer: "Unai Simón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Aymeric_Laporte_2023_%28cropped%29_2.jpg", answer: "Aymeric Laporte" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Dani_Carvajal_10_%28cropped%29.jpg", answer: "Dani Carvajal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Ferran_Torres_Garc%C3%ADa.png", answer: "Ferran Torres" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/2022-07-30_Fu%C3%9Fball%2C_M%C3%A4nner%2C_DFL-Supercup%2C_RB_Leipzig_-_FC_Bayern_M%C3%BCnchen_1DX_3321_by_Stepro_%28cropped%29.jpg", answer: "Christopher Nkunku" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Clauss_asse_ogcn_2425.png", answer: "Jonathan Clauss" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Theo_Hernandez_France_v_Norway_26_June_26-122.jpg", answer: "Théo Hernandez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Wissam_Ben_Yedder_AS_Monaco_capitain_%2820-12-2023%29_%28cropped%29.jpg", answer: "Wissam Ben Yedder" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Bukayo_Saka_England_v_Ghana_23_June_2026-057_%28cropped%29.jpg", answer: "Bukayo Saka" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2613%2C_Phil_Foden.jpg", answer: "Phil Foden" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Declan_Rice_England_v_Ghana_23_June_2026-150.jpg", answer: "Declan Rice" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg", answer: "Harry Kane" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Joshua_Kimmich_Ecuador_v_Germany_25_June_2026-149.jpg", answer: "Joshua Kimmich" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg", answer: "Manuel Neuer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/72/Antonio_Rudiger_Ecuador_v_Germany_25_June_2026-055_%28cropped%29.jpg", answer: "Antonio Rüdiger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Leroy_Sane_Ecuador_v_Germany_25_June_2026-119_%28cropped%29.jpg", answer: "Leroy Sané" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/55/Serge_Gnabry_WC2022.jpg", answer: "Serge Gnabry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/20180602_FIFA_Friendly_Match_Austria_vs._Germany_%C4%B0lkay_G%C3%BCndo%C4%9Fan_850_0728.jpg", answer: "İlkay Gündoğan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/NiclasF%C3%BCllkrug_%28cropped%29.jpg", answer: "Niclas Füllkrug" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93069.jpg", answer: "Nico Schlotterbeck" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Leon_Goretzka_Ecuador_v_Germany_25_June_2026-159.jpg", answer: "Leon Goretzka" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Federico_Chiesa_vs_Zenit_2021-10-20_%28cropped2%29.jpg", answer: "Federico Chiesa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/%D0%9C%D0%B0%D1%82%D1%87_%C2%AB%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%BE%C2%BB_-_%C2%AB%D0%91%D0%B0%D1%80%D1%81%D0%B5%D0%BB%D0%BE%D0%BD%D0%B0%C2%BB_0-1._2_%D0%BD%D0%BE%D1%8F%D0%B1%D1%80%D1%8F_2021_%D0%B3%D0%BE%D0%B4%D0%B0._II_%E2%80%94_1289671_%28cropped%29.jpg", answer: "Frenkie de Jong" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Memphis_Depay_2019.jpg", answer: "Memphis Depay" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Cody_Gakpo_06042025_%282%29_%28cropped%29.jpg", answer: "Cody Gakpo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2672_%28Xavi_Simons%29.jpg", answer: "Xavi Simons" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Edison_ndreca_inter_egnati_%28cropped_Denzel_Dumfries%29.jpg", answer: "Denzel Dumfries" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Yokohama_F._Marinos_-_Manchester_City_%283-5%29_-_53075276224_%28Nathan_Ake%29.jpg", answer: "Nathan Aké" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Jeremie_Frimpong_04012026_%283%29_%28cropped%29.jpg", answer: "Jeremie Frimpong" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg", answer: "Kevin De Bruyne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Romelu_Lukaku_2021.jpg", answer: "Romelu Lukaku" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/06/J%C3%A9r%C3%A9my_Doku_USMNT_v_Belgium_Mar_28_2026-27_%28cropped%29.jpg", answer: "Jérémy Doku" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Jhon_Dur%C3%A1n%2C_Esteghlal_FC_vs_Al-Nassr_FC_%28ACLElite%29%3B_3_Mar_2025.png", answer: "Jhon Durán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/RAFAEL_BORRE_%28cropped2%29.jpg", answer: "Rafael Santos Borré" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Richard-Rios-Palmeiras-Liverpool-abr24.jpg", answer: "Richard Ríos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Moises_Caicedo_Ecuador_v_Germany_25_June_2026-051_%28cropped%29.jpg", answer: "Moisés Caicedo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Piero_Hincapie_Cote_D%27Ivoire_v_Ecuador_14_June_2026-247_%28cropped%29.jpg", answer: "Piero Hincapié" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Kendry_Paez_Cote_D%27Ivoire_v_Ecuador_14_June_2026-37_%28cropped%29.jpg", answer: "Kendry Páez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Gonzalo_Plata_Cote_D%27Ivoire_v_Ecuador_14_June_2026-12_%28cropped%29.jpg", answer: "Gonzalo Plata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Santiago_Gim%C3%A9nez.png", answer: "Santiago Giménez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Edson_%C3%81lvarez.png", answer: "Edson Álvarez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Juli%C3%A1n_Qui%C3%B1ones.png", answer: "Julián Quiñones" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Hirving_Lozano.png", answer: "Hirving Lozano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/Orbel%C3%ADn_Pineda.png", answer: "Orbelín Pineda" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Alexis_S%C3%A1nchez_2017.jpg", answer: "Alexis Sánchez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Ben_Brereton_D%C3%ADaz_25042026_%289%29.jpg", answer: "Ben Brereton Díaz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Audax_Italiano_v_Colo-Colo_20200209_42.jpg", answer: "Gabriel Suazo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Marcelino_Nunez.png", answer: "Marcelino Núñez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg", answer: "Achraf Hakimi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Mohammed_Kudus_of_West_Ham_United.jpeg", answer: "Mohammed Kudus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Thomas_Partey_5_England_v_Ghana_at_2026_Fifa_World_Cup_by_YantsImages_02_%28cropped%29.jpg", answer: "Thomas Partey" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Mahrez_2021.jpg", answer: "Riyad Mahrez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mohamed_Salah_2018.jpg", answer: "Mohamed Salah" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Miguel_Almir%C3%B3n_Red_Bull_Atlanta_5.31.25-069_%28cropped%29.jpg", answer: "Miguel Almirón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Salom%C3%B3n_Rond%C3%B3n_2021.jpg", answer: "Salomón Rondón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Soteldo_2018_%28cropped%29.jpg", answer: "Yeferson Soteldo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Palestino_-_Alianza_Lima_20190204_01.jpg", answer: "Pedro Gallese" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/CSKA_Sporting_%283%29_%28cropped%29.jpg", answer: "André Carrillo" },
     { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Ederson_Brazil_V_Morocco_13_June_2026-14_%28cropped%29.jpg", answer: "Ederson (footballer, born 1993)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Antony_2022.jpg", answer: "Antony (footballer, born 2000)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Danilo_and_Bilal_El_Khannouss_at_2026_FIFA_World_Cup_by_YantsImages_%28cropped%29.jpg", answer: "Danilo (footballer, born July 1991)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Wendell.jpg", answer: "Wendell (footballer, born 1993)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Andre_Fluminense_vs_Vila_Nova_2022.png", answer: "André (footballer, born 2001)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Estevao-Palmeiras-Liverpool-abr24_%28cropped%29.jpg", answer: "Estêvão Willian" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Igor_Jesus_22122025_%281%29_%28Igor_Jesus%29.jpg", answer: "Igor Jesus (footballer, born 2001)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Jo%C3%A3o_Pedro%2C_2025_FIFA_Club_World_Cup_final_%2854654843615%29.jpg", answer: "João Pedro (footballer, born 2001)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Luiz_Henrique_Brazil_V_Morocco_13_June_2026-147.jpg", answer: "Luiz Henrique (footballer, born 2001)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Jugadors_pretemporada_pels_Estats_Units_%28cropped%292.jpg", answer: "Gavi (footballer)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/41/RODRI_-_SWE_vs_ESP_-_UEFA_EURO_2020_QUALIFIERS_-_2019.10.15_%28cropped%29.jpg", answer: "Rodri (footballer, born 1996)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Warren_Zaire-Emery_France_v_Senegal_16_June_2026-279.jpg", answer: "Warren Zaïre-Emery" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Desire_Doue_France_v_Norway_26_June_26-032.jpg", answer: "Désiré Doué" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Amadou_Onana_USMNT_v_Belgium_Mar_28_2026-96_%28cropped%29.jpg", answer: "Amadou Onana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Charles_De_Ketelaere_USMNT_v_Belgium_Mar_28_2026-76_%28cropped%29.jpg", answer: "Charles De Ketelaere" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/96/Arthur_Theate_USMNT_v_Belgium_Mar_28_2026-22_%28cropped%29.jpg", answer: "Arthur Theate" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Ofrenda_de_la_Liga_y_la_Champions-57-L.Mill%C3%A1n_%2852109310843%29_%28Luka_Modri%C4%87%29.jpg", answer: "Luka Modrić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6a/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2611_%28Jo%C5%A1ko_Gvardiol%29.jpg", answer: "Joško Gvardiol" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Chelsea_vs._Arsenal%2C_29_May_2019_18_Kovacic.jpg", answer: "Mateo Kovačić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Marin_Pongracic_Croatia_v_Portugal_2_July_2026-122_%28cropped%29.jpg", answer: "Marin Pongračić" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/M.UGARTE.jpg", answer: "Manuel Ugarte (footballer)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg", answer: "Luis Díaz (footballer, born 1997)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Alexis_Vega.png", answer: "Alexis Vega (Mexican footballer)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg", answer: "Son Heung-min" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Lee_Kang-in_-_2022_%2852551771501%29_%28cropped%29.jpg", answer: "Lee Kang-in" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Kaoru_Mitoma_%282022%29.jpg", answer: "Kaoru Mitoma" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Takefusa_Kubo_2019.png", answer: "Takefusa Kubo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Ritsu_Doan%2C_2019_AFC_Asian_Cup_1.jpg", answer: "Ritsu Dōan" },
];