import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const futbolistasRetirados: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pele_con_brasil_%28cropped%29.jpg", answer: "Pelé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Argentina_celebrando_copa_%28cropped%29.jpg", answer: "Diego Maradona" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Johan_Cruijff_%281974%29.jpg", answer: "Johan Cruyff" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Franz_Beckenbauer_%281975%29.jpg", answer: "Franz Beckenbauer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Di_Stefano_1959.jpg", answer: "Alfredo Di Stéfano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/93/Ferenc_Puskas_en_1965.jpg", answer: "Ferenc Puskás" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Manoel_Francisco_dos_Santos-Garrincha.jpg", answer: "Garrincha" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/55/Eusebio_en_1973.jpg", answer: "Eusébio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/George_best_1976.jpg", answer: "George Best" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/LondonHouseAmsterdam1966_Bobby_Charlton.jpg", answer: "Bobby Charlton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Michel_Platini_2010_%28cropped%29.jpg", answer: "Michel Platini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Marco_van_Basten_%282%29_%28cropped%29.jpg", answer: "Marco van Basten" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/67/25th_Laureus_World_Sports_Awards_-_Ruud_Gullit_-_240422_131911_%28cropped%29.jpg", answer: "Ruud Gullit" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/FrankRijkaard2.jpg", answer: "Frank Rijkaard" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/84/2019_Lothar_Matth%C3%A4us.jpg", answer: "Lothar Matthäus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Paolo_Maldini_AC_Milan_Technical_director_2018.jpg", answer: "Paolo Maldini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Franco_Baresi_2012.jpg", answer: "Franco Baresi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/%D8%B1%D9%88%D8%A8%D8%B1%D8%AA%D9%88_%D8%A8%D8%A7%D8%AC%D9%88_%28cropped%29.jpg", answer: "Roberto Baggio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Giuseppe_Meazza_1935.jpg", answer: "Giuseppe Meazza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Gerd_M%C3%BCller_c1973_%28cropped%29.jpg", answer: "Gerd Müller" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/2015-02-06_Rummenigge_0370_%28cropped%29.JPG", answer: "Karl-Heinz Rummenigge" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Socrates_elgrafico_1983.jpg", answer: "Sócrates" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Senadores_da_57%C2%AA_Legislatura_%2852689451805%29.jpg", answer: "Romário" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Ronaldo_Lu%C3%ADs_Naz%C3%A1rio_de_Lima_2019_%283x4_cropped%29.jpg", answer: "Ronaldo (Brazilian footballer)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/2019_-_Press_conferences_-_Day_1_ENX_6950_%2849019873887%29_%28cropped%29.jpg", answer: "Ronaldinho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Rivaldo.jpg", answer: "Rivaldo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Kak%C3%A1_visited_Stadium_St._Petersburg.jpg", answer: "Kaká" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Cafu_-_26.02.2026_-_Cerim%C3%B4nia_de_apresenta%C3%A7%C3%A3o_das_ta%C3%A7as_da_Copa_do_Mundo_de_2026.jpg", answer: "Cafu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/LS3_1288_%2853332367864%29_%28cropped%29.jpg", answer: "Roberto Carlos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Lucio_Attinelli.JPG", answer: "Lucio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/2021_-_Press_conferences_SM7_0168_%2851649502936%29_%28cropped%29.jpg", answer: "Gilberto Silva" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Juninho_Pernambucano.JPG", answer: "Juninho Pernambucano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Bebeto_brazil_%28cropped%29.jpg", answer: "Bebeto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Tost%C3%A3o_1970.jpg", answer: "Tostão" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Rivellino_1970.jpg", answer: "Rivellino" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Jairzinho_1970s.jpg", answer: "Jairzinho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Carlos_alberto_cosmos.jpg", answer: "Carlos Alberto Torres" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Nilton_Santos_1_%281956%29.tif/lossy-page1-960px-Nilton_Santos_1_%281956%29.tif.jpg", answer: "Nílton Santos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Djalma_Santos.jpg", answer: "Djalma Santos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Paulo_Roberto_Falc%C3%A3o%2C_Roma_1983-84.jpg", answer: "Paulo Roberto Falcão" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Antonio_de_Oliveira_Filho_%28Careca%29_01.jpg", answer: "Careca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/08/Robinho061115-2.jpg", answer: "Robinho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Daniel_passarella_en_1985.jpg", answer: "Daniel Passarella" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Kempes_Valencia_CF.jpg", answer: "Mario Kempes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Omar_Batistuta_%282%29.jpg", answer: "Gabriel Batistuta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Metalist-Inter_%282%29.jpg", answer: "Javier Zanetti" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Juan_Rom%C3%A1n_Riquelme_-_2019.jpg", answer: "Juan Román Riquelme" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Pablo_Aimar_Argentina_v_Egypt_7_July_2026-080.jpg", answer: "Pablo Aimar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Ariel_Ortega_%28cropped%29.jpg", answer: "Ariel Ortega" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Caniggia_sonriente_1988.jpg", answer: "Claudio Caniggia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/30/Burruchaga_final_cropped.jpg", answer: "Jorge Burruchaga" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Ruggeri_debut_boca.jpg", answer: "Oscar Ruggeri" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Jorge_Valdano_Cropped.jpg", answer: "Jorge Valdano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Diego_Simeone_-_240422_192621-2_%28cropped%29.jpg", answer: "Diego Simeone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/08/Esteban_Cambiasso_FC_Internazionale.jpg", answer: "Esteban Cambiasso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Javier_Mascherano_NE_Revolution_Inter_Miami_7.9.25-040_%28cropped%29.jpg", answer: "Javier Mascherano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/31/Carlos_Tevez_with_Argentina_November_2014_%28cropped%29.jpg", answer: "Carlos Tevez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Ag%C3%BCero_in_2018.jpg", answer: "Sergio Agüero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/72/Gonzalo_Higua%C3%ADn_2019.jpg", answer: "Gonzalo Higuaín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/%D0%A4%D0%B5%D1%80%D0%BD%D0%B0%D0%BD%D0%B4%D0%BE_%D0%A0%D0%B5%D0%B4%D0%BE%D0%BD%D0%B4%D0%BE_2019.png", answer: "Fernando Redondo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/018_Summer_Youth_Olympics_%2830382602628%29_%28cropped%29.jpg", answer: "Roberto Ayala" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Walter_Samuel_FC_Internazionale.jpg", answer: "Walter Samuel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Juan_Sebastian_Veron_2017.jpg", answer: "Juan Sebastián Verón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Chelsea_Legends_1_Inter_Forever_4_%2827457022797%29.jpg", answer: "Hernán Crespo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Everton_-_Uni%C3%B3n_Espa%C3%B1ola%2C_2018-04-28_-_Mart%C3%ADn_Palermo_-_01_%28cropped%29.jpg", answer: "Martín Palermo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Diego_Milito_%2822677058983%29_%28cropped%29.jpg", answer: "Diego Milito" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Gabriel_Heinze_en_Newell%27s_Old_Boys_%282022%29.jpg", answer: "Gabriel Heinze" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Suisse_vs_Argentine_-_Maximiliano_Rodriguez_%28cropped2%29.jpg", answer: "Maxi Rodríguez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Hertha_BSC_vs._West_Ham_United_20190731_%28127%29.jpg", answer: "Pablo Zabaleta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Kiev-PSG_%287%29.jpg", answer: "Ezequiel Lavezzi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Bocho.JPG", answer: "Ricardo Bochini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Fillol_river.jpg", answer: "Ubaldo Fillol" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Am%C3%A9rico_Gallego_1982.jpg", answer: "Américo Gallego" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Enzo_Francescoli_1984_%28cropped%29.jpg", answer: "Enzo Francescoli" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/%C3%81lvaro_Chino_Recoba_120520-1175-jikatu_%28cropped%29.jpg", answer: "Álvaro Recoba" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/U10_Diego_Forl%C3%A1n_7524.jpg", answer: "Diego Forlán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Paolo_Montero.jpg", answer: "Paolo Montero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Obdulio_varela_uruguay.jpg", answer: "Obdulio Varela" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/16/Jose_nasazzi_urug.jpg", answer: "José Nasazzi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/WK_74_training_Uruguay_in_Duitsburg%2C_keeper_Mazurkievic_laat_zijn_handen_zien%2C_Bestanddeelnr_927-2464.jpg", answer: "Ladislao Mazurkiewicz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Pibe_Valderrama_2022.jpg", answer: "Carlos Valderrama" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Ren%C3%A9_Higuita%2C_2007.jpg", answer: "René Higuita" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Ivan_Cordoba_-_Inter_Mailand_%281%29.jpg", answer: "Iván Córdoba" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/Freddy_Rincon.jpg", answer: "Freddy Rincón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Tino_Asprilla_en_2019_02.jpg", answer: "Faustino Asprilla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/James_Rodriguez_2018.jpg", answer: "James Rodríguez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Alex_Aguinaga_2015_09_20.jpg", answer: "Álex Aguinaga" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/61/Marcelo_Salas_2015.jpg", answer: "Marcelo Salas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Iv%C3%A1n_Zamorano.jpg", answer: "Iván Zamorano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Don_El%C3%ADas_Figueroa.jpg", answer: "Elías Figueroa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Claudio_Bravo_Footballteam_of_Chile_-_Spain_vs._Chile%2C_10th_September_2013_%28cropped%29.jpg", answer: "Claudio Bravo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Jorge_Campos_1993.jpg", answer: "Jorge Campos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Cuauht%C3%A9moc_Blanco_MORELOS_%28cropped%29.jpg", answer: "Cuauhtémoc Blanco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/Rafael_M%C3%A1rquez_2014.jpg", answer: "Rafael Márquez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Carlos_Hermosillo.png", answer: "Carlos Hermosillo" },
    { image: "https://upload.wikimedia.org/wikipedia/en/a/a4/Antonio-Carbajal.jpg", answer: "Antonio Carbajal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Huguito.jpg", answer: "Hugo Sánchez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Keylor_Navas_2018_%28cropped%29.jpg", answer: "Keylor Navas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Paulo_Wanchope_%28cropped%29.jpg", answer: "Paulo Wanchope" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Salvador_Caba%C3%B1as.jpg", answer: "Salvador Cabañas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Roque_Santa_Cruz_2025_%28cropped%29.jpg", answer: "Roque Santa Cruz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Chilavert_sanlorenzo.jpg", answer: "José Luis Chilavert" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Paulo_C%C3%A9sar_Da_Silva.jpg", answer: "Paulo da Silva" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/72/Palestino_-_River_Plate_20190424_32.jpg", answer: "Marcelo Gallardo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/David_Beckham_UNICEF_%28cropped2%29.jpg", answer: "David Beckham" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Steven_Gerrard_2018.jpg", answer: "Steven Gerrard" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Frank_Lampard_2019.jpg", answer: "Frank Lampard" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/P_Scholes.jpg", answer: "Paul Scholes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wayne_Rooney_%2850121495731%29_%28cropped%29.jpg", answer: "Wayne Rooney" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Web_Summit_2015_-_Dublin%2C_Ireland_-_22183056474_%28cropped%29.jpg", answer: "Rio Ferdinand" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/John_Terry_at_pro-am_Wentworth_golf_course_September_2023_%28cropped%29.jpg", answer: "John Terry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/ACole.JPG", answer: "Ashley Cole" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Gary_Neville_2014_%28cropped%29.jpg", answer: "Gary Neville" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Phil_Neville_2019.jpg", answer: "Phil Neville" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Michael_Owen.jpg", answer: "Michael Owen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Alan_Shearer_2008.jpg", answer: "Alan Shearer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Prime_Minister_Keir_Starmer_hosts_St_George%27s_Day_Reception_%2854470857860%29_%28cropped%29.jpg", answer: "Gary Lineker" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Paul_Gascoigne_2021.png", answer: "Paul Gascoigne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Peter_Shilton.png", answer: "Peter Shilton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Sol_Campbell_%2854921202604%29_%28cropped%29.jpg", answer: "Sol Campbell" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Ledley_King.jpg", answer: "Ledley King" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Joe_Cole2023.jpeg", answer: "Joe Cole" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Emile_Heskey_as_a_player_of_England_national_football_team.jpg", answer: "Emile Heskey" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Didier_Drogba_%282019%29_%28cropped2%29.jpg", answer: "Didier Drogba" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Yaya_Tour%C3%A9_%28cropped%29.jpg", answer: "Yaya Touré" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Kolo_Toure_8932.JPG", answer: "Kolo Touré" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Samuel_2011.jpg", answer: "Samuel Eto'o" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Chelsea_Legends_1_Inter_Forever_4_%2828453496098%29_%28cropped%29.jpg", answer: "Michael Essien" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Match_legends_2017_CC_%285%29.jpg", answer: "Jay-Jay Okocha" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/1_nwankwo_kanu_2017_%28edited%29.jpg", answer: "Nwankwo Kanu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Milla2008cropped.jpg", answer: "Roger Milla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Abedi_Pele_2007.jpg", answer: "Abedi Pele" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/Clar_Weah%2C_George_Weah%2C_Joe_Biden%2C_Jill_Biden_%28cropped%29.jpg", answer: "George Weah" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/92/Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg", answer: "Sadio Mané" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg", answer: "Zinedine Zidane" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Thierry_Henry_%2851649035951%29_%28cropped%29.jpg", answer: "Thierry Henry" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Patrick_Vieira_NYCFC_%28cropped%29.JPG", answer: "Patrick Vieira" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Claude_Mak%C3%A9l%C3%A9l%C3%A9_%2853557564951%29_%28cropped%29.jpg", answer: "Claude Makélélé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Lilian_Thuram_-_F%C3%A9vrier_2013.jpg", answer: "Lilian Thuram" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Fabien_Barthez_at_OM.jpg", answer: "Fabien Barthez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/David_Trezeguet_became_Save_the_Dream_Ambassador%2C_2017_%28cropped%29.jpg", answer: "David Trezeguet" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Youri_Djorkaeff_2011.jpg", answer: "Youri Djorkaeff" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Laurent_blanc_11_11_2013_reves_de_Clara.jpg", answer: "Laurent Blanc" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Marcel_Desailly_-_240422_192752-3_%28cropped%29.jpg", answer: "Marcel Desailly" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Eric_Cantona_Cannes_2009.jpg", answer: "Eric Cantona" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/PapinJP1997_%28cropped%29.jpg", answer: "Jean-Pierre Papin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Bixente_Lizarazu_%28cropped%29.jpg", answer: "Bixente Lizarazu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Just_Fontaine_en_1958.jpg", answer: "Just Fontaine" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/2022-07-30_Fu%C3%9Fball%2C_M%C3%A4nner%2C_DFL-Supercup%2C_RB_Leipzig_-_FC_Bayern_M%C3%BCnchen_1DX_3179_by_Stepro.jpg", answer: "Oliver Kahn" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/2016209185719_2016-07-27_Champions_for_Charity_-_Sven_-_1D_X_-_0149_-_DV3P4742_mod.jpg", answer: "Miroslav Klose" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Philipp_Lahm_auf_der_Berlinale_2024%2C_Ausschnitt.jpg", answer: "Philipp Lahm" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Re-publica_23_-_Tag_3_%2852957826298%29_%28cropped%29.jpg", answer: "Bastian Schweinsteiger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/54_Merci_Ars%C3%A8ne_-_Per_Mertesacker_%2827086040527%29.jpg", answer: "Per Mertesacker" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/10._Tag_der_Legenden_2014_69.jpg", answer: "Michael Ballack" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Thomas_H%C3%A4%C3%9Fler_%282%29_%28cropped%29.JPG", answer: "Thomas Häßler" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/2018-11-30_DFB_presentation_of_the_new_head_coach_of_the_National_Womens_Team_StP_6868_LR10_by_Stepro.jpg", answer: "Oliver Bierhoff" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/af/J%C3%BCrgen_Klinsmann_14021113000678638425063004371092_64131.jpg", answer: "Jürgen Klinsmann" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Andreas_Brehme.jpg", answer: "Andreas Brehme" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/51/6137Sepp_Maier_Torwart-Legende.JPG", answer: "Sepp Maier" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Uwe_Seeler_1966_%28cropped%29.jpg", answer: "Uwe Seeler" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Toni_Kroos_Real_Madrid_2021.jpg", answer: "Toni Kroos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Iker-Casillas-SportsTrade-2021-cropped.jpg", answer: "Iker Casillas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Andr%C3%A9s_Iniesta_2019.jpg", answer: "Andrés Iniesta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Premios_Goya_2020_-_Carles_Pujol.jpg", answer: "Carles Puyol" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Spain-Tahiti%2C_Confederations_Cup_2013_%2802%29_%28Villa_crop%29.jpg", answer: "David Villa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Fernando_Torres_2017.jpg", answer: "Fernando Torres" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Los_Caminos_del_f%C3%BAtbol._Xabi_Alonso_%2839666778464%29_%28cropped%29.jpg", answer: "Xabi Alonso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Sergio_Busquets_NYCFC_Miami_24_Sep_2025-020_%28cropped%29.jpg", answer: "Sergio Busquets" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Gerard_Piqu%C3%A9_Euro_2012_vs_France_01.jpg", answer: "Gerard Piqué" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Spain_-_Chile_-_10-09-2013_-_Geneva_-_Victor_Valdes_6_%28cropped%29.jpg", answer: "Víctor Valdés" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Fernando_Hierro_in_Spain-Iran_press_conference_2018-06-19.jpg", answer: "Fernando Hierro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Josep_Guardiola_2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2797_%28cropped%29.jpg", answer: "Pep Guardiola" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Luis_Enrique_2014.jpg", answer: "Luis Enrique" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Emilio_Butrague%C3%B1o_-_240422_191751-2_%28cropped%29.jpg", answer: "Emilio Butragueño" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Luis_Su%C3%A1rez_Miramontes_1962.jpg", answer: "Luis Suárez (Spanish footballer)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/71/Andoni_Zubizarreta_en_2013-03_-_versi%C3%B3n_ampliada_%28cropped%29.JPG", answer: "Andoni Zubizarreta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/2023_-_Cesc_Fabregas_%28cropped%29.jpg", answer: "Cesc Fàbregas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/David_Silva_2017.jpg", answer: "David Silva" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Juan_Mata_Melbourne_Victory_Signing_Press_Conference.png", answer: "Juan Mata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Santi_Cazorla%2C_2012-08-18_%28cropped%29.jpg", answer: "Santi Cazorla" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg", answer: "Gianluigi Buffon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/25th_Laureus_World_Sports_Awards_-_Alessandro_Del_Piero_-_240421_155220_%28cropped%29.jpg", answer: "Alessandro Del Piero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/KL-2018_%284%29.jpg", answer: "Francesco Totti" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Andrea_Pirlo_%28cropped%29.jpg", answer: "Andrea Pirlo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Lausanne_vs_Sion_27_february_2013_-_Gennaro_Gattuso.jpg", answer: "Gennaro Gattuso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/Fabio_Cannavaro_2011.jpg", answer: "Fabio Cannavaro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Alessandro_Nesta_as_Miami_FC_Manager.jpg", answer: "Alessandro Nesta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Christian_Vieri_%28cropped%29.jpg", answer: "Christian Vieri" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Filippo_Inzaghi_2011.jpg", answer: "Filippo Inzaghi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Gianluca_Zambrotta_2019_%28cropped%29.jpg", answer: "Gianluca Zambrotta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Daniele_De_Rossi_BGR-ITA_2012.jpg", answer: "Daniele De Rossi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/37/Antonio_di_natale.JPG", answer: "Antonio Di Natale" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/46/FC_Zenit_Saint_Petersburg_vs._Juventus%2C_20_October_2021_33_%28Luca_Toni%29.jpg", answer: "Luca Toni" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/30/Chiellini_Mancini_Gravina_Mattarella_2021_%28Giorgio_Chiellini%29.jpg", answer: "Giorgio Chiellini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Leonardo_Bonucci_%28cropped_2%29.jpg", answer: "Leonardo Bonucci" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Angelo_Peruzzi_%282019%29.jpg", answer: "Angelo Peruzzi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Dino_Zoff_-_1972_-_Juventus_FC_%28cropped%29.jpg", answer: "Dino Zoff" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/1975%E2%80%9376_Juventus_FC_-_Gaetano_Scirea.jpg", answer: "Gaetano Scirea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Roberto_Donadoni_-_SSC_Neapel_%282%29_%28cropped%29.jpg", answer: "Roberto Donadoni" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Clarence_Seedorf_Introductory_Press_Conferences%2C_2_June_2025_-_40_%28cropped%29.jpg", answer: "Clarence Seedorf" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Edgar_Davids_%28cropped%29.jpg", answer: "Edgar Davids" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Dennis_Bergkamp_2014_%28cropped%29.jpg", answer: "Dennis Bergkamp" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Patrick_Kluivert_at_Web_Summit_2024_%28cropped_2%29.jpg", answer: "Patrick Kluivert" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Ruud_van_Nistelrooy_2017.jpg", answer: "Ruud van Nistelrooy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Arjen_Robben_v_Shakhtar_2015_%28cropped%29.jpg", answer: "Arjen Robben" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Wesley_Sneijder_%2815487233555%29_%28cropped%29.jpg", answer: "Wesley Sneijder" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Loco-Fener_%2810%29.jpg", answer: "Robin van Persie" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Dirk_Kuijt-Feyenoord-DSC_0058_%28cropped%29.jpg", answer: "Dirk Kuyt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/18/Jaap_Stam_-_1.jpg", answer: "Jaap Stam" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Giovanni_van_Brocnkhorst_20240803.jpg", answer: "Giovanni van Bronckhorst" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/86/2010_Mark_van_Bommel.jpg_%28cropped%29.jpg", answer: "Mark van Bommel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Nigel_de_Jong_2011_%282%29.jpg", answer: "Nigel de Jong" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Arsenal_players_training_before_2019_UEFA_Europa_League_final_07_%28cropped%29.jpg", answer: "Petr Čech" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/46/Pavel_Nedv%C4%9Bd.jpg", answer: "Pavel Nedvěd" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Arsenal_Vs_Burnley_%2824618630252%29.jpg", answer: "Tomáš Rosický" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Jankulovski.jpg", answer: "Marek Jankulovski" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Football_against_poverty_2014_-_Davor_%C5%A0uker_%28cropped%29.jpg", answer: "Davor Šuker" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Prosinecki_in_2025.jpg", answer: "Robert Prosinečki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Zvonimir_Boban_in_2018.jpg", answer: "Zvonimir Boban" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Dejan_Savi%C4%87evi%C4%87.jpg", answer: "Dejan Savićević" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/35/Predrag_Mijatovi%C4%87_2007_b.jpg", answer: "Predrag Mijatović" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoichkov_in_2016.jpg/1920px-Stoichkov_in_2016.jpg", answer: "Hristo Stoichkov" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Dimitar_Berbatov_-_53689576017.jpg", answer: "Dimitar Berbatov" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Lansarea_candidaturii_Gabrielei_Szabo_pentru_Camera_Deputatilor%2C_Voluntari_-_04.05_%2848%29_%2814270956179%29_%28cropped%29.jpg", answer: "Gheorghe Hagi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Adrian_Mutu_2.jpg", answer: "Adrian Mutu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Luis_Figo_2023.jpg", answer: "Luís Figo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Rui_Costa_2019.png", answer: "Rui Costa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Deco_com_o_Fluminense_em_2013_%28cropped%29.jpg", answer: "Deco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Web_Summit_2017_-_SportsTrade_CG1_7194_%2824373526808%29_%28cropped%29.jpg", answer: "Nuno Gomes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Vitor_baia_in_2016.jpg", answer: "Vítor Baía" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Pedro_Pauleta_2012.jpg", answer: "Pauleta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Ricardo_Carvalho.jpg", answer: "Ricardo Carvalho" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/06/Chivu2018.jpg", answer: "Cristian Chivu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Milan_Baro%C5%A13%2C_FCB-SLAVIA_30092018.jpg", answer: "Milan Baroš" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Henrik_Larsson_in_Jan_2014.jpg", answer: "Henrik Larsson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/30/2013_Robbie_Keane_%28cropped%29.jpg", answer: "Robbie Keane" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/67/Ian_Rush_in_Singapore.jpg", answer: "Ian Rush" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Kenny_Dalglish_2009_Singapore.jpg", answer: "Kenny Dalglish" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Peter_Schmeichel_2012-01-25_001.jpg", answer: "Peter Schmeichel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Brian-Laudrup-Darren-Laver-Lars-Hogh_%28cropped%29.jpg", answer: "Brian Laudrup" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Allan_Simonsen_20121027.JPG", answer: "Allan Simonsen" },
];
