export const englishWords = [
  { text: "Engineer", answer: "Ingeniero" },
  { text: "Doctor", answer: "Médico" },
  { text: "Lawyer", answer: "Abogado" },
  { text: "Chef", answer: "Chef" },
  { text: "Pilot", answer: "Piloto" },
  { text: "Farmer", answer: "Granjero" },
  { text: "Police officer", answer: "Policía" },
  { text: "Firefighter", answer: "Bombero" },
  { text: "Journalist", answer: "Periodista" },
  { text: "Actor", answer: "Actor" },
  { text: "Actress", answer: "Actriz" },
  { text: "Singer", answer: "Cantante" },
  { text: "Dancer", answer: "Bailarín" },
  { text: "Scientist", answer: "Científico" },
  { text: "Programmer", answer: "Programador" },
  { text: "Achievement", answer: "Logro" },
  { text: "Advice", answer: "Consejo" },
  { text: "Agreement", answer: "Acuerdo" },
  { text: "Amount", answer: "Cantidad" },
  { text: "Behaviour", answer: "Comportamiento" },
  { text: "Belief", answer: "Creencia" },
  { text: "Branch", answer: "Rama" },
  { text: "Challenge", answer: "Desafío" },
  { text: "Choice", answer: "Elección" },
  { text: "Citizen", answer: "Ciudadano" },
  { text: "Complaint", answer: "Queja" },
  { text: "Connection", answer: "Conexión" },
  { text: "Courage", answer: "Valentía" },
  { text: "Crowd", answer: "Multitud" },
  { text: "Decision", answer: "Decisión" },
  { text: "Degree", answer: "Título universitario" },
  { text: "Demand", answer: "Demanda" },
  { text: "Effort", answer: "Esfuerzo" },
  { text: "Environment", answer: "Medio ambiente" },
  { text: "Equipment", answer: "Equipo" },
  { text: "Evidence", answer: "Evidencia" },
  { text: "Experience", answer: "Experiencia" },
  { text: "Failure", answer: "Fracaso" },
  { text: "Feature", answer: "Característica" },
  { text: "Forecast", answer: "Pronóstico" },
  { text: "Goal", answer: "Objetivo" },
  { text: "Growth", answer: "Crecimiento" },
  { text: "Habit", answer: "Hábito" },
  { text: "Harvest", answer: "Cosecha" },
  { text: "Improvement", answer: "Mejora" },
  { text: "Income", answer: "Ingreso" },
  { text: "Influence", answer: "Influencia" },
  { text: "Journey", answer: "Viaje" },
  { text: "Knowledge", answer: "Conocimiento" },
  { text: "Leader", answer: "Líder" },
  { text: "Neighbourhood", answer: "Barrio" },
  { text: "Opportunity", answer: "Oportunidad" },
  { text: "Package", answer: "Paquete" },
  { text: "Permission", answer: "Permiso" },
  { text: "Population", answer: "Población" },
  { text: "Purpose", answer: "Propósito" },
  { text: "Receipt", answer: "Recibo" },
  { text: "Relationship", answer: "Relación" },
  { text: "Research", answer: "Investigación" },
  { text: "Responsibility", answer: "Responsabilidad" },
  { text: "Schedule", answer: "Horario" },
  { text: "Skill", answer: "Habilidad" },
  { text: "Success", answer: "Éxito" },
  { text: "Value", answer: "Valor" },
  { text: "Volunteer", answer: "Voluntario" },
  { text: "Abandon", answer: "Abandonar" },
  { text: "Accurate", answer: "Preciso" },
  { text: "Acquire", answer: "Adquirir" },
  { text: "Awareness", answer: "Conciencia" },
  { text: "Bargain", answer: "Ganga" },
  { text: "Breathtaking", answer: "Impresionante" },
  { text: "Commitment", answer: "Compromiso" },
  { text: "Consequence", answer: "Consecuencia" },
  { text: "Controversial", answer: "Controvertido" },
  { text: "Convince", answer: "Convencer" },
  { text: "Deadline", answer: "Fecha límite" },
  { text: "Decrease", answer: "Disminuir" },
  { text: "Despite", answer: "A pesar de" },
  { text: "Determine", answer: "Determinar" },
  { text: "Disaster", answer: "Desastre" },
  { text: "Drought", answer: "Sequía" },
  { text: "Endure", answer: "Soportar" },
  { text: "Establish", answer: "Establecer" },
  { text: "Exhausted", answer: "Agotado" },
  { text: "Expand", answer: "Expandir" },
  { text: "Faint", answer: "Desmayarse" },
  { text: "Flexible", answer: "Flexible" },
  { text: "Fortunate", answer: "Afortunado" },
  { text: "Generous", answer: "Generoso" },
  { text: "Headquarters", answer: "Sede central" },
  { text: "Heritage", answer: "Patrimonio" },
  { text: "Hesitate", answer: "Dudar" },
  { text: "Humble", answer: "Humilde" },
  { text: "Inheritance", answer: "Herencia" },
  { text: "Insight", answer: "Perspicacia" },
  { text: "Livelihood", answer: "Medio de vida" },
  { text: "Maintain", answer: "Mantener" },
  { text: "Negotiate", answer: "Negociar" },
  { text: "Nevertheless", answer: "Sin embargo" },
  { text: "Outcome", answer: "Resultado" },
  { text: "Outstanding", answer: "Sobresaliente" },
  { text: "Overcome", answer: "Superar" },
  { text: "Perspective", answer: "Perspectiva" },
  { text: "Poverty", answer: "Pobreza" },
  { text: "Prevent", answer: "Prevenir" },
  { text: "Pursue", answer: "Perseguir" },
  { text: "Reasonable", answer: "Razonable" },
  { text: "Recover", answer: "Recuperarse" },
  { text: "Reluctant", answer: "Reacio" },
  { text: "Reliable", answer: "Confiable" },
  { text: "Remarkable", answer: "Extraordinario" },
  { text: "Sufficient", answer: "Suficiente" },
  { text: "Sustainable", answer: "Sostenible" },
  { text: "Threshold", answer: "Umbral" },
  { text: "Widespread", answer: "Generalizado" },

  // Nivel avanzado
  { text: "Meticulous", answer: "Meticuloso" },
  { text: "Ambiguous", answer: "Ambiguo" },
  { text: "Pragmatic", answer: "Pragmático" },
  { text: "Resilient", answer: "Resiliente" },
  { text: "Versatile", answer: "Versátil" },
  { text: "Redundant", answer: "Redundante" },
  { text: "Skeptical", answer: "Escéptico" },
  { text: "Arbitrary", answer: "Arbitrario" },
  { text: "Blatant", answer: "Descarado" },
  { text: "Subtle", answer: "Sutil" },
  { text: "Tedious", answer: "Tedioso" },
  { text: "Volatile", answer: "Volátil" },
  { text: "Prevalent", answer: "Predominante" },
  { text: "Feasible", answer: "Factible" },
  { text: "Elusive", answer: "Escurridizo" },
  { text: "Candid", answer: "Franco" },
  { text: "Innate", answer: "Innato" },
  { text: "Meager", answer: "Escaso" },
  { text: "Rigorous", answer: "Riguroso" },
  { text: "Sporadic", answer: "Esporádico" },
  { text: "Intricate", answer: "Intrincado" },
  { text: "Deceptive", answer: "Engañoso" },
  { text: "Notorious", answer: "Tristemente célebre" },
  { text: "Diligent", answer: "Diligente" },
  { text: "Gullible", answer: "Crédulo" },
  { text: "Stern", answer: "Severo" },
  { text: "Thrifty", answer: "Ahorrativo" },
  { text: "Wary", answer: "Cauteloso" },
  { text: "Blunt", answer: "Directo" },
  { text: "Dubious", answer: "Dudoso" },
  { text: "Lucid", answer: "Lúcido" },
  { text: "Mundane", answer: "Mundano" },
  { text: "Obsolete", answer: "Obsoleto" },
  { text: "Pertinent", answer: "Pertinente" },
  { text: "Scrupulous", answer: "Escrupuloso" },
  { text: "Tenacious", answer: "Tenaz" },
  { text: "Vindictive", answer: "Vengativo" },
  { text: "Give up", answer: "Rendirse" },
  { text: "Look forward to", answer: "Esperar con ansias" },
  { text: "Put off", answer: "Posponer" },
  { text: "Come across", answer: "Toparse con" },
  { text: "Get along with", answer: "Llevarse bien con" },
  { text: "Break down", answer: "Colapsar / Descomponerse" },
  { text: "Carry out", answer: "Llevar a cabo" },
  { text: "Bring about", answer: "Provocar" },
  { text: "Turn down", answer: "Rechazar" },
  { text: "Figure out", answer: "Descifrar" },
  { text: "Look into", answer: "Investigar" },
  { text: "Hold on", answer: "Aguantar / Esperar" },
  { text: "Set up", answer: "Establecer" },
  { text: "Take over", answer: "Asumir el control" },
  { text: "Wear off", answer: "Desvanecerse (un efecto)" },
  { text: "Come up with", answer: "Idear" },
  { text: "Cut down on", answer: "Reducir" },
  { text: "Go through", answer: "Atravesar" },
  { text: "Make up for", answer: "Compensar" },
  { text: "Put up with", answer: "Tolerar" },
  { text: "Run out of", answer: "Quedarse sin" },
  { text: "Stand out", answer: "Destacarse" },
  { text: "Deceive", answer: "Engañar" },
  { text: "Undermine", answer: "Socavar" },
  { text: "Withstand", answer: "Resistir" },
  { text: "Alleviate", answer: "Aliviar" },
  { text: "Enhance", answer: "Realzar" },
  { text: "Facilitate", answer: "Facilitar" },
  { text: "Hinder", answer: "Obstaculizar" },
  { text: "Jeopardize", answer: "Poner en riesgo" },
  { text: "Mitigate", answer: "Mitigar" },
  { text: "Nurture", answer: "Fomentar" },
  { text: "Overwhelm", answer: "Abrumar" },
  { text: "Ponder", answer: "Reflexionar" },
  { text: "Reconcile", answer: "Reconciliar" },
  { text: "Scrutinize", answer: "Examinar minuciosamente" },
  { text: "Thrive", answer: "Prosperar" },
  { text: "Unveil", answer: "Revelar" },
  { text: "Comply with", answer: "Cumplir con" },
  { text: "Cope with", answer: "Sobrellevar" },
  { text: "Break the ice", answer: "Romper el hielo" },
  { text: "Hit the nail on the head", answer: "Dar en el clavo" },
  { text: "Once in a blue moon", answer: "Muy rara vez" },
  { text: "Under the weather", answer: "Sentirse mal" },
  { text: "Piece of cake", answer: "Pan comido" },
  { text: "Cost an arm and a leg", answer: "Costar un ojo de la cara" },
  { text: "Spill the beans", answer: "Revelar un secreto" },
  { text: "Beat around the bush", answer: "Andarse con rodeos" },
  { text: "Bite the bullet", answer: "Afrontar lo inevitable" },
  { text: "Let the cat out of the bag", answer: "Descubrir el pastel" },
  { text: "Actually", answer: "En realidad" },
  { text: "Embarrassed", answer: "Avergonzado" },
  { text: "Realize", answer: "Darse cuenta" },
  { text: "Library", answer: "Biblioteca" },
  { text: "Sensible", answer: "Sensato" },
  { text: "Fabric", answer: "Tela" },
  { text: "Attend", answer: "Asistir a" },
  { text: "Exit", answer: "Salida" },
  { text: "Argument", answer: "Discusión / Pelea" },
  { text: "Casualty", answer: "Víctima" },
  { text: "Rope", answer: "Cuerda" },
  { text: "Parents", answer: "Padres" },
  { text: "Large", answer: "Grande" },
  { text: "Lecture", answer: "Conferencia" },
  { text: "Idiom", answer: "Modismo" },
  { text: "Pretend", answer: "Fingir" },
  { text: "Introduce", answer: "Presentar" },
  { text: "Notice", answer: "Darse cuenta / Aviso" },
  { text: "Eventually", answer: "Finalmente" },
  { text: "Disgusted", answer: "Asqueado" },
  { text: "Assumption", answer: "Suposición" },
  { text: "Discrepancy", answer: "Discrepancia" },
  { text: "Implication", answer: "Implicancia" },
  { text: "Consistency", answer: "Coherencia" },
  { text: "Ambivalence", answer: "Ambivalencia" },
  { text: "Contradiction", answer: "Contradicción" },
  { text: "Hierarchy", answer: "Jerarquía" },
  { text: "Prerequisite", answer: "Requisito previo" },
  { text: "Scarcity", answer: "Escasez" },
  { text: "Trajectory", answer: "Trayectoria" },
];
