import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const librosPorEmojis: CategoryQuestion[] = [
    { text: "🤺🐴🌾🛡️🌬️🪶📖", answer: "Don Quijote de la Mancha" },
    { text: "🧒🌹🦊🪐⭐✈️❤️", answer: "El Principito" },
    { text: "🧙‍♂️💍🌋🧝‍♂️🏹🧔⚔️", answer: "El Señor de los Anillos" },
    { text: "🧙‍♂️🐉💍🏔️🧌🗺️💰", answer: "El Hobbit" },
    { text: "🧙‍♂️⚡🏰🦉🪄🧹🐍", answer: "Harry Potter y la piedra filosofal" },
    { text: "🦉⚡🏰🧙‍♂️👻⛓️🐺", answer: "Harry Potter y el prisionero de Azkaban" },
    { text: "🐉🏆⚡🏰🔥🪄👑", answer: "Harry Potter y el cáliz de fuego" },
    { text: "👑🪑🐉❄️⚔️🦅🔥", answer: "Juego de Tronos" },
    { text: "🌌🏜️🐛👑⚔️🧂☀️", answer: "Dune" },
    { text: "👁️📺🚫📖👮📡🏛️", answer: "1984" },
    { text: "🔥📚🚒🚫📖🏠😢", answer: "Fahrenheit 451" },
    { text: "👨‍👩‍👧‍👦🏠🌸🧙‍♀️⏳🌧️", answer: "Cien años de soledad" },
    { text: "💰🌍🏜️🧙‍♂️💎⭐", answer: "El alquimista" },
    { text: "🧛‍♂️🦇🌙🩸🏰⚰️", answer: "Drácula" },
    { text: "🧪⚡🧟👨‍🔬🌩️😨", answer: "Frankenstein" },
    { text: "🐋⚓🌊🛶🗡️🌧️", answer: "Moby Dick" },
    { text: "🧓🐟🌊🎣☀️💪", answer: "El viejo y el mar" },
    { text: "🏝️🚢🌴🥥🧍‍♂️🐐", answer: "Robinson Crusoe" },
    { text: "🧒🏴‍☠️🦜💰🗺️⚓", answer: "La isla del tesoro" },
    { text: "🐒🌴🦁🐻🐍👦", answer: "El libro de la selva" },
    { text: "🔍🕵️‍♂️🎩🔎🚬🏠", answer: "Las aventuras de Sherlock Holmes" },
    { text: "👨‍🎓🔑🖼️✝️🧩🏛️", answer: "El código Da Vinci" },
    { text: "🌊🐅🏝️⛵🙏☀️", answer: "La vida de Pi" },
    { text: "❤️💔⚔️🇫🇷🥖👧", answer: "Los miserables" },
    { text: "👨‍⚖️💰🏰⛓️⚔️🎭", answer: "El conde de Montecristo" },
    { text: "💃🎩💍❤️💔📜", answer: "Orgullo y prejuicio" },
    { text: "🏚️🌧️💔🌬️❤️⛰️", answer: "Cumbres borrascosas" },
    { text: "🏚️👩📖❤️👨‍🏫🌧️", answer: "Jane Eyre" },
    { text: "👨‍🎩🖼️⌛😈🌹🎭", answer: "El retrato de Dorian Gray" },
    { text: "👩⚖️🐦🏫👧🤝", answer: "Matar a un ruiseñor" },
    { text: "👧🐇🕳️🎩♠️☕", answer: "Alicia en el país de las maravillas" },
    { text: "🧒🎣🏞️🛶🎨🤠", answer: "Las aventuras de Tom Sawyer" },
    { text: "🧒🛶🏞️🌊🤠🤝", answer: "Las aventuras de Huckleberry Finn" },
    { text: "🚂🔪🕵️‍♂️❄️🚃🎩", answer: "Asesinato en el Orient Express" },
    { text: "🌹🏛️📖🔍⛪🧙", answer: "El nombre de la rosa" },
    { text: "🌍🎈⏰🚂🚢🐘", answer: "La vuelta al mundo en 80 días" },
    { text: "🕳️🌍🔥⛏️🦕🌋", answer: "Viaje al centro de la Tierra" },
    { text: "⚓🌊🦑🤿🌍🔱", answer: "Veinte mil leguas de viaje submarino" },
    { text: "👨‍⚕️🧪😈👤🌙🏃", answer: "El extraño caso del doctor Jekyll y el señor Hyde" },
    { text: "👤🫥🧪👓🏃💥", answer: "El hombre invisible" },
    { text: "🧓💰🎄👻❄️🎁", answer: "Cuento de Navidad" },
    { text: "🍇😠🚜👨‍🌾🌾💸", answer: "Las uvas de la ira" },
    { text: "🌾🐁🤝👨‍🌾💔", answer: "De ratones y hombres" },
    { text: "📖✝️🙏⛪👼🌍", answer: "La Biblia" },
{ text: "☪️📖🕌🌙⭐", answer: "El Corán" },
{ text: "🕉️⚔️👑🚩🛕", answer: "Bhagavad Gita" },
{ text: "☸️🪷🧘📖", answer: "Dhammapada" },
{ text: "🤴📜⚔️🏛️", answer: "El arte de la guerra" },
{ text: "👑🦊⚖️📖", answer: "El príncipe" },
{ text: "🤔🏛️👨‍🎓💭", answer: "La República" },
{ text: "🧠🤔👨‍🎓📜", answer: "Meditaciones" },
{ text: "⚖️👤🧠🧘", answer: "Meditaciones (Marco Aurelio)" },
{ text: "🐒🦁🦊📖🎓", answer: "Fábulas de Esopo" },
{ text: "🏝️🌺👨‍👩‍👧🛶", answer: "Popol Vuh" },
{ text: "🌊⚔️🏺👑🐎", answer: "La Ilíada" },
{ text: "⛵🌊👁️👹🏹", answer: "La Odisea" },
{ text: "🔥👹🌎✍️", answer: "La Divina Comedia" },
{ text: "👹🔥😇🌌", answer: "El paraíso perdido" },
{ text: "🐒👨🧬📖", answer: "El origen de las especies" },
{ text: "🌌⏳⚛️🧠", answer: "Breve historia del tiempo" },
{ text: "💰📈🏭👷", answer: "El capital" },
{ text: "🏛️👥⚒️🚩", answer: "El manifiesto comunista" },
{ text: "🧠💤👶", answer: "La interpretación de los sueños" },
{ text: "🎈🤡🩸🚲🌧️", answer: "It" },
{ text: "🏨🪓❄️👨‍👩‍👦👻", answer: "El resplandor" },
{ text: "🚗💀😱🪦🐈", answer: "Cementerio de animales" },
{ text: "👩🔨🛏️📖😱", answer: "Misery" },
{ text: "👮‍♂️🐕😨🏃‍♂️", answer: "Cujo" },
{ text: "🟢🏃‍♂️⚡🏛️⛓️", answer: "La milla verde" },
{ text: "🧒🔮🔥😨👧", answer: "Carrie" },
{ text: "🏚️🌫️👾😱", answer: "La niebla" },
{ text: "🍊🤖👊🎩🥛", answer: "La naranja mecánica" },
{ text: "🐖⚒️🚩👨‍🌾", answer: "Rebelión en la granja" },
{ text: "🐚🏝️👦🔥⚔️", answer: "El señor de las moscas" },
{ text: "🏚️🌧️💔🌬️", answer: "Cumbres borrascosas" },
{ text: "👧🍭❤️📖😨🚗🌸", answer: "Lolita" },
{ text: "🦖🦕🏝️🧬🦟⚠️🚁", answer: "Jurassic Park" },
{ text: "🕴️🪓🩸💵🎵😈💼", answer: "American Psycho" },
];