import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

// Token de acceso a Brandfetch (centralizado acá para no repetirlo en cada URL)
const BRANDFETCH_TOKEN = "1idRaMZv-oNE3GlcQFC";

const brandfetchDomain = (domain: string) =>
    `https://cdn.brandfetch.io/domain/${domain}?c=${BRANDFETCH_TOKEN}`;

const brandfetchTicker = (ticker: string) =>
    `https://cdn.brandfetch.io/ticker/${ticker}?c=${BRANDFETCH_TOKEN}`;

// Fuente de datos: cada marca con su dominio (o ticker) y el nombre a mostrar
// type: "ticker" si se debe resolver por ticker en vez de dominio (por defecto: dominio)
type LogoEntry = { key: string; answer: string; type?: "ticker" };

const logoEntries: LogoEntry[] = [
    { key: "apple.com", answer: "Apple" },
    { key: "google.com", answer: "Google" },
    { key: "microsoft.com", answer: "Microsoft" },
    { key: "amazon.com", answer: "Amazon" },
    { key: "META", answer: "Meta", type: "ticker" },
    { key: "netflix.com", answer: "Netflix" },
    { key: "spotify.com", answer: "Spotify" },
    { key: "youtube.com", answer: "YouTube" },
    { key: "instagram.com", answer: "Instagram" },
    { key: "twitter.com", answer: "X / Twitter" },
    { key: "whatsapp.com", answer: "WhatsApp" },
    { key: "tiktok.com", answer: "TikTok" },
    { key: "snapchat.com", answer: "Snapchat" },
    { key: "linkedin.com", answer: "LinkedIn" },
    { key: "discord.com", answer: "Discord" },
    { key: "twitch.tv", answer: "Twitch" },
    { key: "pinterest.com", answer: "Pinterest" },
    { key: "reddit.com", answer: "Reddit" },
    { key: "paypal.com", answer: "PayPal" },
    { key: "visa.com", answer: "Visa" },
    { key: "mastercard.com", answer: "Mastercard" },
    { key: "nike.com", answer: "Nike" },
    { key: "adidas.com", answer: "Adidas" },
    { key: "puma.com", answer: "Puma" },
    { key: "reebok.com", answer: "Reebok" },
    { key: "converse.com", answer: "Converse" },
    { key: "levis.com", answer: "Levi's" },
    { key: "zara.com", answer: "Zara" },
    { key: "hm.com", answer: "H&M" },
    { key: "gucci.com", answer: "Gucci" },
    { key: "louisvuitton.com", answer: "Louis Vuitton" },
    { key: "chanel.com", answer: "Chanel" },
    { key: "rolex.com", answer: "Rolex" },
    { key: "ferrari.com", answer: "Ferrari" },
    { key: "lamborghini.com", answer: "Lamborghini" },
    { key: "porsche.com", answer: "Porsche" },
    { key: "bmw.com", answer: "BMW" },
    { key: "mercedes-benz.com", answer: "Mercedes-Benz" },
    { key: "audi.com", answer: "Audi" },
    { key: "toyota.com", answer: "Toyota" },
    { key: "honda.com", answer: "Honda" },
    { key: "ford.com", answer: "Ford" },
    { key: "chevrolet.com", answer: "Chevrolet" },
    { key: "volkswagen.com", answer: "Volkswagen" },
    { key: "cocacola.com", answer: "Coca-Cola" },
    { key: "pepsi.com", answer: "Pepsi" },
    { key: "mcdonalds.com", answer: "McDonald's" },
    { key: "burgerking.com", answer: "Burger King" },
    { key: "kfc.com", answer: "KFC" },
    { key: "subway.com", answer: "Subway" },
    { key: "starbucks.com", answer: "Starbucks" },
    { key: "dominos.com", answer: "Domino's" },
    { key: "pizzahut.com", answer: "Pizza Hut" },
    { key: "ikea.com", answer: "IKEA" },
    { key: "samsung.com", answer: "Samsung" },
    { key: "sony.com", answer: "Sony" },
    { key: "lg.com", answer: "LG" },
    { key: "intel.com", answer: "Intel" },
    { key: "nvidia.com", answer: "NVIDIA" },
    { key: "amd.com", answer: "AMD" },
    { key: "hp.com", answer: "HP" },
    { key: "dell.com", answer: "Dell" },
    { key: "lenovo.com", answer: "Lenovo" },
    { key: "canon.com", answer: "Canon" },
    { key: "nikon.com", answer: "Nikon" },
    { key: "adobe.com", answer: "Adobe" },
    { key: "salesforce.com", answer: "Salesforce" },
    { key: "uber.com", answer: "Uber" },
    { key: "airbnb.com", answer: "Airbnb" },
    { key: "booking.com", answer: "Booking" },
    { key: "ebay.com", answer: "eBay" },
    { key: "aliexpress.com", answer: "AliExpress" },
    { key: "shopify.com", answer: "Shopify" },
    { key: "mercadolibre.com", answer: "Mercado Libre" },
    { key: "rappi.com", answer: "Rappi" },
    { key: "disneyplus.com", answer: "Disney+" },
    { key: "hbo.com", answer: "HBO" },
    { key: "hulu.com", answer: "Hulu" },
    { key: "primevideo.com", answer: "Prime Video" },
    { key: "nintendo.com", answer: "Nintendo" },
    { key: "playstation.com", answer: "PlayStation" },
    { key: "xbox.com", answer: "Xbox" },
    { key: "steam.com", answer: "Steam" },
    { key: "nasa.gov", answer: "NASA" },
    { key: "redbull.com", answer: "Red Bull" },
    { key: "monster.com", answer: "Monster Energy" },
    { key: "lego.com", answer: "LEGO" },
    { key: "barbie.com", answer: "Barbie" },
    { key: "harley-davidson.com", answer: "Harley-Davidson" },
    { key: "lacoste.com", answer: "Lacoste" },
    { key: "ralphlauren.com", answer: "Ralph Lauren" },
    { key: "calvinklein.com", answer: "Calvin Klein" },
    { key: "timberland.com", answer: "Timberland" },
    { key: "newbalance.com", answer: "New Balance" },
    { key: "vans.com", answer: "Vans" },

    // ── Ampliación ──
    { key: "facebook.com", answer: "Facebook" },
    { key: "telegram.org", answer: "Telegram" },
    { key: "slack.com", answer: "Slack" },
    { key: "zoom.us", answer: "Zoom" },
    { key: "dropbox.com", answer: "Dropbox" },
    { key: "github.com", answer: "GitHub" },
    { key: "gitlab.com", answer: "GitLab" },
    { key: "figma.com", answer: "Figma" },
    { key: "notion.so", answer: "Notion" },
    { key: "trello.com", answer: "Trello" },
    { key: "wikipedia.org", answer: "Wikipedia" },
    { key: "yahoo.com", answer: "Yahoo" },
    { key: "bing.com", answer: "Bing" },
    { key: "mozilla.org", answer: "Firefox" },
    { key: "tesla.com", answer: "Tesla" },
    { key: "peugeot.com", answer: "Peugeot" },
    { key: "renault.com", answer: "Renault" },
    { key: "fiat.com", answer: "Fiat" },
    { key: "jeep.com", answer: "Jeep" },
    { key: "landrover.com", answer: "Land Rover" },
    { key: "jaguar.com", answer: "Jaguar" },
    { key: "volvocars.com", answer: "Volvo" },
    { key: "hyundai.com", answer: "Hyundai" },
    { key: "kia.com", answer: "Kia" },
    { key: "mazda.com", answer: "Mazda" },
    { key: "subaru.com", answer: "Subaru" },
    { key: "ducati.com", answer: "Ducati" },
    { key: "yamaha-motor.com", answer: "Yamaha" },
    { key: "underarmour.com", answer: "Under Armour" },
    { key: "fila.com", answer: "Fila" },
    { key: "skechers.com", answer: "Skechers" },
    { key: "crocs.com", answer: "Crocs" },
    { key: "champion.com", answer: "Champion" },
    { key: "balenciaga.com", answer: "Balenciaga" },
    { key: "prada.com", answer: "Prada" },
    { key: "versace.com", answer: "Versace" },
    { key: "armani.com", answer: "Armani" },
    { key: "dior.com", answer: "Dior" },
    { key: "hermes.com", answer: "Hermès" },
    { key: "tiffany.com", answer: "Tiffany & Co." },
    { key: "cartier.com", answer: "Cartier" },
    { key: "omegawatches.com", answer: "Omega" },
    { key: "heineken.com", answer: "Heineken" },
    { key: "budweiser.com", answer: "Budweiser" },
    { key: "corona.com", answer: "Corona" },
    { key: "fanta.com", answer: "Fanta" },
    { key: "sprite.com", answer: "Sprite" },
    { key: "nestle.com", answer: "Nestlé" },
    { key: "danone.com", answer: "Danone" },
    { key: "lays.com", answer: "Lay's" },
    { key: "doritos.com", answer: "Doritos" },
    { key: "oreo.com", answer: "Oreo" },
    { key: "kelloggs.com", answer: "Kellogg's" },
    { key: "colgate.com", answer: "Colgate" },
    { key: "gillette.com", answer: "Gillette" },
    { key: "nivea.com", answer: "Nivea" },
    { key: "loreal.com", answer: "L'Oréal" },
    { key: "dove.com", answer: "Dove" },
    { key: "pampers.com", answer: "Pampers" },
    { key: "fedex.com", answer: "FedEx" },
    { key: "dhl.com", answer: "DHL" },
    { key: "ups.com", answer: "UPS" },
    { key: "delta.com", answer: "Delta Air Lines" },
    { key: "emirates.com", answer: "Emirates" },
    { key: "qatarairways.com", answer: "Qatar Airways" },
    { key: "lufthansa.com", answer: "Lufthansa" },
    { key: "marriott.com", answer: "Marriott" },
    { key: "hilton.com", answer: "Hilton" },
    { key: "walmart.com", answer: "Walmart" },
    { key: "target.com", answer: "Target" },
    { key: "costco.com", answer: "Costco" },
    { key: "bestbuy.com", answer: "Best Buy" },
    { key: "gamestop.com", answer: "GameStop" },
    { key: "epicgames.com", answer: "Epic Games" },
    { key: "riotgames.com", answer: "Riot Games" },
    { key: "ea.com", answer: "EA" },
    { key: "ubisoft.com", answer: "Ubisoft" },
    { key: "blizzard.com", answer: "Blizzard" },
    { key: "roblox.com", answer: "Roblox" },
    { key: "minecraft.net", answer: "Minecraft" },
    { key: "garmin.com", answer: "Garmin" },
    { key: "gopro.com", answer: "GoPro" },
    { key: "fitbit.com", answer: "Fitbit" },
    { key: "bose.com", answer: "Bose" },
    { key: "jbl.com", answer: "JBL" },
    { key: "beatsbydre.com", answer: "Beats" },
    { key: "logitech.com", answer: "Logitech" },
    { key: "razer.com", answer: "Razer" },
    { key: "asus.com", answer: "ASUS" },
    { key: "acer.com", answer: "Acer" },
    { key: "mi.com", answer: "Xiaomi" },
    { key: "huawei.com", answer: "Huawei" },
    { key: "oneplus.com", answer: "OnePlus" },
    { key: "motorola.com", answer: "Motorola" },
    { key: "nokia.com", answer: "Nokia" },
    { key: "panasonic.com", answer: "Panasonic" },
    { key: "philips.com", answer: "Philips" },
    { key: "bosch.com", answer: "Bosch" },
    { key: "3m.com", answer: "3M" },
    { key: "caterpillar.com", answer: "Caterpillar" },
    { key: "deere.com", answer: "John Deere" },
    { key: "boeing.com", answer: "Boeing" },
    { key: "airbus.com", answer: "Airbus" },
    { key: "spacex.com", answer: "SpaceX" },
    { key: "shell.com", answer: "Shell" },
    { key: "goldmansachs.com", answer: "Goldman Sachs" },
    { key: "jpmorgan.com", answer: "JPMorgan Chase" },
    { key: "bankofamerica.com", answer: "Bank of America" },
    { key: "americanexpress.com", answer: "American Express" },
    { key: "hsbc.com", answer: "HSBC" },
    { key: "santander.com", answer: "Santander" },
    { key: "bbva.com", answer: "BBVA" },
];

export const logos: CategoryQuestion[] = logoEntries.map(({ key, answer, type }) => ({
    image: type === "ticker" ? brandfetchTicker(key) : brandfetchDomain(key),
    answer,
}));
