import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const lugaresMonumentos: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Eiffel_Tower_logo.svg/330px-Eiffel_Tower_logo.svg.png", answer: "Torre Eiffel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Front_view_of_Statue_of_Liberty_%28cropped%29.jpg", answer: "Estatua de la Libertad" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Elizabeth_Tower%2C_June_2022.jpg", answer: "Big Ben" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/3840px-Colosseo_2020.jpg", answer: "Coliseo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Italy_-_Pisa_-_Leaning_Tower.jpg", answer: "Torre de Pisa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/3840px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg", answer: "Arco del Triunfo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/SF_maig_2_cropped.jpg", answer: "Sagrada Família" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Taj_Mahal_%28Edited%29.jpeg", answer: "Taj Mahal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Sydney_Australia._%2821339175489%29.jpg", answer: "Ópera de Sídney" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Golden_Gate_Bridge_as_seen_from_Battery_East.jpg/3840px-Golden_Gate_Bridge_as_seen_from_Battery_East.jpg", answer: "Puente Golden Gate" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Brandenburger_Tor_abends.jpg", answer: "Puerta de Brandemburgo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Stonehenge2007_07_30.jpg", answer: "Stonehenge" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/AhuTongariki.JPG", answer: "Moai" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Mount_Rushmore_detail_view_%28100MP%29.jpg/3840px-Mount_Rushmore_detail_view_%28100MP%29.jpg", answer: "Monte Rushmore" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Lincoln_Memorial_east_side.JPG/3840px-Lincoln_Memorial_east_side.JPG", answer: "Memorial de Lincoln" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Capitol_Building_Full_View.jpg/3840px-Capitol_Building_Full_View.jpg", answer: "Capitolio de los Estados Unidos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pyramids_of_the_Giza_Necropolis.jpg/3840px-Pyramids_of_the_Giza_Necropolis.jpg", answer: "Pirámides de Guiza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Sphinx_with_the_third_pyramid.jpg/3840px-Sphinx_with_the_third_pyramid.jpg", answer: "Gran Esfinge de Guiza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/3840px-Chichen_Itza_3.jpg", answer: "El Castillo, Chichén Itzá" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/da/The_Parthenon_in_Athens.jpg", answer: "Partenón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Westernwall2.jpg", answer: "Muro de las Lamentaciones" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg/3840px-Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg", answer: "Basílica de San Pedro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Machu_Picchu%2C_2023_%28012%29.jpg/3840px-Machu_Picchu%2C_2023_%28012%29.jpg", answer: "Machu Picchu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Al_Deir_Petra.JPG/3840px-Al_Deir_Petra.JPG", answer: "Petra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Forbidden_City_-_View_from_Coal_Hill.jpg/3840px-The_Forbidden_City_-_View_from_Coal_Hill.jpg", answer: "Ciudad Prohibida" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/3840px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg", answer: "Gran Muralla China" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Buckingham_Palace_London_Morning_2020_01_%28cropped%29.jpg", answer: "Palacio de Buckingham" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Schloss_Neuschwanstein_2013.jpg/3840px-Schloss_Neuschwanstein_2013.jpg", answer: "Castillo de Neuschwanstein" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg/3840px-Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg", answer: "Alhambra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Burj_Khalifa_%28worlds_tallest_building%29_and_the_Dubai_skyline_%2825781049892%29.jpg/3840px-Burj_Khalifa_%28worlds_tallest_building%29_and_the_Dubai_skyline_%2825781049892%29.jpg", answer: "Burj Khalifa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Aerial_image_of_Pompeii_and_Mount_Vesuvius_%28view_from_the_southeast%29.jpg/3840px-Aerial_image_of_Pompeii_and_Mount_Vesuvius_%28view_from_the_southeast%29.jpg", answer: "Pompeya" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg/3840px-1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg", answer: "Acrópolis de Atenas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/41/Angkor_Wat.jpg", answer: "Angkor Wat" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/3840px-Chichen_Itza_3.jpg", answer: "Chichén Itzá" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Teotihuac%C3%A1n-5973.JPG", answer: "Teotihuacán" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_081_%28cropped%29.jpg/3840px-Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_081_%28cropped%29.jpg", answer: "Palacio de Versalles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Mont-Saint-Michel_vu_du_ciel.jpg/3840px-Mont-Saint-Michel_vu_du_ciel.jpg", answer: "Mont-Saint-Michel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Ramsis%2C_Aswan_Governorate%2C_Egypt_-_panoramio.jpg", answer: "Abu Simbel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg", answer: "Monte Everest" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Chogori.jpg/3840px-Chogori.jpg", answer: "K2" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Aconcagua2016.jpg/3840px-Aconcagua2016.jpg", answer: "Aconcagua" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Kilimanjaro_from_Amboseli.jpg", answer: "Kilimanjaro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg/3840px-View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg", answer: "Monte Fuji" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Panoramic_view_Andes-Chile.jpg", answer: "Andes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Himalayas_and_allied_ranges_NASA_Landsat_showing_the_eight_thousanders%2C_annotated_with_major_rivers.jpg", answer: "Himalaya" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Alps_2007-03-13_10.10UTC_1px-250m.jpg", answer: "Alpes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Moraine_Lake_17092005.jpg", answer: "Montañas Rocosas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Central_pyrenees.jpg", answer: "Pirineos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Blue_Ridge_Parkway_Sunset_%2843691100%29.jpeg", answer: "Montes Apalaches" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Mt_Etna_and_Catania1.jpg", answer: "Monte Etna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Il_cratere_del_Vulcano_-_panoramio.jpg", answer: "Vesubio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Krakatoa_eruption_lithograph.jpg", answer: "Krakatoa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Mauna_Loa_Volcano.jpg", answer: "Mauna Loa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Mexico-Popocatepetl.jpg", answer: "Popocatépetl" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/MSH82_st_helens_plume_from_harrys_ridge_05-19-82.jpg", answer: "Monte Santa Helena" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Sahara_real_color.jpg", answer: "Sáhara" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Gobi_Desert.jpg", answer: "Desierto de Gobi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Atacama.png", answer: "Desierto de Atacama" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Amazon17_%285641020319%29.jpg/3840px-Amazon17_%285641020319%29.jpg", answer: "Selva amazónica" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Blick_vom_Hohfelsen.jpg/3840px-Blick_vom_Hohfelsen.jpg", answer: "Selva Negra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Sherwood_Forest%2C_May%2C_2017-5.jpg/3840px-Sherwood_Forest%2C_May%2C_2017-5.jpg", answer: "Bosque de Sherwood" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Amazon_River_ESA387332.jpg", answer: "Río Amazonas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Beautiful_nature_along_Nile_River_01.jpg", answer: "Nilo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Efmo_View_from_Fire_Point.jpg", answer: "Río Misisipi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Dusk_on_the_Yangtze_River.jpg", answer: "Yangtsé" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/53/View_from_Gell%C3%A9rt_Hill_to_the_Danube%2C_Hungary_-_Budapest_%2828493220635%29.jpg", answer: "Danubio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Rio_de_la_Plata_BA_2.JPG", answer: "Río de la Plata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/61/Cuenca_Paran%C3%A1.png", answer: "Río Paraná" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Lake_Titicaca_ESA22522896.jpeg", answer: "Lago Titicaca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/ISS042-E-263206_-_View_of_Earth.jpg/3840px-ISS042-E-263206_-_View_of_Earth.jpg", answer: "Lago Victoria" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Baikal.A2001296.0420.250m-NASA.jpg", answer: "Lago Baikal" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Caspian_Sea_from_orbit.jpg/3840px-Caspian_Sea_from_orbit.jpg", answer: "Mar Caspio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/94/Lake_Superior%2C_ISS.jpg", answer: "Lago Superior" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/51/LochNessUrquhart.jpg", answer: "Lago Ness" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Mediterranean_Sea_16.61811E_38.99124N.jpg", answer: "Mar Mediterráneo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Caribbean_maritime_boundaries_map.svg/3840px-Caribbean_maritime_boundaries_map.svg.png", answer: "Mar Caribe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Red_Sea_topographic_map-en.jpg", answer: "Mar Rojo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/The_Danube_Spills_into_the_Black_Sea.jpg", answer: "Mar Negro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Dead_Sea_beach_00.JPG", answer: "Mar Muerto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/83/The_Baltic_Sea.png", answer: "Mar Báltico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/NASA_NorthSea1_2.jpg", answer: "Mar del Norte" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Adriatic_Sea_2003.jpg", answer: "Mar Adriático" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Pacific_Ocean_-_en.png", answer: "Océano Pacífico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/47/Atlantic_Ocean_-_en.png", answer: "Océano Atlántico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Indian_Ocean-CIA_WFB_Map.png", answer: "Océano Índico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Arctic_Ocean_-_en.png", answer: "Océano Ártico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Location_Southern_Ocean.svg/960px-Location_Southern_Ocean.svg.png", answer: "Océano Antártico" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Iguazu_Cataratas2.jpg/3840px-Iguazu_Cataratas2.jpg", answer: "Cataratas del Iguazú" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/3Falls_Niagara.jpg", answer: "Cataratas del Niágara" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Cataratas_Victoria%2C_Zambia-Zimbabue%2C_2018-07-27%2C_DD_04.jpg/3840px-Cataratas_Victoria%2C_Zambia-Zimbabue%2C_2018-07-27%2C_DD_04.jpg", answer: "Cataratas Victoria" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e9/SaltoAngel1.jpg", answer: "Salto Ángel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/31/Canyon_River_Tree_%28165872763%29.jpeg", answer: "Gran Cañón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Colca_Canyon_Puno.jpg", answer: "Cañón del Colca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/USA_Antelope-Canyon.jpg", answer: "Cañón del Antílope" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Perito_Moreno_Glacier_2023.jpg/3840px-Perito_Moreno_Glacier_2023.jpg", answer: "Glaciar Perito Moreno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Vatnaj%C3%B6kull.jpeg", answer: "Vatnajökull" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/9_Bisonte_Magdaleniense_pol%C3%ADcromo.jpg", answer: "Cueva de Altamira" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Lascaux_painting.jpg", answer: "Cueva de Lascaux" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Postojna_%2822206343750%29.jpg", answer: "Cueva de Postojna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Easter_Island_5.jpg/3840px-Easter_Island_5.jpg", answer: "Isla de Pascua" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Lobo_marino_%28Zalophus_californianus_wollebaeki%29%2C_Punta_Pitt%2C_isla_de_San_Crist%C3%B3bal%2C_islas_Gal%C3%A1pagos%2C_Ecuador%2C_2015-07-24%2C_DD_11.JPG/3840px-Lobo_marino_%28Zalophus_californianus_wollebaeki%29%2C_Punta_Pitt%2C_isla_de_San_Crist%C3%B3bal%2C_islas_Gal%C3%A1pagos%2C_Ecuador%2C_2015-07-24%2C_DD_11.JPG", answer: "Islas Galápagos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/960px-Flag_of_Greenland.svg.png", answer: "Groenlandia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Madagascar_%28centered_orthographic_projection%29.svg/960px-Madagascar_%28centered_orthographic_projection%29.svg.png", answer: "Madagascar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Bora_Bora_ISS006.jpg", answer: "Bora Bora" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Hawaii.svg/1280px-Flag_of_Hawaii.svg.png", answer: "Hawái" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/960px-Flag_of_Maldives.svg.png", answer: "Maldivas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Sicily_in_Italy.svg/1280px-Sicily_in_Italy.svg.png", answer: "Sicilia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Sardinia_in_Italy.svg/1280px-Sardinia_in_Italy.svg.png", answer: "Cerdeña" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ipanema_rio.jpg/3840px-Ipanema_rio.jpg", answer: "Ipanema" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/City_of_Waikiki_view.jpg/3840px-City_of_Waikiki_view.jpg", answer: "Waikīkī" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Bondi_from_above.jpg", answer: "Playa de Bondi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Emblema_Parque_Nacional_Los_Glaciares.jpg", answer: "Parque Nacional Los Glaciares" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Buenos_Aires_%2820234294752%29.jpg", answer: "Obelisco de Buenos Aires" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Casa_Rosada_exterior_from_Plaza_de_Mayo.JPG/3840px-Casa_Rosada_exterior_from_Plaza_de_Mayo.JPG", answer: "Casa Rosada" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Cabildo_de_Buenos_Aires_2023.jpg/3840px-Cabildo_de_Buenos_Aires_2023.jpg", answer: "Cabildo de Buenos Aires" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Fachada_del_Teatro_Col%C3%B3n_en_Buenos_Aires%2C_Argentina.jpg/3840px-Fachada_del_Teatro_Col%C3%B3n_en_Buenos_Aires%2C_Argentina.jpg", answer: "Teatro Colón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Congreso_Nacional_Buenos_Aires.jpg", answer: "Palacio del Congreso de la Nación Argentina" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Monumento_a_la_Bandera%2C_Rosario.jpg", answer: "Monumento a la Bandera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/1952-01-31_-_Lionel_Terray%2C_Fitzroy%2C_d%C3%A9dicace_-_NB.jpg", answer: "Fitz Roy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/82/Cerro_tronador_desde_lago_mascardi_01b.jpg", answer: "Tronador" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Basecat.JPG", answer: "Cerro Catedral" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Aconcagua2016.jpg/3840px-Aconcagua2016.jpg", answer: "Aconcagua" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Cerro_Uritorco_1.jpg", answer: "Uritorco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/AR378-Quebrada_de_Humahuaca.jpg/3840px-AR378-Quebrada_de_Humahuaca.jpg", answer: "Quebrada de Humahuaca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Salinas_Grandes_C%C3%B3rdoba.JPG", answer: "Salinas Grandes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Cerro_Blanco_volcano_%28AVA_Granule_L1B_20000916145757%29.jpg", answer: "Cerro Blanco (volcán)" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Perito_Moreno_Glacier_2023.jpg/3840px-Perito_Moreno_Glacier_2023.jpg", answer: "Glaciar Perito Moreno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f4/SantaCruz-CuevaManos-P2210651b.jpg", answer: "Cueva de las Manos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Talampaya_NP.jpg", answer: "Parque Nacional Talampaya" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Ischigualasto_provincial_park.jpg", answer: "Parque Provincial Ischigualasto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Iguazu_Cataratas2.jpg/3840px-Iguazu_Cataratas2.jpg", answer: "Cataratas del Iguazú" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/92/View_from_the_Golf_course_at_Llao_Llao.jpg", answer: "Lago Nahuel Huapi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Lake_Argentino_northern_arm_Lago_Argentino_Brazo_Norte_Patagonia_Argentina_Luca_Galuzzi_2005.JPG", answer: "Lago Argentino" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/93/090111-6_Above_%E3%83%93%E3%83%BC%E3%82%B0%E3%83%AB%E6%B0%B4%E9%81%93.jpg", answer: "Canal de Beagle" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Peninsula_Vald%C3%A9s_STS-68.jpg", answer: "Península Valdés" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Chubut-PuntaTombo-P2220157b-small.jpg", answer: "Punta Tombo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Piedra_Movediza_de_Tandil.jpg", answer: "Piedra Movediza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Villa_Ventana_from_the_Sierra_de_la_Ventana.jpg", answer: "Sierra de la Ventana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/47/El_Chalt%C3%A9n.jpg", answer: "El Chaltén" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/El_Calafate_%2825825005237%29.jpg/3840px-El_Calafate_%2825825005237%29.jpg", answer: "El Calafate" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/PT_TORREON3.jpg", answer: "Mar del Plata" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/05/Puerto_Madero_montage.jpg", answer: "Puerto Madero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Vista_a%C3%A9rea_del_Estadio_Alberto_J._Armando_%22La_Bombonera%22_01.jpg/3840px-Vista_a%C3%A9rea_del_Estadio_Alberto_J._Armando_%22La_Bombonera%22_01.jpg", answer: "La Bombonera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Puente_de_la_Mujer%2C_Puerto_Madero%2C_Buenos_Aires%2C_Argentina%2C_29th._Dec._2010_-_Flickr_-_PhillipC_%281%29.jpg/3840px-Puente_de_la_Mujer%2C_Puerto_Madero%2C_Buenos_Aires%2C_Argentina%2C_29th._Dec._2010_-_Flickr_-_PhillipC_%281%29.jpg", answer: "Puente de la Mujer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ushuaia_aerial_panorama.jpg/3840px-Ushuaia_aerial_panorama.jpg", answer: "Ushuaia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Tren_nubes_trenesarg.jpg", answer: "Tren a las Nubes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Champaqui07_205.jpg", answer: "Cerro Champaquí" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Christ_the_Redeemer_-_Cristo_Redentor.jpg", answer: "Cristo Redentor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/62/Praia_de_Copacabana_-_Rio_de_Janeiro%2C_Brasil.jpg", answer: "Copacabana, Río de Janeiro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Estadio_mas_monumental.jpg/3840px-Estadio_mas_monumental.jpg", answer: "Estadio Monumental (Buenos Aires)" },
];
