import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const mitologia: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Zeus_Otricoli_Pio-Clementino_Inv257.jpg", answer: "Zeus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Hera_Campana_Louvre_Ma2283.jpg", answer: "Hera" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Persephone_Hades_BM_Vase_E82_%28cropped%29.jpg", answer: "Hades" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Revista_Atenea.jpg", answer: "Atenea" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Ares_Canope_Villa_Adriana_b.jpg", answer: "Ares" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Hermes_Ingenui_Pio-Clementino_Inv544.jpg", answer: "Hermes" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Nje_Peisazh_i_bukur_kur_mbi_qytetin_e_Krumes_dalin_dy_Ylbera.jpg", answer: "Prende" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/67/Luigi_Nono_%281979%29.jpg", answer: "Prometeo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Mercator_-_Atlas_-_1595.png", answer: "Atlas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Abel-josef-1764-1818-austria-prometheus-merkur-und-die-pand.jpg", answer: "Pandora" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Kylix_Theseus_Aison_MNA_Inv11365_n1.jpg", answer: "Heracles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Head_Odysseus_MAR_Sperlonga.jpg", answer: "Odysseus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Gorgona_pushkin.jpg", answer: "Medusa" },
    { image: "https://upload.wikimedia.org/wikipedia/en/d/dd/Logo_Pegaso.jpg", answer: "Pegaso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Georg_Friedrich_H%C3%A4ndel_as_a_young_man.jpg", answer: "Teseo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d8/A_painting_by_Max_Friedrich_Koch_-_Donar-Thor.jpg", answer: "Thor" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Processed_SAM_loki.jpg", answer: "Loki" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Freyja_and_the_Necklace_by_James_Doyle_Penrose%2C_1890.jpg", answer: "Freyja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Tullstorpstenen%2C_DR_271%2CTullstorp_1-1%2C_Runristning_%28cropped%29.jpg", answer: "Fenrir" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ragnarok_-_Louis_Moe_%2817006%29_-_cropped_%28cropped%29.png/3840px-Ragnarok_-_Louis_Moe_%2817006%29_-_cropped_%28cropped%29.png", answer: "Jörmungandr" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Re-Horakhty.svg/500px-Re-Horakhty.svg.png", answer: "Ra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Anubis_standing.svg/500px-Anubis_standing.svg.png", answer: "Anubis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Standing_Osiris.svg/500px-Standing_Osiris.svg.png", answer: "Osiris" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Isis.svg/500px-Isis.svg.png", answer: "Isis" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Horus_standing.svg/500px-Horus_standing.svg.png", answer: "Horus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Spas_na_Ilyine_-_Patriarch_Seth_2_%28cropped%29.jpg", answer: "Seth" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Venus_2_Approach_Image.jpg", answer: "Venus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Amaterasu_cave_crop.jpg", answer: "Amaterasu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Xiyou.PNG", answer: "Sun Wukong" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Bangalore_Shiva.jpg", answer: "Shiva" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Vishnu_from_Gita_Govinda.jpg", answer: "Vishnu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Ganesha_Basohli_miniature_circa_1730_Dubost_p73.jpg", answer: "Ganesha" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Krishna_Holds_Up_Mount_Govardhan_%28MET_70694%29_cropped.png", answer: "Krishna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/Hanuman_Statue_at_Sidhheshwar_Temple%2C_Chhindwara%2C_MP.jpg", answer: "Hanuman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Quetzalc%C3%B3atl_como_la_serpiente_emplumada_y_el_dios_del_viento_Eh%C3%A9catl%2C_en_el_folio_19.jpg", answer: "Quetzalcōātl" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Kukulkan_%28reconstructed%29.jpg", answer: "Kukulkan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1c/C%C3%A1pac_Inti_Raimi.jpg", answer: "Inti" },
    { image: "https://upload.wikimedia.org/wikipedia/en/a/ad/Unicornio_Album_Cover.jpg", answer: "Unicornio" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Le_Poulpe_Colossal.jpg", answer: "Kraken" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Guercino_Abramo_ripudia_Agar_%28cropped_2%29.jpg", answer: "Abraham" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/94/King_David%2C_the_King_of_Israel.jpg", answer: "David" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Alexandre_Cabanel_-_Fallen_Angel.jpg", answer: "Lucifer" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/be/Satan%C3%A1s.jpg", answer: "Satanás" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Sacrificio_de_Abel%2C_de_Juan_Antonio_de_Fr%C3%ADas_y_Escalante_%28Museo_del_Prado%29.jpg", answer: "Abel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Nuremberg_chronicles_-_BVJA.png", answer: "Buda" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Kleopatra-VII.-Altes-Museum-Berlin1.jpg", answer: "Cleopatra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Statue_of_Poseidon_NAMA_235_%28DerHexer%29%2C_part_2.JPG", answer: "Poseidon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Italy-3104_-_Apollo_%285378415112%29.jpg", answer: "Apolo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Cnidus_Aphrodite_Altemps_Inv8619.jpg", answer: "Afrodita" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/AMI_-_Isis-Persephone.jpg", answer: "Perséfone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Rhea_handing_a_swaddled_stone_to_Cronus%2C_Attic_terracotta_pelike%2C_c._460%E2%80%93450_BC%2C_Met_06.1021.144.jpg_%28cropped%29.jpg", answer: "Cronos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Achilles_fighting_against_Memnon_Leiden_Rijksmuseum_voor_Oudheden.jpg", answer: "Aquiles" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Tondo_Minotaur_London_E4_MAN.jpg", answer: "Minotauro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Herakles_Kerberos_Eurystheus_Louvre_E701.jpg", answer: "Cerbero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Lernaean_Hydra_Getty_Villa_83.AE.346.jpg", answer: "Hidra de Lerna" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Gowy-icaro-prado.jpg", answer: "Ícaro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Georg_von_Rosen_-_Oden_som_vandringsman%2C_1886_%28Odin%2C_the_Wanderer%29.jpg", answer: "Odin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Jupiter_OPAL_2024.png", answer: "Jupiter" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Neptune_Voyager2_color_calibrated.png", answer: "Neptuno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Mars_-_August_30_2021_-_Flickr_-_Kevin_M._Gill.png", answer: "Marte" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/54/Arth_tapestry2.jpg", answer: "Rey Arturo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Arthur-Pyle_The_Enchanter_Merlin.JPG", answer: "Merlin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/St_Catherine%2C_St_George_and_the_Dragon_%28M%C3%A4staren_fr%C3%A5n_Kappenberg%29_-_Nationalmuseum_-_18337_%28brightened%29%2C_draken.png", answer: "Dragon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/14/Basilisk_aldrovandi.jpg", answer: "Basilisco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/55/John_William_Waterhouse_A_Mermaid.jpg", answer: "Sirena" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Terracotta_lekythos_%28oil_flask%29_with_centaur_battling_a_warrior_MET_DP161810.jpg/3840px-Terracotta_lekythos_%28oil_flask%29_with_centaur_battling_a_warrior_MET_DP161810.jpg", answer: "Centauro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Knossos_fresco_in_throne_palace.JPG", answer: "Grifo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Spas_vsederzhitel_sinay_%28cropped1%29.jpg", answer: "Jesus" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Michelangelo%2C_Creation_of_Adam_04.jpg", answer: "Dios" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Michelangelo%2C_Creation_of_Adam_03.jpg", answer: "Adan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Giovanni_Benedetto_Castiglione_gen._Il_Grecchetto_-_Noah_mit_den_Tieren_vor_der_Arche_-_GG_1645_-_Kunsthistorisches_Museum_%28cropped%29.jpg", answer: "Noe" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Rembrandt_Harmensz._van_Rijn_079.jpg", answer: "Moises" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/Simeon_Solomon%2C_King_Solomon%2C_1872_or_1874%2C_NGA_76152_%28cropped%29.jpg", answer: "Salomon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Lucas_Cranach_d.%C3%84._-_Simson_bezwingt_den_L%C3%B6wen.jpg", answer: "Sansón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Madonna_Advocata.png", answer: "Maria" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg", answer: "Jose" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Almeida_J%C3%BAnior_-_Remorso_de_Judas%2C_1880.jpg", answer: "Judas Iscariot" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/87/TINTORETTO_-_Magdalena_penitente_%28Musei_Capitolini%2C_Roma%2C_1598-1602%29_-_copia.jpg", answer: "María Magdalena" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Accademia_-_St_John_the_Baptist_by_Titian_Cat314.jpg/3840px-Accademia_-_St_John_the_Baptist_by_Titian_Cat314.jpg", answer: "Juan el Bautista" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/GuidoReni_MichaelDefeatsSatan.jpg", answer: "Arcángel Miguel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/12/Ghent_Altarpiece_-_Angel_of_the_Annunciation.jpg", answer: "Arcangel Gabriel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Rehberg%2C_Ca%C3%ADn%2C_Museo_de_Bellas_Artes_de_Bilbao.webp", answer: "Cain" },
];
