import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const palabras: CategoryQuestion[] = [
  { text: "Feliz → Sinónimo", answer: "Alegre", possibleAnswers: ["Contento", "Dichoso"] },
  { text: "Triste → Sinónimo", answer: "Apenado", possibleAnswers: ["Melancólico", "Deprimido"] },
  { text: "Grande → Sinónimo", answer: "Enorme", possibleAnswers: ["Gigante", "Inmenso"] },
  { text: "Pequeño → Sinónimo", answer: "Chico", possibleAnswers: ["Reducido", "Diminuto"] },
  { text: "Rápido → Sinónimo", answer: "Veloz", possibleAnswers: ["Ágil"] },
  { text: "Lento → Sinónimo", answer: "Pausado", possibleAnswers: ["Despacio"] },
  { text: "Bonito → Sinónimo", answer: "Hermoso", possibleAnswers: ["Lindo", "Bello"] },
  { text: "Feo → Sinónimo", answer: "Horrible", possibleAnswers: ["Desagradable"] },
  { text: "Fácil → Sinónimo", answer: "Sencillo", possibleAnswers: ["Simple"] },
  { text: "Difícil → Sinónimo", answer: "Complicado", possibleAnswers: ["Complejo"] },

  { text: "Empezar → Sinónimo", answer: "Comenzar", possibleAnswers: ["Iniciar"] },
  { text: "Terminar → Sinónimo", answer: "Finalizar", possibleAnswers: ["Concluir"] },
  { text: "Mirar → Sinónimo", answer: "Observar", possibleAnswers: ["Ver"] },
  { text: "Hablar → Sinónimo", answer: "Conversar", possibleAnswers: ["Dialogar"] },
  { text: "Callar → Sinónimo", answer: "Silenciar", possibleAnswers: ["Enmudecer"] },
  { text: "Comprar → Sinónimo", answer: "Adquirir", possibleAnswers: [] },
  { text: "Vender → Sinónimo", answer: "Comercializar", possibleAnswers: [] },
  { text: "Ayudar → Sinónimo", answer: "Asistir", possibleAnswers: ["Socorrer"] },
  { text: "Buscar → Sinónimo", answer: "Procurar", possibleAnswers: ["Explorar"] },
  { text: "Encontrar → Sinónimo", answer: "Hallar", possibleAnswers: [] },

  { text: "Caminar → Sinónimo", answer: "Andar", possibleAnswers: [] },
  { text: "Correr → Sinónimo", answer: "Trotar", possibleAnswers: [] },
  { text: "Saltar → Sinónimo", answer: "Brincar", possibleAnswers: [] },
  { text: "Caer → Sinónimo", answer: "Desplomarse", possibleAnswers: [] },
  { text: "Subir → Sinónimo", answer: "Ascender", possibleAnswers: [] },
  { text: "Bajar → Sinónimo", answer: "Descender", possibleAnswers: [] },
  { text: "Romper → Sinónimo", answer: "Quebrar", possibleAnswers: [] },
  { text: "Arreglar → Sinónimo", answer: "Reparar", possibleAnswers: [] },
  { text: "Crear → Sinónimo", answer: "Fabricar", possibleAnswers: ["Construir"] },
  { text: "Destruir → Sinónimo", answer: "Demoler", possibleAnswers: [] },

  { text: "Casa → Sinónimo", answer: "Hogar", possibleAnswers: ["Vivienda"] },
  { text: "Auto → Sinónimo", answer: "Coche", possibleAnswers: ["Automóvil", "Carro"] },
  { text: "Trabajo → Sinónimo", answer: "Empleo", possibleAnswers: ["Labor"] },
  { text: "Dinero → Sinónimo", answer: "Plata", possibleAnswers: ["Capital"] },
  { text: "Amigo → Sinónimo", answer: "Compañero", possibleAnswers: [] },
  { text: "Enemigo → Sinónimo", answer: "Adversario", possibleAnswers: ["Rival"] },
  { text: "Error → Sinónimo", answer: "Equivocación", possibleAnswers: ["Fallo"] },
  { text: "Problema → Sinónimo", answer: "Inconveniente", possibleAnswers: ["Dificultad"] },
  { text: "Respuesta → Sinónimo", answer: "Contestación", possibleAnswers: [] },
  { text: "Pregunta → Sinónimo", answer: "Interrogante", possibleAnswers: ["Cuestión"] },

  { text: "Inteligente → Sinónimo", answer: "Listo", possibleAnswers: ["Brillante"] },
  { text: "Tonto → Sinónimo", answer: "Necio", possibleAnswers: ["Ignorante"] },
  { text: "Valiente → Sinónimo", answer: "Intrépido", possibleAnswers: ["Audaz"] },
  { text: "Cobarde → Sinónimo", answer: "Miedoso", possibleAnswers: ["Temeroso"] },
  { text: "Fuerte → Sinónimo", answer: "Robusto", possibleAnswers: ["Resistente"] },
  { text: "Débil → Sinónimo", answer: "Frágil", possibleAnswers: [] },
  { text: "Rico → Sinónimo", answer: "Adinerado", possibleAnswers: ["Acaudalado"] },
  { text: "Pobre → Sinónimo", answer: "Necesitado", possibleAnswers: [] },
  { text: "Viejo → Sinónimo", answer: "Anciano", possibleAnswers: [] },
  { text: "Joven → Sinónimo", answer: "Muchacho", possibleAnswers: [] },

  { text: "Contento → Sinónimo", answer: "Feliz", possibleAnswers: ["Alegre"] },
  { text: "Asustado → Sinónimo", answer: "Aterrado", possibleAnswers: ["Temeroso"] },
  { text: "Enojado → Sinónimo", answer: "Furioso", possibleAnswers: ["Irritado"] },
  { text: "Cansado → Sinónimo", answer: "Fatigado", possibleAnswers: ["Agotado"] },
  { text: "Sorprendido → Sinónimo", answer: "Asombrado", possibleAnswers: [] },
  { text: "Aburrido → Sinónimo", answer: "Fastidiado", possibleAnswers: [] },
  { text: "Hermoso → Sinónimo", answer: "Bello", possibleAnswers: ["Lindo"] },
  { text: "Oscuro → Sinónimo", answer: "Sombrío", possibleAnswers: [] },
  { text: "Claro → Sinónimo", answer: "Luminoso", possibleAnswers: [] },
  { text: "Silencio → Sinónimo", answer: "Calma", possibleAnswers: ["Quietud"] },

  { text: "Rápidamente → Sinónimo", answer: "Velozmente", possibleAnswers: [] },
  { text: "Siempre → Sinónimo", answer: "Constantemente", possibleAnswers: [] },
  { text: "Jamás → Sinónimo", answer: "Nunca", possibleAnswers: [] },
  { text: "Quizás → Sinónimo", answer: "Tal vez", possibleAnswers: ["Acaso"] },
  { text: "Además → Sinónimo", answer: "También", possibleAnswers: [] },
  { text: "Luego → Sinónimo", answer: "Después", possibleAnswers: [] },
  { text: "Antes → Sinónimo", answer: "Previamente", possibleAnswers: [] },
  { text: "Cerca → Sinónimo", answer: "Próximo", possibleAnswers: [] },
  { text: "Lejos → Sinónimo", answer: "Distante", possibleAnswers: [] },
  { text: "Pronto → Sinónimo", answer: "Rápidamente", possibleAnswers: [] },

  { text: "Elegir → Sinónimo", answer: "Escoger", possibleAnswers: ["Seleccionar"] },
  { text: "Guardar → Sinónimo", answer: "Conservar", possibleAnswers: ["Almacenar"] },
  { text: "Lanzar → Sinónimo", answer: "Arrojar", possibleAnswers: ["Tirar"] },
  { text: "Levantar → Sinónimo", answer: "Alzar", possibleAnswers: [] },
  { text: "Empujar → Sinónimo", answer: "Impulsar", possibleAnswers: [] },
  { text: "Tirar → Sinónimo", answer: "Jalar", possibleAnswers: [] },
  { text: "Explicar → Sinónimo", answer: "Aclarar", possibleAnswers: [] },
  { text: "Aprender → Sinónimo", answer: "Estudiar", possibleAnswers: ["Asimilar"] },
  { text: "Enseñar → Sinónimo", answer: "Educar", possibleAnswers: ["Instruir"] },
  { text: "Pensar → Sinónimo", answer: "Reflexionar", possibleAnswers: [] },

  { text: "Recordar → Sinónimo", answer: "Rememorar", possibleAnswers: ["Evocar"] },
  { text: "Olvidar → Sinónimo", answer: "Omitir", possibleAnswers: [] },
  { text: "Aceptar → Sinónimo", answer: "Admitir", possibleAnswers: [] },
  { text: "Rechazar → Sinónimo", answer: "Negar", possibleAnswers: [] },
  { text: "Permitir → Sinónimo", answer: "Autorizar", possibleAnswers: [] },
  { text: "Prohibir → Sinónimo", answer: "Impedir", possibleAnswers: ["Vetar"] },
  { text: "Mostrar → Sinónimo", answer: "Exhibir", possibleAnswers: [] },
  { text: "Ocultar → Sinónimo", answer: "Esconder", possibleAnswers: [] },
  { text: "Llenar → Sinónimo", answer: "Completar", possibleAnswers: ["Colmar"] },
  { text: "Vaciar → Sinónimo", answer: "Desocupar", possibleAnswers: [] },

  { text: "Paz → Sinónimo", answer: "Tranquilidad", possibleAnswers: ["Calma"] },
  { text: "Guerra → Sinónimo", answer: "Conflicto", possibleAnswers: [] },
  { text: "Meta → Sinónimo", answer: "Objetivo", possibleAnswers: ["Propósito"] },
  { text: "Camino → Sinónimo", answer: "Sendero", possibleAnswers: ["Ruta"] },
  { text: "Ciudad → Sinónimo", answer: "Urbe", possibleAnswers: [] },
  { text: "Campo → Sinónimo", answer: "Pradera", possibleAnswers: [] },
  { text: "Bosque → Sinónimo", answer: "Selva", possibleAnswers: [] },
  { text: "Mar → Sinónimo", answer: "Océano", possibleAnswers: [] },
  { text: "Montaña → Sinónimo", answer: "Monte", possibleAnswers: [] },
  { text: "Final → Sinónimo", answer: "Conclusión", possibleAnswers: ["Fin"] },
  { text: "Feliz → Antónimo", answer: "Triste", possibleAnswers: ["Infeliz"] },
  { text: "Triste → Antónimo", answer: "Feliz", possibleAnswers: ["Alegre", "Contento"] },
  { text: "Grande → Antónimo", answer: "Pequeño", possibleAnswers: ["Chico"] },
  { text: "Pequeño → Antónimo", answer: "Grande", possibleAnswers: ["Enorme"] },
  { text: "Alto → Antónimo", answer: "Bajo", possibleAnswers: [] },
  { text: "Bajo → Antónimo", answer: "Alto", possibleAnswers: [] },
  { text: "Largo → Antónimo", answer: "Corto", possibleAnswers: [] },
  { text: "Corto → Antónimo", answer: "Largo", possibleAnswers: [] },
  { text: "Ancho → Antónimo", answer: "Angosto", possibleAnswers: ["Estrecho"] },
  { text: "Angosto → Antónimo", answer: "Ancho", possibleAnswers: [] },

  { text: "Rápido → Antónimo", answer: "Lento", possibleAnswers: [] },
  { text: "Lento → Antónimo", answer: "Rápido", possibleAnswers: ["Veloz"] },
  { text: "Fácil → Antónimo", answer: "Difícil", possibleAnswers: ["Complicado"] },
  { text: "Difícil → Antónimo", answer: "Fácil", possibleAnswers: ["Simple"] },
  { text: "Claro → Antónimo", answer: "Oscuro", possibleAnswers: [] },
  { text: "Oscuro → Antónimo", answer: "Claro", possibleAnswers: [] },
  { text: "Limpio → Antónimo", answer: "Sucio", possibleAnswers: [] },
  { text: "Sucio → Antónimo", answer: "Limpio", possibleAnswers: [] },
  { text: "Seco → Antónimo", answer: "Mojado", possibleAnswers: ["Húmedo"] },
  { text: "Mojado → Antónimo", answer: "Seco", possibleAnswers: [] },

  { text: "Caliente → Antónimo", answer: "Frío", possibleAnswers: [] },
  { text: "Frío → Antónimo", answer: "Caliente", possibleAnswers: [] },
  { text: "Nuevo → Antónimo", answer: "Viejo", possibleAnswers: ["Usado"] },
  { text: "Viejo → Antónimo", answer: "Nuevo", possibleAnswers: [] },
  { text: "Joven → Antónimo", answer: "Anciano", possibleAnswers: ["Viejo"] },
  { text: "Anciano → Antónimo", answer: "Joven", possibleAnswers: [] },
  { text: "Fuerte → Antónimo", answer: "Débil", possibleAnswers: [] },
  { text: "Débil → Antónimo", answer: "Fuerte", possibleAnswers: [] },
  { text: "Pesado → Antónimo", answer: "Liviano", possibleAnswers: ["Ligero"] },
  { text: "Liviano → Antónimo", answer: "Pesado", possibleAnswers: [] },

  { text: "Lleno → Antónimo", answer: "Vacío", possibleAnswers: [] },
  { text: "Vacío → Antónimo", answer: "Lleno", possibleAnswers: [] },
  { text: "Abierto → Antónimo", answer: "Cerrado", possibleAnswers: [] },
  { text: "Cerrado → Antónimo", answer: "Abierto", possibleAnswers: [] },
  { text: "Encendido → Antónimo", answer: "Apagado", possibleAnswers: [] },
  { text: "Apagado → Antónimo", answer: "Encendido", possibleAnswers: [] },
  { text: "Verdadero → Antónimo", answer: "Falso", possibleAnswers: [] },
  { text: "Falso → Antónimo", answer: "Verdadero", possibleAnswers: [] },
  { text: "Correcto → Antónimo", answer: "Incorrecto", possibleAnswers: [] },
  { text: "Incorrecto → Antónimo", answer: "Correcto", possibleAnswers: [] },

  { text: "Entrar → Antónimo", answer: "Salir", possibleAnswers: [] },
  { text: "Salir → Antónimo", answer: "Entrar", possibleAnswers: [] },
  { text: "Subir → Antónimo", answer: "Bajar", possibleAnswers: [] },
  { text: "Bajar → Antónimo", answer: "Subir", possibleAnswers: [] },
  { text: "Comprar → Antónimo", answer: "Vender", possibleAnswers: [] },
  { text: "Vender → Antónimo", answer: "Comprar", possibleAnswers: [] },
  { text: "Aceptar → Antónimo", answer: "Rechazar", possibleAnswers: [] },
  { text: "Rechazar → Antónimo", answer: "Aceptar", possibleAnswers: [] },
  { text: "Permitir → Antónimo", answer: "Prohibir", possibleAnswers: [] },
  { text: "Prohibir → Antónimo", answer: "Permitir", possibleAnswers: [] },

  { text: "Recordar → Antónimo", answer: "Olvidar", possibleAnswers: [] },
  { text: "Olvidar → Antónimo", answer: "Recordar", possibleAnswers: [] },
  { text: "Encontrar → Antónimo", answer: "Perder", possibleAnswers: [] },
  { text: "Perder → Antónimo", answer: "Encontrar", possibleAnswers: [] },
  { text: "Ganar → Antónimo", answer: "Perder", possibleAnswers: [] },
  { text: "Romper → Antónimo", answer: "Arreglar", possibleAnswers: ["Reparar"] },
  { text: "Arreglar → Antónimo", answer: "Romper", possibleAnswers: [] },
  { text: "Crear → Antónimo", answer: "Destruir", possibleAnswers: [] },
  { text: "Destruir → Antónimo", answer: "Crear", possibleAnswers: [] },
  { text: "Construir → Antónimo", answer: "Demoler", possibleAnswers: ["Destruir"] },

  { text: "Amigo → Antónimo", answer: "Enemigo", possibleAnswers: ["Rival"] },
  { text: "Enemigo → Antónimo", answer: "Amigo", possibleAnswers: [] },
  { text: "Paz → Antónimo", answer: "Guerra", possibleAnswers: [] },
  { text: "Guerra → Antónimo", answer: "Paz", possibleAnswers: [] },
  { text: "Éxito → Antónimo", answer: "Fracaso", possibleAnswers: [] },
  { text: "Fracaso → Antónimo", answer: "Éxito", possibleAnswers: [] },
  { text: "Rico → Antónimo", answer: "Pobre", possibleAnswers: [] },
  { text: "Pobre → Antónimo", answer: "Rico", possibleAnswers: ["Adinerado"] },
  { text: "Principio → Antónimo", answer: "Final", possibleAnswers: ["Fin"] },
  { text: "Final → Antónimo", answer: "Principio", possibleAnswers: ["Inicio"] },

  { text: "Día → Antónimo", answer: "Noche", possibleAnswers: [] },
  { text: "Noche → Antónimo", answer: "Día", possibleAnswers: [] },
  { text: "Interior → Antónimo", answer: "Exterior", possibleAnswers: [] },
  { text: "Exterior → Antónimo", answer: "Interior", possibleAnswers: [] },
  { text: "Cerca → Antónimo", answer: "Lejos", possibleAnswers: [] },
  { text: "Lejos → Antónimo", answer: "Cerca", possibleAnswers: [] },
  { text: "Arriba → Antónimo", answer: "Abajo", possibleAnswers: [] },
  { text: "Abajo → Antónimo", answer: "Arriba", possibleAnswers: [] },
  { text: "Dentro → Antónimo", answer: "Fuera", possibleAnswers: [] },
  { text: "Fuera → Antónimo", answer: "Dentro", possibleAnswers: [] },

  { text: "Inicio → Antónimo", answer: "Final", possibleAnswers: ["Fin"] },
  { text: "Silencio → Antónimo", answer: "Ruido", possibleAnswers: [] },
  { text: "Ruido → Antónimo", answer: "Silencio", possibleAnswers: [] },
  { text: "Orden → Antónimo", answer: "Caos", possibleAnswers: ["Desorden"] },
  { text: "Caos → Antónimo", answer: "Orden", possibleAnswers: [] },
  { text: "Valiente → Antónimo", answer: "Cobarde", possibleAnswers: ["Miedoso"] },
  { text: "Cobarde → Antónimo", answer: "Valiente", possibleAnswers: ["Audaz"] },
  { text: "Generoso → Antónimo", answer: "Tacaño", possibleAnswers: [] },
  { text: "Tacaño → Antónimo", answer: "Generoso", possibleAnswers: [] },
  { text: "Humilde → Antónimo", answer: "Orgulloso", possibleAnswers: ["Soberbio"] },

  { text: "Orgulloso → Antónimo", answer: "Humilde", possibleAnswers: [] },
  { text: "Paciente → Antónimo", answer: "Impaciente", possibleAnswers: [] },
  { text: "Impaciente → Antónimo", answer: "Paciente", possibleAnswers: [] },
  { text: "Optimista → Antónimo", answer: "Pesimista", possibleAnswers: [] },
  { text: "Pesimista → Antónimo", answer: "Optimista", possibleAnswers: [] },
  { text: "Legal → Antónimo", answer: "Ilegal", possibleAnswers: [] },
  { text: "Ilegal → Antónimo", answer: "Legal", possibleAnswers: [] },
  { text: "Positivo → Antónimo", answer: "Negativo", possibleAnswers: [] },
  { text: "Negativo → Antónimo", answer: "Positivo", possibleAnswers: [] },
  { text: "Visible → Antónimo", answer: "Invisible", possibleAnswers: [] },
   { text: "NANAZMA", answer: "Manzana" },
{ text: "DATORCOMUPA", answer: "Computadora" },
{ text: "TEBLIBICA", answer: "Biblioteca" },
{ text: "TALEFOEN", answer: "Teléfono" },
{ text: "ORMAHELDAE", answer: "Heladera" },
{ text: "TACLHOCOE", answer: "Chocolate" },
{ text: "RALLEEST", answer: "Estrella" },
{ text: "NTOEMMOU", answer: "Monumento" },
{ text: "TNAANMO", answer: "Montaña" },
{ text: "RTOEMEORT", answer: "Termómetro" },
{ text: "LICEBCITA", answer: "Bicicleta" },
{ text: "VEARPNIAR", answer: "Primavera" },
{ text: "RAONIVNI", answer: "Invierno" },
{ text: "FNAELEET", answer: "Elefante" },
{ text: "COCILRDOO", answer: "Cocodrilo" },
{ text: "AAMRIPOS", answer: "Mariposa" },
{ text: "ENTAIRPES", answer: "Serpiente" },
{ text: "RACUGAN", answer: "Canguro" },
{ text: "RTOUGTA", answer: "Tortuga" },
{ text: "REAIDSTO", answer: "Desierto" },
{ text: "AVLCEON", answer: "Volcán" },
{ text: "QEBAUSOTL", answer: "Básquet" },
{ text: "AJRECED", answer: "Ajedrez" },
{ text: "AINCONTA", answer: "Natación" },
{ text: "RACRREA", answer: "Carrera" },
{ text: "RAGUITRA", answer: "Guitarra" },
{ text: "OANPI", answer: "Piano" },
{ text: "OLIVNI", answer: "Violín" },
{ text: "ALTFUA", answer: "Flauta" },
{ text: "RTOMBA", answer: "Tambor" },
{ text: "RATETO", answer: "Teatro" },
{ text: "NTAPRUI", answer: "Pintura" },
{ text: "ESPNRAEZA", answer: "Esperanza" },
{ text: "DTIBALILIAD", answer: "Habilidad" },
{ text: "LIGTINEEAN", answer: "Inteligencia" },
{ text: "AERTLIBD", answer: "Libertad" },
{ text: "DSIMATA", answer: "Amistad" },
{ text: "RECDAUO", answer: "Recuerdo" },
{ text: "OFEUTUR", answer: "Futuro" },
{ text: "ERSPTNEE", answer: "Presente" },
{ text: "CIEFLIAD", answer: "Felicidad" },
{ text: "IGRAVDEDA", answer: "Gravedad" },
{ text: "AFERMÓTSA", answer: "Atmósfera" },
{ text: "COTEMLÓU", answer: "Molécula" },
{ text: "ÉATMNOO", answer: "Átomo" },
{ text: "ACITCELÉRI", answer: "Electricidad" },
{ text: "TOANMIGESM", answer: "Magnetismo" },
{ text: "FOOTSÍN", answer: "Fotosíntesis" },
{ text: "AIPRNOCÓEM", answer: "Pronunciación" },
{ text: "TUTSICÓINCON", answer: "Constitución" },
{ text: "EROCDAIMCO", answer: "Democracia" },
{ text: "OREVLUCNIÓ", answer: "Revolución" },
{ text: "NTDEEPIEDNNCIA", answer: "Independencia" },
{ text: "LIOIFASOF", answer: "Filosofía" },
{ text: "RIQATUTECAR", answer: "Arquitectura" },
{ text: "OAÉGELQORUAI", answer: "Arqueología" },
{ text: "OTRAMEET", answer: "Meteoro" },
{ text: "ORGNAIMOS", answer: "Organismo" },
{ text: "OSMICROSCOPI", answer: "Microscopio" },
{ text: "RETCELSEOPOI", answer: "Telescopio" },
{ text: "M_NZ_N_", answer: "Manzana" },
  { text: "MA_Z_NA", answer: "Manzana" },
{ text: "N_RA_JA", answer: "Naranja" },
{ text: "C_MP_T_D_RA", answer: "Computadora" },
{ text: "B_BL_OT_CA", answer: "Biblioteca" },
{ text: "T_L_F_NO", answer: "Teléfono" },
{ text: "H_L_D_RA", answer: "Heladera" },
{ text: "B_C_CL_TA", answer: "Bicicleta" },
{ text: "M_TOC_CL_TA", answer: "Motocicleta" },
{ text: "H_L_CÓ_T_RO", answer: "Helicóptero" },
{ text: "S_BM_R_NO", answer: "Submarino" },

{ text: "EL_F_NTE", answer: "Elefante" },
{ text: "C_C_DR_LO", answer: "Cocodrilo" },
{ text: "M_R_PO_A", answer: "Mariposa" },
{ text: "S_RP_E_TE", answer: "Serpiente" },
{ text: "R_N_C_R_NTE", answer: "Rinoceronte" },
{ text: "M_RC_ÉL_GO", answer: "Murciélago" },
{ text: "H_P_PÓT_MO", answer: "Hipopótamo" },
{ text: "C_M_LE_N", answer: "Camaleón" },
{ text: "P_NG_Ü_NO", answer: "Pingüino" },
{ text: "OR_NG_TÁN", answer: "Orangután" },

{ text: "T_RM_M_TR_", answer: "Termómetro" },
{ text: "A_TM_SF_RA", answer: "Atmósfera" },
{ text: "M_L_C_LA", answer: "Molécula" },
{ text: "_L_CT_IC_DAD", answer: "Electricidad" },
{ text: "M_GN_T_SM_", answer: "Magnetismo" },
{ text: "F_T_S_NT_SIS", answer: "Fotosíntesis" },
{ text: "GR_V_D_D", answer: "Gravedad" },
{ text: "O_G_N_SMO", answer: "Organismo" },
{ text: "M_CR_SC_PIO", answer: "Microscopio" },
{ text: "T_L_SC_PIO", answer: "Telescopio" },

{ text: "PR_M_V_RA", answer: "Primavera" },
{ text: "_NV_ER_O", answer: "Invierno" },
{ text: "C_RD_LL_RA", answer: "Cordillera" },
{ text: "D_S_ERTO", answer: "Desierto" },
{ text: "M_NT_ÑA", answer: "Montaña" },
{ text: "ARCH_P_ÉL_GO", answer: "Archipiélago" },
{ text: "P_NÍ_S_LA", answer: "Península" },
{ text: "G_L_X_A", answer: "Galaxia" },
{ text: "_N_V_RSO", answer: "Universo" },
{ text: "S_TÉL_TE", answer: "Satélite" },

{ text: "ESP_R_NZA", answer: "Esperanza" },
{ text: "F_L_C_DAD", answer: "Felicidad" },
{ text: "H_B_L_DAD", answer: "Habilidad" },
{ text: "L_B_RT_D", answer: "Libertad" },
{ text: "AM_ST_D", answer: "Amistad" },
{ text: "R_CU_RDO", answer: "Recuerdo" },
{ text: "M_M_RIA", answer: "Memoria" },
{ text: "P_CI_NCIA", answer: "Paciencia" },
{ text: "V_L_NT_A", answer: "Valentía" },
{ text: "_NT_L_G_NCIA", answer: "Inteligencia" },
{ text: "M_RC_D_S", answer: "Mercedes" },
{ text: "C_MP_NA", answer: "Campana" },
{ text: "T_RN_LL_", answer: "Tornillo" },
{ text: "D_ST_RN_LL_D_R", answer: "Destornillador" },
{ text: "M_RT_LL_", answer: "Martillo" },
{ text: "A_R_C_T_", answer: "Alicate" },
{ text: "L_DR_LL_", answer: "Ladrillo" },
{ text: "C_M_NT_", answer: "Cemento" },
{ text: "H_RM_GÓN", answer: "Hormigón" },
{ text: "A_SC_NS_R", answer: "Ascensor" },

{ text: "M_CH_LA", answer: "Mochila" },
{ text: "B_LS_LL_", answer: "Bolsillo" },
{ text: "C_M_S_TA", answer: "Camiseta" },
{ text: "P_NT_LÓN", answer: "Pantalón" },
{ text: "Z_P_T_LL_", answer: "Zapatilla" },
{ text: "S_ND_L_A", answer: "Sandalia" },
{ text: "C_NT_RÓN", answer: "Cinturón" },
{ text: "P_R_G_AS", answer: "Paraguas" },
{ text: "M_N_C_A", answer: "Muñeca" },
{ text: "P_LS_RA", answer: "Pulsera" },

{ text: "C_R_T_RA", answer: "Carretera" },
{ text: "S_M_F_R_", answer: "Semáforo" },
{ text: "R_T_ND_", answer: "Rotonda" },
{ text: "A_V_N_DA", answer: "Avenida" },
{ text: "V_R_DA", answer: "Vereda" },
{ text: "B_LV_R", answer: "Bulevar" },
{ text: "G_LR_A", answer: "Galería" },
{ text: "F_RR_C_RR_L", answer: "Ferrocarril" },
{ text: "A_R_P_RTO", answer: "Aeropuerto" },
{ text: "E_T_C_ÓN", answer: "Estación" },

{ text: "T_MP_R_T_RA", answer: "Temperatura" },
{ text: "H_M_D_D", answer: "Humedad" },
{ text: "P_R_NÓST_C_", answer: "Pronóstico" },
{ text: "T_RM_M_TR_", answer: "Termómetro" },
{ text: "B_RÓM_TR_", answer: "Barómetro" },
{ text: "P_R_C_P_T_C_ÓN", answer: "Precipitación" },
{ text: "R_MP_GO", answer: "Relámpago" },
{ text: "T_U_NO", answer: "Trueno" },
{ text: "N_BL_NA", answer: "Neblina" },
{ text: "L_V_NA", answer: "Llovizna" },

{ text: "H_MB_RG_ESA", answer: "Hamburguesa" },
{ text: "S_NDW_CH", answer: "Sándwich" },
{ text: "M_L_N_SA", answer: "Milanesa" },
{ text: "E_MP_N_DA", answer: "Empanada" },
{ text: "L_SAÑA", answer: "Lasaña" },
{ text: "R_V_OL_S", answer: "Ravioles" },
{ text: "C_N_L_N_S", answer: "Canelones" },
{ text: "A_BÓ_D_GAS", answer: "Albóndigas" },
{ text: "T_RT_LL_A", answer: "Tortilla" },
{ text: "C_RQ_ETAS", answer: "Croquetas" },

{ text: "C_MP_ONATO", answer: "Campeonato" },
{ text: "Á_B_TR_", answer: "Árbitro" },
{ text: "V_ST_ARIO", answer: "Vestuario" },
{ text: "E_T_DIO", answer: "Estadio" },
{ text: "T_RN_O", answer: "Torneo" },
{ text: "E_TR_N_DOR", answer: "Entrenador" },
{ text: "S_PL_NTE", answer: "Suplente" },
{ text: "C_P_TÁN", answer: "Capitán" },
{ text: "D_F_NS_R", answer: "Defensor" },
{ text: "D_L_NT_RO", answer: "Delantero" },

{ text: "C_NTR_LL_D_R", answer: "Controlador" },
{ text: "A_L_C_LAR", answer: "Auricular" },
{ text: "T_CL_D_", answer: "Teclado" },
{ text: "M_N_T_R", answer: "Monitor" },
{ text: "I_PR_S_RA", answer: "Impresora" },
{ text: "N_V_G_D_R", answer: "Navegador" },
{ text: "C_NTR_S_ÑA", answer: "Contraseña" },
{ text: "D_SC_RG_A", answer: "Descarga" },
{ text: "A_L_C_C_ÓN", answer: "Aplicación" },
{ text: "P_NT_LL_A", answer: "Pantalla" },

];