import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const peliculas2010aActualidad: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/viBWzktrBmhzRw4ehmUIrrN4C0z.jpg", answer: "127 Hours", possibleAnswers: ["127 Horas"] },
    { image: "https://image.tmdb.org/t/p/original/eDLp4uFdqP1gpy9oMrutwH6Q64I.jpg", answer: "Black Swan", possibleAnswers: ["Cisne Negro"] },
    { image: "https://image.tmdb.org/t/p/original/fAqpfILTPsaKpAzoAvkXf5glgSo.jpg", answer: "Blue Valentine" },
    { image: "https://image.tmdb.org/t/p/original/vzhb18e8CVKhs3KAwhOb64XOM63.jpg", answer: "Carancho" },
    { image: "https://image.tmdb.org/t/p/original/f3ATwil5vmUeTsogBaMEKbBYBth.jpg", answer: "Incendies" },
    { image: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg", answer: "Inception", possibleAnswers: ["El Origen"] },
    { image: "https://image.tmdb.org/t/p/original/abQxLSkGxpHyUxRjRXACt8NbiGf.jpg", answer: "Room in Rome", possibleAnswers: ["Habitación en Roma"] },
    { image: "https://image.tmdb.org/t/p/original/6R9nT6m8wmzayV5XOQq3TRA6yZw.jpg", answer: "Scott Pilgrim vs. the World", possibleAnswers: ["Scott Pilgrim contra el Mundo"] },
    { image: "https://image.tmdb.org/t/p/original/rbZvGN1A1QyZuoKzhCw8QPmf2q0.jpg", answer: "Shutter Island", possibleAnswers: ["Isla siniestra"] },
    { image: "https://image.tmdb.org/t/p/original/2kqmEQZqime0G3ULgrKtAq3WVdH.jpg", answer: "The Fighter", possibleAnswers: ["El Ganador"] },
    { image: "https://image.tmdb.org/t/p/original/m4MGxxEgAMqIX9x8MCg5pYeyYjU.jpg", answer: "The King's Speech", possibleAnswers: ["El Discurso del Rey"] },
    { image: "https://image.tmdb.org/t/p/original/1PXwh3nJzgRkkYnqfWInJNypeL4.jpg", answer: "The Social Network", possibleAnswers: ["La Red Social"] },
    { image: "https://image.tmdb.org/t/p/original/owAe5rRStnX7ibVAPmza3NCXjCy.jpg", answer: "The Town", possibleAnswers: ["The Town: Ciudad de Ladrones"] },
    { image: "https://image.tmdb.org/t/p/original/5dwlH8Krm2bsuc2Pubw2cBb03g5.jpg", answer: "True Grit", possibleAnswers: ["Temple de Acero"] },
    { image: "https://image.tmdb.org/t/p/original/fqRJLbbakXAT88XTBVz0no4xavg.jpg", answer: "Chinese Take-Away", possibleAnswers: ["Un Cuento Chino"] },
    { image: "https://image.tmdb.org/t/p/original/iymDDg4upZWgpbSeiE1JCjsSPBs.jpg", answer: "Drive" },
    { image: "https://image.tmdb.org/t/p/original/Aj81Gu3u1a64qXFOLDuF5gdxyy0.jpg", answer: "Hugo", possibleAnswers: ["La Invención de Hugo"] },
    { image: "https://image.tmdb.org/t/p/original/qcIKxhqGMIj8uujsSoSMZWr8QqU.jpg", answer: "In the Grey", possibleAnswers: ["Infierno Blanco"] },
    { image: "https://image.tmdb.org/t/p/original/b5bcKhvN6VP82U5ztNdPfOLiolD.jpg", answer: "Midnight in Paris", possibleAnswers: ["Medianoche en París"] },
    { image: "https://image.tmdb.org/t/p/original/kYlBNDkB5qFdpTDpnlQdH0CdK3T.jpg", answer: "Moneyball", possibleAnswers: ["Moneyball: Rompiendo las Reglas"] },
    { image: "https://image.tmdb.org/t/p/original/dNFbrnF0mIBm0rClbfEFWTtsgMP.jpg", answer: "The Girl with the Dragon Tattoo", possibleAnswers: ["Los Hombres que No Amaban a las Mujeres"] },
    { image: "https://image.tmdb.org/t/p/original/cK070s3Qdn1Ib7Gq8RgIyJKgvu3.jpg", answer: "The Intouchables", possibleAnswers: ["Amigos Intocables"] },
    { image: "https://image.tmdb.org/t/p/original/tcx15vswrQJCGET5lGxESQ4J5LG.jpg", answer: "War Horse", possibleAnswers: ["Caballo de Batalla"] },
    { image: "https://image.tmdb.org/t/p/original/zXVledoXBJnYyrwdSLvnYmhgJXy.jpg", answer: "X-Men: First Class 35mm Special", possibleAnswers: ["X-Men: Primera Generación"] },
    { image: "https://image.tmdb.org/t/p/original/iVk4mVKwNE66JbBcoDwcYFvuUXM.jpg", answer: "Argo" },
    { image: "https://image.tmdb.org/t/p/original/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg", answer: "Django Unchained", possibleAnswers: ["Django sin Cadenas"] },
    { image: "https://image.tmdb.org/t/p/original/bsG8LkZx1ijrcf3fP6AvBlGTxkX.jpg", answer: "Les Misérables", possibleAnswers: ["Los Miserables"] },
    { image: "https://image.tmdb.org/t/p/original/21YsCNMub5455NQCn3jh9SmRFyG.jpg", answer: "Life of Pi", possibleAnswers: ["La Vida de Pi"] },
    { image: "https://image.tmdb.org/t/p/original/hwOFrwHladQ8FktYn3aJNAt8KA1.jpg", answer: "Lincoln" },
    { image: "https://image.tmdb.org/t/p/original/4GPCnwvTbsDleH5QIOyDLMsK8a2.jpg", answer: "Looper", possibleAnswers: ["En Tierra de Nadie"] },
    { image: "https://image.tmdb.org/t/p/original/bsYv9IFIGfpAV0oUbe7YTiyxhox.jpg", answer: "Moonrise Kingdom", possibleAnswers: ["Moonrise Kingdom: Un Reino Bajo la Luna"] },
    { image: "https://image.tmdb.org/t/p/original/12GpsUm9nVVKFlcjDTflKLClFVA.jpg", answer: "Silver Linings Playbook", possibleAnswers: ["El Lado Bueno de las Cosas"] },
    { image: "https://image.tmdb.org/t/p/original/jovIEk4cAxWmA2dBcPrfhn3jzYN.jpg", answer: "Sinister" },
    { image: "https://image.tmdb.org/t/p/original/wkA622CCN2X0uwpgqYEOnUYEDf5.jpg", answer: "Skyfall" },
    { image: "https://image.tmdb.org/t/p/original/pGFQCp12a8andfPlpnmXz44IIvY.jpg", answer: "The Avengers", possibleAnswers: ["Los Vengadores"] },
    { image: "https://image.tmdb.org/t/p/original/dWLoSzvw52y1gt7ni9gZXdy693e.jpg", answer: "The Cabin in the Woods", possibleAnswers: ["La Cabaña en el Bosque"] },
    { image: "https://image.tmdb.org/t/p/original/y2DB71C4nyIdMrANijz8mzvQtk6.jpg", answer: "The Dark Knight Rises", possibleAnswers: ["Batman: El Caballero de la Noche Asciende"] },
    { image: "https://image.tmdb.org/t/p/original/yVBQ65YBYZ9UhzJ4NGdRgeXtyTL.jpg", answer: "The Hunger Games", possibleAnswers: ["Los Juegos del Hambre"] },
    { image: "https://image.tmdb.org/t/p/original/evo3crueRIK9Eutb3lnDLVbD2xD.jpg", answer: "The Hunt", possibleAnswers: ["La Cacería"] },
    { image: "https://image.tmdb.org/t/p/original/6vvt0ghvrrzEB8Z1BLvmHOWUdxw.jpg", answer: "The Master", possibleAnswers: ["El Maestro"] },
    { image: "https://image.tmdb.org/t/p/original/4Bb1kMIfrT2tYRZ9M6Jhqy6gkeF.jpg", answer: "12 Years a Slave", possibleAnswers: ["12 Años de Esclavitud"] },
    { image: "https://image.tmdb.org/t/p/original/3r2G1vSDf4S3Pl5lJ9BDm9FTxe6.jpg", answer: "American Hustle", possibleAnswers: ["Una Gran Estafa Americana"] },
    { image: "https://image.tmdb.org/t/p/original/deYWtXTc56YdXyIuuMuA8dvBY16.jpg", answer: "Enemy" },
    { image: "https://image.tmdb.org/t/p/original/a2n6bKD7qhCPCAEALgsAhWOAQcc.jpg", answer: "Gravity" },
    { image: "https://image.tmdb.org/t/p/original/sPPsR9f4K0movWVQ99u4uMqFzEL.jpg", answer: "Her", possibleAnswers: ["Her (Ella)"] },
    { image: "https://image.tmdb.org/t/p/original/kdkCTC6Cl20TJSf4B1eIJXAFeXl.jpg", answer: "Inside Llewyn Davis" },
    { image: "https://image.tmdb.org/t/p/original/yKsMvfVx8vrvAM6NQSTEX0rBmMK.jpg", answer: "Prisoners", possibleAnswers: ["Prisioneros"] },
    { image: "https://image.tmdb.org/t/p/original/ecKQlAEG95k62SMGhvX83oEqANK.jpg", answer: "The Conjuring", possibleAnswers: ["El Conjuro"] },
    { image: "https://image.tmdb.org/t/p/original/7Nwnmyzrtd0FkcRyPqmdzTPppQa.jpg", answer: "The Wolf of Wall Street", possibleAnswers: ["El Lobo de Wall Street"] },
    { image: "https://image.tmdb.org/t/p/original/kg2FOT2Oe5PSCgs3L4vLel6B7ck.jpg", answer: "World War Z", possibleAnswers: ["Guerra Mundial Z"] },
    { image: "https://image.tmdb.org/t/p/original/Ac2s9RJEi1ZeaQopoLsqlsmWQmx.jpg", answer: "Boyhood" },
    { image: "https://image.tmdb.org/t/p/original/1RWLMyC9KcFfcaoViMiJGSSZzzr.jpg", answer: "Captain America: The Winter Soldier", possibleAnswers: ["Capitán América y el Soldado del Invierno"] },
    { image: "https://image.tmdb.org/t/p/original/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg", answer: "Edge of Tomorrow", possibleAnswers: ["Al Filo del Mañana"] },
    { image: "https://image.tmdb.org/t/p/original/uqOuJ50EtTj7kkDIXP8LCg7G45D.jpg", answer: "Ex Machina" },
    { image: "https://image.tmdb.org/t/p/original/iWak7wT0j6ycCc8lKr4NBz9c7n5.jpg", answer: "Gone Girl", possibleAnswers: ["Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/uLtVbjvS1O7gXL8lUOwsFOH4man.jpg", answer: "Guardians of the Galaxy", possibleAnswers: ["Guardianes de la Galaxia"] },
    { image: "https://image.tmdb.org/t/p/original/2ssWTSVklAEc98frZUQhgtGHx7s.jpg", answer: "Interstellar" },
    { image: "https://image.tmdb.org/t/p/original/ikaRI4yMxKOje5SmOlAhOBUnicL.jpg", answer: "It Follows", possibleAnswers: ["Sigues Ahí"] },
    { image: "https://image.tmdb.org/t/p/original/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg", answer: "John Wick" },
    { image: "https://image.tmdb.org/t/p/original/bdI6U1mT0kCdTJ6TWtiFxQ42GSn.jpg", answer: "Nightcrawler", possibleAnswers: ["El Reportero"] },
    { image: "https://image.tmdb.org/t/p/original/k0hlAzTryCYX1O1LyC6P8tAa8s0.jpg", answer: "The Amazing Spider-Man 2", possibleAnswers: ["The Amazing Spider-Man 2: El Poder de Electro"] },
    { image: "https://image.tmdb.org/t/p/original/oQaVV7p916HO5MDI820zzs1pin9.jpg", answer: "The Fault in Our Stars", possibleAnswers: ["Bajo la Misma Estrella"] },
    { image: "https://image.tmdb.org/t/p/original/9udCLTxTFl28RxnK8Q05E154ZGa.jpg", answer: "The Grand Budapest Hotel", possibleAnswers: ["El Gran Hotel Budapest"] },
    { image: "https://image.tmdb.org/t/p/original/usuRn9DUKQQr4nBWnrQzlOuZ1Q4.jpg", answer: "The Imitation Game", possibleAnswers: ["El Código Enigma"] },
    { image: "https://image.tmdb.org/t/p/original/dh2QT3TPtAQf057yeLpNMuaJlmp.jpg", answer: "The Theory of Everything", possibleAnswers: ["La Teoría del Todo"] },
    { image: "https://image.tmdb.org/t/p/original/wbQa0EnWUyRzQ5d1pHLNRlmsCUP.jpg", answer: "Whiplash" },
    { image: "https://image.tmdb.org/t/p/original/dHnki2Dh6lbOtfksrh8H5lg08f5.jpg", answer: "Wild Tales", possibleAnswers: ["Relatos Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/3czpqXzFy5UcNuD1AubecRLWkwD.jpg", answer: "X-Men: Days of Future Past", possibleAnswers: ["X-Men: Días del Futuro Pasado"] },
    { image: "https://image.tmdb.org/t/p/original/12M3SvYO4WMdlXCajWklz1zUAly.jpg", answer: "Bridge of Spies", possibleAnswers: ["El Puente de los Espías"] },
    { image: "https://image.tmdb.org/t/p/original/kODNw6GJNdgldUMEhKPlCw8wQCr.jpg", answer: "Creed" },
    { image: "https://image.tmdb.org/t/p/original/nQQIUwEEqa6sjPvnqcGbjJxbdit.jpg", answer: "Crimson Peak", possibleAnswers: ["La Cumbre Escarlata"] },
    { image: "https://image.tmdb.org/t/p/original/P7d3lyBaYbAXVor6iB2avLvc4K.jpg", answer: "Everest" },
    { image: "https://image.tmdb.org/t/p/original/uT895WNwm0aIJRtGizcQhrejWUo.jpg", answer: "Mad Max: Fury Road", possibleAnswers: ["Mad Max: Furia en el Camino"] },
    { image: "https://image.tmdb.org/t/p/original/cGV6R2vzT4TYIabf3JgmrOISQ0y.jpg", answer: "Room", possibleAnswers: ["La Habitación"] },
    { image: "https://image.tmdb.org/t/p/original/fKPgObonYgPgCdu88yjV7Hpn7Dp.jpg", answer: "Sicario" },
    { image: "https://image.tmdb.org/t/p/original/zT9iYKMtmU82Jo44WbiuMOW7jRi.jpg", answer: "Southpaw", possibleAnswers: ["Fuerza Mayor"] },
    { image: "https://image.tmdb.org/t/p/original/8lBViysvNJBPkl6zG1LVAaW3qhj.jpg", answer: "Spectre" },
    { image: "https://image.tmdb.org/t/p/original/8FbbcmwmpGd7brfiC7f7lWFNGdi.jpg", answer: "Spotlight" },
    { image: "https://image.tmdb.org/t/p/original/xj49X22pmh61fWBsveCkHtVtOBS.jpg", answer: "Steve Jobs" },
    { image: "https://image.tmdb.org/t/p/original/u6UyFHkkpUGzZec88PYaaamya5E.jpg", answer: "The Big Short", possibleAnswers: ["La Gran Apuesta"] },
    { image: "https://image.tmdb.org/t/p/original/wbA13Xns8EtbIubDOPLl7kCYYA4.jpg", answer: "The Clan", possibleAnswers: ["El Clan"] },
    { image: "https://image.tmdb.org/t/p/original/7g1zO5t0bd27Iqn5ZUDJmksOGPJ.jpg", answer: "The Hateful Eight", possibleAnswers: ["Los Odiosos Ocho"] },
    { image: "https://image.tmdb.org/t/p/original/iH2esZUZvt8qlJgu74WBvibDnfF.jpg", answer: "The Lobster" },
    { image: "https://image.tmdb.org/t/p/original/lzMS0CI3FLQYC5EgJoWeIaEt0lm.jpg", answer: "The Martian", possibleAnswers: ["Misión Rescate"] },
    { image: "https://image.tmdb.org/t/p/original/hEQYZq2CDB2LSJVxxlazdBOKeyW.jpg", answer: "The Revenant", possibleAnswers: ["El Renacido"] },
    { image: "https://image.tmdb.org/t/p/original/zi2oYYNSSv7t44iSt5YrxHX9PYs.jpg", answer: "The Witch", possibleAnswers: ["La Bruja"] },
    { image: "https://image.tmdb.org/t/p/original/8MUZz7oPXQftFTslZpRP3CVMOoq.jpg", answer: "Arrival", possibleAnswers: ["La Llegada"] },
    { image: "https://image.tmdb.org/t/p/original/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg", answer: "Captain America: Civil War", possibleAnswers: ["Capitán América: Civil War"] },
    { image: "https://image.tmdb.org/t/p/original/3zvZ699gMW2RhWc0GisIukzq0Ls.jpg", answer: "Doctor Strange" },
    { image: "https://image.tmdb.org/t/p/original/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg", answer: "La La Land", possibleAnswers: ["La La Land (La Ciudad de las Estrellas)"] },
    { image: "https://image.tmdb.org/t/p/original/fjk4eE8Ypke4YLv5A3ArDH4GzYH.jpg", answer: "Manchester by the Sea", possibleAnswers: ["Manchester Frente al Mar"] },
    { image: "https://image.tmdb.org/t/p/original/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg", answer: "Moonlight" },
    { image: "https://image.tmdb.org/t/p/original/1Xi0FNU0uj82GfUw2vWHsVCiRv5.jpg", answer: "Night Silence", possibleAnswers: ["Silencio"] },
    { image: "https://image.tmdb.org/t/p/original/o4mhrLxv6I70kvYA42qANGUF7ya.jpg", answer: "The Angry Birds Movie", possibleAnswers: ["Angry Birds: La Película"] },
    { image: "https://image.tmdb.org/t/p/original/mFCS5OuhPYT79KXu5jl7RqznPR1.jpg", answer: "The Conjuring 2", possibleAnswers: ["El Conjuro 2"] },
    { image: "https://image.tmdb.org/t/p/original/5WparwIlAtSZW0tcWbK2NHEZJC6.jpg", answer: "The Founder", possibleAnswers: ["Hambre de Poder"] },
    { image: "https://image.tmdb.org/t/p/original/3upEZ0ltY7WwOSFVXrtiP34D48p.jpg", answer: "The Handmaiden", possibleAnswers: ["La Doncella"] },
    { image: "https://image.tmdb.org/t/p/original/yxYUN3fBPJdTNdXC1l8L24XFPhX.jpg", answer: "The Nice Guys", possibleAnswers: ["Dos Buenos Tipos"] },
    { image: "https://image.tmdb.org/t/p/original/brnfCYyz8EMbBrHgmh8sCwBi5i1.jpg", answer: "Train to Busan", possibleAnswers: ["Estación Zombie: Tren a Busan"] },
    { image: "https://image.tmdb.org/t/p/original/sTQNRqLbfCXolrb5CizAW1dj528.jpg", answer: "X-Men: Apocalypse", possibleAnswers: ["X-Men: Apocalipsis"] },
    { image: "https://image.tmdb.org/t/p/original/yir5430WblZSZuIMd9C6pIZerfA.jpg", answer: "Baby Driver" },
    { image: "https://image.tmdb.org/t/p/original/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg", answer: "Blade Runner 2049" },
    { image: "https://image.tmdb.org/t/p/original/4Xh2a1WeTp6b8Ksvug0pAMbX3dT.jpg", answer: "Call Me by Your Name", possibleAnswers: ["Llámame por tu Nombre"] },
    { image: "https://image.tmdb.org/t/p/original/6prkTmEEsB3f9hhKBzUePLe27b2.jpg", answer: "Darkest Hour", possibleAnswers: ["Las Horas Más Oscuras"] },
    { image: "https://image.tmdb.org/t/p/original/ddIkmH3TpR6XSc47jj0BrGK5Rbz.jpg", answer: "Dunkirk", possibleAnswers: ["Dunkerque"] },
    { image: "https://image.tmdb.org/t/p/original/5AhkjcqqRxBdpYZ0TeOuTCuOUYq.jpg", answer: "Good Time" },
    { image: "https://image.tmdb.org/t/p/original/jwBiY1kE5089i2WpfS1MHDYp3VO.jpg", answer: "Lady Bird" },
    { image: "https://image.tmdb.org/t/p/original/4DZxWNSAyksN6N3JkvpJ53Yq6zU.jpg", answer: "Logan" },
    { image: "https://image.tmdb.org/t/p/original/sJZd1H4cl2Nxhj0nutVCK5pMczL.jpg", answer: "Phantom Thread", possibleAnswers: ["El Hilo Fantasma"] },
    { image: "https://image.tmdb.org/t/p/original/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg", answer: "Spider-Man: Homecoming", possibleAnswers: ["Spider-Man: De Regreso a Casa"] },
    { image: "https://image.tmdb.org/t/p/original/GOwNU7Z9G3ORjNxdZnURfuIGS6.jpg", answer: "The Florida Project" },
    { image: "https://image.tmdb.org/t/p/original/mVHyU4pnu9b2LWByPGGM0GGCA1v.jpg", answer: "The Get Out", possibleAnswers: ["¡Huye!"] },
    { image: "https://image.tmdb.org/t/p/original/abirSHwWgKajV3hXhaIR5lcCIXe.jpg", answer: "The Shape of Water", possibleAnswers: ["La Forma del Agua"] },
    { image: "https://image.tmdb.org/t/p/original/2wS8pMZgvzq7kaZb5LHX54poQnA.jpg", answer: "mother!" },
    { image: "https://image.tmdb.org/t/p/original/nHRUtBwFNnNN70vcQ7lAsjc2T6S.jpg", answer: "A Quiet Place", possibleAnswers: ["Un Lugar en Silencio"] },
    { image: "https://image.tmdb.org/t/p/original/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg", answer: "Avengers: Infinity War", possibleAnswers: ["Vengadores: Infinity War"] },
    { image: "https://image.tmdb.org/t/p/original/19Ed4XgjahPm4U8JT7SnntERIlt.jpg", answer: "Black Panther", possibleAnswers: ["Pantera Negra"] },
    { image: "https://image.tmdb.org/t/p/original/dcvbs8z0GEXslC1kCT77x19XDeR.jpg", answer: "Bohemian Rhapsody" },
    { image: "https://image.tmdb.org/t/p/original/qQEt2FqF8McryFBNX30dyDJKiEK.jpg", answer: "Burning" },
    { image: "https://image.tmdb.org/t/p/original/v0sblc9A8eaE8EqDQ5Y6fELj4oB.jpg", answer: "Climax" },
    { image: "https://image.tmdb.org/t/p/original/zeHB7aP46Xs3u4aFLuAq2GFeUGb.jpg", answer: "Crazy Rich Asians", possibleAnswers: ["Locamente Millonarios"] },
    { image: "https://image.tmdb.org/t/p/original/9il7qNbeYnPMYlutsVYDsj4hRyb.jpg", answer: "Creed II" },
    { image: "https://image.tmdb.org/t/p/original/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg", answer: "Deadpool 2" },
    { image: "https://image.tmdb.org/t/p/original/jrudoaXcoLyHRPdolyOGemXgPEs.jpg", answer: "First Man", possibleAnswers: ["Primer Hombre en la Luna"] },
    { image: "https://image.tmdb.org/t/p/original/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg", answer: "Hereditary", possibleAnswers: ["El Legado del Diablo"] },
    { image: "https://image.tmdb.org/t/p/original/8HbNKB2pMiD3mfLgbxe7DgAKjdS.jpg", answer: "Insidious Inferno" },
    { image: "https://image.tmdb.org/t/p/original/5a7lMDn3nAj2ByO0X1fg6BhUphR.jpg", answer: "Ready Player One", possibleAnswers: ["Ready Player One: Comienza el Juego"] },
    { image: "https://image.tmdb.org/t/p/original/k49RhOmaKfoybjR3vBSaOJrIGmc.jpg", answer: "Shoplifters", possibleAnswers: ["Un Asunto de Familia"] },
    { image: "https://image.tmdb.org/t/p/original/iSskYDN193CJfTbSpFfscSwZ9Sx.jpg", answer: "The Favourite", possibleAnswers: ["La Favorita"] },
    { image: "https://image.tmdb.org/t/p/original/2lBOQK06tltt8SQaswgb8d657Mv.jpg", answer: "1917" },
    { image: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg", answer: "Avengers: Endgame", possibleAnswers: ["Vengadores: Endgame"] },
    { image: "https://image.tmdb.org/t/p/original/2vq5GTJOahE03mNYZGxIynlHcWr.jpg", answer: "Ford v Ferrari", possibleAnswers: ["Le Mans 66: La Historia de Ford vs Ferrari"] },
    { image: "https://image.tmdb.org/t/p/original/6LVSrgm83UYWlrLTCVGmWhFKYO0.jpg", answer: "It Chapter Two", possibleAnswers: ["It: Capítulo 2"] },
    { image: "https://image.tmdb.org/t/p/original/lTyikzfGgRX5ZqIfVeT26APYfRL.jpg", answer: "Jojo Rabbit" },
    { image: "https://image.tmdb.org/t/p/original/rlay2M5QYvi6igbGcFjq8jxeusY.jpg", answer: "Joker" },
    { image: "https://image.tmdb.org/t/p/original/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg", answer: "Knives Out", possibleAnswers: ["Puñales por la Espalda"] },
    { image: "https://image.tmdb.org/t/p/original/lqxxwTRk0l7CubY6JkJdhnwJEkn.jpg", answer: "Little Women", possibleAnswers: ["Mujercitas"] },
    { image: "https://image.tmdb.org/t/p/original/wDwQXLDUuiEaaiuWIDBpbqnwYGX.jpg", answer: "Marriage Story", possibleAnswers: ["Historia de un Matrimonio"] },
    { image: "https://image.tmdb.org/t/p/original/pYgj8e2Y6RufnSyOA6OnzmxFXxZ.jpg", answer: "Midsommar", possibleAnswers: ["Midsommar: El Terror no Espera la Noche"] },
    { image: "https://image.tmdb.org/t/p/original/xwgBHC2FgoIrQitl8jZwXXdsR9u.jpg", answer: "Once Upon a Time... in Hollywood", possibleAnswers: ["Había Una Vez en... Hollywood"] },
    { image: "https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg", answer: "Parasite", possibleAnswers: ["Parásitos"] },
    { image: "https://image.tmdb.org/t/p/original/isnJGDrfR9dIrHMsPTvHtJaGEpc.jpg", answer: "Rocketman" },
    { image: "https://image.tmdb.org/t/p/original/7b5R8FfGUzlxfhOkPpL3xyIeuyF.jpg", answer: "Sound of Metal" },
    { image: "https://image.tmdb.org/t/p/original/34jW8LvjRplM8Pv06cBFDpLlenR.jpg", answer: "Spider-Man: Far From Home", possibleAnswers: ["Spider-Man: Lejos de Casa"] },
    { image: "https://image.tmdb.org/t/p/original/hClLP88yMIuhslwSVxtYrvWmxfp.jpg", answer: "The Gentlemen" },
    { image: "https://image.tmdb.org/t/p/original/1RDto0tLo8Fhq7OcwgDaM7nECb7.jpg", answer: "The Irishman", possibleAnswers: ["El Irlandés"] },
    { image: "https://image.tmdb.org/t/p/original/sYLzRuEcwSz0L1Z92wQNrETHU9O.jpg", answer: "The Lighthouse", possibleAnswers: ["El Faro"] },
    { image: "https://image.tmdb.org/t/p/original/eGljNfNCrPhFYG2RXXmmE0OKu5.jpg", answer: "Uncut Gems", possibleAnswers: ["Diamantes en Bruto"] },
    { image: "https://image.tmdb.org/t/p/original/sC0b8iPUHfZdD8kseLiHw3N8gkp.jpg", answer: "Us", possibleAnswers: ["Nosotros"] },
    { image: "https://image.tmdb.org/t/p/original/a2pPepVPtKY7E4XEkT7W3ZxUOY5.jpg", answer: "Another Round", possibleAnswers: ["Otra Ronda"] },
    { image: "https://image.tmdb.org/t/p/original/bKCpRjjTKcr3KAITmwjVMobbBYg.jpg", answer: "Minari" },
    { image: "https://image.tmdb.org/t/p/original/563sRDK3rZS31TXCdTY4lfcwrNK.jpg", answer: "Nomadland" },
    { image: "https://image.tmdb.org/t/p/original/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg", answer: "Palm Springs" },
    { image: "https://image.tmdb.org/t/p/original/mQOUyqDybTqxl73hO5LujCZsM1o.jpg", answer: "Tenet" },
    { image: "https://image.tmdb.org/t/p/original/h3weAFgg06GqchI2xDfufBgSFTj.jpg", answer: "The Father", possibleAnswers: ["El Padre"] },
    { image: "https://image.tmdb.org/t/p/original/uuBYYlbfiYD7ny5VNj46NG14ykR.jpg", answer: "A Quiet Place Part II", possibleAnswers: ["Un Lugar en Silencio Parte II"] },
    { image: "https://image.tmdb.org/t/p/original/v85FlkbMYKa5du1glm0YfYNsL2n.jpg", answer: "CODA" },
    { image: "https://image.tmdb.org/t/p/original/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg", answer: "Don't Look Up" },
    { image: "https://image.tmdb.org/t/p/original/r6aqhlmJmu8Dv5E7QYEruaEXKYm.jpg", answer: "Drive My Car" },
    { image: "https://image.tmdb.org/t/p/original/qVgZu5BTx6pu4owCvVOm4zjTfOi.jpg", answer: "Dune" },
    { image: "https://image.tmdb.org/t/p/original/a8tH0jl37366bLVyPB08dncgqqd.jpg", answer: "Home Sweet Home Alone", possibleAnswers: ["Mi Pobre Angelito: Solo en Casa"] },
    { image: "https://image.tmdb.org/t/p/original/fkn5KBUUKxbG7MjOs9poAOAik40.jpg", answer: "Licorice Pizza" },
    { image: "https://image.tmdb.org/t/p/original/g0YNGpmlXsgHfhGnJz3c5uyzZ1B.jpg", answer: "Nightmare Alley", possibleAnswers: ["El Callejón de las Almas Perdidas"] },
    { image: "https://image.tmdb.org/t/p/original/bz7pwNGCbV576COsDcYN9MbEACC.jpg", answer: "No Time to Die", possibleAnswers: ["Sin Tiempo para Morir"] },
    { image: "https://image.tmdb.org/t/p/original/r7K6Xt0RX4Mw0cAbZVw5cyb1Tux.jpg", answer: "Shang-Chi and the Legend of the Ten Rings", possibleAnswers: ["Shang-Chi y la Leyenda de los Diez Anillos"] },
    { image: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg", answer: "Spider-Man: No Way Home" },
    { image: "https://image.tmdb.org/t/p/original/p26c040MErns7DJYhisa1CpVB5i.jpg", answer: "The Conjuring: The Devil Made Me Do It", possibleAnswers: ["El Conjuro 3: El Diablo me Obligó a Hacerlo"] },
    { image: "https://image.tmdb.org/t/p/original/xS0rl1YrVt51ztzjRf6qoIPZ7TA.jpg", answer: "The French Dispatch of the Liberty, Kansas Evening Sun", possibleAnswers: ["La Crónica Francesa"] },
    { image: "https://image.tmdb.org/t/p/original/fJ1iAY7Gnh74AWJXArZdlzGtnrA.jpg", answer: "The Last Duel", possibleAnswers: ["El Último Duelo"] },
    { image: "https://image.tmdb.org/t/p/original/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg", answer: "The Matrix Resurrections", possibleAnswers: ["Matrix Resurrecciones"] },
    { image: "https://image.tmdb.org/t/p/original/woYGBHERSMhIHqmkkRCbCXp81l4.jpg", answer: "The Worst Person in the World", possibleAnswers: ["La Peor Persona del Mundo"] },
    { image: "https://image.tmdb.org/t/p/original/cFhRpFEhgMlqdFdjh2Jg52nqj2N.jpg", answer: "Vortex" },
    { image: "https://image.tmdb.org/t/p/original/4jdduww9j5RyzO4ITRcuBFhqNN1.jpg", answer: "Aftersun" },
    { image: "https://image.tmdb.org/t/p/original/xBwtP27cx8WfjHJVFkpuV6F1RES.jpg", answer: "All Quiet on the Western Front", possibleAnswers: ["Sin Novedad en el Frente"] },
    { image: "https://image.tmdb.org/t/p/original/gh1Rghpf3BIISHSAw9GsObG4TN3.jpg", answer: "Argentina 1985" },
    { image: "https://image.tmdb.org/t/p/original/5fxTB08O7CW1hAcN2MWOKodp1h1.jpg", answer: "Babylon" },
    { image: "https://image.tmdb.org/t/p/original/kSeU4uk19t82k6Cao7hc6ktDYhF.jpg", answer: "Barbarian" },
    { image: "https://image.tmdb.org/t/p/original/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg", answer: "Bullet Train", possibleAnswers: ["Bala Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/A1bWhTFQKkhF1yhSKWosSyzn2Hp.jpg", answer: "Decision to Leave" },
    { image: "https://image.tmdb.org/t/p/original/rLo9T9jEg67UZPq3midjLnTUYYi.jpg", answer: "Elvis" },
    { image: "https://image.tmdb.org/t/p/original/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg", answer: "Everything Everywhere All at Once", possibleAnswers: ["Todo en Todas Partes al Mismo Tiempo"] },
    { image: "https://image.tmdb.org/t/p/original/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg", answer: "Glass Onion: A Knives Out Mystery", possibleAnswers: ["Puñales por la Espalda 2: Glass Onion"] },
    { image: "https://image.tmdb.org/t/p/original/yRutvYkM3OP8N9oqqfjSK1VC7fs.jpg", answer: "Nope" },
    { image: "https://image.tmdb.org/t/p/original/kMZIMqEXO5MFd5Y1Ha2jZZF4pvF.jpg", answer: "Smile" },
    { image: "https://image.tmdb.org/t/p/original/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg", answer: "The Batman" },
    { image: "https://image.tmdb.org/t/p/original/4vSBj7BYsyuKCx96EJzGyp20WfY.jpg", answer: "The Menu", possibleAnswers: ["El Menú"] },
    { image: "https://image.tmdb.org/t/p/original/46FRuCeAn6TrS4F1P4F9zhyCpyo.jpg", answer: "The Whale", possibleAnswers: ["La Ballena"] },
    { image: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg", answer: "Top Gun: Maverick" },
    { image: "https://image.tmdb.org/t/p/original/lDVl2jf6VB8ODl1olZ6FLvOV1gX.jpg", answer: "Anatomy of a Fall", possibleAnswers: ["Anatomía de una Caída"] },
    { image: "https://image.tmdb.org/t/p/original/iloUOSs3Rcq3aMr04CrGRWVVBkq.jpg", answer: "Asteroid City" },
    { image: "https://image.tmdb.org/t/p/original/3N5QNUqS76GFYNoEayfkkJyAyTN.jpg", answer: "Barbie" },
    { image: "https://image.tmdb.org/t/p/original/gOIztYywR291pC4k3IpDq7Vj3Kj.jpg", answer: "Creed III" },
    { image: "https://image.tmdb.org/t/p/original/acvE3RWjDLgvbL2RtcyzkrsAyNV.jpg", answer: "Killers of the Flower Moon", possibleAnswers: ["Los Asesinos de la Luna"] },
    { image: "https://image.tmdb.org/t/p/original/33pMXav77ICRnceEBLhL8lXTywv.jpg", answer: "Napoleon", possibleAnswers: ["Napoleón"] },
    { image: "https://image.tmdb.org/t/p/original/r013C8Me2bZ0pUi0OWJRh0h7MzT.jpg", answer: "Obsession" },
    { image: "https://image.tmdb.org/t/p/original/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg", answer: "Oppenheimer" },
    { image: "https://image.tmdb.org/t/p/original/7HR38hMBl23lf38MAN63y4pKsHz.jpg", answer: "Past Lives", possibleAnswers: ["Vidas Pasadas"] },
    { image: "https://image.tmdb.org/t/p/original/hjWxngV6tidwDkfJDEgMjHD2KEz.jpg", answer: "Perfect Days" },
    { image: "https://image.tmdb.org/t/p/original/zh6IdheEYinU4TPtorWsjx6qPQE.jpg", answer: "Poor Things", possibleAnswers: ["Pobres Criaturas"] },
    { image: "https://image.tmdb.org/t/p/original/yCN98oNvavyHvFvdvwqmw9TkY9A.jpg", answer: "Saltburn" },
    { image: "https://image.tmdb.org/t/p/original/uUJp5I4IbzuhdUiEx4R9OAoFpbz.jpg", answer: "Saw X", possibleAnswers: ["El Juego del Miedo X"] },
    { image: "https://image.tmdb.org/t/p/original/46Os8U0DEPmI0OnvKDxucl6SLVZ.jpg", answer: "Talk to Me" },
    { image: "https://image.tmdb.org/t/p/original/A99WMiz0ASpH9coOFrxSEuwTWx0.jpg", answer: "The Holdovers", possibleAnswers: ["Los que se Quedan"] },
    { image: "https://image.tmdb.org/t/p/original/f9Atch0jlzcOT9RbF8UccqfNOpd.jpg", answer: "The Killer", possibleAnswers: ["El Asesino"] },
    { image: "https://image.tmdb.org/t/p/original/pnTSOKcYnvdpQNQElAtJM1rWOxH.jpg", answer: "The Zone of Interest", possibleAnswers: ["Zona de Interés"] },
    { image: "https://image.tmdb.org/t/p/original/otugS74HEHdca4aTCtt8HtXvPYV.jpg", answer: "A Complete Unknown", possibleAnswers: ["Un Completo Desconocido"] },
    { image: "https://image.tmdb.org/t/p/original/87GU2ifjNYtgYtcRH1NNH1P4ODo.jpg", answer: "Anora" },
    { image: "https://image.tmdb.org/t/p/original/kF8ljC7Y4p1UsmKBi2LxelZpqw.jpg", answer: "Beetlejuice Beetlejuice" },
    { image: "https://image.tmdb.org/t/p/original/tq8COKsI99Bivjd4CZIYVGoKcIx.jpg", answer: "Challengers" },
    { image: "https://image.tmdb.org/t/p/original/eZzNdjNDvaSoyywy9ICg2UmFwul.jpg", answer: "Conclave" },
    { image: "https://image.tmdb.org/t/p/original/cOoVcVQ3i1m5b2xtqKBtoTSbxC1.jpg", answer: "Deadpool & Wolverine" },
    { image: "https://image.tmdb.org/t/p/original/eZ239CUp1d6OryZEBPnO2n87gMG.jpg", answer: "Dune: Part Two", possibleAnswers: ["Dune: Parte Dos"] },
    { image: "https://image.tmdb.org/t/p/original/u2eA9pqi1q3DvevT7RuDuJHxxBT.jpg", answer: "Emilia Pérez" },
    { image: "https://image.tmdb.org/t/p/original/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg", answer: "Gladiator II", possibleAnswers: ["Gladiador II"] },
    { image: "https://image.tmdb.org/t/p/original/yZq3kFveiDtfJpwQTgZwXBxs4aE.jpg", answer: "I'm Still Here", possibleAnswers: ["Aún Estoy Aquí"] },
    { image: "https://image.tmdb.org/t/p/original/hmZnqijPaaACjenDkrbWcCmcADI.jpg", answer: "The Brutalist", possibleAnswers: ["El Brutalista"] },
    { image: "https://image.tmdb.org/t/p/original/8ODNt5olCeIqBYTP3GgXEQYTfeX.jpg", answer: "The Substance", possibleAnswers: ["La Sustancia"] },
    { image: "https://image.tmdb.org/t/p/original/fyZ6SDUS4o9jp2EHxfZa3qS9ean.jpg", answer: "Wicked" },
    { image: "https://image.tmdb.org/t/p/original/6WqqEjiycNvDLjbEClM1zCwIbDD.jpg", answer: "28 Years Later", possibleAnswers: ["28 Años Después"] },
    { image: "https://image.tmdb.org/t/p/original/x0J0OMKwnX1eeVRQWeb2D05yd3K.jpg", answer: "After the Hunt" },
    { image: "https://image.tmdb.org/t/p/original/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg", answer: "Avatar: Fire and Ash", possibleAnswers: ["Avatar: Fuego y Ceniza"] },
    { image: "https://image.tmdb.org/t/p/original/tN3pTxkQoP96wtaEahYuRVdUWb2.jpg", answer: "Bugonia" },
    { image: "https://image.tmdb.org/t/p/original/41043LV7mfluH8iXEUPVseCDAv5.jpg", answer: "Caught Stealing" },
    { image: "https://image.tmdb.org/t/p/original/dEkFlZzj2cb5F7SShvqkL54E4lr.jpg", answer: "Die My Love" },
    { image: "https://image.tmdb.org/t/p/original/5PJkK2iVXRO1ydrtgwuJdevmnOe.jpg", answer: "Eddington" },
    { image: "https://image.tmdb.org/t/p/original/3cVrg7tzSf5AgEecYWDOSAzXAeX.jpg", answer: "Exit 8" },
    { image: "https://image.tmdb.org/t/p/original/lkDYN0whyE82mcM20rwtwjbniKF.jpg", answer: "F1" },
    { image: "https://image.tmdb.org/t/p/original/hpXBJxLD2SEf8l2CspmSeiHrBKX.jpg", answer: "Frankenstein" },
    { image: "https://image.tmdb.org/t/p/original/lMLyfSiaumaKniwynwAxu69CLTz.jpg", answer: "Hamnet" },
    { image: "https://image.tmdb.org/t/p/original/wR9D9hQvCVBux16NauY4b7letdU.jpg", answer: "Jay Kelly" },
    { image: "https://image.tmdb.org/t/p/original/6h7w8R4BA7vubEmEEW5vYEjuoz6.jpg", answer: "Marty Supreme" },
    { image: "https://image.tmdb.org/t/p/original/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg", answer: "Michael" },
    { image: "https://image.tmdb.org/t/p/original/538U9snNc2fpnOmYXAPUh3zn31H.jpg", answer: "Mission: Impossible - The Final Reckoning", possibleAnswers: ["Misión: Imposible - Sentencia Final"] },
    { image: "https://image.tmdb.org/t/p/original/zpEWFNqoN8Qg1SzMMHmaGyOBTdW.jpg", answer: "One Battle After Another", possibleAnswers: ["Una Batalla Tras Otra"] },
    { image: "https://image.tmdb.org/t/p/original/82lM4GJ9uuNvNDOEpxFy77uv4Ak.jpg", answer: "Predator: Badlands", possibleAnswers: ["Depredador: Tierras Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/eGX66zonvc4bXg3rM08RUxdYSDx.jpg", answer: "Superman" },
    { image: "https://image.tmdb.org/t/p/original/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg", answer: "The Drama" },
    { image: "https://image.tmdb.org/t/p/original/s94NjfKkcSczZ1FembwmQZwsuwY.jpg", answer: "The Fantastic 4: First Steps", possibleAnswers: ["Los 4 Fantásticos: Primeros Pasos"] },
    { image: "https://image.tmdb.org/t/p/original/aHj7d7wSLqrg5cjAcgHhiGr97Ih.jpg", answer: "The Running Man" },
    { image: "https://image.tmdb.org/t/p/original/hTCr9dDf0EcBGZSUaY0YCeBjBr5.jpg", answer: "The Smashing Machine" },
    { image: "https://image.tmdb.org/t/p/original/fiRDzpcJe7qz3yIR43hdXIE3NHv.jpg", answer: "Wake Up Dead Man: A Knives Out Mystery", possibleAnswers: ["Puñales por la Espalda 3: Wake Up Dead Man"] },
    { image: "https://image.tmdb.org/t/p/original/8VyTWJrNEyV2MTWvniDVp0MpOAe.jpg", answer: "Weapons" },
    { image: "https://image.tmdb.org/t/p/original/fFyLcR22R4ynrecqjMniKXm0UTp.jpg", answer: "Project Hail Mary" },
    { image: "https://image.tmdb.org/t/p/original/Af907x5h9W1wVis8XrSd7ynTWuy.jpg", answer: "The Devil Wears Prada 2", possibleAnswers: ["El Diablo Viste a la Moda 2"] },
    { image: "https://image.tmdb.org/t/p/original/r57L2UBLPKcHdZQYg8tagv9XqK2.jpg", answer: "The Odyssey", possibleAnswers: ["La Odisea"] },
];
