import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const peliculas1970a1990: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/txXPooNu7fr4YhLwx7AlXkU0PnN.jpg", answer: "Patton" },
    { image: "https://image.tmdb.org/t/p/original/nLFxvLokHe3bQmrmAfljIfax2jQ.jpg", answer: "A Clockwork Orange", possibleAnswers: ["La Naranja Mecánica"] },
    { image: "https://image.tmdb.org/t/p/original/AoGLKkPvBcZP27jwSA85fY8emvJ.jpg", answer: "Duel", possibleAnswers: ["Duelo"] },
    { image: "https://image.tmdb.org/t/p/original/kfSZaOr9ApNR52gWKlpXHD0id0W.jpg", answer: "Aguirre, the Wrath of God", possibleAnswers: ["Aguirre, la Cólera de Dios"] },
    { image: "https://image.tmdb.org/t/p/original/qOGuM0QINhH7MfNAiOZtmlaDLgj.jpg", answer: "Solaris" },
    { image: "https://image.tmdb.org/t/p/original/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg", answer: "The Godfather", possibleAnswers: ["El Padrino"] },
    { image: "https://image.tmdb.org/t/p/original/qdecDSIVoqctIoYoOhLH3TgSYLD.jpg", answer: "Mean Streets", possibleAnswers: ["Calles Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/pyvkujOZ5qvY2NlQVC71flfgVWE.jpg", answer: "Chinatown", possibleAnswers: ["Barrio Chino"] },
    { image: "https://image.tmdb.org/t/p/original/s7yfiwIshKQIT6M8ZcTnFKXHs8B.jpg", answer: "The Conversation", possibleAnswers: ["La Conversación"] },
    { image: "https://image.tmdb.org/t/p/original/kGzFbGhp99zva6oZODW5atUtnqi.jpg", answer: "The Godfather Part II", possibleAnswers: ["El Padrino, Parte II"] },
    { image: "https://image.tmdb.org/t/p/original/ef6SvWbSfCFlKodJZqpIaTvsRRP.jpg", answer: "Barry Lyndon" },
    { image: "https://image.tmdb.org/t/p/original/1KgXxv6tHXOnakqYvMPvFwYKWiw.jpg", answer: "Monty Python and the Holy Grail", possibleAnswers: ["Los Caballeros de la Mesa Cuadrada y sus Locos Seguidores"] },
    { image: "https://image.tmdb.org/t/p/original/uA8eSNAUUUyfHNIrG4h0zHxzt9W.jpg", answer: "One Flew Over the Cuckoo's Nest", possibleAnswers: ["Atrapado sin Salida"] },
    { image: "https://image.tmdb.org/t/p/original/zwJFfKQdfiptK2GY6N8GkZFrAxJ.jpg", answer: "Carrie" },
    { image: "https://image.tmdb.org/t/p/original/xUZ2G8MRGEljqgqLxMJItK4iHfY.jpg", answer: "Rocky" },
    { image: "https://image.tmdb.org/t/p/original/9uddYYTNcLWpzUkl5iw1RUYhLhY.jpg", answer: "Taxi Driver" },
    { image: "https://image.tmdb.org/t/p/original/yBCekmb7vK70xUhtsRQBcTu65sB.jpg", answer: "Close Encounters of the Third Kind", possibleAnswers: ["Encuentros Cercanos del Tercer Tipo"] },
    { image: "https://image.tmdb.org/t/p/original/yUiXA68FfQeA8cRBhd0Ao0jIRZt.jpg", answer: "Star Wars", possibleAnswers: ["La Guerra de las Galaxias"] },
    { image: "https://image.tmdb.org/t/p/original/rspbS1E9wJtslrb8amfJgtMBUVh.jpg", answer: "Dawn of the Dead", possibleAnswers: ["El Amanecer de los Muertos"] },
    { image: "https://image.tmdb.org/t/p/original/sHI9xlFRWCJ38AIIfOqnGjuEvXz.jpg", answer: "Halloween", possibleAnswers: ["La Noche de Halloween"] },
    { image: "https://image.tmdb.org/t/p/original/be5T7oHxmDG4ytEimwPdmDHZD9N.jpg", answer: "The Crucifix: Blood of the Exorcist" },
    { image: "https://image.tmdb.org/t/p/original/a5zBQfXmLk3qqRYF7AioWpiAxk2.jpg", answer: "The Deer Hunter", possibleAnswers: ["El Cazador"] },
    { image: "https://image.tmdb.org/t/p/original/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg", answer: "Alien", possibleAnswers: ["Alien, el Octavo Pasajero"] },
    { image: "https://image.tmdb.org/t/p/original/49fzLedFVKgGgFChLMuulDJBY1c.jpg", answer: "Apocalypse Now" },
    { image: "https://image.tmdb.org/t/p/original/lOrM3OQhHlzEkpF7Ih3GghecrA8.jpg", answer: "Life of Brian", possibleAnswers: ["La Vida de Brian"] },
    { image: "https://image.tmdb.org/t/p/original/5aZ2PDpNhjTdk77uSAIDzrpsAUr.jpg", answer: "Rocky II" },
    { image: "https://image.tmdb.org/t/p/original/6yrbWzzrPp7pwz6zHdifspJk8t3.jpg", answer: "Stalker" },
    { image: "https://image.tmdb.org/t/p/original/wQyvrsNSTzFVEGgarZbFkFyIciy.jpg", answer: "Airplane!", possibleAnswers: ["¿Y Dónde Está el Piloto?"] },
    { image: "https://image.tmdb.org/t/p/original/7qsKE8GsgjreeQ2mTLd5oKZ7Tbf.jpg", answer: "Kagemusha", possibleAnswers: ["La Sombra del Guerrero"] },
    { image: "https://image.tmdb.org/t/p/original/tvNuhRlpRozDgsX1zR9gQ2aHv1X.jpg", answer: "Raging Bull", possibleAnswers: ["Toro Salvaje"] },
    { image: "https://image.tmdb.org/t/p/original/6huSptAsqYg3wbsi1jbMognSgmp.jpg", answer: "The Elephant Man", possibleAnswers: ["El Hombre Elefante"] },
    { image: "https://image.tmdb.org/t/p/original/k9pshruhCpJAdH9RaGJO6jaWQ4X.jpg", answer: "The Empire Strikes Back", possibleAnswers: ["El Imperio Contraataca"] },
    { image: "https://image.tmdb.org/t/p/original/8nHYzBDeEPS0hbWYphQplhbTjQ3.jpg", answer: "The Fog", possibleAnswers: ["La Niebla"] },
    { image: "https://image.tmdb.org/t/p/original/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg", answer: "The Shining", possibleAnswers: ["El Resplandor"] },
    { image: "https://image.tmdb.org/t/p/original/nk87CtgZ7wd86W37oJHGYAJbmLz.jpg", answer: "Blow Out", possibleAnswers: ["Impacto"] },
    { image: "https://image.tmdb.org/t/p/original/zGgIlpKE2xP18bhCGsnn79vh80j.jpg", answer: "Das Boot", possibleAnswers: ["El Submarino"] },
    { image: "https://image.tmdb.org/t/p/original/6vNuos23LwWjY1FJuojwPAgo8Ss.jpg", answer: "Escape from New York", possibleAnswers: ["1997: Rescate en Nueva York"] },
    { image: "https://image.tmdb.org/t/p/original/zPACwR32amTNvzId9qyapCWXYDJ.jpg", answer: "Raiders of the Lost Ark", possibleAnswers: ["En Busca del Arca Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/onq6lsJLX8ay5iwxEbKX3qJKeO9.jpg", answer: "The Evil Dead", possibleAnswers: ["Diabólico"] },
    { image: "https://image.tmdb.org/t/p/original/rg4XBpSQqMDiA0YQiSTxoWJYsIL.jpg", answer: "Time for Revenge", possibleAnswers: ["Tiempo de Revancha"] },
    { image: "https://image.tmdb.org/t/p/original/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg", answer: "E.T. the Extra-Terrestrial", possibleAnswers: ["E.T., el Extraterrestre"] },
    { image: "https://image.tmdb.org/t/p/original/8reX3CMog1QHqGoym2Esvuk5MnK.jpg", answer: "Fanny and Alexander", possibleAnswers: ["Fanny y Alexander"] },
    { image: "https://image.tmdb.org/t/p/original/hCxxOJojCUFyuahDx167glJgp7E.jpg", answer: "First Blood", possibleAnswers: ["Rambo: Acorralado"] },
    { image: "https://image.tmdb.org/t/p/original/46iMqI1qzAtnXJxGRNCFwYNYqOo.jpg", answer: "Fitzcarraldo" },
    { image: "https://image.tmdb.org/t/p/original/gum3tuO1zKHBdElSQPS08PJ1w67.jpg", answer: "Gandhi" },
    { image: "https://image.tmdb.org/t/p/original/bvkPno6U02lLyvPWCnmibq4eIaN.jpg", answer: "Poltergeist", possibleAnswers: ["Poltergeist: Fenómenos Extraños"] },
    { image: "https://image.tmdb.org/t/p/original/ljOHSIyTbxdkQFjcJyWKfGm2i2r.jpg", answer: "Rocky III" },
    { image: "https://image.tmdb.org/t/p/original/7Mh1DM4kCMbN93C2MlUavYbH5YM.jpg", answer: "The King of Comedy", possibleAnswers: ["El Rey de la Comedia"] },
    { image: "https://image.tmdb.org/t/p/original/r9leYNa8nTRCceZrZhP1DXkgKVb.jpg", answer: "The Thing", possibleAnswers: ["La Cosa (El Enigma de Otro Mundo)"] },
    { image: "https://image.tmdb.org/t/p/original/ziECpBRIyclmBNaFSWlvCfsKbMD.jpg", answer: "Return of the Jedi", possibleAnswers: ["El Regreso del Jedi"] },
    { image: "https://image.tmdb.org/t/p/original/1qM2BYNE11Viby8ImC9LC00DgDr.jpg", answer: "Scarface", possibleAnswers: ["Caracortada"] },
    { image: "https://image.tmdb.org/t/p/original/rnQyWw68dPHPRtvSWMtLSueXf05.jpg", answer: "Amadeus" },
    { image: "https://image.tmdb.org/t/p/original/rGPoNNk4fvgG2mvkNAxJJPlszOu.jpg", answer: "Blood Simple", possibleAnswers: ["Sangre Fácil"] },
    { image: "https://image.tmdb.org/t/p/original/8L8eulemyt46IBL1PDOtJlJUvNk.jpg", answer: "Camila Jam", possibleAnswers: ["Camila"] },
    { image: "https://image.tmdb.org/t/p/original/3KDHaahgXlUhmpXzoRZrLc7QSBM.jpg", answer: "Ghostbusters", possibleAnswers: ["Los Cazafantasmas"] },
    { image: "https://image.tmdb.org/t/p/original/f133nWlU6yUkZqqwcCXCbTEJWHr.jpg", answer: "Indiana Jones and the Temple of Doom", possibleAnswers: ["Indiana Jones y el Templo Maldito"] },
    { image: "https://image.tmdb.org/t/p/original/xlDUjb0Q5Dv6jPQRF5VE4IMjIy.jpg", answer: "Once Upon a Time in America", possibleAnswers: ["Érase una Vez en América"] },
    { image: "https://image.tmdb.org/t/p/original/fWrq3u16gaBJ6nYNWcR3XaOhQPq.jpg", answer: "Paris, Texas" },
    { image: "https://image.tmdb.org/t/p/original/xRgvH4nm73AwOfwlt0hipHUsKNT.jpg", answer: "Sweet Money", possibleAnswers: ["Plata Dulce"] },
    { image: "https://image.tmdb.org/t/p/original/v8DepuF6gizphLzIyNZeQiB0hij.jpg", answer: "The Karate Kid" },
    { image: "https://image.tmdb.org/t/p/original/ffdqHMWkh1h9MABwIfbfRJhgFW6.jpg", answer: "The Terminator", possibleAnswers: ["El Exterminador del Futuro"] },
    { image: "https://image.tmdb.org/t/p/original/tV2KZZR5JaqTSXiNKowGqQMQtex.jpg", answer: "After Hours", possibleAnswers: ["Después de Hora"] },
    { image: "https://image.tmdb.org/t/p/original/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg", answer: "Back to the Future", possibleAnswers: ["Volver al Futuro"] },
    { image: "https://image.tmdb.org/t/p/original/3ssNAWypRl47iriwBFNx7RUEUub.jpg", answer: "Ran" },
    { image: "https://image.tmdb.org/t/p/original/uiUb4KJ6tadldqlJme49TW1r3jA.jpg", answer: "Rocky IV" },
    { image: "https://image.tmdb.org/t/p/original/kjVgUMsG0PKBXzlP8HGNQpWDxAX.jpg", answer: "The Breakfast Club", possibleAnswers: ["El Club de los Cinco"] },
    { image: "https://image.tmdb.org/t/p/original/lh6MbyxwCribn3hdAo81xLdPGoV.jpg", answer: "The Color Purple", possibleAnswers: ["El Color Púrpura"] },
    { image: "https://image.tmdb.org/t/p/original/qYQmznfMC433HrX5m58MJB0QOlK.jpg", answer: "The Official Story", possibleAnswers: ["La Historia Oficial"] },
    { image: "https://image.tmdb.org/t/p/original/3c9csN2cguE6KwIEcJJ06pQVl5s.jpg", answer: "Waiting for the Hearse", possibleAnswers: ["Esperando la Carroza"] },
    { image: "https://image.tmdb.org/t/p/original/4kix6fAblJIH6eMs0Ku2loyZJXK.jpg", answer: "Aliens", possibleAnswers: ["Aliens: El Regreso"] },
    { image: "https://image.tmdb.org/t/p/original/ehHskGgDUchxGyG33vUQZWNng43.jpg", answer: "Big Trouble in Little China", possibleAnswers: ["Golpe en la Pequeña China"] },
    { image: "https://image.tmdb.org/t/p/original/s1CBwblInR0ZBIv59CSko2QdLD3.jpg", answer: "Blue Velvet", possibleAnswers: ["Terciopelo Azul"] },
    { image: "https://image.tmdb.org/t/p/original/leehjwM57DKJ79XMUll4oAF0kin.jpg", answer: "Ferris Bueller's Day Off", possibleAnswers: ["Todo en Un Día"] },
    { image: "https://image.tmdb.org/t/p/original/vr0gwTvit5pTZs2wXOkvpsxCfli.jpg", answer: "Platoon", possibleAnswers: ["Pelotón"] },
    { image: "https://image.tmdb.org/t/p/original/hhCp6ZLDjS5wUHkGg7k3VGvH3Xm.jpg", answer: "The Color of Money", possibleAnswers: ["El Color del Dinero"] },
    { image: "https://image.tmdb.org/t/p/original/aQwxkvskonfPByfj5PTriJuyFXr.jpg", answer: "The Fly", possibleAnswers: ["La Mosca"] },
    { image: "https://image.tmdb.org/t/p/original/6iDQCBUSZKzY8Rnu8ECwl2gXcfG.jpg", answer: "Dirty Dancing", possibleAnswers: ["Dirty Dancing (Baile Caliente)"] },
    { image: "https://image.tmdb.org/t/p/original/dOvEJK2u0slAGTfhdZOjnNgCQet.jpg", answer: "Evil Dead II", possibleAnswers: ["Terroríficamente Muertos"] },
    { image: "https://image.tmdb.org/t/p/original/3k2TRmqMjgt7tcwkYwZQdctnty3.jpg", answer: "Full Metal Jacket", possibleAnswers: ["Nacido para Matar"] },
    { image: "https://image.tmdb.org/t/p/original/oAA0nLghMmlvUH1uPiS7HVcCpnc.jpg", answer: "Lethal Weapon", possibleAnswers: ["Arma Mortal"] },
    { image: "https://image.tmdb.org/t/p/original/oSFshBf9Wrv5UcmZYAmy28BwSSh.jpg", answer: "Raising Arizona", possibleAnswers: ["Arizona Baby"] },
    { image: "https://image.tmdb.org/t/p/original/xACuC5FwpCdayrcCsJPxYzrl8BO.jpg", answer: "RoboCop" },
    { image: "https://image.tmdb.org/t/p/original/k29qVmwWwR0i5A1UMIws1Vmv6hV.jpg", answer: "The Last Emperor", possibleAnswers: ["El Último Emperador"] },
    { image: "https://image.tmdb.org/t/p/original/2CisgvF2HcIVnbMZbSjASCtSgEb.jpg", answer: "The Princess Bride", possibleAnswers: ["La Princesa Prometida"] },
    { image: "https://image.tmdb.org/t/p/original/i1oWUGVDNBhGBykcCRBlX326udb.jpg", answer: "The Untouchables", possibleAnswers: ["Los Intocables"] },
    { image: "https://image.tmdb.org/t/p/original/7TlGXrB4WQ3wbpOCUQnBXseCuOl.jpg", answer: "Wings of Desire", possibleAnswers: ["El Cielo Sobre Berlín"] },
    { image: "https://image.tmdb.org/t/p/original/aSA7RuKmCQBnYKn70GYPi6ckgoY.jpg", answer: "Bloodsport", possibleAnswers: ["Contacto Sangriento"] },
    { image: "https://image.tmdb.org/t/p/original/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg", answer: "Cinema Paradiso" },
    { image: "https://image.tmdb.org/t/p/original/bvk2AAH64lP2YZs02Q3jskfHT8j.jpg", answer: "Die Hard", possibleAnswers: ["Duro de Matar"] },
    { image: "https://image.tmdb.org/t/p/original/b3tos7Tsd6lsTe52Nn4TMrEQg65.jpg", answer: "Rain Man" },
    { image: "https://image.tmdb.org/t/p/original/rBqdcQeM1h05YjF9rFtPWnNaDO2.jpg", answer: "The Last Temptation of Christ", possibleAnswers: ["La Última Tentación de Cristo"] },
    { image: "https://image.tmdb.org/t/p/original/1wi1hcbl6KYqARjdQ4qrBWZdiau.jpg", answer: "The Naked Gun", possibleAnswers: ["La Pistola Desnuda"] },
    { image: "https://image.tmdb.org/t/p/original/udIE8Cdon9wnYmVIOFYrBPfA2Mq.jpg", answer: "Who Framed Roger Rabbit", possibleAnswers: ["¿Quién Engañó a Roger Rabbit?"] },
    { image: "https://image.tmdb.org/t/p/original/w6tPctxWAsHoQXeKxxNOT6lYKpx.jpg", answer: "Back to the Future Part II", possibleAnswers: ["Volver al Futuro Parte II"] },
    { image: "https://image.tmdb.org/t/p/original/y9QjSsIH4vBIIqGmAFT1zJzsqPh.jpg", answer: "Born on the Fourth of July", possibleAnswers: ["Nacido el Cuatro de Julio"] },
    { image: "https://image.tmdb.org/t/p/original/lFIXZpwwlF9hg8NM3RazaIJDuaj.jpg", answer: "Dead Poets Society", possibleAnswers: ["La Sociedad de los Poetas Muertos"] },
    { image: "https://image.tmdb.org/t/p/original/12fvZHskx57kQfNEUXJ3v0flWYQ.jpg", answer: "Indiana Jones and the Last Crusade", possibleAnswers: ["Indiana Jones y la Última Cruzada"] },
    { image: "https://image.tmdb.org/t/p/original/mW6XzxelLY8T2oW2NjciG9LpZT5.jpg", answer: "The Abyss", possibleAnswers: ["El Abismo"] },
    { image: "https://image.tmdb.org/t/p/original/i8aIbji5vcPoHwcLBZYQSniGkAI.jpg", answer: "When Harry Met Sally...", possibleAnswers: ["Cuando Harry Conoció a Sally"] },
    { image: "https://image.tmdb.org/t/p/original/AtF7TESJEMmImBRUj9Z7HmW2ZH0.jpg", answer: "Back to the Future Part III", possibleAnswers: ["Volver al Futuro Parte III"] },
    { image: "https://image.tmdb.org/t/p/original/uNLIMPxknsV4n3IAEDpS1iqF5dm.jpg", answer: "Edward Scissorhands", possibleAnswers: ["El Joven Manos de Tijera"] },
    { image: "https://image.tmdb.org/t/p/original/6nLdSON3ErniBZTXWG7WRqs5jGz.jpg", answer: "Ghost", possibleAnswers: ["Ghost: La Sombra del Amor"] },
    { image: "https://image.tmdb.org/t/p/original/gILte6Zd7m1YneIr6MVhh30S9pr.jpg", answer: "GoodFellas", possibleAnswers: ["Buenos Muchachos"] },
    { image: "https://image.tmdb.org/t/p/original/sGEqHTylawwS6hwKultk1mKUjdB.jpg", answer: "Pretty Woman" },
    { image: "https://image.tmdb.org/t/p/original/zNnjHLDtV8Ti3aworltaeaLMov4.jpg", answer: "The Godfather Part III", possibleAnswers: ["El Padrino, Parte III"] },
    { image: "https://image.tmdb.org/t/p/original/x2wOlXuK4NzPDQ0OBZiJjNNOp6Y.jpg", answer: "Total Recall", possibleAnswers: ["El Vengador del Futuro"] },
    { image: "https://image.tmdb.org/t/p/original/6xJ2odkMFmO2LptVUBR8t8wBldQ.jpg", answer: "Wild at Heart", possibleAnswers: ["Corazón Salvaje"] },
    { image: "https://image.tmdb.org/t/p/original/i1yf91svRHX45l9BXL8rVFzLoPH.jpg", answer: "Jaws", possibleAnswers: ["Tiburon"] },
    { image: "https://image.tmdb.org/t/p/original/xcjJ5khg2yzOa282mza39Lbrm7j.jpg", answer: "The Exorcist", possibleAnswers: ["El exorcista"] },
    { image: "https://image.tmdb.org/t/p/original/qr7dUqleMRd0VgollazbmyP9XjI.jpg", answer: "Blade Runner" },
    { image: "https://image.tmdb.org/t/p/original/3KDHaahgXlUhmpXzoRZrLc7QSBM.jpg", answer: "Ghostbusters" },
    { image: "https://image.tmdb.org/t/p/original/kF8ljC7Y4p1UsmKBi2LxelZpqw.jpg", answer: "Beetlejuice Beetlejuice" },
    { image: "https://image.tmdb.org/t/p/original/8n9dYsTbXTykzm2Nuy7R2ftapXQ.jpg", answer: "Annie Hall" },
    { image: "https://image.tmdb.org/t/p/original/adnSTomHU9YyqV2lx38CgM0UxLS.jpg", answer: "Manhattan" },
    { image: "https://image.tmdb.org/t/p/original/m10uqk0HI5JcITAbxNJIIiGA8HP.jpg", answer: "Dog Day Afternoon", possibleAnswers: ["Tarde de Perros"] },
    { image: "https://image.tmdb.org/t/p/original/9pUh1fC8TqVtYPeKpdfNyVK0qnn.jpg", answer: "Kramer vs. Kramer", possibleAnswers: ["Kramer contra Kramer"] },
    { image: "https://image.tmdb.org/t/p/original/2SRJMIoJzABzgyGw01U6VbQbvJD.jpg", answer: "Grease" },
    { image: "https://image.tmdb.org/t/p/original/yjGllQUm28R4X9xD9T5xMszirgw.jpg", answer: "Stand by Me", possibleAnswers: ["Cuenta Conmigo"] },
    { image: "https://image.tmdb.org/t/p/original/5UX6M0aEphiW6Xmy5rpYX75glbo.jpg", answer: "Gremlins" },
];
