import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const peliculas1990a2009: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/cW1XlxgvxZIFkakYc9yrLpDoYhK.jpg", answer: "Barton Fink" },
    { image: "https://image.tmdb.org/t/p/original/ntgpger7OwFNlEldxuvvFHDKzjW.jpg", answer: "Cape Fear" },
    { image: "https://image.tmdb.org/t/p/original/77gjiDyD94aJfqZq6AJAcMLxZhd.jpg", answer: "JFK" },
    { image: "https://image.tmdb.org/t/p/original/izkMjmhauFx9DjoBQqM5sM5WAwE.jpg", answer: "Terminator 2: Judgment Day", possibleAnswers: ["Terminator 2: El Juicio Final"] },
    { image: "https://image.tmdb.org/t/p/original/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg", answer: "The Silence of the Lambs", possibleAnswers: ["El Silencio de los Inocentes"] },
    { image: "https://image.tmdb.org/t/p/original/eA15zhxnhQSg4k5MUbbTERIU23Z.jpg", answer: "Thelma & Louise" },
    { image: "https://image.tmdb.org/t/p/original/7x4SNxO5HWArighxxFeet5sn3il.jpg", answer: "Batman Returns", possibleAnswers: ["Batman Vuelve"] },
    { image: "https://image.tmdb.org/t/p/original/88S6EYQBVyQktDfSqsB33I169jN.jpg", answer: "Bram Stoker's Dracula", possibleAnswers: ["Drácula, de Bram Stoker"] },
    { image: "https://image.tmdb.org/t/p/original/l0JgqFNxeMb1OoHq1CzdYC3Y5J8.jpg", answer: "Candyman" },
    { image: "https://image.tmdb.org/t/p/original/jwt159hXWA9Q5xpBo8hWb3zwLi7.jpg", answer: "Reservoir Dogs", possibleAnswers: ["Perros de Reserva"] },
    { image: "https://image.tmdb.org/t/p/original/mhpDSuNyHPMsccI7zISEaskTgOQ.jpg", answer: "The Last of the Mohicans", possibleAnswers: ["El Último Mohicano"] },
    { image: "https://image.tmdb.org/t/p/original/rvRGFevvZK48onX0PYI1eQLbuJd.jpg", answer: "Unforgiven", possibleAnswers: ["Los Imperdonables"] },
    { image: "https://image.tmdb.org/t/p/original/9s4ZDw0j6qByLgwJtUsRcepBXSw.jpg", answer: "Carlito's Way", possibleAnswers: ["Atrapado por su Pasado"] },
    { image: "https://image.tmdb.org/t/p/original/4W6RYDNe4OByNryOCvJprrutm9h.jpg", answer: "Groundhog Day", possibleAnswers: ["Hechizo del Tiempo"] },
    { image: "https://image.tmdb.org/t/p/original/o7LzVmlOSYc3EspyVMC9bsTTARc.jpg", answer: "Jurassic Park", possibleAnswers: ["Parque Jurásico"] },
    { image: "https://image.tmdb.org/t/p/original/f9X91dUckoRzOZlw4XBUOfkN9FC.jpg", answer: "Mrs. Doubtfire", possibleAnswers: ["Papá por Siempre"] },
    { image: "https://image.tmdb.org/t/p/original/nWO4sGqH950N2fij8X0Pwumqe9k.jpg", answer: "Philadelphia" },
    { image: "https://image.tmdb.org/t/p/original/zb6fM1CX41D9rF9hdgclu0peUmy.jpg", answer: "Schindler's List", possibleAnswers: ["La Lista de Schindler"] },
    { image: "https://image.tmdb.org/t/p/original/nAyUVvcdOKHmukdgGHZ7xR5er1q.jpg", answer: "Three Colors: Blue", possibleAnswers: ["Tres Colores: Azul"] },
    { image: "https://image.tmdb.org/t/p/original/1Uh8yuXlFcMDpVHWZJidjanT06e.jpg", answer: "True Romance", possibleAnswers: ["Amor a Quemarropa"] },
    { image: "https://image.tmdb.org/t/p/original/nbvREKIjX16mwNZtFqAoQTTHPnQ.jpg", answer: "Ace Ventura: Pet Detective", possibleAnswers: ["Ace Ventura: Detective de Mascotas"] },
    { image: "https://image.tmdb.org/t/p/original/vuglA60RqvpHK9rIcG8sXaiWw1L.jpg", answer: "Chungking Express" },
    { image: "https://image.tmdb.org/t/p/original/8uBTDGRcNHhYChcoazP5rleRME7.jpg", answer: "Dumb and Dumber", possibleAnswers: ["Tonto y Retonto"] },
    { image: "https://image.tmdb.org/t/p/original/3jrwJiMCe7VZP0DNcywHYOKg0Zu.jpg", answer: "Ed Wood" },
    { image: "https://image.tmdb.org/t/p/original/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg", answer: "Forrest Gump" },
    { image: "https://image.tmdb.org/t/p/original/fj0hwDJEOOHllRim2BMt5L7tbjf.jpg", answer: "Léon: The Professional", possibleAnswers: ["El Perfecto Asesino"] },
    { image: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", answer: "Pulp Fiction", possibleAnswers: ["Tiempos Violentos"] },
    { image: "https://image.tmdb.org/t/p/original/bQlw59HncOXX9alFlOYKHAvSnm.jpg", answer: "The Mask", possibleAnswers: ["La Máscara"] },
    { image: "https://image.tmdb.org/t/p/original/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg", answer: "The Shawshank Redemption", possibleAnswers: ["Sueño de Fuga"] },
    { image: "https://image.tmdb.org/t/p/original/pZcoSJUb3Lgr9Rzg2shg1PtTBP9.jpg", answer: "Three Colors: Red", possibleAnswers: ["Tres Colores: Rojo"] },
    { image: "https://image.tmdb.org/t/p/original/b1CVjSYinzm6tx1TGA7c75W8X9k.jpg", answer: "Three Colors: White", possibleAnswers: ["Tres Colores: Blanco"] },
    { image: "https://image.tmdb.org/t/p/original/jRZ3joUcg8YDCQYl4Tog5xhY6wk.jpg", answer: "True Lies", possibleAnswers: ["Mentiras Verdaderas"] },
    { image: "https://image.tmdb.org/t/p/original/iZGiMD0p1M2AOmzKknFo5bkuz94.jpg", answer: "Casino" },
    { image: "https://image.tmdb.org/t/p/original/xKsnZDERG1dk95wuZ5q9iks3OL3.jpg", answer: "Heat" },
    { image: "https://image.tmdb.org/t/p/original/viGCwLxupyoaLsa6hrnu1gYrB0B.jpg", answer: "La Haine", possibleAnswers: ["El Odio"] },
    { image: "https://image.tmdb.org/t/p/original/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg", answer: "Se7en", possibleAnswers: ["Seven: Los Siete Pecados Capitales"] },
    { image: "https://image.tmdb.org/t/p/original/4TnGcUsyd6ixuLWHaaEG5BGkAIp.jpg", answer: "The Bridges of Madison County", possibleAnswers: ["Los Puentes de Madison"] },
    { image: "https://image.tmdb.org/t/p/original/hy0Hx9fMPk2fmw26Li60z1S2giU.jpg", answer: "The Usual Suspects", possibleAnswers: ["Los Sospechosos de Siempre"] },
    { image: "https://image.tmdb.org/t/p/original/747dgDfL5d8esobk7h4odaOFhUq.jpg", answer: "Fargo" },
    { image: "https://image.tmdb.org/t/p/original/4rt35cuyJ3CwpZgeIdXm5fmCinx.jpg", answer: "Hard Eight" },
    { image: "https://image.tmdb.org/t/p/original/sra8XnL96OyLHENcglmZJg6HA8z.jpg", answer: "Mission: Impossible", possibleAnswers: ["Misión: Imposible"] },
    { image: "https://image.tmdb.org/t/p/original/vh7np635kDIcfO6x2Y9ElgLJsuI.jpg", answer: "Scream", possibleAnswers: ["Scream: Vigila Quién Llama"] },
    { image: "https://image.tmdb.org/t/p/original/AmTrqk910ot3aYLBGyIG78Xfa18.jpg", answer: "Amistad" },
    { image: "https://image.tmdb.org/t/p/original/ArpTzQZHWh4UVsgUvV6S7WjTq1n.jpg", answer: "Boogie Nights" },
    { image: "https://image.tmdb.org/t/p/original/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg", answer: "Contact" },
    { image: "https://image.tmdb.org/t/p/original/hPsCR1ny6GnctJkWqeJwihTDD7T.jpg", answer: "Gattaca" },
    { image: "https://image.tmdb.org/t/p/original/xj1Sv1xm4Y0ydBueGuf10Y9qM0O.jpg", answer: "Good Will Hunting", possibleAnswers: ["En Busca del Destino"] },
    { image: "https://image.tmdb.org/t/p/original/gvaeY5kz3wHrMU6xLdnybziwYXw.jpg", answer: "Jackie Brown" },
    { image: "https://image.tmdb.org/t/p/original/hUn13Hom8OWMYpR1ay0diwswwdP.jpg", answer: "L.A. Confidential", possibleAnswers: ["Los Ángeles al Desnudo"] },
    { image: "https://image.tmdb.org/t/p/original/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg", answer: "Life Is Beautiful", possibleAnswers: ["La Vida es Bella"] },
    { image: "https://image.tmdb.org/t/p/original/5v3Iubz9lkZwMEG17j0RHPLcwvx.jpg", answer: "Lost Highway", possibleAnswers: ["Carretera Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg", answer: "Titanic" },
    { image: "https://image.tmdb.org/t/p/original/sWi4SSeVPii4NU365Df9vzX1yOX.jpg", answer: "Dark City", possibleAnswers: ["Ciudad en Tinieblas"] },
    { image: "https://image.tmdb.org/t/p/original/lPLTLCBn39Wiy1RPQLB9xOKyF2v.jpg", answer: "Enemy of the State", possibleAnswers: ["Enemigo del Estado"] },
    { image: "https://image.tmdb.org/t/p/original/9FrpAtF87VKblKkDEiIZzYgO40K.jpg", answer: "Rush Hour", possibleAnswers: ["Una Pareja Explosiva"] },
    { image: "https://image.tmdb.org/t/p/original/bdD39MpSVhKjxarTxLSfX6baoMP.jpg", answer: "Saving Private Ryan", possibleAnswers: ["Rescatando al Soldado Ryan"] },
    { image: "https://image.tmdb.org/t/p/original/hXsy4XCCHrUk81XoRhcooyWejao.jpg", answer: "The Big Lebowski", possibleAnswers: ["El Gran Lebowski"] },
    { image: "https://image.tmdb.org/t/p/original/aCHn2TXYJfzPXQKA6r9mKPbMlUB.jpg", answer: "The Truman Show", possibleAnswers: ["El Show de Truman"] },
    { image: "https://image.tmdb.org/t/p/original/2ndw55F40IkALzWyjCCza3M6nqM.jpg", answer: "American Beauty" },
    { image: "https://image.tmdb.org/t/p/original/aCBbGxcbWgUJxmIiv5JDC7p5vmN.jpg", answer: "Bringing Out the Dead", possibleAnswers: ["Vidas al Límite"] },
    { image: "https://image.tmdb.org/t/p/original/aC6wW62V6b0csr5iUnbOjYAqfhg.jpg", answer: "Eyes Wide Shut" },
    { image: "https://image.tmdb.org/t/p/original/c6OLXfKAk5BKeR6broC8pYiCquX.jpg", answer: "Fight Club", possibleAnswers: ["El Club de la Pelea"] },
    { image: "https://image.tmdb.org/t/p/original/mFfyE5DPFDqoes4HIcElHc2a15y.jpg", answer: "Magnolia" },
    { image: "https://image.tmdb.org/t/p/original/enTZhfxAdgOCdFdbj52MR3F10yC.jpg", answer: "Notting Hill" },
    { image: "https://image.tmdb.org/t/p/original/m8t7K3LcAY7bpyQ7iQ5kGsrcjnh.jpg", answer: "Sleepy Hollow", possibleAnswers: ["La Leyenda del Jinete sin Cabeza"] },
    { image: "https://image.tmdb.org/t/p/original/3TeGmKJfkik1D1rIoqGb1aR4k9c.jpg", answer: "Star Wars: Episode I - The Phantom Menace", possibleAnswers: ["Star Wars: Episodio I - La Amenaza Fantasma"] },
    { image: "https://image.tmdb.org/t/p/original/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg", answer: "The Green Mile", possibleAnswers: ["Milagros Inesperados"] },
    { image: "https://image.tmdb.org/t/p/original/2GIr0LArTvO33HQVPEdp49FLdNV.jpg", answer: "The Insider", possibleAnswers: ["El Dilema"] },
    { image: "https://image.tmdb.org/t/p/original/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg", answer: "The Matrix", possibleAnswers: ["Matrix"] },
    { image: "https://image.tmdb.org/t/p/original/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg", answer: "The Sixth Sense", possibleAnswers: ["El Sexto Sentido"] },
    { image: "https://image.tmdb.org/t/p/original/1S81PpyGwS8eVx4W75uSKzMw4B0.jpg", answer: "The Straight Story", possibleAnswers: ["Una Historia Verdadera"] },
    { image: "https://image.tmdb.org/t/p/original/oCFVYPXI4IfhtF3GapU2jkDicDI.jpg", answer: "Cast Away", possibleAnswers: ["Náufrago"] },
    { image: "https://image.tmdb.org/t/p/original/jhk6D8pim3yaByu1801kMoxXFaX.jpg", answer: "Gladiator", possibleAnswers: ["Gladiador"] },
    { image: "https://image.tmdb.org/t/p/original/ffQFnAUm2Uu4RU0nijpjPRf9TBT.jpg", answer: "In the Mood for Love", possibleAnswers: ["Deseando Amar"] },
    { image: "https://image.tmdb.org/t/p/original/24DZfupDlhXeTchmcOkoGRhP5Vg.jpg", answer: "Mission: Impossible II", possibleAnswers: ["Misión: Imposible II"] },
    { image: "https://image.tmdb.org/t/p/original/e4tZvefBtA6P1T0vAPfeXG4Bj3r.jpg", answer: "Nine Queens", possibleAnswers: ["Nueve Reinas"] },
    { image: "https://image.tmdb.org/t/p/original/n7p6UTAZtkeoHkwCO42BEQaMFJY.jpg", answer: "A.I. Artificial Intelligence", possibleAnswers: ["Inteligencia Artificial"] },
    { image: "https://image.tmdb.org/t/p/original/g9ClaS5EqU0Hk8WIbMNhld0Bk6f.jpg", answer: "Mulholland Drive" },
    { image: "https://image.tmdb.org/t/p/original/kPRHoq1g68O5qawcnrB1c4LeO4I.jpg", answer: "Son of the Bride", possibleAnswers: ["El Hijo de la Novia"] },
    { image: "https://image.tmdb.org/t/p/original/mWDdRXTivGE7aaY2vo1Ie0PfCX5.jpg", answer: "The Lord of the Rings: The Fellowship of the Ring", possibleAnswers: ["El Señor de los Anillos: La Comunidad del Anillo"] },
    { image: "https://image.tmdb.org/t/p/original/cbuX448RKetr5Y5cZkmJEfu3xji.jpg", answer: "The Royal Tenenbaums", possibleAnswers: ["Los Excéntricos Tenenbaums"] },
    { image: "https://image.tmdb.org/t/p/original/7aW9IZjpsoTXYEARlnOvTtl6EBr.jpg", answer: "Y Tu Mamá También" },
    { image: "https://image.tmdb.org/t/p/original/aJFwk1clMal1prxAvKAgHxKPAf.jpg", answer: "28 Days Later", possibleAnswers: ["Exterminio"] },
    { image: "https://image.tmdb.org/t/p/original/ggC3Brchf4RqPitEh7cROFoeAWn.jpg", answer: "Catch Me If You Can", possibleAnswers: ["Atrápame Si Puedes"] },
    { image: "https://image.tmdb.org/t/p/original/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg", answer: "City of God", possibleAnswers: ["Ciudad de Dios"] },
    { image: "https://image.tmdb.org/t/p/original/p8yXQse3IDZiwEjWRHda3EzDQjA.jpg", answer: "Gangs of New York", possibleAnswers: ["Pandillas de Nueva York"] },
    { image: "https://image.tmdb.org/t/p/original/jU8MC5uSgBkZXyZYGtZgMsMsfeN.jpg", answer: "Insomnia" },
    { image: "https://image.tmdb.org/t/p/original/xV1EfNSEg6id6juJPr1vM6p9x5X.jpg", answer: "Irreversible" },
    { image: "https://image.tmdb.org/t/p/original/PrMb3oeEluauy0q9ZO5xL33A6C.jpg", answer: "Minority Report", possibleAnswers: ["Sentencia Previa"] },
    { image: "https://image.tmdb.org/t/p/original/zQ8AxTPiCiS5nnwXpwTBPBHSaa5.jpg", answer: "Spider-Man", possibleAnswers: ["El Hombre Araña"] },
    { image: "https://image.tmdb.org/t/p/original/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg", answer: "The Lord of the Rings: The Two Towers", possibleAnswers: ["El Señor de los Anillos: Las Dos Torres"] },
    { image: "https://image.tmdb.org/t/p/original/c0fB9xk7D1aVb3Bg2rk2SVJcGn.jpg", answer: "The Pianist", possibleAnswers: ["El Pianista"] },
    { image: "https://image.tmdb.org/t/p/original/r3xsFBD1VTUusk393bBc7SsDUJe.jpg", answer: "Dogville" },
    { image: "https://image.tmdb.org/t/p/original/iffzIhuLAO38Po6sh1s6ZEVwlNL.jpg", answer: "Kill Bill: Vol. 1" },
    { image: "https://image.tmdb.org/t/p/original/6ITVHoipvxAS8luzKtHTbPaHLtT.jpg", answer: "Lost in Translation", possibleAnswers: ["Perdidos en Tokio"] },
    { image: "https://image.tmdb.org/t/p/original/zMHyNxNt4zhL939XX8QLBW3gWfu.jpg", answer: "Master and Commander: The Far Side of the World", possibleAnswers: ["Master and Commander: Al Otro Lado del Mundo"] },
    { image: "https://image.tmdb.org/t/p/original/6Kn6qW3an3DkPl3MahWemTzrjCt.jpg", answer: "Memories of Murder", possibleAnswers: ["Recuerdos de un Asesino"] },
    { image: "https://image.tmdb.org/t/p/original/sdwjQEM869JFwMytTmvr6ggvaUl.jpg", answer: "Oldboy" },
    { image: "https://image.tmdb.org/t/p/original/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg", answer: "The Lord of the Rings: The Return of the King", possibleAnswers: ["El Señor de los Anillos: El Retorno del Rey"] },
    { image: "https://image.tmdb.org/t/p/original/ihOJcrorpDQtHTzIOrobbOhpJsj.jpg", answer: "The Matrix Reloaded", possibleAnswers: ["Matrix Recargado"] },
    { image: "https://image.tmdb.org/t/p/original/kJYPag1YrA4PsXIftFdq3QEaanV.jpg", answer: "The Matrix Revolutions", possibleAnswers: ["Matrix Revoluciones"] },
    { image: "https://image.tmdb.org/t/p/original/qVzmXKKOTtd3szkiCheCNrfa394.jpg", answer: "Collateral" },
    { image: "https://image.tmdb.org/t/p/original/cmyrTgVrfsQNlQG4o6m7E5HoP0L.jpg", answer: "Downfall", possibleAnswers: ["El Hundimiento"] },
    { image: "https://image.tmdb.org/t/p/original/W1ffLQGHoxfAOq0ZYdPtJlvAdb.jpg", answer: "Eternal Sunshine of the Spotless Mind", possibleAnswers: ["Eterno Resplandor de una Mente sin Recuerdos"] },
    { image: "https://image.tmdb.org/t/p/original/pgG6tzJzC8mjGqhaT8IWwEk00xf.jpg", answer: "Kill Bill: Vol. 2" },
    { image: "https://image.tmdb.org/t/p/original/nP3y0TkR6XniFs9J53qQkg4Bnnk.jpg", answer: "Mean Girls", possibleAnswers: ["Chicas Pesadas"] },
    { image: "https://image.tmdb.org/t/p/original/oGMomeS7bE43eN8SGJUaKvQnmud.jpg", answer: "Million Dollar Baby" },
    { image: "https://image.tmdb.org/t/p/original/umtxTkop7Ec9UFynjB7Z53lmkX1.jpg", answer: "Ray" },
    { image: "https://image.tmdb.org/t/p/original/ok4ot3YbfDYZcINXf91JUfq3maB.jpg", answer: "Saw", possibleAnswers: ["El Juego del Miedo"] },
    { image: "https://image.tmdb.org/t/p/original/wb34q3VgzHgL8frVMywrN3wXmqx.jpg", answer: "Shaun of the Dead", possibleAnswers: ["Muertos de Risa"] },
    { image: "https://image.tmdb.org/t/p/original/6KLKdhk9wZvJ6OcTzDCoxup0Kmh.jpg", answer: "The Aviator", possibleAnswers: ["El Aviador"] },
    { image: "https://image.tmdb.org/t/p/original/zywtNiaZ9r7azrcNdl2j0jOgrkw.jpg", answer: "The Terminal", possibleAnswers: ["La Terminal"] },
    { image: "https://image.tmdb.org/t/p/original/y51M7Ca95sCXTCDvJaRP1uzxKbg.jpg", answer: "Troy", possibleAnswers: ["Troya"] },
    { image: "https://image.tmdb.org/t/p/original/9IIBboV7MCT0bTxzXHmWK1Hq558.jpg", answer: "Batman Begins", possibleAnswers: ["Batman Inicia"] },
    { image: "https://image.tmdb.org/t/p/original/8itHQecANtOevcCdr3AhVxFCYkw.jpg", answer: "Kingdom of Heaven", possibleAnswers: ["El Reino de los Cielos"] },
    { image: "https://image.tmdb.org/t/p/original/titl6uMe5u974sLAA2Zy1kFi4sC.jpg", answer: "Munich", possibleAnswers: ["Múnich"] },
    { image: "https://image.tmdb.org/t/p/original/pMBKzEotLUzk3NuQiyVjZEDlH70.jpg", answer: "Walk the Line", possibleAnswers: ["En la Cuerda Floja"] },
    { image: "https://image.tmdb.org/t/p/original/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg", answer: "War of the Worlds", possibleAnswers: ["La Guerra de los Mundos"] },
    { image: "https://image.tmdb.org/t/p/original/lgBZlJ1LHQel5nneNQMoesmvc7l.jpg", answer: "300" },
    { image: "https://image.tmdb.org/t/p/original/klJMCIblHLFwCuGjKz7tyOpekIC.jpg", answer: "Casino Royale" },
    { image: "https://image.tmdb.org/t/p/original/gFGLwUBhVrq0bq4j9DU08xQDRU2.jpg", answer: "Children of Men", possibleAnswers: ["Hijos del Hombre"] },
    { image: "https://image.tmdb.org/t/p/original/qyePa65qZVnuYWivTBXkHV9aI3A.jpg", answer: "Inland Empire" },
    { image: "https://image.tmdb.org/t/p/original/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg", answer: "Pan's Labyrinth", possibleAnswers: ["El Laberinto del Fauno"] },
    { image: "https://image.tmdb.org/t/p/original/6WRrGYalXXveItfpnipYdayFkQB.jpg", answer: "The Departed", possibleAnswers: ["Los Infiltrados"] },
    { image: "https://image.tmdb.org/t/p/original/g11nKgir3nIhlG2gIDWIvJeR4fz.jpg", answer: "The Lives of Others", possibleAnswers: ["La Vida de los Otros"] },
    { image: "https://image.tmdb.org/t/p/original/z3br1ub7spqGMkxgjgJSdM4DC21.jpg", answer: "The Prestige", possibleAnswers: ["El Gran Truco"] },
    { image: "https://image.tmdb.org/t/p/original/5jhG1lTgV0MS6tDkBMQSSitttTT.jpg", answer: "The Pursuit of Happyness", possibleAnswers: ["En Busca de la Felicidad"] },
    { image: "https://image.tmdb.org/t/p/original/83ownpZPvBHJD5UVNShzQfa3LaW.jpg", answer: "28 Weeks Later", possibleAnswers: ["Exterminio 2"] },
    { image: "https://image.tmdb.org/t/p/original/qbVCChwbGWDAgsCXKZxyjBrRiWx.jpg", answer: "Death Proof", possibleAnswers: ["A Prueba de Muerte"] },
    { image: "https://image.tmdb.org/t/p/original/ePgD1cwmklyrFBjl6z96IuixuSY.jpg", answer: "I Am Legend", possibleAnswers: ["Soy Leyenda"] },
    { image: "https://image.tmdb.org/t/p/original/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg", answer: "No Country for Old Men", possibleAnswers: ["Sin Lugar para los Débiles"] },
    { image: "https://image.tmdb.org/t/p/original/w1oD1MzHjnBJc5snKupIQaSBLIh.jpg", answer: "Spider-Man 3", possibleAnswers: ["El Hombre Araña 3"] },
    { image: "https://image.tmdb.org/t/p/original/hKJ513GbmTSmTXJU1uCXclh5Wkh.jpg", answer: "The Darjeeling Limited", possibleAnswers: ["Viaje a Darjeeling"] },
    { image: "https://image.tmdb.org/t/p/original/9UAKA6ceZi6TgQwTAAMt7DWwYPI.jpg", answer: "There Will Be Blood", possibleAnswers: ["Pozos de Ambición"] },
    { image: "https://image.tmdb.org/t/p/original/3zCPI4JFc54xvLaJ71oI2KoP3az.jpg", answer: "Zodiac" },
    { image: "https://image.tmdb.org/t/p/original/dGaV9hfxztBIaCs0MsMlamRw9hC.jpg", answer: "Burn After Reading", possibleAnswers: ["Quemar Después de Leer"] },
    { image: "https://image.tmdb.org/t/p/original/cyecB7godJ6kNHGONFjUyVN9OX5.jpg", answer: "Iron Man" },
    { image: "https://image.tmdb.org/t/p/original/2fswjyrY3GEzeoVn6mF8pNeNcgf.jpg", answer: "The Curious Case of Benjamin Button", possibleAnswers: ["El Curioso Caso de Benjamin Button"] },
    { image: "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg", answer: "The Dark Knight", possibleAnswers: ["Batman: El Caballero de la Noche"] },
    { image: "https://image.tmdb.org/t/p/original/wcJmFsz8RqIhozMwvU81hreTX4i.jpg", answer: "The Wrestler", possibleAnswers: ["El Luchador"] },
    { image: "https://image.tmdb.org/t/p/original/6j3YrwkG4TZo8oNR4U4SDpql4pP.jpg", answer: "A Serious Man", possibleAnswers: ["Un Hombre Serio"] },
    { image: "https://image.tmdb.org/t/p/original/utABPVjXBlM8NUOBecCyLLuzQSe.jpg", answer: "Antichrist", possibleAnswers: ["Anticristo"] },
    { image: "https://image.tmdb.org/t/p/original/jhM3wgWUrrOkz9r4xwV5cV5RhI4.jpg", answer: "District 9", possibleAnswers: ["Distrito 9"] },
    { image: "https://image.tmdb.org/t/p/original/2Mlw0JRNZHXLYxbeJ0LmiCCTiok.jpg", answer: "Enter the Void" },
    { image: "https://image.tmdb.org/t/p/original/hwNtEmmugU5Yd7hpfprNWI0DGIn.jpg", answer: "Inglourious Basterds", possibleAnswers: ["Bastardos sin Gloria"] },
    { image: "https://image.tmdb.org/t/p/original/85g84VtSf9tu1A9JqqruXEHspb7.jpg", answer: "Sherlock Holmes" },
    { image: "https://image.tmdb.org/t/p/original/fNHCogWhABNAmzk0IFdzQP5XLYj.jpg", answer: "The Secret in Their Eyes", possibleAnswers: ["El Secreto de Sus Ojos"] },
    { image: "https://image.tmdb.org/t/p/original/ih2xVgeMS8R5WUetYE8Mr9hVTlB.jpg", answer: "Home Alone", possibleAnswers: ["Mi Pobre Angelito"] },
    { image: "https://image.tmdb.org/t/p/original/H40nWdJngUc6gtytMAbElm9HOu.jpg", answer: "A Few Good Men", possibleAnswers: ["Cuestión de Honor"] },
    { image: "https://image.tmdb.org/t/p/original/uw4SnKFZ453Gxmj5XR5Susj8TNo.jpg", answer: "Independence Day" },
    { image: "https://image.tmdb.org/t/p/original/o9puyKpayQoX8ikIaYtf2PfKv3.jpg", answer: "Men in Black", possibleAnswers: ["Hombres de Negro"] },
    { image: "https://image.tmdb.org/t/p/original/z9DFGaWj4G4kZUWLZ6ESs1NP1Fp.jpg", answer: "American Pie" },
    { image: "https://image.tmdb.org/t/p/original/1JnemtgRmn3vcVE4GEzUkJVuL8B.jpg", answer: "The Blair Witch Project", possibleAnswers: ["El Proyecto de la Bruja de Blair"] },
    { image: "https://image.tmdb.org/t/p/original/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg", answer: "Memento" },
    { image: "https://image.tmdb.org/t/p/original/fAGYRJCujRBMw7TCuTp893eSG8e.jpg", answer: "Requiem for a Dream" },
    { image: "https://image.tmdb.org/t/p/original/5oaMV2q0qzxkIW2ukU3lldLu5q2.jpg", answer: "American Psycho", possibleAnswers: ["Psicópata Americano"] },
    { image: "https://image.tmdb.org/t/p/original/6n53UI4mX9QMfe2S0Pgt8mGebY1.jpg", answer: "Amélie" },
    { image: "https://image.tmdb.org/t/p/original/vXzqV2RtJlT9WhNEM4NYWCEC6ZI.jpg", answer: "Brokeback Mountain", possibleAnswers: ["En Terreno Vedado"] },
    { image: "https://image.tmdb.org/t/p/original/mpRU00GeyQixJ6OglFGlWiWV820.jpg", answer: "The Devil Wears Prada", possibleAnswers: ["El Diablo Viste a la Moda"] },
    { image: "https://image.tmdb.org/t/p/original/4YzGG8IPduUQRVnQ0vN5laHA1rH.jpg", answer: "Little Miss Sunshine" },
    { image: "https://image.tmdb.org/t/p/original/coru98UcFBzJIU7bxZguxaePgu0.jpg", answer: "Superbad", possibleAnswers: ["Supercool"] },
    { image: "https://image.tmdb.org/t/p/original/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg", answer: "Avatar" },
    { image: "https://image.tmdb.org/t/p/original/1M2i4Mxd03elGOTmEkIvqrHfmyS.jpg", answer: "(500) Days of Summer", possibleAnswers: ["(500) Días con Ella"] },
    { image: "https://image.tmdb.org/t/p/original/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg", answer: "The Notebook", possibleAnswers: ["Diario de una pasión"] },
    { image: "https://image.tmdb.org/t/p/original/gTghF8ardwJ48XLHkiapWk3ZmSo.jpg", answer: "Snatch", possibleAnswers: ["Snatch: Cerdos y diamantes"] },
    { image: "https://image.tmdb.org/t/p/original/ow2boWFZWza7D4qDvJohg9GJVoH.jpg", answer: "Thirteen", possibleAnswers: ["Thirteen: 13 años"] },
    { image: "https://image.tmdb.org/t/p/original/t3HVA7XdVnQneMjI5hYjEhXmHY3.jpg", answer: "Matilda" },
    { image: "https://image.tmdb.org/t/p/original/75UPGUm2Zm6M60szq1gQisDF4g.jpg", answer: "The Butterfly Effect", possibleAnswers: ["El efecto mariposa"] },
    { image: "https://image.tmdb.org/t/p/original/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg", answer: "The Hangover", possibleAnswers: ["¿Qué pasó ayer?", "Resacón en Las Vegas"] },
    { image: "https://image.tmdb.org/t/p/original/qA2TyqPldTtoTVY3LKrNIG5g6bH.jpg", answer: "Before Sunrise", possibleAnswers: ["Antes del amanecer"] },
    { image: "https://image.tmdb.org/t/p/original/tcZi0LQc5iu2u6i5aOWyj9NBBvl.jpg", answer: "Before Sunset", possibleAnswers: ["Antes del atardecer"] },
    { image: "https://image.tmdb.org/t/p/original/m5dA4JZsj78EBTa2D6imWOAebwB.jpg", answer: "Scary Movie" },
    { image: "https://image.tmdb.org/t/p/original/cjSB3ZjaMpaa9oHFyeYha3KG0mp.jpg", answer: "Scary Movie 2" },
    { image: "https://image.tmdb.org/t/p/original/q8GwhIAttJwqmjDtbLW8JvEMMdw.jpg", answer: "Punch-Drunk Love", possibleAnswers: ["Embriagado de amor"] },
    { image: "https://image.tmdb.org/t/p/original/atoIgfAk2Ig2HFJLD0VUnjiPWEz.jpg", answer: "Charlie and the Chocolate Factory", possibleAnswers: ["Charlie y la fábrica de chocolate"] },
    { image: "https://image.tmdb.org/t/p/original/hi3lxLd93iKwCmVAfhMV9m1k2jr.jpg", answer: "The Machinist", possibleAnswers: ["El maquinista"] },
    { image: "https://image.tmdb.org/t/p/original/x903dx8Km6XNLFEmvbXc98vePSV.jpg", answer: "Yi Yi", possibleAnswers: ["Yi Yi: Un uno y un dos"] },
    { image: "https://image.tmdb.org/t/p/original/dF6GNQ0TnZkr1t4wBt36Xc0Pccd.jpg", answer: "Hostel" },
    { image: "https://image.tmdb.org/t/p/original/ckTh7Ej33m9O4eiKDQ1u91Opd9N.jpg", answer: "Leaving Las Vegas" },
    { image: "https://image.tmdb.org/t/p/original/tEhvOU8nJp4v9goYwrJTASJJD3C.jpg", answer: "The Piano Teacher", possibleAnswers: ["La pianista"] },
    { image: "https://image.tmdb.org/t/p/original/s9Bn7Mx4U9cWOR1WdFZjU1DTAkh.jpg", answer: "Zathura: A Space Adventure", possibleAnswers: ["Zathura: Una aventura espacial"] },
    { image: "https://image.tmdb.org/t/p/original/vxvzf0cGtFY2Vpw5ULWumCIW6Ri.jpg", answer: "Dancer in the Dark", possibleAnswers: ["Bailarina en la oscuridad"] },
    { image: "https://image.tmdb.org/t/p/original/tgRQsrjBKdic7llxhI7pqLJb8kS.jpg", answer: "Rounders" },
    { image: "https://image.tmdb.org/t/p/original/yCtgdv7TfgZLHj6R9IQKD5TjljP.jpg", answer: "The Celebration", possibleAnswers: ["Celebración", "Festen"] },
    { image: "https://image.tmdb.org/t/p/original/qJaR9AZx2Qq2oJ3krnSO0Z5ne5I.jpg", answer: "Fear and Loathing in Las Vegas", possibleAnswers: ["Miedo y asco en Las Vegas"] },
    { image: "https://image.tmdb.org/t/p/original/nY2faCdUVHzuH6FmDI6QsAURE68.jpg", answer: "Breaking the Waves", possibleAnswers: ["Rompiendo las olas"] },
    { image: "https://image.tmdb.org/t/p/original/qQNGhBijPIBlFkGwjtQk6sflml9.jpg", answer: "The Adventures of Sharkboy and Lavagirl", possibleAnswers: ["Las aventuras de Sharkboy y Lavagirl"] },
    { image: "https://image.tmdb.org/t/p/original/6qHI1IYj7QlLSCwHRzkL62X175s.jpg", answer: "American History X", possibleAnswers: ["Historia americana X"] },
    { image: "https://image.tmdb.org/t/p/original/yvPbncYhMu9FfTjDhq0N5lgnVkO.jpg", answer: "10 Things I Hate About You", possibleAnswers: ["10 cosas que odio de ti"] },
    { image: "https://image.tmdb.org/t/p/original/amGU1FpELmenVvNmPShW58Orepy.jpg", answer: "Twin Peaks: Fire Walk with Me", possibleAnswers: ["Twin Peaks: Fuego, camina conmigo"] },
    { image: "https://image.tmdb.org/t/p/original/msCHK5Kh1YbdZ0zPJ2nzPUhhSN9.jpg", answer: "Donnie Darko" },
    { image: "https://image.tmdb.org/t/p/original/iTkxwBriD9YKg4Q35qWEIlLXd6e.jpg", answer: "Amores Perros" },

];
