import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const peliculas1920a1969: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/hZHeDPQGNKN9NN9GuW7qVbM2tDx.jpg", answer: "The Gold Rush", possibleAnswers: ["La Quimera del Oro"] },
    { image: "https://image.tmdb.org/t/p/original/Ma7mQsldFCaQpsZbm8zolgLfmV.jpg", answer: "City Lights", possibleAnswers: ["Luces de la Ciudad"] },
    { image: "https://image.tmdb.org/t/p/original/kSlO1pHpwQfPQdgVPr7dJiJNtJ8.jpg", answer: "Modern Times", possibleAnswers: ["Tiempos Modernos"] },
    { image: "https://image.tmdb.org/t/p/original/4FHcxMtVruMr7ltU2cItWssLjTP.jpg", answer: "Gone with the Wind", possibleAnswers: ["Lo que el Viento se Llevó"] },
    { image: "https://image.tmdb.org/t/p/original/faR0hBQfnk32Y2mqYjtuGuL0Imf.jpg", answer: "Rebecca", possibleAnswers: ["Rebeca"] },
    { image: "https://image.tmdb.org/t/p/original/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg", answer: "The Great Dictator", possibleAnswers: ["El Gran Dictador"] },
    { image: "https://image.tmdb.org/t/p/original/ruF3Lmd4A8MHbnEBE6lxPMbsHGL.jpg", answer: "Citizen Kane", possibleAnswers: ["El Ciudadano Kane"] },
    { image: "https://image.tmdb.org/t/p/original/87wqeMeUeMRLjsE1IWNKJcPlpuC.jpg", answer: "Casablanca" },
    { image: "https://image.tmdb.org/t/p/original/byQdu1nzQLI9t1VeoP1xuQfru3L.jpg", answer: "Double Indemnity", possibleAnswers: ["Pacto de Sangre"] },
    { image: "https://image.tmdb.org/t/p/original/40Rl5nZRxXQ4kHV4Lhghj5iQZZN.jpg", answer: "Notorious", possibleAnswers: ["Encadenados"] },
    { image: "https://image.tmdb.org/t/p/original/81LX4wktTXWEXjLNlkHTmJm7tRu.jpg", answer: "Rope", possibleAnswers: ["La Soga"] },
    { image: "https://image.tmdb.org/t/p/original/tDn1dA52bQH9B85vilHeU7C83W1.jpg", answer: "Rashomon" },
    { image: "https://image.tmdb.org/t/p/original/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg", answer: "Sunset Boulevard", possibleAnswers: ["El Crepúsculo de los Dioses"] },
    { image: "https://image.tmdb.org/t/p/original/8Tnn2UOlecCKNLKG8ZK5Mu6bK94.jpg", answer: "Strangers on a Train", possibleAnswers: ["Extraños en un Tren"] },
    { image: "https://image.tmdb.org/t/p/original/pQ06lTkmJd1mbotdl847HoV2iaA.jpg", answer: "Ikiru", possibleAnswers: ["Vivir"] },
    { image: "https://image.tmdb.org/t/p/original/gzRISGjiDMj4xqYE9ES2KNIXxpo.jpg", answer: "Roman Holiday", possibleAnswers: ["Vacaciones en Roma"] },
    { image: "https://image.tmdb.org/t/p/original/mD6EAjfIr7CLdFlCIJjh7CJeWX3.jpg", answer: "Dial M for Murder", possibleAnswers: ["Crimen Perfecto"] },
    { image: "https://image.tmdb.org/t/p/original/zGs5tZOlvc9cprdcU6kDOVNpujf.jpg", answer: "Rear Window", possibleAnswers: ["La Ventana Indiscreta"] },
    { image: "https://image.tmdb.org/t/p/original/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg", answer: "Seven Samurai", possibleAnswers: ["Los Siete Samuráis"] },
    { image: "https://image.tmdb.org/t/p/original/9yepEBnQNcKzWWyHdUiX8Mnqc6U.jpg", answer: "Nights of Cabiria", possibleAnswers: ["Las Noches de Cabiria"] },
    { image: "https://image.tmdb.org/t/p/original/nbMY2UcNnaAr3jrrowzN0NaxQyr.jpg", answer: "Paths of Glory", possibleAnswers: ["Senderos de Gloria"] },
    { image: "https://image.tmdb.org/t/p/original/dRHfCeAoJ6SsMffQ6lavNU9E55z.jpg", answer: "The Bridge on the River Kwai", possibleAnswers: ["El Puente sobre el Río Kwai"] },
    { image: "https://image.tmdb.org/t/p/original/6s2BqtDvp1BMiP70zCDU5OW6hMy.jpg", answer: "The Seventh Seal", possibleAnswers: ["El Séptimo Sello"] },
    { image: "https://image.tmdb.org/t/p/original/rohRr9XqTRF8YwLMGAnTprg3GnL.jpg", answer: "Throne of Blood", possibleAnswers: ["Trono de Sangre"] },
    { image: "https://image.tmdb.org/t/p/original/BBVAUchYvkmPThVIqipgAfabfl.jpg", answer: "Wild Strawberries", possibleAnswers: ["Fresas Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/VCebm5PHUChrD0ve24O1dThnxU.jpg", answer: "The Hidden Fortress", possibleAnswers: ["La Fortaleza Escondida"] },
    { image: "https://image.tmdb.org/t/p/original/ousBoWTm1CltjAGSYOELYP0jFFC.jpg", answer: "Touch of Evil", possibleAnswers: ["Sed de Mal"] },
    { image: "https://image.tmdb.org/t/p/original/rtVwkTqllcmyY4TVOycgVBHppWf.jpg", answer: "Vertigo", possibleAnswers: ["Vértigo"] },
    { image: "https://image.tmdb.org/t/p/original/nk5gq5rNLBJiHvNGMRT6I9VRQX7.jpg", answer: "Ben-Hur" },
    { image: "https://image.tmdb.org/t/p/original/OR8oloCZ3klJtB7Y0i8pSqWw5a.jpg", answer: "North by Northwest", possibleAnswers: ["Intriga Internacional"] },
    { image: "https://image.tmdb.org/t/p/original/5zTwAcnI3zCJ0mucPPnoBtkSWEV.jpg", answer: "Some Like It Hot", possibleAnswers: ["Una Eva y Dos Adanes"] },
    { image: "https://image.tmdb.org/t/p/original/eN2NdMeJLNzLYzWIEEoaGzZAsiD.jpg", answer: "La Dolce Vita" },
    { image: "https://image.tmdb.org/t/p/original/mufF1aYvwdpKerhq5R1YrVcbJLY.jpg", answer: "Psycho", possibleAnswers: ["Psicosis"] },
    { image: "https://image.tmdb.org/t/p/original/9caD0fGCrp96JTFFeGyI0CGNj7.jpg", answer: "Spartacus", possibleAnswers: ["Espartaco"] },
    { image: "https://image.tmdb.org/t/p/original/2L8U8rUyWeFTb6n1egTNeJsEsvj.jpg", answer: "The Apartment", possibleAnswers: ["El Apartamento"] },
    { image: "https://image.tmdb.org/t/p/original/jXZ2tyJl44yKvh22I6ooQwU5rFM.jpg", answer: "Breakfast at Tiffany's", possibleAnswers: ["Desayuno en Tiffany's"] },
    { image: "https://image.tmdb.org/t/p/original/5BBwSVytssbFuSPZE4DtJVhROjN.jpg", answer: "Yojimbo" },
    { image: "https://image.tmdb.org/t/p/original/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg", answer: "Harakiri" },
    { image: "https://image.tmdb.org/t/p/original/z30x999Uku15xcFbe5s3hLvQPDl.jpg", answer: "Lawrence of Arabia", possibleAnswers: ["Lawrence de Arabia"] },
    { image: "https://image.tmdb.org/t/p/original/b9diKSmofRcgjbUxDrSPms82yAN.jpg", answer: "Lolita" },
    { image: "https://image.tmdb.org/t/p/original/i1NjlccZcuqbgDCS92RHdhEnx59.jpg", answer: "High and Low", possibleAnswers: ["Entre el Cielo y el Infierno"] },
    { image: "https://image.tmdb.org/t/p/original/q8niSuT02ZlBJDfCxoK2YZal3PL.jpg", answer: "The Great Escape", possibleAnswers: ["La Gran Evasión"] },
    { image: "https://image.tmdb.org/t/p/original/9gMkOYzk7P9QXwndhLRAC8cMZcJ.jpg", answer: "A Fistful of Dollars", possibleAnswers: ["Por un Puñado de Dólares"] },
    { image: "https://image.tmdb.org/t/p/original/7i0L2ee4Iy0aXV6vR5u1ZmblOrx.jpg", answer: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", possibleAnswers: ["Dr. Insólito o: Cómo Aprendí a Dejar de Preocuparme y Amar la Bomba"] },
    { image: "https://image.tmdb.org/t/p/original/dxfFh9pTKDaYH2B6PwcR6ohCM1L.jpg", answer: "Woman in the Dunes", possibleAnswers: ["La Mujer de la Arena"] },
    { image: "https://image.tmdb.org/t/p/original/wUaDgHfW7fViru7IubWa6Nronq9.jpg", answer: "Doctor Zhivago" },
    { image: "https://image.tmdb.org/t/p/original/hs6OPto38fF589ScpGhl7uSU4MI.jpg", answer: "For a Few Dollars More", possibleAnswers: ["La Muerte Tenía un Precio"] },
    { image: "https://image.tmdb.org/t/p/original/jqha8JCXm0aJ5SJ03Jd0JmGgWRs.jpg", answer: "Andrei Rublev" },
    { image: "https://image.tmdb.org/t/p/original/amr72SENYz7AM4Hq5WBXxFBJEY6.jpg", answer: "Persona" },
    { image: "https://image.tmdb.org/t/p/original/ze7GsNSv418o7pzqc9fb00LWWDk.jpg", answer: "The Battle of Algiers", possibleAnswers: ["La Batalla de Argel"] },
    { image: "https://image.tmdb.org/t/p/original/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg", answer: "The Good, the Bad and the Ugly", possibleAnswers: ["El Bueno, el Malo y el Feo"] },
    { image: "https://image.tmdb.org/t/p/original/gZqkMnORel0oiE0oSrBPfVQPB9w.jpg", answer: "The Dirty Dozen", possibleAnswers: ["Los Doce del Patíbulo"] },
    { image: "https://image.tmdb.org/t/p/original/w5IDXtifKntw0ajv2co7jFlTQDM.jpg", answer: "2001: A Space Odyssey", possibleAnswers: ["2001: Odisea del Espacio"] },
{ image: "https://image.tmdb.org/t/p/original/h1x4YiBtQEGY2dMx7k0fvlErlSn.jpg", answer: "Night of the Living Dead", possibleAnswers: ["La Noche de los Muertos Vivientes"] },
    { image: "https://image.tmdb.org/t/p/original/h31SOVlekuHXsMWVGxI8nPPfY82.jpg", answer: "Once Upon a Time in the West", possibleAnswers: ["Hasta Que Llegó su Hora"] },
    { image: "https://image.tmdb.org/t/p/original/qszuXKhzYR24oRpsmh7eZaPbvL8.jpg", answer: "Rosemary's Baby", possibleAnswers: ["El Bebé de Rosemary"] },
    { image: "https://image.tmdb.org/t/p/original/2gAStVyyv9C3BSEKhP0a1aM3Qy9.jpg", answer: "Nosferatu" },
    { image: "https://image.tmdb.org/t/p/original/eeMoFKxjjiCi6iep2GEZtSAMYIr.jpg", answer: "Metropolis" },
    { image: "https://image.tmdb.org/t/p/original/mzox4HbcV9W42MH2dB1QsdDVGo3.jpg", answer: "The General", possibleAnswers: ["El Maquinista de la General"] },
    { image: "https://image.tmdb.org/t/p/original/mRM2NB0i3wv4HqxXvwIjEVi4Qqq.jpg", answer: "King Kong" },
    { image: "https://image.tmdb.org/t/p/original/g1OvTd1eF346vmx8qsJnjaiooZ6.jpg", answer: "The Wizard of Oz", possibleAnswers: ["El Mago de Oz"] },
    { image: "https://image.tmdb.org/t/p/original/n0og4mDtl08x9RLTWXt8zUKpqXQ.jpg", answer: "The Best Years of Our Lives", possibleAnswers: ["Los Mejores Años de Nuestra Vida"] },
    { image: "https://image.tmdb.org/t/p/original/3q35nBLCIdEbxYfsr7D5ocYQXKz.jpg", answer: "It's a Wonderful Life", possibleAnswers: ["¡Qué Bello es Vivir!"] },
    { image: "https://image.tmdb.org/t/p/original/zAL3LOswagN9onjN8DPcNFTqKuD.jpg", answer: "All About Eve", possibleAnswers: ["Eva al Desnudo"] },
    { image: "https://image.tmdb.org/t/p/original/6qOyw4yfzbzTp5YsCX26C28Do0S.jpg", answer: "Singin' in the Rain", possibleAnswers: ["Cantando Bajo la Lluvia"] },
    { image: "https://image.tmdb.org/t/p/original/qqHQsStV6exghCM7zbObuYBiYxw.jpg", answer: "12 Angry Men", possibleAnswers: ["12 Hombres sin Piedad"] },
    { image: "https://image.tmdb.org/t/p/original/xfEU7DOlQPwz8Y0TBhKmpETuNIc.jpg", answer: "Anatomy of a Murder", possibleAnswers: ["Anatomía de un Asesinato"] },
    { image: "https://image.tmdb.org/t/p/original/prVH6SyQ6yDmzVxxkcr57zhLM5C.jpg", answer: "Mary Poppins" },
    { image: "https://image.tmdb.org/t/p/original/ioQYjcRnU54ir5ltgyS7k53zw5x.jpg", answer: "The Sound of Music", possibleAnswers: ["La Novicia Rebelde"] },
    { image: "https://image.tmdb.org/t/p/original/sZxPKiNCK8piKBtXAbm3Ucj6RQk.jpg", answer: "Who's Afraid of Virginia Woolf?", possibleAnswers: ["¿Quién le Teme a Virginia Woolf?"] },
    { image: "https://image.tmdb.org/t/p/original/fyzSiE8IWezmd3ls1amHNeOkrEf.jpg", answer: "Bonnie and Clyde" },
    { image: "https://image.tmdb.org/t/p/original/lIY8ZTp6OJTAMfiorDGsPsJ5LT.jpg", answer: "The Graduate", possibleAnswers: ["El Graduado"] },
    { image: "https://image.tmdb.org/t/p/original/tSipsYTp565LkopntX1lZNLPYHP.jpg", answer: "Sherlock Jr.", possibleAnswers: ["El Moderno Sherlock Holmes"] },
    { image: "https://image.tmdb.org/t/p/original/vyINER8nv4kAJyCIq2Sr1xjOOjC.jpg", answer: "The Lost Weekend", possibleAnswers: ["Días sin Huella"] },
    { image: "https://image.tmdb.org/t/p/original/dY0suaAdGpOqh7JkLeIN6lT7k9d.jpg", answer: "The Killing", possibleAnswers: ["Atraco Perfecto"] },
];
