import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const movieQuestions: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg", answer: "The Godfather", possibleAnswers: ["El Padrino"] },
    { image: "https://image.tmdb.org/t/p/original/kGzFbGhp99zva6oZODW5atUtnqi.jpg", answer: "The Godfather Part II", possibleAnswers: ["El Padrino II"] },
    { image: "https://image.tmdb.org/t/p/original/zNnjHLDtV8Ti3aworltaeaLMov4.jpg", answer: "The Godfather Part III", possibleAnswers: ["El Padrino III"] },
    { image: "https://image.tmdb.org/t/p/original/gILte6Zd7m1YneIr6MVhh30S9pr.jpg", answer: "GoodFellas", possibleAnswers: ["Buenos muchachos"] },
    { image: "https://image.tmdb.org/t/p/original/iZGiMD0p1M2AOmzKknFo5bkuz94.jpg", answer: "Casino", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/1RDto0tLo8Fhq7OcwgDaM7nECb7.jpg", answer: "The Irishman", possibleAnswers: ["El irlandés"] },
    { image: "https://image.tmdb.org/t/p/original/1qM2BYNE11Viby8ImC9LC00DgDr.jpg", answer: "Scarface", possibleAnswers: ["Caracortada"] },
    { image: "https://image.tmdb.org/t/p/original/xKsnZDERG1dk95wuZ5q9iks3OL3.jpg", answer: "Heat", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/6WRrGYalXXveItfpnipYdayFkQB.jpg", answer: "The Departed", possibleAnswers: ["Los infiltrados"] },
    { image: "https://image.tmdb.org/t/p/original/9uddYYTNcLWpzUkl5iw1RUYhLhY.jpg", answer: "Taxi Driver", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/tvNuhRlpRozDgsX1zR9gQ2aHv1X.jpg", answer: "Raging Bull", possibleAnswers: ["Toro salvaje"] },
    { image: "https://image.tmdb.org/t/p/original/7Nwnmyzrtd0FkcRyPqmdzTPppQa.jpg", answer: "The Wolf of Wall Street", possibleAnswers: ["El lobo de Wall Street"] },
    { image: "https://image.tmdb.org/t/p/original/rbZvGN1A1QyZuoKzhCw8QPmf2q0.jpg", answer: "Shutter Island", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/ntgpger7OwFNlEldxuvvFHDKzjW.jpg", answer: "Cape Fear", possibleAnswers: ["El cabo del miedo"] },
    { image: "https://image.tmdb.org/t/p/original/6KLKdhk9wZvJ6OcTzDCoxup0Kmh.jpg", answer: "The Aviator", possibleAnswers: ["El aviador"] },
    { image: "https://image.tmdb.org/t/p/original/acvE3RWjDLgvbL2RtcyzkrsAyNV.jpg", answer: "Killers of the Flower Moon", possibleAnswers: ["Los asesinos de la luna"] },
    { image: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", answer: "Pulp Fiction", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/jwt159hXWA9Q5xpBo8hWb3zwLi7.jpg", answer: "Reservoir Dogs", possibleAnswers: ["Perros de reserva"] },
    { image: "https://image.tmdb.org/t/p/original/gvaeY5kz3wHrMU6xLdnybziwYXw.jpg", answer: "Jackie Brown", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/iffzIhuLAO38Po6sh1s6ZEVwlNL.jpg", answer: "Kill Bill: Vol. 1", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/pgG6tzJzC8mjGqhaT8IWwEk00xf.jpg", answer: "Kill Bill: Vol. 2", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/hwNtEmmugU5Yd7hpfprNWI0DGIn.jpg", answer: "Inglourious Basterds", possibleAnswers: ["Bastardos sin gloria"] },
    { image: "https://image.tmdb.org/t/p/original/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg", answer: "Django Unchained", possibleAnswers: ["Django sin cadenas"] },
    { image: "https://image.tmdb.org/t/p/original/7g1zO5t0bd27Iqn5ZUDJmksOGPJ.jpg", answer: "The Hateful Eight", possibleAnswers: ["Los ocho más odiados"] },
    { image: "https://image.tmdb.org/t/p/original/xwgBHC2FgoIrQitl8jZwXXdsR9u.jpg", answer: "Once Upon a Time... in Hollywood", possibleAnswers: ["Había una vez en... Hollywood"] },
    { image: "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg", answer: "The Dark Knight", possibleAnswers: ["El caballero de la noche"] },
    { image: "https://image.tmdb.org/t/p/original/9IIBboV7MCT0bTxzXHmWK1Hq558.jpg", answer: "Batman Begins", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/y2DB71C4nyIdMrANijz8mzvQtk6.jpg", answer: "The Dark Knight Rises", possibleAnswers: ["El caballero de la noche asciende"] },
    { image: "https://image.tmdb.org/t/p/original/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg", answer: "The Batman", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/rlay2M5QYvi6igbGcFjq8jxeusY.jpg", answer: "Joker", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/z3br1ub7spqGMkxgjgJSdM4DC21.jpg", answer: "The Prestige", possibleAnswers: ["El gran truco (El prestigio)"] },
    { image: "https://image.tmdb.org/t/p/original/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg", answer: "Memento", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/jU8MC5uSgBkZXyZYGtZgMsMsfeN.jpg", answer: "Insomnia", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg", answer: "Inception", possibleAnswers: ["Origen"] },
    { image: "https://image.tmdb.org/t/p/original/2ssWTSVklAEc98frZUQhgtGHx7s.jpg", answer: "Interstellar", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mQOUyqDybTqxl73hO5LujCZsM1o.jpg", answer: "Tenet", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg", answer: "Oppenheimer", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/ddIkmH3TpR6XSc47jj0BrGK5Rbz.jpg", answer: "Dunkirk", possibleAnswers: ["Dunkerque"] },
    { image: "https://image.tmdb.org/t/p/original/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg", answer: "The Matrix", possibleAnswers: ["Matrix"] },
    { image: "https://image.tmdb.org/t/p/original/ihOJcrorpDQtHTzIOrobbOhpJsj.jpg", answer: "The Matrix Reloaded", possibleAnswers: ["Matrix Recargado"] },
    { image: "https://image.tmdb.org/t/p/original/kJYPag1YrA4PsXIftFdq3QEaanV.jpg", answer: "The Matrix Revolutions", possibleAnswers: ["Matrix Revoluciones"] },
    { image: "https://image.tmdb.org/t/p/original/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg", answer: "The Matrix Resurrections", possibleAnswers: ["Matrix Resurrecciones"] },
    { image: "https://image.tmdb.org/t/p/original/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg", answer: "John Wick", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/r17jFHAemzcWPPtoO0UxjIX0xas.jpg", answer: "John Wick: Chapter 2", possibleAnswers: ["John Wick: Pacto de sangre"] },
    { image: "https://image.tmdb.org/t/p/original/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg", answer: "John Wick: Chapter 3 - Parabellum", possibleAnswers: ["John Wick 3: Parabellum"] },
    { image: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg", answer: "John Wick: Chapter 4", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lywmuPU5Hr1Mnpb9UGeDbILmkTx.jpg", answer: "Speed", possibleAnswers: ["Máxima velocidad"] },
    { image: "https://image.tmdb.org/t/p/original/yGOHbICOQwlJ20UjK8F2ChGJjvl.jpg", answer: "Point Break", possibleAnswers: ["Punto de quiebre"] },
    { image: "https://image.tmdb.org/t/p/original/x3YFn10ehQKMRIJwIfiDAX8S9Xt.jpg", answer: "Constantine", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/2Y6Q7eYDXoolcHjYCAyJQlE2CVT.jpg", answer: "The Devil's Advocate", possibleAnswers: ["El abogado del diablo"] },
    { image: "https://image.tmdb.org/t/p/original/jhk6D8pim3yaByu1801kMoxXFaX.jpg", answer: "Gladiator", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg", answer: "Alien", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4kix6fAblJIH6eMs0Ku2loyZJXK.jpg", answer: "Aliens", possibleAnswers: ["Aliens: El regreso"] },
    { image: "https://image.tmdb.org/t/p/original/hJ5R9d6QuH3tzr8L8neZZTuzNXm.jpg", answer: "Blade Runner", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mVr0UiqyltcfqxbAUcLl9zWL8ah.jpg", answer: "Blade Runner 2049", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lzMS0CI3FLQYC5EgJoWeIaEt0lm.jpg", answer: "The Martian", possibleAnswers: ["Marte (The Martian)"] },
    { image: "https://image.tmdb.org/t/p/original/7jaNOECZG8uS1tlq69HsY5xY8P9.jpg", answer: "Black Hawk Down", possibleAnswers: ["La caída del Halcón Negro"] },
    { image: "https://image.tmdb.org/t/p/original/8itHQecANtOevcCdr3AhVxFCYkw.jpg", answer: "Kingdom of Heaven", possibleAnswers: ["El reino de los cielos"] },
    { image: "https://image.tmdb.org/t/p/original/33pMXav77ICRnceEBLhL8lXTywv.jpg", answer: "Napoleon", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/dLL90vskYFn1S89RZp5TUguK9wl.jpg", answer: "American Gangster", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/rBfY9GOG028ZlBmuSc7SkhmCUJP.jpg", answer: "Robin Hood", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4LrL40XecjGLRpX5I2gzMTUt04l.jpg", answer: "The Last Duel", possibleAnswers: ["El último duelo"] },
    { image: "https://image.tmdb.org/t/p/original/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg", answer: "The Shawshank Redemption", possibleAnswers: ["Sueño de fuga"] },
    { image: "https://image.tmdb.org/t/p/original/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg", answer: "The Green Mile", possibleAnswers: ["Milagros inesperados"] },
    { image: "https://image.tmdb.org/t/p/original/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg", answer: "Forrest Gump", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bdD39MpSVhKjxarTxLSfX6baoMP.jpg", answer: "Saving Private Ryan", possibleAnswers: ["Rescatando al soldado Ryan"] },
    { image: "https://image.tmdb.org/t/p/original/zb6fM1CX41D9rF9hdgclu0peUmy.jpg", answer: "Schindler's List", possibleAnswers: ["La lista de Schindler"] },
    { image: "https://image.tmdb.org/t/p/original/ggC3Brchf4RqPitEh7cROFoeAWn.jpg", answer: "Catch Me If You Can", possibleAnswers: ["Atrápame si puedes"] },
    { image: "https://image.tmdb.org/t/p/original/PrMb3oeEluauy0q9ZO5xL33A6C.jpg", answer: "Minority Report", possibleAnswers: ["Sentencia previa"] },
    { image: "https://image.tmdb.org/t/p/original/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg", answer: "War of the Worlds", possibleAnswers: ["La guerra de los mundos"] },
    { image: "https://image.tmdb.org/t/p/original/12M3SvYO4WMdlXCajWklz1zUAly.jpg", answer: "Bridge of Spies", possibleAnswers: ["Puente de espías"] },
    { image: "https://image.tmdb.org/t/p/original/zywtNiaZ9r7azrcNdl2j0jOgrkw.jpg", answer: "The Terminal", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5a7lMDn3nAj2ByO0X1fg6BhUphR.jpg", answer: "Ready Player One", possibleAnswers: ["Ready Player One: Comienza el juego"] },
    { image: "https://image.tmdb.org/t/p/original/hwOFrwHladQ8FktYn3aJNAt8KA1.jpg", answer: "Lincoln", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/titl6uMe5u974sLAA2Zy1kFi4sC.jpg", answer: "Munich", possibleAnswers: ["Múnich"] },
    { image: "https://image.tmdb.org/t/p/original/o7LzVmlOSYc3EspyVMC9bsTTARc.jpg", answer: "Jurassic Park", possibleAnswers: ["Parque Jurásico"] },
    { image: "https://image.tmdb.org/t/p/original/A4rYaPdzgocCjQ0n9LUSYUxyvpS.jpg", answer: "The Lost World: Jurassic Park", possibleAnswers: ["El mundo perdido: Parque Jurásico"] },
    { image: "https://image.tmdb.org/t/p/original/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg", answer: "Jurassic World Rebirth", possibleAnswers: ["Jurassic World: El renacer"] },
    { image: "https://image.tmdb.org/t/p/original/vCQRs9QMADZEbGiS4hJkjAzis36.jpg", answer: "Cruel Jaws", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg", answer: "E.T. the Extra-Terrestrial", possibleAnswers: ["E.T., el extraterrestre"] },
    { image: "https://image.tmdb.org/t/p/original/yBCekmb7vK70xUhtsRQBcTu65sB.jpg", answer: "Close Encounters of the Third Kind", possibleAnswers: ["Encuentros cercanos del tercer tipo"] },
    { image: "https://image.tmdb.org/t/p/original/f133nWlU6yUkZqqwcCXCbTEJWHr.jpg", answer: "Indiana Jones and the Temple of Doom", possibleAnswers: ["Indiana Jones y el templo maldito"] },
    { image: "https://image.tmdb.org/t/p/original/12fvZHskx57kQfNEUXJ3v0flWYQ.jpg", answer: "Indiana Jones and the Last Crusade", possibleAnswers: ["Indiana Jones y la última cruzada"] },
    { image: "https://image.tmdb.org/t/p/original/p96949hcwUG2BwE6MgKmw0uYNCx.jpg", answer: "Indiana Jones and the Kingdom of the Crystal Skull", possibleAnswers: ["Indiana Jones y el reino de la calavera de cristal"] },
    { image: "https://image.tmdb.org/t/p/original/57JocxmicOoAMhkUSmdKBlpZWMT.jpg", answer: "Indiana Jones and the Dial of Destiny", possibleAnswers: ["Indiana Jones y el dial del destino"] },
    { image: "https://image.tmdb.org/t/p/original/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg", answer: "Titanic", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg", answer: "Avatar", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/kJsPVzdyBrYHLomuNv5SJDXUQ2f.jpg", answer: "Avatar: The Way of Water", possibleAnswers: ["Avatar: El sentido del agua"] },
    { image: "https://image.tmdb.org/t/p/original/ffdqHMWkh1h9MABwIfbfRJhgFW6.jpg", answer: "The Terminator", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/izkMjmhauFx9DjoBQqM5sM5WAwE.jpg", answer: "Terminator 2: Judgment Day", possibleAnswers: ["Terminator 2: El juicio final"] },
    { image: "https://image.tmdb.org/t/p/original/voVkSwgFYv9GOpRNfUAwj6qYRTL.jpg", answer: "Terminator 3: Rise of the Machines", possibleAnswers: ["Terminator 3: La rebelión de las máquinas"] },
    { image: "https://image.tmdb.org/t/p/original/uT895WNwm0aIJRtGizcQhrejWUo.jpg", answer: "Mad Max: Fury Road", possibleAnswers: ["Mad Max: Furia en el camino"] },
    { image: "https://image.tmdb.org/t/p/original/MMSI9WzRmOdqXarevQ3Kqnytrx.jpg", answer: "Mad Max 2", possibleAnswers: ["Mad Max 2: El guerrero de la carretera"] },
    { image: "https://image.tmdb.org/t/p/original/uT895WNwm0aIJRtGizcQhrejWUo.jpg", answer: "Mad Max: Fury Road", possibleAnswers: ["Mad Max: Furia en el camino"] },
    { image: "https://image.tmdb.org/t/p/original/raph7qjAGTMXaIjVxt6ZDSXRzUr.jpg", answer: "Furiosa: A Mad Max Saga", possibleAnswers: ["Furiosa: De la saga Mad Max"] },
    { image: "https://image.tmdb.org/t/p/original/bvk2AAH64lP2YZs02Q3jskfHT8j.jpg", answer: "Die Hard", possibleAnswers: ["Duro de matar"] },
    { image: "https://image.tmdb.org/t/p/original/cDtefl7KGnKrDziEUXetMnztvqr.jpg", answer: "Die Hard 2", possibleAnswers: ["Duro de matar 2"] },
    { image: "https://image.tmdb.org/t/p/original/fBvSfLetWlAMevQVHa0nBDV1Fon.jpg", answer: "Die Hard: With a Vengeance", possibleAnswers: ["Duro de matar: La venganza"] },
    { image: "https://image.tmdb.org/t/p/original/oAA0nLghMmlvUH1uPiS7HVcCpnc.jpg", answer: "Lethal Weapon", possibleAnswers: ["Arma mortal"] },
    { image: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg", answer: "Top Gun: Maverick", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg", answer: "Top Gun: Maverick", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/sra8XnL96OyLHENcglmZJg6HA8z.jpg", answer: "Mission: Impossible", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/24DZfupDlhXeTchmcOkoGRhP5Vg.jpg", answer: "Mission: Impossible II", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bYKeB9uUcPmvikjouEEQ86uvPw9.jpg", answer: "Mission: Impossible III", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/ih4lZkUpmSE7AP3maymiO72xJ1z.jpg", answer: "Mission: Impossible - Ghost Protocol", possibleAnswers: ["Misión Imposible: Protocolo fantasma"] },
    { image: "https://image.tmdb.org/t/p/original/vYIUN5rrCncHFY8WvcuXQlM4hk5.jpg", answer: "Mission: Impossible - Rogue Nation", possibleAnswers: ["Misión Imposible: Nación secreta"] },
    { image: "https://image.tmdb.org/t/p/original/5jnoAA74Qwb5w6B9FMvnc20n6Ie.jpg", answer: "Mission: Impossible - Fallout", possibleAnswers: ["Misión: Imposible - Repercusión"] },
    { image: "https://image.tmdb.org/t/p/original/628Dep6AxEtDxjZoGP78TsOxYbK.jpg", answer: "Mission: Impossible - Dead Reckoning Part One", possibleAnswers: ["Misión: Imposible - Sentencia mortal Parte 1"] },
    { image: "https://image.tmdb.org/t/p/original/klJMCIblHLFwCuGjKz7tyOpekIC.jpg", answer: "Casino Royale", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/uGs5Z7dMguf7kxWubGFcp9EhKcy.jpg", answer: "Quantum of Solace", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/wkA622CCN2X0uwpgqYEOnUYEDf5.jpg", answer: "Skyfall", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8lBViysvNJBPkl6zG1LVAaW3qhj.jpg", answer: "Spectre", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bz7pwNGCbV576COsDcYN9MbEACC.jpg", answer: "No Time to Die", possibleAnswers: ["Sin tiempo para morir"] },
    { image: "https://image.tmdb.org/t/p/original/fIWsCpYR9iGDMSbMTSAzy8L7Kg5.jpg", answer: "GoldenEye", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg", answer: "The Silence of the Lambs", possibleAnswers: ["El silencio de los inocentes"] },
    { image: "https://image.tmdb.org/t/p/original/3Nb9AQaq3elLNCUBxG8VprmqfhZ.jpg", answer: "Hannibal", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/7c65xpnYlea6VITznLLRS9cTuwS.jpg", answer: "Red Dragon", possibleAnswers: ["Dragón rojo"] },
    { image: "https://image.tmdb.org/t/p/original/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg", answer: "Se7en", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3zCPI4JFc54xvLaJ71oI2KoP3az.jpg", answer: "Zodiac", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/iWak7wT0j6ycCc8lKr4NBz9c7n5.jpg", answer: "Gone Girl", possibleAnswers: ["Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/c6OLXfKAk5BKeR6broC8pYiCquX.jpg", answer: "Fight Club", possibleAnswers: ["El club de la pelea"] },
    { image: "https://image.tmdb.org/t/p/original/2fswjyrY3GEzeoVn6mF8pNeNcgf.jpg", answer: "The Curious Case of Benjamin Button", possibleAnswers: ["El curioso caso de Benjamin Button"] },
    { image: "https://image.tmdb.org/t/p/original/1PXwh3nJzgRkkYnqfWInJNypeL4.jpg", answer: "The Social Network", possibleAnswers: ["Red social"] },
    { image: "https://image.tmdb.org/t/p/original/gJfd2SzUsvY1q1iszthJ3ryuvEA.jpg", answer: "Panic Room", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/dNFbrnF0mIBm0rClbfEFWTtsgMP.jpg", answer: "The Girl with the Dragon Tattoo", possibleAnswers: ["Los hombres que no amaban a las mujeres"] },
    { image: "https://image.tmdb.org/t/p/original/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg", answer: "No Country for Old Men", possibleAnswers: ["Sin lugar para los débiles"] },
    { image: "https://image.tmdb.org/t/p/original/9UAKA6ceZi6TgQwTAAMt7DWwYPI.jpg", answer: "There Will Be Blood", possibleAnswers: ["Pozos de ambición"] },
    { image: "https://image.tmdb.org/t/p/original/fKPgObonYgPgCdu88yjV7Hpn7Dp.jpg", answer: "Sicario", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/n1ItmvzsDV5yLgDodSCLZpFlsP6.jpg", answer: "Prisoners", possibleAnswers: ["Prisioneros"] },
    { image: "https://image.tmdb.org/t/p/original/deYWtXTc56YdXyIuuMuA8dvBY16.jpg", answer: "Enemy", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/uKPbFF08QkRMvIAsgCh1soeyPhZ.jpg", answer: "Arrival", possibleAnswers: ["La llegada"] },
    { image: "https://image.tmdb.org/t/p/original/mVr0UiqyltcfqxbAUcLl9zWL8ah.jpg", answer: "Blade Runner 2049", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/f3ATwil5vmUeTsogBaMEKbBYBth.jpg", answer: "Incendies", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/wbQa0EnWUyRzQ5d1pHLNRlmsCUP.jpg", answer: "Whiplash", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg", answer: "La La Land", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5fxTB08O7CW1hAcN2MWOKodp1h1.jpg", answer: "Babylon", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/jrudoaXcoLyHRPdolyOGemXgPEs.jpg", answer: "First Man", possibleAnswers: ["El primer hombre"] },
    { image: "https://image.tmdb.org/t/p/original/s0OrExdg7i3RLR7oqzHRk4q2kL4.jpg", answer: "Birdman or (The Unexpected Virtue of Ignorance)", possibleAnswers: ["Birdman o (La inesperada virtud de la ignorancia)"] },
    { image: "https://image.tmdb.org/t/p/original/mNQtUJv1F3u0uSKILFrGjIHqkxx.jpg", answer: "The Revenant", possibleAnswers: ["El renacido"] },
    { image: "https://image.tmdb.org/t/p/original/46FRuCeAn6TrS4F1P4F9zhyCpyo.jpg", answer: "The Whale", possibleAnswers: ["La ballena"] },
    { image: "https://image.tmdb.org/t/p/original/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg", answer: "Everything Everywhere All at Once", possibleAnswers: ["Todo en todas partes al mismo tiempo"] },
    { image: "https://image.tmdb.org/t/p/original/sPPsR9f4K0movWVQ99u4uMqFzEL.jpg", answer: "Her", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/uqOuJ50EtTj7kkDIXP8LCg7G45D.jpg", answer: "Ex Machina", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/9trZvBr44UGedUOiGo3jgSUw13e.jpg", answer: "Annihilation", possibleAnswers: ["Aniquilación"] },
    { image: "https://image.tmdb.org/t/p/original/mvUAo9ACgmLpS4Ofc2IwD4n7WCt.jpg", answer: "Moon", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4GPCnwvTbsDleH5QIOyDLMsK8a2.jpg", answer: "Looper", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/s2Cu1y9Al9RbwRU5blAH8wMCrBI.jpg", answer: "Source Code", possibleAnswers: ["Código fuente"] },
    { image: "https://image.tmdb.org/t/p/original/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg", answer: "Edge of Tomorrow", possibleAnswers: ["Al filo del mañana"] },
    { image: "https://image.tmdb.org/t/p/original/jhM3wgWUrrOkz9r4xwV5cV5RhI4.jpg", answer: "District 9", possibleAnswers: ["Distrito 9"] },
    { image: "https://image.tmdb.org/t/p/original/gFGLwUBhVrq0bq4j9DU08xQDRU2.jpg", answer: "Children of Men", possibleAnswers: ["Hijos de los hombres"] },
    { image: "https://image.tmdb.org/t/p/original/ePgD1cwmklyrFBjl6z96IuixuSY.jpg", answer: "I Am Legend", possibleAnswers: ["Soy leyenda"] },
    { image: "https://image.tmdb.org/t/p/original/kg2FOT2Oe5PSCgs3L4vLel6B7ck.jpg", answer: "World War Z", possibleAnswers: ["Guerra Mundial Z"] },
    { image: "https://image.tmdb.org/t/p/original/aJFwk1clMal1prxAvKAgHxKPAf.jpg", answer: "28 Days Later", possibleAnswers: ["Exterminio"] },
    { image: "https://image.tmdb.org/t/p/original/83ownpZPvBHJD5UVNShzQfa3LaW.jpg", answer: "28 Weeks Later", possibleAnswers: ["Exterminio: La sentencia"] },
    { image: "https://image.tmdb.org/t/p/original/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg", answer: "The Sixth Sense", possibleAnswers: ["El sexto sentido"] },
    { image: "https://image.tmdb.org/t/p/original/rsPjEr7o02mo8ex6wD2PbRwasUe.jpg", answer: "Signs", possibleAnswers: ["Señales"] },
    { image: "https://image.tmdb.org/t/p/original/A7CYNTa3fWyU0t207XiecgriQv5.jpg", answer: "Unbreakable", possibleAnswers: ["El protegido"] },
    { image: "https://image.tmdb.org/t/p/original/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg", answer: "Split", possibleAnswers: ["Fragmentado"] },
    { image: "https://image.tmdb.org/t/p/original/rzsMWXQ7GaN60wIpg3yf01iBmXy.jpg", answer: "Glass", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lxwCRTWWfCisuarrFFUhW43eBnW.jpg", answer: "The Village", possibleAnswers: ["El bosque"] },
    { image: "https://image.tmdb.org/t/p/original/rbBe9WQ1OqCxzgwskOTnaY6JdUA.jpg", answer: "The Others", possibleAnswers: ["Los otros"] },
    { image: "https://image.tmdb.org/t/p/original/mWDdRXTivGE7aaY2vo1Ie0PfCX5.jpg", answer: "The Lord of the Rings: The Fellowship of the Ring", possibleAnswers: ["El señor de los anillos: La comunidad del anillo"] },
    { image: "https://image.tmdb.org/t/p/original/nr5smF4avc77lhWHNcGLF7guXv1.jpg", answer: "The Grudge", possibleAnswers: ["La maldición"] },
    { image: "https://image.tmdb.org/t/p/original/be5T7oHxmDG4ytEimwPdmDHZD9N.jpg", answer: "The Crucifix: Blood of the Exorcist", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg", answer: "The Shining", possibleAnswers: ["El resplandor"] },
    { image: "https://image.tmdb.org/t/p/original/ap6Zc5NDOfbZaMhkRDyghbGeLf0.jpg", answer: "Doctor Sleep", possibleAnswers: ["Doctor Sueño"] },
    { image: "https://image.tmdb.org/t/p/original/qVGpxnjrGlHaSTCqTQI6viBDSfp.jpg", answer: "It", possibleAnswers: ["Eso"] },
    { image: "https://image.tmdb.org/t/p/original/6LVSrgm83UYWlrLTCVGmWhFKYO0.jpg", answer: "It Chapter Two", possibleAnswers: ["Eso: Capítulo 2"] },
    { image: "https://image.tmdb.org/t/p/original/sHI9xlFRWCJ38AIIfOqnGjuEvXz.jpg", answer: "Halloween", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/aTovumsNlDjof7YVoU5nW2RHaYn.jpg", answer: "Halloween Ends", possibleAnswers: ["Halloween: El final"] },
    { image: "https://image.tmdb.org/t/p/original/3eUyLEF5M0ky3h6KJsWiWzaakB8.jpg", answer: "Scream 7", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/k6ANeyxAfMRi5xhxIXv1Scn9vc2.jpg", answer: "Scream VI", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/nzSjTiecdosBfwMGAdpt9CxltCI.jpg", answer: "A Nightmare on Elm Street", possibleAnswers: ["Pesadilla en la calle del infierno"] },
    { image: "https://image.tmdb.org/t/p/original/16zzKM5vDxnYiqG6Tg6wOkOLSmj.jpg", answer: "Friday the 13th", possibleAnswers: ["Viernes 13"] },
    { image: "https://image.tmdb.org/t/p/original/ok4ot3YbfDYZcINXf91JUfq3maB.jpg", answer: "Saw", possibleAnswers: ["El juego del miedo"] },
    { image: "https://image.tmdb.org/t/p/original/1lWeIA03iGXTlDv0yzsN0wUdT9T.jpg", answer: "Saw II", possibleAnswers: ["El juego del miedo II"] },
    { image: "https://image.tmdb.org/t/p/original/uUJp5I4IbzuhdUiEx4R9OAoFpbz.jpg", answer: "Saw X", possibleAnswers: ["El juego del miedo X"] },
    { image: "https://image.tmdb.org/t/p/original/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg", answer: "Final Destination Bloodlines", possibleAnswers: ["Destino final: Lazos de sangre"] },
    { image: "https://image.tmdb.org/t/p/original/ecKQlAEG95k62SMGhvX83oEqANK.jpg", answer: "The Conjuring", possibleAnswers: ["El conjuro"] },
    { image: "https://image.tmdb.org/t/p/original/mFCS5OuhPYT79KXu5jl7RqznPR1.jpg", answer: "The Conjuring 2", possibleAnswers: ["El conjuro 2"] },
    { image: "https://image.tmdb.org/t/p/original/cMnVmutb5mVgIBeiMOncAbwNjvG.jpg", answer: "The Nun", possibleAnswers: ["La monja"] },
    { image: "https://image.tmdb.org/t/p/original/pWZ0srAfPx4XyJMlFkKBlmYfx3C.jpg", answer: "Annabelle", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8HbNKB2pMiD3mfLgbxe7DgAKjdS.jpg", answer: "Insidious Inferno", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/jovIEk4cAxWmA2dBcPrfhn3jzYN.jpg", answer: "Sinister", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/kMZIMqEXO5MFd5Y1Ha2jZZF4pvF.jpg", answer: "Smile", possibleAnswers: ["Sonríe"] },
    { image: "https://image.tmdb.org/t/p/original/46Os8U0DEPmI0OnvKDxucl6SLVZ.jpg", answer: "Talk to Me", possibleAnswers: ["Háblame"] },
    { image: "https://image.tmdb.org/t/p/original/6ToGkmqn0KG0UGGGUAC1Ww0e5CM.jpg", answer: "Longlegs", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mVHyU4pnu9b2LWByPGGM0GGCA1v.jpg", answer: "The Get Out", possibleAnswers: ["Get Out: Déjame salir"] },
    { image: "https://image.tmdb.org/t/p/original/sC0b8iPUHfZdD8kseLiHw3N8gkp.jpg", answer: "Us", possibleAnswers: ["Nosotros"] },
    { image: "https://image.tmdb.org/t/p/original/yRutvYkM3OP8N9oqqfjSK1VC7fs.jpg", answer: "Nope", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3N5QNUqS76GFYNoEayfkkJyAyTN.jpg", answer: "Barbie", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4vSBj7BYsyuKCx96EJzGyp20WfY.jpg", answer: "The Menu", possibleAnswers: ["El menú"] },
    { image: "https://image.tmdb.org/t/p/original/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg", answer: "Knives Out", possibleAnswers: ["Puñales por la espalda"] },
    { image: "https://image.tmdb.org/t/p/original/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg", answer: "Glass Onion: A Knives Out Mystery", possibleAnswers: ["Puñales por la espalda: Un misterio de Knives Out"] },
    { image: "https://image.tmdb.org/t/p/original/A99WMiz0ASpH9coOFrxSEuwTWx0.jpg", answer: "The Holdovers", possibleAnswers: ["Los que se quedan"] },
    { image: "https://image.tmdb.org/t/p/original/t2SXZ7KLriaLyf5QT8Iar6fSOGp.jpg", answer: "Civil War", possibleAnswers: ["Guerra civil"] },
    { image: "https://image.tmdb.org/t/p/original/8ODNt5olCeIqBYTP3GgXEQYTfeX.jpg", answer: "The Substance", possibleAnswers: ["La sustancia"] },
    { image: "https://image.tmdb.org/t/p/original/zh6IdheEYinU4TPtorWsjx6qPQE.jpg", answer: "Poor Things", possibleAnswers: ["Pobres criaturas"] },
    { image: "https://image.tmdb.org/t/p/original/nHRUtBwFNnNN70vcQ7lAsjc2T6S.jpg", answer: "A Quiet Place", possibleAnswers: ["Un lugar en silencio"] },
    { image: "https://image.tmdb.org/t/p/original/uuBYYlbfiYD7ny5VNj46NG14ykR.jpg", answer: "A Quiet Place Part II", possibleAnswers: ["Un lugar en silencio, parte II"] },
    { image: "https://image.tmdb.org/t/p/original/sYLzRuEcwSz0L1Z92wQNrETHU9O.jpg", answer: "The Lighthouse", possibleAnswers: ["El faro"] },
    { image: "https://image.tmdb.org/t/p/original/fMiEp00v8gGWEceL4QeLu6H6z69.jpg", answer: "The Northman", possibleAnswers: ["El hombre del norte"] },
    { image: "https://image.tmdb.org/t/p/original/iymDDg4upZWgpbSeiE1JCjsSPBs.jpg", answer: "Drive", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bdI6U1mT0kCdTJ6TWtiFxQ42GSn.jpg", answer: "Nightcrawler", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5oaMV2q0qzxkIW2ukU3lldLu5q2.jpg", answer: "American Psycho", possibleAnswers: ["Psicópata americano"] },
    { image: "https://image.tmdb.org/t/p/original/msCHK5Kh1YbdZ0zPJ2nzPUhhSN9.jpg", answer: "Donnie Darko", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/fAGYRJCujRBMw7TCuTp893eSG8e.jpg", answer: "Requiem for a Dream", possibleAnswers: ["Réquiem por un sueño"] },
    { image: "https://image.tmdb.org/t/p/original/aCHn2TXYJfzPXQKA6r9mKPbMlUB.jpg", answer: "The Truman Show", possibleAnswers: ["El show de Truman"] },
    { image: "https://image.tmdb.org/t/p/original/W1ffLQGHoxfAOq0ZYdPtJlvAdb.jpg", answer: "Eternal Sunshine of the Spotless Mind", possibleAnswers: ["Eterno resplandor de una mente sin recuerdos"] },
    { image: "https://image.tmdb.org/t/p/original/oCFVYPXI4IfhtF3GapU2jkDicDI.jpg", answer: "Cast Away", possibleAnswers: ["Náufrago"] },
    { image: "https://image.tmdb.org/t/p/original/c0fB9xk7D1aVb3Bg2rk2SVJcGn.jpg", answer: "The Pianist", possibleAnswers: ["El pianista"] },
    { image: "https://image.tmdb.org/t/p/original/4Bb1kMIfrT2tYRZ9M6Jhqy6gkeF.jpg", answer: "12 Years a Slave", possibleAnswers: ["12 años de esclavitud"] },
    { image: "https://image.tmdb.org/t/p/original/usuRn9DUKQQr4nBWnrQzlOuZ1Q4.jpg", answer: "The Imitation Game", possibleAnswers: ["El código Enigma"] },
    { image: "https://image.tmdb.org/t/p/original/hCJFWTPghXCwwSpvPpAoIB8318Q.jpg", answer: "A Beautiful Mind", possibleAnswers: ["Una mente brillante"] },
    { image: "https://image.tmdb.org/t/p/original/m4MGxxEgAMqIX9x8MCg5pYeyYjU.jpg", answer: "The King's Speech", possibleAnswers: ["El discurso del rey"] },
    { image: "https://image.tmdb.org/t/p/original/2lBOQK06tltt8SQaswgb8d657Mv.jpg", answer: "1917", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/xBwtP27cx8WfjHJVFkpuV6F1RES.jpg", answer: "All Quiet on the Western Front", possibleAnswers: ["Sin novedad en el frente"] },
    { image: "https://image.tmdb.org/t/p/original/2vq5GTJOahE03mNYZGxIynlHcWr.jpg", answer: "Ford v Ferrari", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/D3eDUNEzJPBDG3TCJcR7RyRgTA.jpg", answer: "Rush", possibleAnswers: ["Rush: Pasión y gloria"] },
    { image: "https://image.tmdb.org/t/p/original/dcvbs8z0GEXslC1kCT77x19XDeR.jpg", answer: "Bohemian Rhapsody", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/isnJGDrfR9dIrHMsPTvHtJaGEpc.jpg", answer: "Rocketman", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/rLo9T9jEg67UZPq3midjLnTUYYi.jpg", answer: "Elvis", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/wCuUKiRaz0wEESsYqmQy005xvTE.jpg", answer: "Parasite", possibleAnswers: ["Parásitos"] },
    { image: "https://image.tmdb.org/t/p/original/sdwjQEM869JFwMytTmvr6ggvaUl.jpg", answer: "Oldboy", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/6Kn6qW3an3DkPl3MahWemTzrjCt.jpg", answer: "Memories of Murder", possibleAnswers: ["Memorias de un asesino"] },
    { image: "https://image.tmdb.org/t/p/original/qFKb25O9ROiGYt3GwtuXG5Lb2J.jpg", answer: "Train to Busan", possibleAnswers: ["Estación Zombie: Tren a Busan"] },
    { image: "https://image.tmdb.org/t/p/original/3upEZ0ltY7WwOSFVXrtiP34D48p.jpg", answer: "The Handmaiden", possibleAnswers: ["La doncella"] },
];
