import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const peliculasSigloPasado: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg", answer: "The Godfather", possibleAnswers: ["El Padrino"] },
    { image: "https://image.tmdb.org/t/p/original/kGzFbGhp99zva6oZODW5atUtnqi.jpg", answer: "The Godfather Part II", possibleAnswers: ["El Padrino, Parte II"] },
    { image: "https://image.tmdb.org/t/p/original/zNnjHLDtV8Ti3aworltaeaLMov4.jpg", answer: "The Godfather Part III", possibleAnswers: ["El Padrino, Parte III"] },
    { image: "https://image.tmdb.org/t/p/original/49fzLedFVKgGgFChLMuulDJBY1c.jpg", answer: "Apocalypse Now" },
    { image: "https://image.tmdb.org/t/p/original/s7yfiwIshKQIT6M8ZcTnFKXHs8B.jpg", answer: "The Conversation", possibleAnswers: ["La Conversación"] },
    { image: "https://image.tmdb.org/t/p/original/88S6EYQBVyQktDfSqsB33I169jN.jpg", answer: "Bram Stoker's Dracula", possibleAnswers: ["Drácula, de Bram Stoker"] },
    { image: "https://image.tmdb.org/t/p/original/9uddYYTNcLWpzUkl5iw1RUYhLhY.jpg", answer: "Taxi Driver" },
    { image: "https://image.tmdb.org/t/p/original/tvNuhRlpRozDgsX1zR9gQ2aHv1X.jpg", answer: "Raging Bull", possibleAnswers: ["Toro Salvaje"] },
    { image: "https://image.tmdb.org/t/p/original/gILte6Zd7m1YneIr6MVhh30S9pr.jpg", answer: "GoodFellas", possibleAnswers: ["Buenos Muchachos"] },
    { image: "https://image.tmdb.org/t/p/original/iZGiMD0p1M2AOmzKknFo5bkuz94.jpg", answer: "Casino" },
    { image: "https://image.tmdb.org/t/p/original/qdecDSIVoqctIoYoOhLH3TgSYLD.jpg", answer: "Mean Streets", possibleAnswers: ["Calles Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/7Mh1DM4kCMbN93C2MlUavYbH5YM.jpg", answer: "The King of Comedy", possibleAnswers: ["El Rey de la Comedia"] },
    { image: "https://image.tmdb.org/t/p/original/ntgpger7OwFNlEldxuvvFHDKzjW.jpg", answer: "Cape Fear" },
    { image: "https://image.tmdb.org/t/p/original/hhCp6ZLDjS5wUHkGg7k3VGvH3Xm.jpg", answer: "The Color of Money", possibleAnswers: ["El Color del Dinero"] },
    { image: "https://image.tmdb.org/t/p/original/tV2KZZR5JaqTSXiNKowGqQMQtex.jpg", answer: "After Hours", possibleAnswers: ["Después de Hora"] },
    { image: "https://image.tmdb.org/t/p/original/rBqdcQeM1h05YjF9rFtPWnNaDO2.jpg", answer: "The Last Temptation of Christ", possibleAnswers: ["La Última Tentación de Cristo"] },
    { image: "https://image.tmdb.org/t/p/original/aCBbGxcbWgUJxmIiv5JDC7p5vmN.jpg", answer: "Bringing Out the Dead", possibleAnswers: ["Vidas al Límite"] },
    { image: "https://image.tmdb.org/t/p/original/w5IDXtifKntw0ajv2co7jFlTQDM.jpg", answer: "2001: A Space Odyssey", possibleAnswers: ["2001: Odisea del Espacio"] },
    { image: "https://image.tmdb.org/t/p/original/nLFxvLokHe3bQmrmAfljIfax2jQ.jpg", answer: "A Clockwork Orange", possibleAnswers: ["La Naranja Mecánica"] },
    { image: "https://image.tmdb.org/t/p/original/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg", answer: "The Shining", possibleAnswers: ["El Resplandor"] },
    { image: "https://image.tmdb.org/t/p/original/3k2TRmqMjgt7tcwkYwZQdctnty3.jpg", answer: "Full Metal Jacket", possibleAnswers: ["Nacido para Matar"] },
    { image: "https://image.tmdb.org/t/p/original/ef6SvWbSfCFlKodJZqpIaTvsRRP.jpg", answer: "Barry Lyndon" },
    { image: "https://image.tmdb.org/t/p/original/7i0L2ee4Iy0aXV6vR5u1ZmblOrx.jpg", answer: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", possibleAnswers: ["Dr. Insólito o: Cómo Aprendí a Dejar de Preocuparme y Amar la Bomba"] },
    { image: "https://image.tmdb.org/t/p/original/nbMY2UcNnaAr3jrrowzN0NaxQyr.jpg", answer: "Paths of Glory", possibleAnswers: ["Senderos de Gloria"] },
    { image: "https://image.tmdb.org/t/p/original/b9diKSmofRcgjbUxDrSPms82yAN.jpg", answer: "Lolita" },
    { image: "https://image.tmdb.org/t/p/original/aC6wW62V6b0csr5iUnbOjYAqfhg.jpg", answer: "Eyes Wide Shut" },
    { image: "https://image.tmdb.org/t/p/original/mufF1aYvwdpKerhq5R1YrVcbJLY.jpg", answer: "Psycho", possibleAnswers: ["Psicosis"] },
    { image: "https://image.tmdb.org/t/p/original/rtVwkTqllcmyY4TVOycgVBHppWf.jpg", answer: "Vertigo", possibleAnswers: ["Vértigo"] },
    { image: "https://image.tmdb.org/t/p/original/zGs5tZOlvc9cprdcU6kDOVNpujf.jpg", answer: "Rear Window", possibleAnswers: ["La Ventana Indiscreta"] },
    { image: "https://image.tmdb.org/t/p/original/OR8oloCZ3klJtB7Y0i8pSqWw5a.jpg", answer: "North by Northwest", possibleAnswers: ["Intriga Internacional"] },
    { image: "https://image.tmdb.org/t/p/original/o4mhrLxv6I70kvYA42qANGUF7ya.jpg", answer: "The Angry Birds Movie", possibleAnswers: ["Angry Birds: La Película"] },
    { image: "https://image.tmdb.org/t/p/original/faR0hBQfnk32Y2mqYjtuGuL0Imf.jpg", answer: "Rebecca", possibleAnswers: ["Rebeca"] },
    { image: "https://image.tmdb.org/t/p/original/mD6EAjfIr7CLdFlCIJjh7CJeWX3.jpg", answer: "Dial M for Murder", possibleAnswers: ["Crimen Perfecto"] },
    { image: "https://image.tmdb.org/t/p/original/81LX4wktTXWEXjLNlkHTmJm7tRu.jpg", answer: "Rope", possibleAnswers: ["La Soga"] },
    { image: "https://image.tmdb.org/t/p/original/8Tnn2UOlecCKNLKG8ZK5Mu6bK94.jpg", answer: "Strangers on a Train", possibleAnswers: ["Extraños en un Tren"] },
    { image: "https://image.tmdb.org/t/p/original/40Rl5nZRxXQ4kHV4Lhghj5iQZZN.jpg", answer: "Notorious", possibleAnswers: ["Encadenados"] },
    { image: "https://image.tmdb.org/t/p/original/s1CBwblInR0ZBIv59CSko2QdLD3.jpg", answer: "Blue Velvet", possibleAnswers: ["Terciopelo Azul"] },
    { image: "https://image.tmdb.org/t/p/original/6huSptAsqYg3wbsi1jbMognSgmp.jpg", answer: "The Elephant Man", possibleAnswers: ["El Hombre Elefante"] },
    { image: "https://image.tmdb.org/t/p/original/6xJ2odkMFmO2LptVUBR8t8wBldQ.jpg", answer: "Wild at Heart", possibleAnswers: ["Corazón Salvaje"] },
    { image: "https://image.tmdb.org/t/p/original/hGnJhGSeyWlerHcLNnD06sbX5wU.jpg", answer: "Lost Highway", possibleAnswers: ["Carretera Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/1S81PpyGwS8eVx4W75uSKzMw4B0.jpg", answer: "The Straight Story", possibleAnswers: ["Una Historia Verdadera"] },
    { image: "https://image.tmdb.org/t/p/original/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg", answer: "Se7en", possibleAnswers: ["Seven: Los Siete Pecados Capitales"] },
    { image: "https://image.tmdb.org/t/p/original/c6OLXfKAk5BKeR6broC8pYiCquX.jpg", answer: "Fight Club", possibleAnswers: ["El Club de la Pelea"] },
    { image: "https://image.tmdb.org/t/p/original/usuRn9DUKQQr4nBWnrQzlOuZ1Q4.jpg", answer: "The Imitation Game", possibleAnswers: ["El Código Enigma"] },
    { image: "https://image.tmdb.org/t/p/original/jwt159hXWA9Q5xpBo8hWb3zwLi7.jpg", answer: "Reservoir Dogs", possibleAnswers: ["Perros de Reserva"] },
    { image: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", answer: "Pulp Fiction", possibleAnswers: ["Tiempos Violentos"] },
    { image: "https://image.tmdb.org/t/p/original/gvaeY5kz3wHrMU6xLdnybziwYXw.jpg", answer: "Jackie Brown" },
    { image: "https://image.tmdb.org/t/p/original/vCQRs9QMADZEbGiS4hJkjAzis36.jpg", answer: "Cruel Jaws" },
    { image: "https://image.tmdb.org/t/p/original/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg", answer: "E.T. the Extra-Terrestrial", possibleAnswers: ["E.T., el Extraterrestre"] },
    { image: "https://image.tmdb.org/t/p/original/o7LzVmlOSYc3EspyVMC9bsTTARc.jpg", answer: "Jurassic Park", possibleAnswers: ["Parque Jurásico"] },
    { image: "https://image.tmdb.org/t/p/original/zb6fM1CX41D9rF9hdgclu0peUmy.jpg", answer: "Schindler's List", possibleAnswers: ["La Lista de Schindler"] },
    { image: "https://image.tmdb.org/t/p/original/bdD39MpSVhKjxarTxLSfX6baoMP.jpg", answer: "Saving Private Ryan", possibleAnswers: ["Rescatando al Soldado Ryan"] },
    { image: "https://image.tmdb.org/t/p/original/zPACwR32amTNvzId9qyapCWXYDJ.jpg", answer: "Raiders of the Lost Ark", possibleAnswers: ["En Busca del Arca Perdida"] },
    { image: "https://image.tmdb.org/t/p/original/f133nWlU6yUkZqqwcCXCbTEJWHr.jpg", answer: "Indiana Jones and the Temple of Doom", possibleAnswers: ["Indiana Jones y el Templo Maldito"] },
    { image: "https://image.tmdb.org/t/p/original/12fvZHskx57kQfNEUXJ3v0flWYQ.jpg", answer: "Indiana Jones and the Last Crusade", possibleAnswers: ["Indiana Jones y la Última Cruzada"] },
    { image: "https://image.tmdb.org/t/p/original/yBCekmb7vK70xUhtsRQBcTu65sB.jpg", answer: "Close Encounters of the Third Kind", possibleAnswers: ["Encuentros Cercanos del Tercer Tipo"] },
    { image: "https://image.tmdb.org/t/p/original/AoGLKkPvBcZP27jwSA85fY8emvJ.jpg", answer: "Duel", possibleAnswers: ["Duelo"] },
    { image: "https://image.tmdb.org/t/p/original/lh6MbyxwCribn3hdAo81xLdPGoV.jpg", answer: "The Color Purple", possibleAnswers: ["El Color Púrpura"] },
    { image: "https://image.tmdb.org/t/p/original/AmTrqk910ot3aYLBGyIG78Xfa18.jpg", answer: "Amistad" },
    { image: "https://image.tmdb.org/t/p/original/yUiXA68FfQeA8cRBhd0Ao0jIRZt.jpg", answer: "Star Wars", possibleAnswers: ["La Guerra de las Galaxias"] },
    { image: "https://image.tmdb.org/t/p/original/k9pshruhCpJAdH9RaGJO6jaWQ4X.jpg", answer: "The Empire Strikes Back", possibleAnswers: ["El Imperio Contraataca"] },
    { image: "https://image.tmdb.org/t/p/original/ziECpBRIyclmBNaFSWlvCfsKbMD.jpg", answer: "Return of the Jedi", possibleAnswers: ["El Regreso del Jedi"] },
    { image: "https://image.tmdb.org/t/p/original/3TeGmKJfkik1D1rIoqGb1aR4k9c.jpg", answer: "Star Wars: Episode I - The Phantom Menace", possibleAnswers: ["Star Wars: Episodio I - La Amenaza Fantasma"] },
    { image: "https://image.tmdb.org/t/p/original/xdofxnT2FADbSFOJflOTLnCoZe9.jpg", answer: "American Graffiti" },
    { image: "https://image.tmdb.org/t/p/original/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg", answer: "Alien", possibleAnswers: ["Alien, el Octavo Pasajero"] },
    { image: "https://image.tmdb.org/t/p/original/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg", answer: "Blade Runner 2049" },
    { image: "https://image.tmdb.org/t/p/original/eA15zhxnhQSg4k5MUbbTERIU23Z.jpg", answer: "Thelma & Louise" },
    { image: "https://image.tmdb.org/t/p/original/jhk6D8pim3yaByu1801kMoxXFaX.jpg", answer: "Gladiator", possibleAnswers: ["Gladiador"] },
    { image: "https://image.tmdb.org/t/p/original/ffdqHMWkh1h9MABwIfbfRJhgFW6.jpg", answer: "The Terminator", possibleAnswers: ["El Exterminador del Futuro"] },
    { image: "https://image.tmdb.org/t/p/original/izkMjmhauFx9DjoBQqM5sM5WAwE.jpg", answer: "Terminator 2: Judgment Day", possibleAnswers: ["Terminator 2: El Juicio Final"] },
    { image: "https://image.tmdb.org/t/p/original/4kix6fAblJIH6eMs0Ku2loyZJXK.jpg", answer: "Aliens", possibleAnswers: ["Aliens: El Regreso"] },
    { image: "https://image.tmdb.org/t/p/original/mW6XzxelLY8T2oW2NjciG9LpZT5.jpg", answer: "The Abyss", possibleAnswers: ["El Abismo"] },
    { image: "https://image.tmdb.org/t/p/original/jRZ3joUcg8YDCQYl4Tog5xhY6wk.jpg", answer: "True Lies", possibleAnswers: ["Mentiras Verdaderas"] },
    { image: "https://image.tmdb.org/t/p/original/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg", answer: "Titanic" },
    { image: "https://image.tmdb.org/t/p/original/1qM2BYNE11Viby8ImC9LC00DgDr.jpg", answer: "Scarface", possibleAnswers: ["Caracortada"] },
    { image: "https://image.tmdb.org/t/p/original/i1oWUGVDNBhGBykcCRBlX326udb.jpg", answer: "The Untouchables", possibleAnswers: ["Los Intocables"] },
    { image: "https://image.tmdb.org/t/p/original/9s4ZDw0j6qByLgwJtUsRcepBXSw.jpg", answer: "Carlito's Way", possibleAnswers: ["Atrapado por su Pasado"] },
    { image: "https://image.tmdb.org/t/p/original/nk87CtgZ7wd86W37oJHGYAJbmLz.jpg", answer: "Blow Out", possibleAnswers: ["Impacto"] },
    { image: "https://image.tmdb.org/t/p/original/zwJFfKQdfiptK2GY6N8GkZFrAxJ.jpg", answer: "Carrie" },
    { image: "https://image.tmdb.org/t/p/original/sra8XnL96OyLHENcglmZJg6HA8z.jpg", answer: "Mission: Impossible", possibleAnswers: ["Misión: Imposible"] },
    { image: "https://image.tmdb.org/t/p/original/sHI9xlFRWCJ38AIIfOqnGjuEvXz.jpg", answer: "Halloween", possibleAnswers: ["La Noche de Halloween"] },
    { image: "https://image.tmdb.org/t/p/original/r9leYNa8nTRCceZrZhP1DXkgKVb.jpg", answer: "The Thing", possibleAnswers: ["La Cosa (El Enigma de Otro Mundo)"] },
    { image: "https://image.tmdb.org/t/p/original/6vNuos23LwWjY1FJuojwPAgo8Ss.jpg", answer: "Escape from New York", possibleAnswers: ["1997: Rescate en Nueva York"] },
    { image: "https://image.tmdb.org/t/p/original/3k2DQBryXzaL7DoAtu6veWWluwt.jpg", answer: "They Live", possibleAnswers: ["Están Vivos"] },
    { image: "https://image.tmdb.org/t/p/original/ehHskGgDUchxGyG33vUQZWNng43.jpg", answer: "Big Trouble in Little China", possibleAnswers: ["Golpe en la Pequeña China"] },
    { image: "https://image.tmdb.org/t/p/original/8nHYzBDeEPS0hbWYphQplhbTjQ3.jpg", answer: "The Fog", possibleAnswers: ["La Niebla"] },
    { image: "https://image.tmdb.org/t/p/original/747dgDfL5d8esobk7h4odaOFhUq.jpg", answer: "Fargo" },
    { image: "https://image.tmdb.org/t/p/original/hXsy4XCCHrUk81XoRhcooyWejao.jpg", answer: "The Big Lebowski", possibleAnswers: ["El Gran Lebowski"] },
    { image: "https://image.tmdb.org/t/p/original/cEsnLkTCJ4jh9Oym7nPAPGnOMm3.jpg", answer: "Miller's Crossing", possibleAnswers: ["Muerte entre las Flores"] },
    { image: "https://image.tmdb.org/t/p/original/rGPoNNk4fvgG2mvkNAxJJPlszOu.jpg", answer: "Blood Simple", possibleAnswers: ["Sangre Fácil"] },
    { image: "https://image.tmdb.org/t/p/original/oSFshBf9Wrv5UcmZYAmy28BwSSh.jpg", answer: "Raising Arizona", possibleAnswers: ["Arizona Baby"] },
    { image: "https://image.tmdb.org/t/p/original/cW1XlxgvxZIFkakYc9yrLpDoYhK.jpg", answer: "Barton Fink" },
    { image: "https://image.tmdb.org/t/p/original/ArpTzQZHWh4UVsgUvV6S7WjTq1n.jpg", answer: "Boogie Nights" },
    { image: "https://image.tmdb.org/t/p/original/mFfyE5DPFDqoes4HIcElHc2a15y.jpg", answer: "Magnolia" },
    { image: "https://image.tmdb.org/t/p/original/4rt35cuyJ3CwpZgeIdXm5fmCinx.jpg", answer: "Hard Eight" },
    { image: "https://image.tmdb.org/t/p/original/9IIBboV7MCT0bTxzXHmWK1Hq558.jpg", answer: "Batman Begins", possibleAnswers: ["Batman Inicia"] },
    { image: "https://image.tmdb.org/t/p/original/7x4SNxO5HWArighxxFeet5sn3il.jpg", answer: "Batman Returns", possibleAnswers: ["Batman Vuelve"] },
    { image: "https://image.tmdb.org/t/p/original/uNLIMPxknsV4n3IAEDpS1iqF5dm.jpg", answer: "Edward Scissorhands", possibleAnswers: ["El Joven Manos de Tijera"] },
    { image: "https://image.tmdb.org/t/p/original/3jrwJiMCe7VZP0DNcywHYOKg0Zu.jpg", answer: "Ed Wood" },
    { image: "https://image.tmdb.org/t/p/original/m8t7K3LcAY7bpyQ7iQ5kGsrcjnh.jpg", answer: "Sleepy Hollow", possibleAnswers: ["La Leyenda del Jinete sin Cabeza"] },
    { image: "https://image.tmdb.org/t/p/original/kF8ljC7Y4p1UsmKBi2LxelZpqw.jpg", answer: "Beetlejuice Beetlejuice" },
    { image: "https://image.tmdb.org/t/p/original/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg", answer: "Back to the Future", possibleAnswers: ["Volver al Futuro"] },
    { image: "https://image.tmdb.org/t/p/original/w6tPctxWAsHoQXeKxxNOT6lYKpx.jpg", answer: "Back to the Future Part II", possibleAnswers: ["Volver al Futuro Parte II"] },
    { image: "https://image.tmdb.org/t/p/original/AtF7TESJEMmImBRUj9Z7HmW2ZH0.jpg", answer: "Back to the Future Part III", possibleAnswers: ["Volver al Futuro Parte III"] },
    { image: "https://image.tmdb.org/t/p/original/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg", answer: "Forrest Gump" },
    { image: "https://image.tmdb.org/t/p/original/udIE8Cdon9wnYmVIOFYrBPfA2Mq.jpg", answer: "Who Framed Roger Rabbit", possibleAnswers: ["¿Quién Engañó a Roger Rabbit?"] },
    { image: "https://image.tmdb.org/t/p/original/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg", answer: "Contact" },
    { image: "https://image.tmdb.org/t/p/original/oCFVYPXI4IfhtF3GapU2jkDicDI.jpg", answer: "Cast Away", possibleAnswers: ["Náufrago"] },
    { image: "https://image.tmdb.org/t/p/original/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg", answer: "The Shawshank Redemption", possibleAnswers: ["Sueño de Fuga"] },
    { image: "https://image.tmdb.org/t/p/original/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg", answer: "The Green Mile", possibleAnswers: ["Milagros Inesperados"] },
    { image: "https://image.tmdb.org/t/p/original/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg", answer: "The Silence of the Lambs", possibleAnswers: ["El Silencio de los Inocentes"] },
    { image: "https://image.tmdb.org/t/p/original/nWO4sGqH950N2fij8X0Pwumqe9k.jpg", answer: "Philadelphia" },
    { image: "https://image.tmdb.org/t/p/original/fj0hwDJEOOHllRim2BMt5L7tbjf.jpg", answer: "Léon: The Professional", possibleAnswers: ["El Perfecto Asesino"] },
    { image: "https://image.tmdb.org/t/p/original/jW21PoKwqs79wk6bfiYezox63mK.jpg", answer: "The Fifth Element", possibleAnswers: ["El Quinto Elemento"] },
    { image: "https://image.tmdb.org/t/p/original/rk56vslwBXUCcNlQ74s6gmpJqxa.jpg", answer: "Nikita" },
    { image: "https://image.tmdb.org/t/p/original/xKsnZDERG1dk95wuZ5q9iks3OL3.jpg", answer: "Heat" },
    { image: "https://image.tmdb.org/t/p/original/2GIr0LArTvO33HQVPEdp49FLdNV.jpg", answer: "The Insider", possibleAnswers: ["El Dilema"] },
    { image: "https://image.tmdb.org/t/p/original/mhpDSuNyHPMsccI7zISEaskTgOQ.jpg", answer: "The Last of the Mohicans", possibleAnswers: ["El Último Mohicano"] },
    { image: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg", answer: "Top Gun: Maverick" },
    { image: "https://image.tmdb.org/t/p/original/1Uh8yuXlFcMDpVHWZJidjanT06e.jpg", answer: "True Romance", possibleAnswers: ["Amor a Quemarropa"] },
    { image: "https://image.tmdb.org/t/p/original/qKWQ9IEDkMawD7sgKnIGCdFAhct.jpg", answer: "Crimson Tide", possibleAnswers: ["Marea Roja"] },
    { image: "https://image.tmdb.org/t/p/original/lPLTLCBn39Wiy1RPQLB9xOKyF2v.jpg", answer: "Enemy of the State", possibleAnswers: ["Enemigo del Estado"] },
    { image: "https://image.tmdb.org/t/p/original/vr0gwTvit5pTZs2wXOkvpsxCfli.jpg", answer: "Platoon", possibleAnswers: ["Pelotón"] },
    { image: "https://image.tmdb.org/t/p/original/7Nwnmyzrtd0FkcRyPqmdzTPppQa.jpg", answer: "The Wolf of Wall Street", possibleAnswers: ["El Lobo de Wall Street"] },
    { image: "https://image.tmdb.org/t/p/original/y9QjSsIH4vBIIqGmAFT1zJzsqPh.jpg", answer: "Born on the Fourth of July", possibleAnswers: ["Nacido el Cuatro de Julio"] },
    { image: "https://image.tmdb.org/t/p/original/77gjiDyD94aJfqZq6AJAcMLxZhd.jpg", answer: "JFK" },
    { image: "https://image.tmdb.org/t/p/original/k3TOt50cHvTLXWYPnXP0szhiXB8.jpg", answer: "Natural Born Killers", possibleAnswers: ["Asesinos por Naturaleza"] },
    { image: "https://image.tmdb.org/t/p/original/rvRGFevvZK48onX0PYI1eQLbuJd.jpg", answer: "Unforgiven", possibleAnswers: ["Los Imperdonables"] },
    { image: "https://image.tmdb.org/t/p/original/4TnGcUsyd6ixuLWHaaEG5BGkAIp.jpg", answer: "The Bridges of Madison County", possibleAnswers: ["Los Puentes de Madison"] },
    { image: "https://image.tmdb.org/t/p/original/uA8eSNAUUUyfHNIrG4h0zHxzt9W.jpg", answer: "One Flew Over the Cuckoo's Nest", possibleAnswers: ["Atrapado sin Salida"] },
    { image: "https://image.tmdb.org/t/p/original/rnQyWw68dPHPRtvSWMtLSueXf05.jpg", answer: "Amadeus" },
    { image: "https://image.tmdb.org/t/p/original/pyvkujOZ5qvY2NlQVC71flfgVWE.jpg", answer: "Chinatown" },
    { image: "https://image.tmdb.org/t/p/original/qszuXKhzYR24oRpsmh7eZaPbvL8.jpg", answer: "Rosemary's Baby", possibleAnswers: ["El Bebé de Rosemary"] },
    { image: "https://image.tmdb.org/t/p/original/c0fB9xk7D1aVb3Bg2rk2SVJcGn.jpg", answer: "The Pianist", possibleAnswers: ["El Pianista"] },
    { image: "https://image.tmdb.org/t/p/original/9gMkOYzk7P9QXwndhLRAC8cMZcJ.jpg", answer: "A Fistful of Dollars", possibleAnswers: ["Por un Puñado de Dólares"] },
    { image: "https://image.tmdb.org/t/p/original/hs6OPto38fF589ScpGhl7uSU4MI.jpg", answer: "For a Few Dollars More", possibleAnswers: ["La Muerte Tenía un Precio"] },
    { image: "https://image.tmdb.org/t/p/original/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg", answer: "The Good, the Bad and the Ugly", possibleAnswers: ["El Bueno, el Malo y el Feo"] },
    { image: "https://image.tmdb.org/t/p/original/h31SOVlekuHXsMWVGxI8nPPfY82.jpg", answer: "Once Upon a Time in the West", possibleAnswers: ["Hasta Que Llegó su Hora"] },
    { image: "https://image.tmdb.org/t/p/original/xlDUjb0Q5Dv6jPQRF5VE4IMjIy.jpg", answer: "Once Upon a Time in America", possibleAnswers: ["Érase una Vez en América"] },
    { image: "https://image.tmdb.org/t/p/original/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg", answer: "Seven Samurai", possibleAnswers: ["Los Siete Samuráis"] },
    { image: "https://image.tmdb.org/t/p/original/tDn1dA52bQH9B85vilHeU7C83W1.jpg", answer: "Rashomon" },
    { image: "https://image.tmdb.org/t/p/original/5BBwSVytssbFuSPZE4DtJVhROjN.jpg", answer: "Yojimbo" },
    { image: "https://image.tmdb.org/t/p/original/3ssNAWypRl47iriwBFNx7RUEUub.jpg", answer: "Ran" },
    { image: "https://image.tmdb.org/t/p/original/pQ06lTkmJd1mbotdl847HoV2iaA.jpg", answer: "Ikiru", possibleAnswers: ["Vivir"] },
    { image: "https://image.tmdb.org/t/p/original/i1NjlccZcuqbgDCS92RHdhEnx59.jpg", answer: "High and Low", possibleAnswers: ["Entre el Cielo y el Infierno"] },
    { image: "https://image.tmdb.org/t/p/original/7qsKE8GsgjreeQ2mTLd5oKZ7Tbf.jpg", answer: "Kagemusha", possibleAnswers: ["La Sombra del Guerrero"] },
    { image: "https://image.tmdb.org/t/p/original/rohRr9XqTRF8YwLMGAnTprg3GnL.jpg", answer: "Throne of Blood", possibleAnswers: ["Trono de Sangre"] },
    { image: "https://image.tmdb.org/t/p/original/VCebm5PHUChrD0ve24O1dThnxU.jpg", answer: "The Hidden Fortress", possibleAnswers: ["La Fortaleza Escondida"] },
    { image: "https://image.tmdb.org/t/p/original/6s2BqtDvp1BMiP70zCDU5OW6hMy.jpg", answer: "The Seventh Seal", possibleAnswers: ["El Séptimo Sello"] },
    { image: "https://image.tmdb.org/t/p/original/BBVAUchYvkmPThVIqipgAfabfl.jpg", answer: "Wild Strawberries", possibleAnswers: ["Fresas Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/amr72SENYz7AM4Hq5WBXxFBJEY6.jpg", answer: "Persona" },
    { image: "https://image.tmdb.org/t/p/original/8reX3CMog1QHqGoym2Esvuk5MnK.jpg", answer: "Fanny and Alexander", possibleAnswers: ["Fanny y Alexander"] },
    { image: "https://image.tmdb.org/t/p/original/eN2NdMeJLNzLYzWIEEoaGzZAsiD.jpg", answer: "La Dolce Vita" },
    { image: "https://image.tmdb.org/t/p/original/3cVrg7tzSf5AgEecYWDOSAzXAeX.jpg", answer: "Exit 8" },
    { image: "https://image.tmdb.org/t/p/original/iFQzlUmO5QmMPcSHHDdfd522x33.jpg", answer: "Amarcord" },
    { image: "https://image.tmdb.org/t/p/original/9yepEBnQNcKzWWyHdUiX8Mnqc6U.jpg", answer: "Nights of Cabiria", possibleAnswers: ["Las Noches de Cabiria"] },
    { image: "https://image.tmdb.org/t/p/original/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg", answer: "Sunset Boulevard" },
    { image: "https://image.tmdb.org/t/p/original/byQdu1nzQLI9t1VeoP1xuQfru3L.jpg", answer: "Double Indemnity", possibleAnswers: ["Pacto de Sangre"] },
    { image: "https://image.tmdb.org/t/p/original/5zTwAcnI3zCJ0mucPPnoBtkSWEV.jpg", answer: "Some Like It Hot", possibleAnswers: ["Una Eva y Dos Adanes"] },
    { image: "https://image.tmdb.org/t/p/original/2L8U8rUyWeFTb6n1egTNeJsEsvj.jpg", answer: "The Apartment", possibleAnswers: ["El Apartamento"] },
    { image: "https://image.tmdb.org/t/p/original/Ma7mQsldFCaQpsZbm8zolgLfmV.jpg", answer: "City Lights", possibleAnswers: ["Luces de la Ciudad"] },
    { image: "https://image.tmdb.org/t/p/original/kSlO1pHpwQfPQdgVPr7dJiJNtJ8.jpg", answer: "Modern Times", possibleAnswers: ["Tiempos Modernos"] },
    { image: "https://image.tmdb.org/t/p/original/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg", answer: "The Great Dictator", possibleAnswers: ["El Gran Dictador"] },
    { image: "https://image.tmdb.org/t/p/original/hZHeDPQGNKN9NN9GuW7qVbM2tDx.jpg", answer: "The Gold Rush", possibleAnswers: ["La Quimera del Oro"] },
    { image: "https://image.tmdb.org/t/p/original/ruF3Lmd4A8MHbnEBE6lxPMbsHGL.jpg", answer: "Citizen Kane", possibleAnswers: ["El Ciudadano Kane"] },
    { image: "https://image.tmdb.org/t/p/original/ousBoWTm1CltjAGSYOELYP0jFFC.jpg", answer: "Touch of Evil", possibleAnswers: ["Sed de Mal"] },
    { image: "https://image.tmdb.org/t/p/original/z30x999Uku15xcFbe5s3hLvQPDl.jpg", answer: "Lawrence of Arabia", possibleAnswers: ["Lawrence de Arabia"] },
    { image: "https://image.tmdb.org/t/p/original/dRHfCeAoJ6SsMffQ6lavNU9E55z.jpg", answer: "The Bridge on the River Kwai", possibleAnswers: ["El Puente sobre el Río Kwai"] },
    { image: "https://image.tmdb.org/t/p/original/wUaDgHfW7fViru7IubWa6Nronq9.jpg", answer: "Doctor Zhivago" },
    { image: "https://image.tmdb.org/t/p/original/a5zBQfXmLk3qqRYF7AioWpiAxk2.jpg", answer: "The Deer Hunter", possibleAnswers: ["El Cazador"] },
    { image: "https://image.tmdb.org/t/p/original/zGgIlpKE2xP18bhCGsnn79vh80j.jpg", answer: "Das Boot", possibleAnswers: ["El Submarino"] },
    { image: "https://image.tmdb.org/t/p/original/txXPooNu7fr4YhLwx7AlXkU0PnN.jpg", answer: "Patton" },
    { image: "https://image.tmdb.org/t/p/original/q8niSuT02ZlBJDfCxoK2YZal3PL.jpg", answer: "The Great Escape", possibleAnswers: ["La Gran Evasión"] },
    { image: "https://image.tmdb.org/t/p/original/gZqkMnORel0oiE0oSrBPfVQPB9w.jpg", answer: "The Dirty Dozen", possibleAnswers: ["Los Doce del Patíbulo"] },
    { image: "https://image.tmdb.org/t/p/original/nk5gq5rNLBJiHvNGMRT6I9VRQX7.jpg", answer: "Ben-Hur" },
    { image: "https://image.tmdb.org/t/p/original/9caD0fGCrp96JTFFeGyI0CGNj7.jpg", answer: "Spartacus", possibleAnswers: ["Espartaco"] },
    { image: "https://image.tmdb.org/t/p/original/k29qVmwWwR0i5A1UMIws1Vmv6hV.jpg", answer: "The Last Emperor", possibleAnswers: ["El Último Emperador"] },
    { image: "https://image.tmdb.org/t/p/original/gum3tuO1zKHBdElSQPS08PJ1w67.jpg", answer: "Gandhi" },
    { image: "https://image.tmdb.org/t/p/original/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg", answer: "The Matrix", possibleAnswers: ["Matrix"] },
    { image: "https://image.tmdb.org/t/p/original/hPsCR1ny6GnctJkWqeJwihTDD7T.jpg", answer: "Gattaca" },
    { image: "https://image.tmdb.org/t/p/original/sWi4SSeVPii4NU365Df9vzX1yOX.jpg", answer: "Dark City", possibleAnswers: ["Ciudad en Tinieblas"] },
    { image: "https://image.tmdb.org/t/p/original/x2wOlXuK4NzPDQ0OBZiJjNNOp6Y.jpg", answer: "Total Recall", possibleAnswers: ["El Vengador del Futuro"] },
    { image: "https://image.tmdb.org/t/p/original/xACuC5FwpCdayrcCsJPxYzrl8BO.jpg", answer: "RoboCop" },
    { image: "https://image.tmdb.org/t/p/original/82lM4GJ9uuNvNDOEpxFy77uv4Ak.jpg", answer: "Predator: Badlands", possibleAnswers: ["Depredador: Tierras Salvajes"] },
    { image: "https://image.tmdb.org/t/p/original/aQwxkvskonfPByfj5PTriJuyFXr.jpg", answer: "The Fly", possibleAnswers: ["La Mosca"] },
    { image: "https://image.tmdb.org/t/p/original/be5T7oHxmDG4ytEimwPdmDHZD9N.jpg", answer: "The Crucifix: Blood of the Exorcist" },
    { image: "https://image.tmdb.org/t/p/original/5sfbPsenSrbH8pzVMjEd0LUu50Y.jpg", answer: "The Omen", possibleAnswers: ["La Profecía"] },
    { image: "https://image.tmdb.org/t/p/original/bvkPno6U02lLyvPWCnmibq4eIaN.jpg", answer: "Poltergeist" },
    { image: "https://image.tmdb.org/t/p/original/vh7np635kDIcfO6x2Y9ElgLJsuI.jpg", answer: "Scream" },
    { image: "https://image.tmdb.org/t/p/original/rUAn3Ul1tL7JXMjZ951UOI3F0UA.jpg", answer: "Misery" },
    { image: "https://image.tmdb.org/t/p/original/l0JgqFNxeMb1OoHq1CzdYC3Y5J8.jpg", answer: "Candyman" },
    { image: "https://image.tmdb.org/t/p/original/h1x4YiBtQEGY2dMx7k0fvlErlSn.jpg", answer: "Night of the Living Dead", possibleAnswers: ["La Noche de los Muertos Vivientes"] },
    { image: "https://image.tmdb.org/t/p/original/rspbS1E9wJtslrb8amfJgtMBUVh.jpg", answer: "Dawn of the Dead", possibleAnswers: ["El Amanecer de los Muertos"] },
    { image: "https://image.tmdb.org/t/p/original/onq6lsJLX8ay5iwxEbKX3qJKeO9.jpg", answer: "The Evil Dead", possibleAnswers: ["Diabólico"] },
    { image: "https://image.tmdb.org/t/p/original/dOvEJK2u0slAGTfhdZOjnNgCQet.jpg", answer: "Evil Dead II", possibleAnswers: ["Terroríficamente Muertos"] },
    { image: "https://image.tmdb.org/t/p/original/bvk2AAH64lP2YZs02Q3jskfHT8j.jpg", answer: "Die Hard", possibleAnswers: ["Duro de Matar"] },
    { image: "https://image.tmdb.org/t/p/original/oAA0nLghMmlvUH1uPiS7HVcCpnc.jpg", answer: "Lethal Weapon", possibleAnswers: ["Arma Mortal"] },
    { image: "https://image.tmdb.org/t/p/original/lywmuPU5Hr1Mnpb9UGeDbILmkTx.jpg", answer: "Speed", possibleAnswers: ["Máxima Velocidad"] },
    { image: "https://image.tmdb.org/t/p/original/tsSWHgaFlzzkp3o976juBZbmcs2.jpg", answer: "Face/Off", possibleAnswers: ["Contracara"] },
    { image: "https://image.tmdb.org/t/p/original/qDVdTL1KqGmGLGsy7UPA3vksku7.jpg", answer: "The Rock", possibleAnswers: ["La Roca"] },
    { image: "https://image.tmdb.org/t/p/original/vsmlShNNHrYlERZaqMOsZ3YctoO.jpg", answer: "Con Air" },
    { image: "https://image.tmdb.org/t/p/original/hCxxOJojCUFyuahDx167glJgp7E.jpg", answer: "First Blood", possibleAnswers: ["Rambo: Acorralado"] },
    { image: "https://image.tmdb.org/t/p/original/xUZ2G8MRGEljqgqLxMJItK4iHfY.jpg", answer: "Rocky" },
    { image: "https://image.tmdb.org/t/p/original/5aZ2PDpNhjTdk77uSAIDzrpsAUr.jpg", answer: "Rocky II" },
    { image: "https://image.tmdb.org/t/p/original/ljOHSIyTbxdkQFjcJyWKfGm2i2r.jpg", answer: "Rocky III" },
    { image: "https://image.tmdb.org/t/p/original/uiUb4KJ6tadldqlJme49TW1r3jA.jpg", answer: "Rocky IV" },
    { image: "https://image.tmdb.org/t/p/original/aSA7RuKmCQBnYKn70GYPi6ckgoY.jpg", answer: "Bloodsport", possibleAnswers: ["Contacto Sangriento"] },
    { image: "https://image.tmdb.org/t/p/original/v8DepuF6gizphLzIyNZeQiB0hij.jpg", answer: "The Karate Kid" },
    { image: "https://image.tmdb.org/t/p/original/4W6RYDNe4OByNryOCvJprrutm9h.jpg", answer: "Groundhog Day", possibleAnswers: ["Hechizo del Tiempo"] },
    { image: "https://image.tmdb.org/t/p/original/3KDHaahgXlUhmpXzoRZrLc7QSBM.jpg", answer: "Ghostbusters", possibleAnswers: ["Los Cazafantasmas"] },
    { image: "https://image.tmdb.org/t/p/original/wQyvrsNSTzFVEGgarZbFkFyIciy.jpg", answer: "Airplane!", possibleAnswers: ["¿Y Dónde Está el Piloto?"] },
    { image: "https://image.tmdb.org/t/p/original/1wi1hcbl6KYqARjdQ4qrBWZdiau.jpg", answer: "The Naked Gun", possibleAnswers: ["La Pistola Desnuda"] },
    { image: "https://image.tmdb.org/t/p/original/1KgXxv6tHXOnakqYvMPvFwYKWiw.jpg", answer: "Monty Python and the Holy Grail", possibleAnswers: ["Los Caballeros de la Mesa Cuadrada y sus Locos Seguidores"] },
    { image: "https://image.tmdb.org/t/p/original/lOrM3OQhHlzEkpF7Ih3GghecrA8.jpg", answer: "Life of Brian", possibleAnswers: ["La Vida de Brian"] },
    { image: "https://image.tmdb.org/t/p/original/2CisgvF2HcIVnbMZbSjASCtSgEb.jpg", answer: "The Princess Bride", possibleAnswers: ["La Princesa Prometida"] },
    { image: "https://image.tmdb.org/t/p/original/leehjwM57DKJ79XMUll4oAF0kin.jpg", answer: "Ferris Bueller's Day Off", possibleAnswers: ["Todo en Un Día"] },
    { image: "https://image.tmdb.org/t/p/original/kjVgUMsG0PKBXzlP8HGNQpWDxAX.jpg", answer: "The Breakfast Club", possibleAnswers: ["El Club de los Cinco"] },
    { image: "https://image.tmdb.org/t/p/original/f9X91dUckoRzOZlw4XBUOfkN9FC.jpg", answer: "Mrs. Doubtfire", possibleAnswers: ["Papá por Siempre"] },
    { image: "https://image.tmdb.org/t/p/original/a8tH0jl37366bLVyPB08dncgqqd.jpg", answer: "Home Sweet Home Alone", possibleAnswers: ["Mi Pobre Angelito: Solo en Casa"] },
    { image: "https://image.tmdb.org/t/p/original/bQlw59HncOXX9alFlOYKHAvSnm.jpg", answer: "The Mask", possibleAnswers: ["La Máscara"] },
    { image: "https://image.tmdb.org/t/p/original/nbvREKIjX16mwNZtFqAoQTTHPnQ.jpg", answer: "Ace Ventura: Pet Detective", possibleAnswers: ["Ace Ventura: Detective de Mascotas"] },
    { image: "https://image.tmdb.org/t/p/original/8uBTDGRcNHhYChcoazP5rleRME7.jpg", answer: "Dumb and Dumber", possibleAnswers: ["Tonto y Retonto"] },
    { image: "https://image.tmdb.org/t/p/original/87wqeMeUeMRLjsE1IWNKJcPlpuC.jpg", answer: "Casablanca" },
    { image: "https://image.tmdb.org/t/p/original/4FHcxMtVruMr7ltU2cItWssLjTP.jpg", answer: "Gone with the Wind", possibleAnswers: ["Lo que el Viento se Llevó"] },
    { image: "https://image.tmdb.org/t/p/original/gzRISGjiDMj4xqYE9ES2KNIXxpo.jpg", answer: "Roman Holiday", possibleAnswers: ["Vacaciones en Roma"] },
    { image: "https://image.tmdb.org/t/p/original/jXZ2tyJl44yKvh22I6ooQwU5rFM.jpg", answer: "Breakfast at Tiffany's", possibleAnswers: ["Desayuno en Tiffany's"] },
    { image: "https://image.tmdb.org/t/p/original/sGEqHTylawwS6hwKultk1mKUjdB.jpg", answer: "Pretty Woman" },
    { image: "https://image.tmdb.org/t/p/original/i8aIbji5vcPoHwcLBZYQSniGkAI.jpg", answer: "When Harry Met Sally...", possibleAnswers: ["Cuando Harry Conoció a Sally"] },
    { image: "https://image.tmdb.org/t/p/original/6nLdSON3ErniBZTXWG7WRqs5jGz.jpg", answer: "Ghost", possibleAnswers: ["Ghost: La Sombra del Amor"] },
    { image: "https://image.tmdb.org/t/p/original/6iDQCBUSZKzY8Rnu8ECwl2gXcfG.jpg", answer: "Dirty Dancing" },
    { image: "https://image.tmdb.org/t/p/original/enTZhfxAdgOCdFdbj52MR3F10yC.jpg", answer: "Notting Hill" },
    { image: "https://image.tmdb.org/t/p/original/xj1Sv1xm4Y0ydBueGuf10Y9qM0O.jpg", answer: "Good Will Hunting", possibleAnswers: ["En Busca del Destino"] },
    { image: "https://image.tmdb.org/t/p/original/lFIXZpwwlF9hg8NM3RazaIJDuaj.jpg", answer: "Dead Poets Society", possibleAnswers: ["La Sociedad de los Poetas Muertos"] },
    { image: "https://image.tmdb.org/t/p/original/b3tos7Tsd6lsTe52Nn4TMrEQg65.jpg", answer: "Rain Man" },
    { image: "https://image.tmdb.org/t/p/original/2ndw55F40IkALzWyjCCza3M6nqM.jpg", answer: "American Beauty" },
    { image: "https://image.tmdb.org/t/p/original/aCHn2TXYJfzPXQKA6r9mKPbMlUB.jpg", answer: "The Truman Show", possibleAnswers: ["El Show de Truman"] },
    { image: "https://image.tmdb.org/t/p/original/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg", answer: "The Sixth Sense", possibleAnswers: ["El Sexto Sentido"] },
    { image: "https://image.tmdb.org/t/p/original/hy0Hx9fMPk2fmw26Li60z1S2giU.jpg", answer: "The Usual Suspects", possibleAnswers: ["Los Sospechosos de Siempre"] },
    { image: "https://image.tmdb.org/t/p/original/hUn13Hom8OWMYpR1ay0diwswwdP.jpg", answer: "L.A. Confidential", possibleAnswers: ["Los Ángeles al Desnudo"] },
    { image: "https://image.tmdb.org/t/p/original/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg", answer: "Cinema Paradiso" },
    { image: "https://image.tmdb.org/t/p/original/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg", answer: "Life Is Beautiful", possibleAnswers: ["La Vida es Bella"] },
    { image: "https://image.tmdb.org/t/p/original/viGCwLxupyoaLsa6hrnu1gYrB0B.jpg", answer: "La Haine", possibleAnswers: ["El Odio"] },
    { image: "https://image.tmdb.org/t/p/original/ze7GsNSv418o7pzqc9fb00LWWDk.jpg", answer: "The Battle of Algiers", possibleAnswers: ["La Batalla de Argel"] },
    { image: "https://image.tmdb.org/t/p/original/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg", answer: "Harakiri" },
    { image: "https://image.tmdb.org/t/p/original/dxfFh9pTKDaYH2B6PwcR6ohCM1L.jpg", answer: "Woman in the Dunes", possibleAnswers: ["La Mujer de la Arena"] },
    { image: "https://image.tmdb.org/t/p/original/6yrbWzzrPp7pwz6zHdifspJk8t3.jpg", answer: "Stalker" },
    { image: "https://image.tmdb.org/t/p/original/qOGuM0QINhH7MfNAiOZtmlaDLgj.jpg", answer: "Solaris" },
    { image: "https://image.tmdb.org/t/p/original/jqha8JCXm0aJ5SJ03Jd0JmGgWRs.jpg", answer: "Andrei Rublev" },
    { image: "https://image.tmdb.org/t/p/original/kfSZaOr9ApNR52gWKlpXHD0id0W.jpg", answer: "Aguirre, the Wrath of God", possibleAnswers: ["Aguirre, la Cólera de Dios"] },
    { image: "https://image.tmdb.org/t/p/original/46iMqI1qzAtnXJxGRNCFwYNYqOo.jpg", answer: "Fitzcarraldo" },
    { image: "https://image.tmdb.org/t/p/original/fWrq3u16gaBJ6nYNWcR3XaOhQPq.jpg", answer: "Paris, Texas" },
    { image: "https://image.tmdb.org/t/p/original/7TlGXrB4WQ3wbpOCUQnBXseCuOl.jpg", answer: "Wings of Desire", possibleAnswers: ["El Cielo Sobre Berlín"] },
    { image: "https://image.tmdb.org/t/p/original/nAyUVvcdOKHmukdgGHZ7xR5er1q.jpg", answer: "Three Colors: Blue", possibleAnswers: ["Tres Colores: Azul"] },
    { image: "https://image.tmdb.org/t/p/original/b1CVjSYinzm6tx1TGA7c75W8X9k.jpg", answer: "Three Colors: White", possibleAnswers: ["Tres Colores: Blanco"] },
    { image: "https://image.tmdb.org/t/p/original/pZcoSJUb3Lgr9Rzg2shg1PtTBP9.jpg", answer: "Three Colors: Red", possibleAnswers: ["Tres Colores: Rojo"] },
    { image: "https://image.tmdb.org/t/p/original/vuglA60RqvpHK9rIcG8sXaiWw1L.jpg", answer: "Chungking Express" },
    { image: "https://image.tmdb.org/t/p/original/ffQFnAUm2Uu4RU0nijpjPRf9TBT.jpg", answer: "In the Mood for Love", possibleAnswers: ["Deseando Amar"] },
    { image: "https://image.tmdb.org/t/p/original/qYQmznfMC433HrX5m58MJB0QOlK.jpg", answer: "The Official Story", possibleAnswers: ["La Historia Oficial"] },
    { image: "https://image.tmdb.org/t/p/original/3c9csN2cguE6KwIEcJJ06pQVl5s.jpg", answer: "Waiting for the Hearse", possibleAnswers: ["Esperando la Carroza"] },
    { image: "https://image.tmdb.org/t/p/original/8L8eulemyt46IBL1PDOtJlJUvNk.jpg", answer: "Camila Jam", possibleAnswers: ["Camila"] },
    { image: "https://image.tmdb.org/t/p/original/rg4XBpSQqMDiA0YQiSTxoWJYsIL.jpg", answer: "Time for Revenge", possibleAnswers: ["Tiempo de Revancha"] },
    { image: "https://image.tmdb.org/t/p/original/xRgvH4nm73AwOfwlt0hipHUsKNT.jpg", answer: "Sweet Money", possibleAnswers: ["Plata Dulce"] },
    { image: "https://image.tmdb.org/t/p/original/e4tZvefBtA6P1T0vAPfeXG4Bj3r.jpg", answer: "Nine Queens", possibleAnswers: ["Nueve Reinas"] },
];
