import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const animatedMovieQuestions: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/4yWayBvwl9gHXaWrDrAslxjL7mh.jpg", answer: "Snow White and the Seven Dwarfs", possibleAnswers: ["Blancanieves y los siete enanitos"] },
    { image: "https://image.tmdb.org/t/p/original/q7vmCCmyiHnuKGMzHZlr0fD44b9.jpg", answer: "Cinderella", possibleAnswers: ["La Cenicienta"] },
    { image: "https://image.tmdb.org/t/p/original/me67dwJnUBt3O9NqZaBdEQ6i4vM.jpg", answer: "Sleeping Beauty", possibleAnswers: ["La Bella Durmiente"] },
    { image: "https://image.tmdb.org/t/p/original/pbMbDlOAkVuvnxovBA2ENin59xH.jpg", answer: "The Little Mermaid", possibleAnswers: ["La Sirenita"] },
    { image: "https://image.tmdb.org/t/p/original/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg", answer: "Beauty and the Beast", possibleAnswers: ["La Bella y la Bestia"] },
    { image: "https://image.tmdb.org/t/p/original/nenJjvfe2Eq8uBMXFJnWj5mw4bi.jpg", answer: "Aladdin", possibleAnswers: ["Aladdín"] },
    { image: "https://image.tmdb.org/t/p/original/fDZ2DCKW2D7J0ABNr9EICdD2H1s.jpg", answer: "Pocahontas", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mUYV0ZdsDEliGaQahcQH1F3grsP.jpg", answer: "Mulan", possibleAnswers: ["Mulán"] },
    { image: "https://image.tmdb.org/t/p/original/y5tad0a4yRbxYgOHGllEIEeCCKt.jpg", answer: "The Princess and the Frog", possibleAnswers: ["La Princesa y el Sapo"] },
    { image: "https://image.tmdb.org/t/p/original/cWczNud8Y8i8ab0Z4bxos4myWYO.jpg", answer: "Tangled", possibleAnswers: ["Enredados"] },
    { image: "https://image.tmdb.org/t/p/original/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg", answer: "Frozen", possibleAnswers: ["Frozen: Una aventura congelada"] },
    { image: "https://image.tmdb.org/t/p/original/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg", answer: "Frozen II", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg", answer: "Moana", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/zmX7ObPaRfiCmY6LMalUb1bJDKj.jpg", answer: "Raya and the Last Dragon", possibleAnswers: ["Raya y el último dragón"] },
    { image: "https://image.tmdb.org/t/p/original/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg", answer: "Encanto", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4D1pdB27uph7J8HQzNf8QvvH9bn.jpg", answer: "Toy Story 5", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/7iUDfakacY1HpajP1DtHrCuDB95.jpg", answer: "Toy Story 2", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/uAfhsySkr1UzQg1zdg3dZQRz9Fd.jpg", answer: "Toy Story 3", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/q62bpQ67qaXY0u6b2wFEnQYIbPd.jpg", answer: "Toy Story 4", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/hwwFyowfcbLRVmRBOkvnABBNIOs.jpg", answer: "A Bug's Life", possibleAnswers: ["Bichos, una aventura en miniatura"] },
    { image: "https://image.tmdb.org/t/p/original/sDTnMOJ3H5wI38OxObmCtK7wfd5.jpg", answer: "Monsters, Inc.", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mIpCxBWNz6SHCQBe2K2PFr5MB7f.jpg", answer: "Monsters University", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/eCynaAOgYYiw5yN5lBwz3IxqvaW.jpg", answer: "Finding Nemo", possibleAnswers: ["Buscando a Nemo"] },
    { image: "https://image.tmdb.org/t/p/original/wijltj1toRcicHlCn8Cpsp4yPXe.jpg", answer: "Finding Dory", possibleAnswers: ["Buscando a Dory"] },
    { image: "https://image.tmdb.org/t/p/original/lxwzY9vNwjDgxWKt3zZ6zcU6rEJ.jpg", answer: "The Incredibles", possibleAnswers: ["Los Increíbles"] },
    { image: "https://image.tmdb.org/t/p/original/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg", answer: "Incredibles 2", possibleAnswers: ["Los Increíbles 2"] },
    { image: "https://image.tmdb.org/t/p/original/xgDj56UWyeWQcxQ44f5A3RTWuSs.jpg", answer: "Ratatouille", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/qE0FswzjACs2kvAycYVS2zcmgec.jpg", answer: "Balls Up", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/o3i6AfTcWAuNvzAUV3q5lOmi6Gx.jpg", answer: "Inside Out", possibleAnswers: ["Intensa-Mente"] },
    { image: "https://image.tmdb.org/t/p/original/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg", answer: "Inside Out 2", possibleAnswers: ["Intensa-Mente 2"] },
    { image: "https://image.tmdb.org/t/p/original/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg", answer: "Coco", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/rQaHA74pevnGsxcKGaoZVGWe9TC.jpg", answer: "Soul", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg", answer: "Luca", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/q00H8EqULYSK74lgevMkhmGGLHn.jpg", answer: "The Lion King", possibleAnswers: ["El Rey León"] },
    { image: "https://image.tmdb.org/t/p/original/a0E1mbejev56Ii51hCnYUDj4tZS.jpg", answer: "Tarzan", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/oG9dcGSSu13fjFp1Uly15ZXjRKV.jpg", answer: "Hercules", possibleAnswers: ["Hércules"] },
    { image: "https://image.tmdb.org/t/p/original/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg", answer: "Lilo & Stitch", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mZj8EUr6F1x2PWZjKPxaeYd5WRw.jpg", answer: "The Emperor's New Groove", possibleAnswers: ["Las locuras del emperador"] },
    { image: "https://image.tmdb.org/t/p/original/lgotja3xMoJZbynwHfcQcJAEMWH.jpg", answer: "Zootopia 2", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4s2d3xdyqotiVNHTlTlJjrr3q0H.jpg", answer: "Big Hero 6", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/sRvXNDItGlWCqtO3j6wks52FmbD.jpg", answer: "Shrek", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8ohobj5lAIbl5XWw11FywS3IRrS.jpg", answer: "Shrek 2", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/wvXxKpFGXvQJRB0nvvfURhRD3C0.jpg", answer: "Shrek the Third", possibleAnswers: ["Shrek Tercero"] },
    { image: "https://image.tmdb.org/t/p/original/uzzTystB8lL0mRDII5Sfs5HxgkI.jpg", answer: "Shrek Forever After", possibleAnswers: ["Shrek para siempre"] },
    { image: "https://image.tmdb.org/t/p/original/qdthf9WrRDSaIkGVQGhhJ9pz1hn.jpg", answer: "Kung Fu Panda", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/reHkSQwiYKK4SabnGDY1FWKie82.jpg", answer: "Kung Fu Panda 2", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/s3FiHTdpQVpqIqdBxLLiy40wGut.jpg", answer: "Kung Fu Panda 3", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/AeDzjt00Hfh9CuW7TIUdYBJmWYM.jpg", answer: "How to Train Your Dragon", possibleAnswers: ["Cómo entrenar a tu dragón"] },
    { image: "https://image.tmdb.org/t/p/original/8AAuJtCzaibYkbE0QVHc8EBsELB.jpg", answer: "How to Train Your Dragon 2", possibleAnswers: ["Cómo entrenar a tu dragón 2"] },
    { image: "https://image.tmdb.org/t/p/original/h3KN24PrOheHVYs9ypuOIdFBEpX.jpg", answer: "How to Train Your Dragon: The Hidden World", possibleAnswers: ["Cómo entrenar a tu dragón 3: El mundo oculto"] },
    { image: "https://image.tmdb.org/t/p/original/tPaurpIUskVji5vwV0dhy9pq4Vs.jpg", answer: "Madagascar", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3yXLkSTrVhG66MIAr3X6C4gjccw.jpg", answer: "Madagascar: Escape 2 Africa", possibleAnswers: ["Madagascar 2"] },
    { image: "https://image.tmdb.org/t/p/original/uDR9UjSuykTL8g3N3bh3siZ4n3C.jpg", answer: "Madagascar 3: Europe's Most Wanted", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg", answer: "Spirited Away", possibleAnswers: ["El viaje de Chihiro"] },
    { image: "https://image.tmdb.org/t/p/original/zkThiZAaAie8Lw7RAc5yPTOewBV.jpg", answer: "My Neighbor Totoro", possibleAnswers: ["Mi vecino Totoro"] },
    { image: "https://image.tmdb.org/t/p/original/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg", answer: "Princess Mononoke", possibleAnswers: ["La princesa Mononoke"] },
    { image: "https://image.tmdb.org/t/p/original/nv5wwZou159v5OC61i4ElR7OqyY.jpg", answer: "Howl's Moving Castle", possibleAnswers: ["El increíble castillo vagabundo"] },
    { image: "https://image.tmdb.org/t/p/original/h5pAEVma835u8xoE60kmLVopLct.jpg", answer: "Kiki's Delivery Service", possibleAnswers: ["Nicky, la aprendiz de bruja"] },
    { image: "https://image.tmdb.org/t/p/original/shqLeIkqPAAXM8iT6wVDiXUYz1p.jpg", answer: "Ponyo", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/938lqhAQaO3hmLg44VbUR7OqlMs.jpg", answer: "The Wind Rises", possibleAnswers: ["El viento se levanta"] },
    { image: "https://image.tmdb.org/t/p/original/ulVUa2MvnJAjAeRt7h23FFJVRKH.jpg", answer: "Warriors of the Wind", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/pgWLJI42GG98S1DqjTELLtB7VPB.jpg", answer: "Grave of the Fireflies", possibleAnswers: ["La tumba de las luciérnagas"] },
    { image: "https://image.tmdb.org/t/p/original/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg", answer: "Your Name.", possibleAnswers: ["Tu nombre"] },
    { image: "https://image.tmdb.org/t/p/original/ize3ZieqSy0TCWljmVoEiy8fSFS.jpg", answer: "Weathering with You", possibleAnswers: ["El tiempo contigo"] },
    { image: "https://image.tmdb.org/t/p/original/4tdV5AeojEdbvn6VpeQrbuDlmzs.jpg", answer: "Suzume", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg", answer: "A Silent Voice: The Movie", possibleAnswers: ["La forma de la voz"] },
    { image: "https://image.tmdb.org/t/p/original/oMqgJMCaNIqeJtilc71D4nRqdmt.jpg", answer: "Wolf Children", possibleAnswers: ["Los niños lobo: Ame y Yuki"] },
    { image: "https://image.tmdb.org/t/p/original/fK40VGYIm7hmKrLJ26fgPQU0qRG.jpg", answer: "Akira", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/gTRXgigmgKpeJjW07iq686HZyBD.jpg", answer: "Ghost in the Shell", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mHG7dpLb0ZScSY3LpP443IHRmjy.jpg", answer: "Perfect Blue", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/6oXn0037WWw4fTCc3Qczof71lSp.jpg", answer: "Paprika", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/hofnlIyF6bePkgQOpcuRWLvzf15.jpg", answer: "Coraline", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/dSfrsjhqC6lYe7LYDYnzWeXZmEl.jpg", answer: "The Nightmare Before Christmas", possibleAnswers: ["El extraño mundo de Jack"] },
    { image: "https://image.tmdb.org/t/p/original/v23fWgJUEt8EMmvn19btIacxP8E.jpg", answer: "Corpse Bride", possibleAnswers: ["El cadáver de la novia"] },
    { image: "https://image.tmdb.org/t/p/original/mOtKQlXdL5J4lwqcSFlkZmgmFeZ.jpg", answer: "Rango", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/fRhpdmaA1wTAboeiKW2ZHvDezIm.jpg", answer: "ParaNorman", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bhspYsRMHgMqzUlxiVpIY8OrqMt.jpg", answer: "Kubo and the Two Strings", possibleAnswers: ["Kubo y la búsqueda samurái"] },
    { image: "https://image.tmdb.org/t/p/original/3eYkMSjWbvTaZso7ow5ub9ikNNq.jpg", answer: "Chicken Run", possibleAnswers: ["Pollitos en fuga"] },
    { image: "https://image.tmdb.org/t/p/original/Aqvtwgu1G4eEwIf8nSIxiCN5ewC.jpg", answer: "Wallace & Gromit: The Curse of the Were-Rabbit", possibleAnswers: ["Wallace y Gromit: La maldición de las verduras"] },
    { image: "https://image.tmdb.org/t/p/original/4XPNNt0zfZKBqxxVWaQALd57UHl.jpg", answer: "Flow", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/jl2YIADk391yc6Qjy9JhgCRkHJk.jpg", answer: "Memoir of a Snail", possibleAnswers: ["Memorias de un caracol"] },
    { image: "https://image.tmdb.org/t/p/original/cYQvXNPZLow73lhspVQ7CYlT3Mi.jpg", answer: "Klaus", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg", answer: "Spider-Man: Into the Spider-Verse", possibleAnswers: ["Spider-Man: Un nuevo universo"] },
    { image: "https://image.tmdb.org/t/p/original/9xfDWXAUbFXQK585JvByT5pEAhe.jpg", answer: "Spider-Man: Across the Spider-Verse", possibleAnswers: ["Spider-Man: A través del Spider-Verso"] },
    { image: "https://image.tmdb.org/t/p/original/e782pDRAlu4BG0ahd777n8zfPzZ.jpg", answer: "Guillermo del Toro's Pinocchio", possibleAnswers: ["Pinocho de Guillermo del Toro"] },
    { image: "https://image.tmdb.org/t/p/original/75nSb1fbWooipwcSU5bUttiOriI.jpg", answer: "The Boy and the Heron", possibleAnswers: ["El niño y la garza"] },
    { image: "https://image.tmdb.org/t/p/original/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg", answer: "Turning Red", possibleAnswers: ["Red"] },
    { image: "https://image.tmdb.org/t/p/original/vsZLf5uog08pAnfsMuDWrsLWUUF.jpg", answer: "The Mitchells vs. the Machines", possibleAnswers: ["Los Mitchell contra las máquinas"] },
    { image: "https://image.tmdb.org/t/p/original/xI5oKkOyu7H9Wm18C7U4oJYXIWo.jpg", answer: "Marcel the Shell with Shoes On, Three", possibleAnswers: [] },
];
