import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const personajesPeliculas: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/en/5/52/American-psycho-patrick-bateman.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Patrick Bateman" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/4a/The_Narrator_%28Edward_Norton%2C_left%29_and_Tyler_Durden_%28Brad_Pitt%2C_right%29_from_Fight_Club_%281999%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Narrador / Tyler Durden" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/JordanBelfort2017.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Jordan Belfort" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Darth_Vader_at_Galaxy%E2%80%99s_Edge_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Darth Vader" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Daniel_Radcliffe_as_Harry_Potter.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Harry Potter" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/42/Mia_Wallace.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Mia Wallace" },
    { image: "https://upload.wikimedia.org/wikipedia/en/7/7d/The_bride_%28kill_bill%29.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "La Novia" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/e8/Hans_Landa_IB_2009.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Hans Landa" },
    { image: "https://upload.wikimedia.org/wikipedia/en/d/df/Michaelcoreleone.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Michael Corleone" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Marlon_Brando_as_Vito_Corleone_%28high_quality%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Vito Corleone" },
    { image: "https://upload.wikimedia.org/wikipedia/en/1/19/Tony_Montana_in_Scarface_%281983%29%2C_portrayed_by_Al_Pacino.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Tony Montana" },
    { image: "https://upload.wikimedia.org/wikipedia/en/a/af/Travis_Bickle.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Travis Bickle" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Henry_Hill_%281980%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Henry Hill" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/69/FrankLucas.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Frank Lucas" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/6e/Hannibal_Lecter_in_Silence_of_the_Lambs.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Hannibal Lecter" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/b4/SOTLClariceLecter.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Clarice Starling" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Anthony_Perkins_Psycho_Publicity_Photo.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Norman Bates" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/bb/The_shining_heres_johnny.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Jack Torrance" },
    { image: "https://upload.wikimedia.org/wikipedia/en/1/19/Amy_Dunne.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Amy Dunne" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Malcolm_McDowell_Clockwork_Orange.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Alex DeLarge" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/6b/Randle_Patrick_McMurphy_picture.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Randle McMurphy" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/ed/Nurse_Ratched.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Enfermera Ratched" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Gregory_Peck_Atticus_Publicity_Photo.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Atticus Finch" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Vivien_Leigh_Gone_Wind_Restored.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Scarlett O'Hara" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Clark_Gable_as_Rhett_Butler_in_Gone_With_the_Wind_trailer.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Rhett Butler" },
    { image: "https://upload.wikimedia.org/wikipedia/en/c/c5/Fleming007impression.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "James Bond" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Johnny_Depp_as_Captain_Jack_Sparrow_in_Queensland%2C_Australia.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Jack Sparrow" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/60/Jason_bourne_infobox.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Jason Bourne" },
    { image: "https://upload.wikimedia.org/wikipedia/en/9/9f/John_Wick_Keanu.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "John Wick" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/53/Rocky_balboa.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Rocky Balboa" },
    { image: "https://upload.wikimedia.org/wikipedia/en/1/17/Ellen_ripley.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Ellen Ripley" },
    { image: "https://upload.wikimedia.org/wikipedia/en/d/d8/Michael_J._Fox_as_Marty_McFly_in_Back_to_the_Future%2C_1985.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Marty McFly" },
    { image: "https://upload.wikimedia.org/wikipedia/en/c/c9/Han_Solo_with_Blaster.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Han Solo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/67/Luke_Skywalker_-_Welcome_Banner_%28Cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Luke Skywalker" },
    { image: "https://upload.wikimedia.org/wikipedia/en/1/1b/Princess_Leia%27s_characteristic_hairstyle.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Princesa Leia" },
    { image: "https://upload.wikimedia.org/wikipedia/en/9/9b/Yoda_Empire_Strikes_Back.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Yoda" },
    { image: "https://upload.wikimedia.org/wikipedia/en/c/c6/NeoTheMatrix.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Neo" },
    { image: "https://upload.wikimedia.org/wikipedia/en/a/ab/Morpheus.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Morfeo" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/b9/Terminator-2-judgement-day.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Terminator" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/5f/Batman_Three_Jokers.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Joker" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/bd/Gandalf_from_The_Trolls_are_Turned_to_Stone_-_J.R.R_Tolkien.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Gandalf" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Gollum_at_Wellington_Airport.jpg/3840px-Gollum_at_Wellington_Airport.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Gollum" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Charlie_and_the_Chocolate_Factory_%281964%29_front_cover%2C_first_US_edition_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Willy Wonka" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/eb/Freddy_Krueger_%28Robert_Englund%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Freddy Krueger" },
    { image: "https://upload.wikimedia.org/wikipedia/en/f/f7/Jason_Voorhees_%28Ken_Kirzinger%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Jason Voorhees" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/e9/MichaelMyers2018.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Michael Myers" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/38/Chucky_Appearance_%28TV_Series%29.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Chucky" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/52/Pennywise_Skarsgard_and_Curry.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Pennywise" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/3b/Edwardscissorhandsposter.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Eduardo Manostijeras" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/5c/Keyser_S%C3%B6ze_-_photo.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Keyser Söze" },
    { image: "https://upload.wikimedia.org/wikipedia/en/1/1a/RoboCop_%28Peter_Weller%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "RoboCop" },
    { image: "https://upload.wikimedia.org/wikipedia/en/d/d3/Wolverine_%28circa_2024%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Wolverine" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/47/Iron_Man_%28circa_2018%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Iron Man" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/b7/Thanos_%28Infobox_image%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Thanos" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Katniss_Everdeen_%28Jennifer_Lawrence%29_figure_at_Madame_Tussauds_London_%2831139647115%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Katniss Everdeen" },
    { image: "https://upload.wikimedia.org/wikipedia/en/2/2a/Voldemort_book_and_film.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Voldemort" },
    { image: "https://upload.wikimedia.org/wikipedia/en/d/d3/Hermione_Granger_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Hermione Granger" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/5e/Ron_Weasley_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Ron Weasley" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/e8/Dumbledore_-_Prisoner_of_Azkaban.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Albus Dumbledore" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/b9/Ootp076.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Severus Snape" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/41/Anton_Chigurh.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Anton Chigurh" },
    { image: "https://upload.wikimedia.org/wikipedia/en/a/a6/Miranda_Priestly.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Miranda Priestly" },
    { image: "https://upload.wikimedia.org/wikipedia/en/0/0f/Regina_George.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Regina George" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/92/Frankenstein%2C_or_the_Modern_Prometheus_%28Revised_Edition%2C_1831%29_Creature.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Frankenstein's monster" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/39/Matilda-Mara-Wilson.webp?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Matilda Wormwood" },
    { image: "https://upload.wikimedia.org/wikipedia/en/1/1c/Agatha_Trunchbull.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Tronchatoro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Mickey_Mouse_%28poster_version%29.svg/960px-Mickey_Mouse_%28poster_version%29.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Mickey Mouse" },
    { image: "https://upload.wikimedia.org/wikipedia/en/9/94/Simba_%28_Disney_character_-_adult%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Simba" },
    { image: "https://upload.wikimedia.org/wikipedia/en/a/a0/Mufasa_promotional_image.webp?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Mufasa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Scar_%28xndr%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Scar" },
    { image: "https://upload.wikimedia.org/wikipedia/en/2/21/Baymax_%28Marvel_Comics%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Baymax" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Buzz_Lightyear_sculpture_of_Toy_Story_Hotel_Shanghai_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Buzz Lightyear" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/6a/Mike_Wazowski.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Mike Wazowski" },
    { image: "https://upload.wikimedia.org/wikipedia/en/9/9f/Carl_from_Up_2009.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Carl Fredricksen" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/3d/Po_from_DreamWorks_Animation%27s_Kung_Fu_Panda.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Po" },
    { image: "https://upload.wikimedia.org/wikipedia/en/0/09/Gru_from_DM4.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Gru" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/51/Ponyo.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Ponyo" },
    { image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Bugs_Bunny.svg/250px-Bugs_Bunny.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Bugs Bunny" },
    { image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Daffy_Duck.svg/330px-Daffy_Duck.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Pato Lucas" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/4c/GokumangaToriyama.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Goku" },
    { image: "https://upload.wikimedia.org/wikipedia/en/9/9a/NarutoUzumaki.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Naruto Uzumaki" },
    { image: "https://upload.wikimedia.org/wikipedia/en/c/cb/Monkey_D_Luffy.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Monkey D. Luffy" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/e5/SMVolume1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Sailor Moon" },
    { image: "https://upload.wikimedia.org/wikipedia/en/7/75/Cinderella2024design.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Cenicienta" },
    { image: "https://upload.wikimedia.org/wikipedia/en/7/77/Ariel_disney.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Ariel" },
    { image: "https://upload.wikimedia.org/wikipedia/en/d/d5/Belle_disney.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Bella" },
    { image: "https://upload.wikimedia.org/wikipedia/en/0/00/Jasmine_%28Aladdin%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Jasmín" },
    { image: "https://upload.wikimedia.org/wikipedia/en/0/0c/The_Genie_Aladdin.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "El Genio" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/5e/Elsa_from_Disney%27s_Frozen.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Elsa" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/6d/Olaf_from_Disney%27s_Frozen.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Olaf" },
    { image: "https://upload.wikimedia.org/wikipedia/en/5/56/Moana_%28character%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Moana" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Woody_at_Toy_Story_Land%2C_Hong_Kong.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Woody" },
    { image: "https://upload.wikimedia.org/wikipedia/en/8/82/Lightning_McQueen.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Rayo McQueen" },
    { image: "https://upload.wikimedia.org/wikipedia/en/f/f7/Mater_%28Cars%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Mate" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/30/Joy_-_Inside_Out.webp?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Alegría" },
    { image: "https://upload.wikimedia.org/wikipedia/en/b/b9/Princess_Fiona.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Fiona" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/6c/Donkey_%28Shrek%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Burro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Minion_sculpture_in_Brisbane%2C_2024.jpg/1920px-Minion_sculpture_in_Brisbane%2C_2024.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Los Minions" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/SpongeBob_character.svg/330px-SpongeBob_character.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Bob Esponja" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Patrick_Star_character.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Patricio Estrella" },
    { image: "https://upload.wikimedia.org/wikipedia/en/2/2e/Kristoff_Bjorgman.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Kristoff" },
    { image: "https://upload.wikimedia.org/wikipedia/en/c/ce/Sven_from_Frozen.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Sven" },
    { image: "https://upload.wikimedia.org/wikipedia/en/4/4a/Disney-beast.PNG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Bestia" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/e3/Ursula%28TheLittleMermaid%29character.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Úrsula" },
    { image: "https://upload.wikimedia.org/wikipedia/en/9/91/Pumbaa.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Timón y Pumba" },
    { image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Stitch_%28Lilo_%26_Stitch%29.svg/330px-Stitch_%28Lilo_%26_Stitch%29.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail", answer: "Stitch" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/05/Peter_pan_1911_pipes_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Peter Pan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Captain_Hook.PNG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Capitán Garfio" },
    { image: "https://upload.wikimedia.org/wikipedia/en/6/64/Cruella_de_Vil.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Cruella de Vil" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Pooh_Shepard1928.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Winnie Pooh" },
    { image: "https://upload.wikimedia.org/wikipedia/en/3/34/Pooh_meets_Tigger%2C_illustration_by_EH_Shepard.gif?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Tigger" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Mowgli-1895-illustration.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Mowgli" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/The_second_jungle_book_%281895%29_%28Baloo%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Baloo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Alice_par_John_Tenniel_04.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Alicia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tennel_Cheshire_proof.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Gato de Cheshire" },
    { image: "https://upload.wikimedia.org/wikipedia/en/e/ec/Scrat_Ice_Age.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled", answer: "Scrat" },
];
