import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const personajesHistoricos: CategoryQuestion[] = [
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Jos%C3%A9_de_San_Mart%C3%ADn_%28retrato%2C_c.1828%29.jpg", answer: "José de San Martín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Manuel_belgrano_by_carbonier_retouched.jpg", answer: "Manuel Belgrano" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Mariano_Moreno_en_su_mesa_de_trabajo.jpg", answer: "Mariano Moreno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/97/Cornelio_Saavedra_-_1810.jpg", answer: "Cornelio Saavedra" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Bernardino_Rivadavia_2.jpg", answer: "Bernardino Rivadavia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Juan_Manuel_de_Rosas.jpg", answer: "Juan Manuel de Rosas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Daguerrotipo_de_Justo_Jos%C3%A9_de_Urquiza_%28recorte%29.jpg", answer: "Justo José de Urquiza" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Sarmiento.jpg", answer: "Domingo Faustino Sarmiento" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Bartolom%C3%A9_Mitre_01.jpg", answer: "Bartolomé Mitre" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Nicol%C3%A1s_Avellaneda_-_1910.JPG", answer: "Nicolás Avellaneda" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/RetratoROcaMuseo.jpg", answer: "Julio Argentino Roca" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Retrato_de_Carlos_Pellegrini.jpg", answer: "Carlos Pellegrini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/30/Hipolito_Yrigoyen_-_NAC.jpg", answer: "Hipólito Yrigoyen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Marcelo_T._de_Alvear%2C_ca._1915.jpg", answer: "Marcelo Torcuato de Alvear" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Presidente_Agust%C3%ADn_Pedro_Justo.png", answer: "Agustín Pedro Justo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Juan_Domingo_Per%C3%B3n_%28cropped%29.jpg", answer: "Juan Perón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Evita_color.jpg", answer: "Eva Perón" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Arturo_Frondizi.jpg", answer: "Arturo Frondizi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Illia_banda_presidencial.jpg", answer: "Arturo Umberto Illia" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Ra%C3%BAl_Alfons%C3%ADn_con_banda_presidencial_%28cropped%29.jpg", answer: "Raúl Alfonsín" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/14/Menem_con_banda_presidencial.jpg", answer: "Carlos Menem" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Fernando_de_la_R%C3%BAa_con_bast%C3%B3n_y_banda_de_presidente.jpg", answer: "Fernando de la Rúa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Inauguration_of_Javier_Milei_11243_%28cropped2%29.jpg", answer: "Eduardo Duhalde" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Presidente_Nestor_Kirchner_%28cropped%29.jpg", answer: "Néstor Kirchner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/22/Cristinakirchnermensaje2010.jpg", answer: "Cristina Fernández de Kirchner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Retrato_oficial_del_Presidente_Mauricio_Macri.jpg", answer: "Mauricio Macri" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Mensaje_de_fin_de_a%C3%B1o_del_Presidente_Alberto_Fern%C3%A1ndez_%28cropped%29.jpg", answer: "Alberto Fernández" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Javier_Milei_in_pull-aside_meeting_at_the_United_Nations_Headquarters_%283x4_cropped%29.jpg", answer: "Javier Milei" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Patricia_Bullrich_-_Retrato_Oficial_2024.png", answer: "Patricia Bullrich" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Sergio_Massa_-_Presentaci%C3%B3n_nueva_l%C3%ADnea_de_financiamiento_para_la_producci%C3%B3n_de_contenidos_audiovisuales_%28cropped2%29.jpg", answer: "Sergio Massa" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Horacio-Rodriguez-Larreta_%28cropped%29.jpg", answer: "Horacio Rodríguez Larreta" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8e/20260417_Barcelona_Reuni%C3%B3n_Petro_Kicillof_1_%28cropped%29.jpg", answer: "Axel Kicillof" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Victoria_Villarruel_Abril_2025_%28cropped%29.jpg", answer: "Victoria Villarruel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/MartinLousteau.jpg", answer: "Martín Lousteau" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/06/Elisa_Carrio.jpg", answer: "Elisa Carrió" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Conversa_com_Juan_Grabois%2C_Lisboa%2C_Mar._2023_%2852760468063%29_%28cropped%29.jpg", answer: "Juan Grabois" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/46/Myriam_Bregman.png", answer: "Myriam Bregman" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/XV_Reuni%C3%B3n_Institucional_de_la_Regi%C3%B3n_Centro_-_02_%28cropped%29.jpg", answer: "Juan Schiaretti" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Sesi%C3%B3n_13-06-2018_Diputado_Maximo_Kirchner_%28cropped%29.jpg", answer: "Máximo Kirchner" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Guillermo_Moreno_2010-06-14.jpg", answer: "Guillermo Moreno" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Ricardo_L%C3%B3pez_Murphy_HCDN.png", answer: "Ricardo López Murphy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Espertcomision_%28cropped%29.jpg", answer: "José Luis Espert" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Miguel_%C3%81ngel_Pichetto_en_2018.jpg", answer: "Miguel Ángel Pichetto" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/An%C3%ADbal_Fern%C3%A1ndez%2C_Security_Minister.jpg", answer: "Aníbal Fernández" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/51/Randazzo2_%28cropped%29.jpg", answer: "Florencio Randazzo" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/DanielScioli.jpg", answer: "Daniel Scioli" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/61/Felipe_Sol%C3%A1_2019.jpg", answer: "Felipe Solá" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Santoro54372.jpg", answer: "Leandro Santoro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/3840px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg", answer: "George Washington" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Abraham_Lincoln_1863_Portrait_%283x4_cropped%29.jpg", answer: "Abraham Lincoln" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Theodore_Roosevelt_by_the_Pach_Bros_%284x5_cropped%29.jpg", answer: "Theodore Roosevelt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/FDR-1944-Campaign-Portrait_%283x4_retouched%2C_cropped%29.jpg", answer: "Franklin D. Roosevelt" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg", answer: "John F. Kennedy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Richard_Nixon_presidential_portrait_%281%29.jpg", answer: "Richard Nixon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/16/Official_Portrait_of_President_Reagan_1981.jpg", answer: "Ronald Reagan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Bill_Clinton_%28cropped_4%29.jpg", answer: "Bill Clinton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/84/George-W-Bush_%28cropped_2%29.jpeg", answer: "George W. Bush" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg", answer: "Barack Obama" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg", answer: "Donald Trump" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg", answer: "Joe Biden" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/41/Kamala_Harris_Vice_Presidential_Portrait.jpg", answer: "Kamala Harris" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Former_United_States_Secretary_of_State_Hillary_Rodham_Clinton_at_the_U.S._Department_of_State_on_September_26%2C_2023_in_Washington%2C_D.C._14_%28cropped%29.jpg", answer: "Hillary Clinton" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Bernie_Sanders_February_2026_%28cropped%29.jpg", answer: "Bernie Sanders" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Alexandria_Ocasio-Cortez_Official_Portrait.jpg", answer: "Alexandria Ocasio-Cortez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sir_Winston_Churchill_-_19086236948_%28restored%29.jpg/3840px-Sir_Winston_Churchill_-_19086236948_%28restored%29.jpg", answer: "Winston Churchill" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/47/Margaret_Thatcher_stock_portrait_%282%29_%28cropped%29.jpg", answer: "Margaret Thatcher" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Tony_Blair_%282010%29_%283x4_cropped%29.jpg", answer: "Tony Blair" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/David_Cameron_Official_Portrait_2023_%28cropped%29.jpg", answer: "David Cameron" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Boris_Johnson_official_portrait_%28cropped%29.jpg", answer: "Boris Johnson" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/db/Official_portrait_of_Liz_Truss_%283x4_cropped_b%29.jpg", answer: "Liz Truss" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Portrait_of_Prime_Minister_Rishi_Sunak_%28cropped%29.jpg", answer: "Rishi Sunak" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Prime_Minister_Keir_Starmer_Portrait_%28cropped%29.jpg", answer: "Keir Starmer" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg", answer: "Napoleon" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/De_Gaulle-OWI_%28cropped%29_%28c%29%282%29.jpg", answer: "Charles de Gaulle" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/52/President_Fran%C3%A7ois_Mitterrand_in_1983_%28cropped%29.jpg", answer: "François Mitterrand" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Jacques_Chirac_%281997%29_%28cropped%29.jpg", answer: "Jacques Chirac" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Nicolas_Sarkozy_in_2010.jpg", answer: "Nicolas Sarkozy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Fran%C3%A7ois_Hollande_November_2015.jpg", answer: "François Hollande" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Emmanuel_Macron_2025_%28cropped%29.jpg", answer: "Emmanuel Macron" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Marine_Le_Pen_2025_%283x4_cropped%29.jpg", answer: "Marine Le Pen" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Otto_von_Bismarck_1885_%28cropped%29.jpg", answer: "Otto von Bismarck" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Hitler_portrait_crop_%28cropped%29%282%29.jpg", answer: "Adolf Hitler" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Angela_Merkel_2019_cropped.jpg", answer: "Angela Merkel" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/27/Olaf_Scholz_September_2024.jpg", answer: "Olaf Scholz" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Mussolini_mezzobusto.jpg", answer: "Benito Mussolini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Silvio_Berlusconi_1996.jpg", answer: "Silvio Berlusconi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Mario_Draghi%2C_2022.03.07_%28cropped%29.jpg", answer: "Mario Draghi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/96/Giorgia_Meloni_Official_2024_%28cropped%29.jpg", answer: "Giorgia Meloni" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/09/Francisco_Franco_posed_portrait_photograph.jpg", answer: "Francisco Franco" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Adolfo_Su%C3%A1rez_1979c_%28cropped%29.jpg", answer: "Adolfo Suárez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Aznar_Kyriakides_2020_%28cropped%29.jpg", answer: "José María Aznar" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/12/Jos%C3%A9_Luis_Rodr%C3%ADguez_Zapatero_en_el_III_Foro_Mundial_de_Derechos_Humanos_2023_%28cropped%29.jpg", answer: "José Luis Rodríguez Zapatero" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Mariano_Rajoy_in_2018.jpg", answer: "Mariano Rajoy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Pedro_S%C3%A1nchez_in_2026.jpg", answer: "Pedro Sánchez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Lenin_in_1920_%28cropped%29.jpg", answer: "Vladimir Lenin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/08/StalinCropped1943.jpg", answer: "Joseph Stalin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/1956_Press_Photo_Communist_Party_Secretary_Nikita_S._Khrushchev_in_Moscow_%28cropped%29.jpg", answer: "Nikita Khrushchev" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/57/RIAN_archive_850809_General_Secretary_of_the_CPSU_CC_M._Gorbachev_%28crop%29.jpg", answer: "Mikhail Gorbachev" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Boris_Yeltsin_%283x4_cropped%29.jpg", answer: "Boris Yeltsin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/65/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9F%D1%83%D1%82%D0%B8%D0%BD_%2808-03-2024%29_%28cropped%29_%28higher_res%29_2.jpg", answer: "Vladimir Putin" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Dmitry_Medvedev_%282026-02-06%29.jpg", answer: "Dmitry Medvedev" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Mao_Zedong_1950_Portrait_%283x4_cropped%29%282%29.jpg", answer: "Mao Zedong" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Deng_Xiaoping_at_the_arrival_ceremony_for_the_Vice_Premier_of_China_%28cropped%29.jpg", answer: "Deng Xiaoping" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Xi_Jinping_meets_Putin_May_2026.jpg", answer: "Xi Jinping" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Kim_Il-sung_in_1950.jpg", answer: "Kim Il Sung" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Kim_Jong-il_on_August_24%2C_2011.jpg", answer: "Kim Jong Il" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Kim_Jong-un_and_Vladimir_Putin_%282023-09-13%29_12_%28cropped_2%29.jpg", answer: "Kim Jong Un" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Fidel_Castro_1950s.jpg", answer: "Fidel Castro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Raul-castro-2015_%28cropped%29%282%29.jpg", answer: "Raúl Castro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Hugo_Ch%C3%A1vez_official_portrait_%28cropped%29.jpg", answer: "Hugo Chávez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Nicol%C3%A1s_Maduro_in_2023_%28cropped%29.jpg", answer: "Nicolás Maduro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/50/Getulio_Vargas_%281930%29.jpg", answer: "Getúlio Vargas" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Juscelino_Kubitschek_in_1956.jpg", answer: "Juscelino Kubitschek" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/4/46/Fernando_Henrique_Cardoso_%281999%29.jpg", answer: "Fernando Henrique Cardoso" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_%28ombros%29_denoise_%28cropped%29.jpg", answer: "Luiz Inácio Lula da Silva" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Dilma_Rousseff_-_foto_oficial_2011-01-09.jpg", answer: "Dilma Rousseff" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Jair_Bolsonaro_2019_Portrait_%283x4_cropped%29.jpg", answer: "Jair Bolsonaro" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Augusto_Pinochet_official_portrait_%283x4_cropped_b%29.jpg", answer: "Augusto Pinochet" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Salvador_Allende_Gossens-.jpg", answer: "Salvador Allende" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Retrato_Oficial_Presidente_Boric_Font.jpg", answer: "Gabriel Boric" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Mujica.jpg", answer: "José Mujica" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Foto_Oficial_Presidente_Luis_Lacalle_Pou_%28cropped%29.jpg", answer: "Luis Lacalle Pou" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/1/10/Photograph_of_Benito_Juarez.jpg", answer: "Benito Juárez" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Andr%C3%A9s_Manuel_L%C3%B3pez_Obrador_junio_2024.jpg", answer: "Andrés Manuel López Obrador" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Claudia_Sheinbaum_in_2025_%283x4_cropped%29.jpg", answer: "Claudia Sheinbaum" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Pierre_Trudeau_%281975%29.jpg", answer: "Pierre Trudeau" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Prime_Minister_Trudeau%27s_message_on_Christmas_2023_%280m29s%29_%28cropped%29.jpg", answer: "Justin Trudeau" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg", answer: "Mahatma Gandhi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/97/Nehru_in_the_Netherlands%2C_1957.jpg", answer: "Jawaharlal Nehru" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Indira_Gandhi_official_portrait.png", answer: "Indira Gandhi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/The_official_portrait_of_Shri_Narendra_Modi%2C_the_Prime_Minister_of_the_Republic_of_India.jpg", answer: "Narendra Modi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg", answer: "Nelson Mandela" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/David_Ben-Gurion_%28D597-087%29.jpg", answer: "David Ben-Gurion" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Benjamin_Netanyahu%2C_February_2023.jpg", answer: "Benjamin Netanyahu" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Volodymyr_Zelensky_2022_official_portrait_%28cropped%29.jpg", answer: "Volodymyr Zelenskyy" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Portret_van_de_Turkse_leider_Mustafa_Kemal_Ataturk_%28Atat%C3%BCrk_Kemal_Pascha%29_%281881-1938%29_in_westers%2C_SFA003017837.jpg", answer: "Mustafa Kemal Atatürk" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Turkish_President_Recep_Tayyip_Erdo%C4%9Fan_in_January_2024_%28cropped%29.jpg", answer: "Recep Tayyip Erdoğan" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Ruhollah_Khomeini_by_Jamaran_1.jpg", answer: "Ruhollah Khomeini" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/2/26/Ali_Khamenei_Nowruz_message_official_portrait_1397_02_%283_x_4_cropped%29.jpg", answer: "Ali Khamenei" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Saddam_Hussein_in_1998.png", answer: "Saddam Hussein" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Muammar_al-Gaddafi_at_the_AU_summit.jpg", answer: "Muammar Gaddafi" },
    { image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Bashar_al-Assad_%282018-05-17%29_02_%28cropped%29.jpg", answer: "Bashar al-Assad" },
];
