import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const numerosRomanos: CategoryQuestion[] = [
  { text: "I", answer: "1" },
  { text: "II", answer: "2" },
  { text: "III", answer: "3" },
  { text: "IV", answer: "4" },
  { text: "V", answer: "5" },
  { text: "VI", answer: "6" },
  { text: "VII", answer: "7" },
  { text: "VIII", answer: "8" },
  { text: "IX", answer: "9" },
  { text: "X", answer: "10" },
  { text: "XI", answer: "11" },
  { text: "XII", answer: "12" },
  { text: "XIII", answer: "13" },
  { text: "XIV", answer: "14" },
  { text: "XV", answer: "15" },
  { text: "XVI", answer: "16" },
  { text: "XVII", answer: "17" },
  { text: "XVIII", answer: "18" },
  { text: "XIX", answer: "19" },
  { text: "XX", answer: "20" },
  { text: "XXI", answer: "21" },
  { text: "XXII", answer: "22" },
  { text: "XXIII", answer: "23" },
  { text: "XXIV", answer: "24" },
  { text: "XXV", answer: "25" },
  { text: "XXVI", answer: "26" },
  { text: "XXVII", answer: "27" },
  { text: "XXVIII", answer: "28" },
  { text: "XXIX", answer: "29" },
  { text: "XXX", answer: "30" },

  { text: "XXXV", answer: "35" },
  { text: "XL", answer: "40" },
  { text: "XLII", answer: "42" },
  { text: "XLV", answer: "45" },
  { text: "XLIX", answer: "49" },
  { text: "L", answer: "50" },
  { text: "LI", answer: "51" },
  { text: "LV", answer: "55" },
  { text: "LX", answer: "60" },
  { text: "LXV", answer: "65" },
  { text: "LXX", answer: "70" },
  { text: "LXXV", answer: "75" },
  { text: "LXXX", answer: "80" },
  { text: "LXXXV", answer: "85" },
  { text: "XC", answer: "90" },
  { text: "XCV", answer: "95" },
  { text: "XCIX", answer: "99" },
  { text: "C", answer: "100" },

  { text: "CI", answer: "101" },
  { text: "CV", answer: "105" },
  { text: "CX", answer: "110" },
  { text: "CXV", answer: "115" },
  { text: "CXX", answer: "120" },
  { text: "CXXV", answer: "125" },
  { text: "CXXX", answer: "130" },
  { text: "CXL", answer: "140" },
  { text: "CL", answer: "150" },
  { text: "CLX", answer: "160" },
  { text: "CLXX", answer: "170" },
  { text: "CLXXX", answer: "180" },
  { text: "CXC", answer: "190" },
  { text: "CC", answer: "200" },
  { text: "CCL", answer: "250" },
  { text: "CCC", answer: "300" },
  { text: "CCCL", answer: "350" },
  { text: "CD", answer: "400" },
  { text: "CDL", answer: "450" },
  { text: "D", answer: "500" },

  { text: "DI", answer: "501" },
  { text: "DV", answer: "505" },
  { text: "DX", answer: "510" },
  { text: "DXXV", answer: "525" },
  { text: "DL", answer: "550" },
  { text: "DLXXV", answer: "575" },
  { text: "DC", answer: "600" },
  { text: "DCL", answer: "650" },
  { text: "DCC", answer: "700" },
  { text: "DCCL", answer: "750" },
  { text: "DCCC", answer: "800" },
  { text: "DCCCL", answer: "850" },
  { text: "CM", answer: "900" },
  { text: "CML", answer: "950" },
  { text: "CMXC", answer: "990" },
  { text: "CMXCIX", answer: "999" },

  { text: "M", answer: "1000" },
  { text: "MI", answer: "1001" },
  { text: "MX", answer: "1010" },
  { text: "MXXV", answer: "1025" },
  { text: "ML", answer: "1050" },
  { text: "MC", answer: "1100" },
  { text: "MCC", answer: "1200" },
  { text: "MCD", answer: "1400" },
  { text: "MD", answer: "1500" },
  { text: "MDC", answer: "1600" },
  { text: "MDCLXVI", answer: "1666" },
  { text: "MDCCLXXVI", answer: "1776" },
  { text: "MCM", answer: "1900" },
  { text: "MCMXLV", answer: "1945" },
  { text: "MCMLXXXIV", answer: "1984" },
  { text: "MCMXC", answer: "1990" },
  { text: "MCMXCIX", answer: "1999" },
  { text: "MM", answer: "2000" },
  { text: "MMX", answer: "2010" },
  { text: "MMXXV", answer: "2025" },
  // Decimal → Romano
{ text: "1 → romano", answer: "I" },
{ text: "2 → romano", answer: "II" },
{ text: "3 → romano", answer: "III" },
{ text: "4 → romano", answer: "IV" },
{ text: "5 → romano", answer: "V" },
{ text: "6 → romano", answer: "VI" },
{ text: "7 → romano", answer: "VII" },
{ text: "8 → romano", answer: "VIII" },
{ text: "9 → romano", answer: "IX" },
{ text: "10 → romano", answer: "X" },
{ text: "11 → romano", answer: "XI" },
{ text: "12 → romano", answer: "XII" },
{ text: "13 → romano", answer: "XIII" },
{ text: "14 → romano", answer: "XIV" },
{ text: "15 → romano", answer: "XV" },
{ text: "16 → romano", answer: "XVI" },
{ text: "17 → romano", answer: "XVII" },
{ text: "18 → romano", answer: "XVIII" },
{ text: "19 → romano", answer: "XIX" },
{ text: "20 → romano", answer: "XX" },
{ text: "21 → romano", answer: "XXI" },
{ text: "22 → romano", answer: "XXII" },
{ text: "23 → romano", answer: "XXIII" },
{ text: "24 → romano", answer: "XXIV" },
{ text: "25 → romano", answer: "XXV" },
{ text: "26 → romano", answer: "XXVI" },
{ text: "27 → romano", answer: "XXVII" },
{ text: "28 → romano", answer: "XXVIII" },
{ text: "29 → romano", answer: "XXIX" },
{ text: "30 → romano", answer: "XXX" },

{ text: "31 → romano", answer: "XXXI" },
{ text: "32 → romano", answer: "XXXII" },
{ text: "33 → romano", answer: "XXXIII" },
{ text: "34 → romano", answer: "XXXIV" },
{ text: "35 → romano", answer: "XXXV" },
{ text: "36 → romano", answer: "XXXVI" },
{ text: "37 → romano", answer: "XXXVII" },
{ text: "38 → romano", answer: "XXXVIII" },
{ text: "39 → romano", answer: "XXXIX" },

{ text: "40 → romano", answer: "XL" },
{ text: "41 → romano", answer: "XLI" },
{ text: "42 → romano", answer: "XLII" },
{ text: "43 → romano", answer: "XLIII" },
{ text: "44 → romano", answer: "XLIV" },
{ text: "45 → romano", answer: "XLV" },
{ text: "46 → romano", answer: "XLVI" },
{ text: "47 → romano", answer: "XLVII" },
{ text: "48 → romano", answer: "XLVIII" },
{ text: "49 → romano", answer: "XLIX" },

{ text: "50 → romano", answer: "L" },
{ text: "55 → romano", answer: "LV" },
{ text: "60 → romano", answer: "LX" },
{ text: "65 → romano", answer: "LXV" },
{ text: "70 → romano", answer: "LXX" },
{ text: "75 → romano", answer: "LXXV" },
{ text: "80 → romano", answer: "LXXX" },
{ text: "85 → romano", answer: "LXXXV" },
{ text: "90 → romano", answer: "XC" },
{ text: "95 → romano", answer: "XCV" },
{ text: "99 → romano", answer: "XCIX" },

{ text: "100 → romano", answer: "C" },
{ text: "101 → romano", answer: "CI" },
{ text: "105 → romano", answer: "CV" },
{ text: "110 → romano", answer: "CX" },
{ text: "115 → romano", answer: "CXV" },
{ text: "120 → romano", answer: "CXX" },
{ text: "125 → romano", answer: "CXXV" },
{ text: "130 → romano", answer: "CXXX" },
{ text: "140 → romano", answer: "CXL" },
{ text: "150 → romano", answer: "CL" },
{ text: "160 → romano", answer: "CLX" },
{ text: "170 → romano", answer: "CLXX" },
{ text: "180 → romano", answer: "CLXXX" },
{ text: "190 → romano", answer: "CXC" },
{ text: "199 → romano", answer: "CXCIX" },
{ text: "200 → romano", answer: "CC" },
{ text: "250 → romano", answer: "CCL" },
{ text: "300 → romano", answer: "CCC" },
{ text: "350 → romano", answer: "CCCL" },
{ text: "400 → romano", answer: "CD" },
{ text: "450 → romano", answer: "CDL" },
{ text: "500 → romano", answer: "D" },

{ text: "501 → romano", answer: "DI" },
{ text: "505 → romano", answer: "DV" },
{ text: "510 → romano", answer: "DX" },
{ text: "525 → romano", answer: "DXXV" },
{ text: "550 → romano", answer: "DL" },
{ text: "575 → romano", answer: "DLXXV" },
{ text: "600 → romano", answer: "DC" },
{ text: "650 → romano", answer: "DCL" },
{ text: "700 → romano", answer: "DCC" },
{ text: "750 → romano", answer: "DCCL" },
{ text: "800 → romano", answer: "DCCC" },
{ text: "850 → romano", answer: "DCCCL" },
{ text: "900 → romano", answer: "CM" },
{ text: "950 → romano", answer: "CML" },
{ text: "990 → romano", answer: "CMXC" },
{ text: "999 → romano", answer: "CMXCIX" },

{ text: "1000 → romano", answer: "M" },
{ text: "1001 → romano", answer: "MI" },
{ text: "1005 → romano", answer: "MV" },
{ text: "1010 → romano", answer: "MX" },
{ text: "1025 → romano", answer: "MXXV" },
{ text: "1050 → romano", answer: "ML" },
{ text: "1100 → romano", answer: "MC" },
{ text: "1200 → romano", answer: "MCC" },
{ text: "1300 → romano", answer: "MCCC" },
{ text: "1400 → romano", answer: "MCD" },
{ text: "1500 → romano", answer: "MD" },
{ text: "1600 → romano", answer: "MDC" },
{ text: "1666 → romano", answer: "MDCLXVI" },
{ text: "1700 → romano", answer: "MDCC" },
{ text: "1776 → romano", answer: "MDCCLXXVI" },
{ text: "1800 → romano", answer: "MDCCC" },
{ text: "1900 → romano", answer: "MCM" },
{ text: "1945 → romano", answer: "MCMXLV" },
{ text: "1950 → romano", answer: "MCML" },
{ text: "1984 → romano", answer: "MCMLXXXIV" },
{ text: "1990 → romano", answer: "MCMXC" },
{ text: "1999 → romano", answer: "MCMXCIX" },
{ text: "2000 → romano", answer: "MM" },
{ text: "2001 → romano", answer: "MMI" },
{ text: "2010 → romano", answer: "MMX" },
{ text: "2020 → romano", answer: "MMXX" },
{ text: "2024 → romano", answer: "MMXXIV" },
{ text: "2025 → romano", answer: "MMXXV" },
{ text: "2030 → romano", answer: "MMXXX" },
{ text: "2050 → romano", answer: "MML" }
];