import type { CategoryQuestion } from "../DATA/categoriesAgrupment";

export const series: CategoryQuestion[] = [
    { image: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", answer: "Breaking Bad", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/og2jKploGHYnCz68vV1nRSEE0xV.jpg", answer: "Better Call Saul", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg", answer: "Game of Thrones", possibleAnswers: ["Juego de Tronos"] },
    { image: "https://image.tmdb.org/t/p/original/577eXC8wFQT0eUrJcgznSiFPRmk.jpg", answer: "House of the Dragon", possibleAnswers: ["La Casa del Dragón"] },
    { image: "https://image.tmdb.org/t/p/original/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg", answer: "The Sopranos", possibleAnswers: ["Los Soprano"] },
    { image: "https://image.tmdb.org/t/p/original/layPSOJGckJv3PXZDIVluMq69mn.jpg", answer: "The Wire", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/A5lVyejMsP5G7rAJBwU9ug3Wzou.jpg", answer: "Mad Men", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bcdUYUFk8GdpZJPiSAas9UeocLH.jpg", answer: "Succession", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/acevLdSl5I2MK5RYAm7gwAndt1w.jpg", answer: "The Last of Us", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg", answer: "Chernobyl", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/v8YFr8BbU9qsO8PYIulzTeM6Qk.jpg", answer: "True Detective", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/yUOFocKDW7MCC5isx4FK8A68QFp.jpg", answer: "Lost", possibleAnswers: ["Perdidos"] },
    { image: "https://image.tmdb.org/t/p/original/n3Brk7roueE9HOwVmYlJx5j462g.jpg", answer: "Prison Break", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/aSGSxGMTP893DPMCvMl9AdnEICE.jpg", answer: "Dexter", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/rAOjnEFTuNysY7bot8zonhImGMh.jpg", answer: "The Walking Dead", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/r0Q6eeN9L1ORL9QsV0Sg8ZV3vnv.jpg", answer: "House", possibleAnswers: ["Dr. House"] },
    { image: "https://image.tmdb.org/t/p/original/jP0Rhj9OTPDAwQlHQwOLFDdeE8t.jpg", answer: "Grey's Anatomy", possibleAnswers: ["Anatomía de Grey"] },
    { image: "https://image.tmdb.org/t/p/original/b1t0mS2MAqnMdh5opqi94rlDEjn.jpg", answer: "ER", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/f3cin9kOz4nOrlYEMxGFQhv4bdN.jpg", answer: "The Good Doctor", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8rvLEmdI4gLrMO1rLqbNdnNcPFE.jpg", answer: "Sherlock", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/dzq83RHwQcnP6WGJ6YkenIqeaa5.jpg", answer: "Peaky Blinders", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/13kblIK8DnxMurcRDkeyy2sGR7v.jpg", answer: "Vikings", possibleAnswers: ["Vikingos"] },
    { image: "https://image.tmdb.org/t/p/original/8VXhcrl5z2I1zEU9X3pkkNrZlD.jpg", answer: "The Crown", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg", answer: "The Mandalorian", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/quCeAmVQHfsdcYkicbxZWVauCVb.jpg", answer: "Andor", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg", answer: "The Boys", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/tldMHeR7UnihV5ffrxxM8cDhbtT.jpg", answer: "Gen V", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/9qrroces8C6R9aKr08hACNPVXdZ.jpg", answer: "INVINCIBLE", possibleAnswers: ["Invencible"] },
    { image: "https://image.tmdb.org/t/p/original/rX5hvSRB2k4YoIvRg6Zky52rWk0.jpg", answer: "Westworld", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3jDXL4Xvj3AzDOF6UH1xeyHW8MH.jpg", answer: "Dark", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/dg3OindVAGZBjlT3xYKqIAdukPL.jpg", answer: "Black Mirror", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4ceSkV7cmCon4exXaZwuhW1VdE0.jpg", answer: "Mr. Robot", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lpDVJuIro21gtMj9iXMFKHuroZN.jpg", answer: "MINDHUNTER", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/y9ekzkPFmWSqUU3Kj0wHmYUM8qu.jpg", answer: "Narcos", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/64jEzC7YeKEpnn1YwjCGRo9ZvOX.jpg", answer: "Narcos: Mexico", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/aatG9iVAUL7U7OyFEmupESpOrD2.jpg", answer: "Ozark", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg", answer: "Money Heist", possibleAnswers: ["La Casa de Papel"] },
    { image: "https://image.tmdb.org/t/p/original/2meX1nMdScFOoV4370rqHWKmXhY.jpg", answer: "Squid Game", possibleAnswers: ["El juego del calamar"] },
    { image: "https://image.tmdb.org/t/p/original/QZaPkNUvhdcKONuO2fXuqtcQRo.jpg", answer: "Alice in Borderland", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg", answer: "The Queen's Gambit", possibleAnswers: ["Gambito de Dama"] },
    { image: "https://image.tmdb.org/t/p/original/ixgFmf1X59PUZam2qbAfskx2gQr.jpg", answer: "Severance", possibleAnswers: ["Separación"] },
    { image: "https://image.tmdb.org/t/p/original/uTWhbLc7Bj4qNSdW3ZvZKL8cOHv.jpg", answer: "Silo", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/coaPCIqQBPUZsOnJcWZxhaORcDT.jpg", answer: "Fallout", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg", answer: "Wednesday", possibleAnswers: ["Merlina"] },
    { image: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg", answer: "Stranger Things", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg", answer: "Euphoria", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/6umsRLI7t0ydFwCl0JNEIO0q2LH.jpg", answer: "Bridgerton", possibleAnswers: ["Los Bridgerton"] },
    { image: "https://image.tmdb.org/t/p/original/aJtG4txtmiRHwAAqENQHZvBs6kY.jpg", answer: "The Bear", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg", answer: "The Office", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/frwl2zBNAl5ZbFDJGoJv0mYo0rF.jpg", answer: "Parks and Recreation", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/9AeiA1XtP5sel2tAf9LaGeUjhDb.jpg", answer: "Brooklyn Nine-Nine", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg", answer: "Friends", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3f8aW6vcYRP6mTZdgXm83BiuB9t.jpg", answer: "How I Met Your Mother", possibleAnswers: ["Cómo conocí a tu madre"] },
    { image: "https://image.tmdb.org/t/p/original/rwYvhVv0vwbulMwxOfEsuAr1JrT.jpg", answer: "The Big Bang Theory", possibleAnswers: ["El Big Bang"] },
    { image: "https://image.tmdb.org/t/p/original/2pOmuq4nkWZzwZbOfZq7CyyQAsM.jpg", answer: "Two and a Half Men", possibleAnswers: ["Dos hombres y medio"] },
    { image: "https://image.tmdb.org/t/p/original/nO7EzksrBzlNpAg5rgv8HzaBIkx.jpg", answer: "Modern Family", possibleAnswers: ["Familia Moderna"] },
    { image: "https://image.tmdb.org/t/p/original/1xRfgONYmK3T6FSmbtcuo8eyxVt.jpg", answer: "Community", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/qCXY93t7QnKp6aWT1WKaQo0Qt5r.jpg", answer: "Arrested Development", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/uqTCaYBoSLT9MAdyQ9tU6QyCZ3A.jpg", answer: "It's Always Sunny in Philadelphia", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/tMRdEsMg9MyXAkcufK9YJEeIaNW.jpg", answer: "Seinfeld", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/4FqKFhF4BrNsrK3EdRpVJofVqCp.jpg", answer: "Frasier", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5U7NIuRK836GutAlo7TLPfmVtGW.jpg", answer: "Cheers", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/vcFW09U4834DyFOeRZpsx9x1D3S.jpg", answer: "Doctor Who", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/ywK4VrR7vL56mDGXDLMtFypwqA8.jpg", answer: "Star Trek", possibleAnswers: ["Viaje a las Estrellas"] },
    { image: "https://image.tmdb.org/t/p/original/qmliLoo6GVheM2FihatlAXxCKyF.jpg", answer: "Star Trek: The Next Generation", possibleAnswers: ["Star Trek: La Nueva Generación"] },
    { image: "https://image.tmdb.org/t/p/original/ePr0k72sypMpZYubz6w34dcW68Y.jpg", answer: "Star Trek: Discovery", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lodNd9ITHf32q8ybHArHqoWOcXf.jpg", answer: "Star Trek: Picard", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/sEjNaoENrqIZONKNn1iLFB0Us9k.jpg", answer: "Battlestar Galactica", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/w00lfexrsOeR25dO4hsWhbcUnmD.jpg", answer: "The X-Files", possibleAnswers: ["Los Expedientes Secretos X"] },
    { image: "https://image.tmdb.org/t/p/original/eksjqZGaGUtSZJD6nWQPsqzDMn0.jpg", answer: "Fringe", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/j5w04XEuFv85N3RIovXBJIHxjSb.jpg", answer: "Twin Peaks", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lBmlLro9ZfY815ZXE5NKhYNxPRQ.jpg", answer: "Buffy the Vampire Slayer", possibleAnswers: ["Buffy la Cazavampiros"] },
    { image: "https://image.tmdb.org/t/p/original/ro0tlgnsco4SwbdAgmscLkSlMSL.jpg", answer: "Supernatural", possibleAnswers: ["Sobrenatural"] },
    { image: "https://image.tmdb.org/t/p/original/4wVq9ICc4MI2XcssrumpCOhKLpI.jpg", answer: "Smallville", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mAXOCbZzvmDa6PCh5dcIPOB51Qc.jpg", answer: "Lucifer", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/foGkPxpw9h8zln81j63mix5B7m8.jpg", answer: "The Witcher", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/2JcrP4gNhU3KMbdajoEi1OvDl1Y.jpg", answer: "Merlin", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/jIArNHIekrCSVgdMbKPAXpPY03Y.jpg", answer: "The Simpsons", possibleAnswers: ["Los Simpson"] },
    { image: "https://image.tmdb.org/t/p/original/4xKG4S1IyLIglHbCYGJDsptgQNh.jpg", answer: "Futurama", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/l7wShoIdIUwaDIbsHno9pO5MZXT.jpg", answer: "Family Guy", possibleAnswers: ["Padre de familia"] },
    { image: "https://image.tmdb.org/t/p/original/iixxhk3ycXmFqBn616pAsC3lu53.jpg", answer: "American Dad!", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3UviYOlhn8EgXMBuiT6MnUuo1w9.jpg", answer: "South Park", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5BDNWWHweQL0q1fmTv7gmRXfnl4.jpg", answer: "Rick and Morty", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/qFYDJUIFh8zgEDy3EvnHwhgOl0S.jpg", answer: "BoJack Horseman", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg", answer: "Arcane", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/oCMZpwLBcb3dnRuzEKWNWrw1tHz.jpg", answer: "BLUE EYE SAMURAI", possibleAnswers: ["Samurái de Ojos Azules"] },
    { image: "https://image.tmdb.org/t/p/original/nBrkOZyI75artyizuBFeya48KbO.jpg", answer: "Love, Death & Robots", possibleAnswers: ["Amor, Muerte y Robots"] },
    { image: "https://image.tmdb.org/t/p/original/xUB3xFMgsHgPmdWnUWkHTJ03vHa.jpg", answer: "Avatar: The Last Airbender", possibleAnswers: ["Avatar: La Leyenda de Aang"] },
    { image: "https://image.tmdb.org/t/p/original/hmrNfrUl3FFaymDj6Iw5oKQjIs2.jpg", answer: "The Legend of Korra", possibleAnswers: ["La Leyenda de Korra"] },
    { image: "https://image.tmdb.org/t/p/original/CrVAqxtdmvelqVcj8pVeQg7wNV.jpg", answer: "Samurai Jack", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/pe4B3OYBb7qYCdkAz7nKWordbls.jpg", answer: "Adventure Time", possibleAnswers: ["Hora de Aventura"] },
    { image: "https://image.tmdb.org/t/p/original/bhF63Jd90gRYyTHd4y5GCGA2vX6.jpg", answer: "Regular Show", possibleAnswers: ["Un Show Más"] },
    { image: "https://image.tmdb.org/t/p/original/gmO3aezFgDcrhcymhNSJLGZ3CT.jpg", answer: "The Amazing World of Gumball", possibleAnswers: ["El Increíble Mundo de Gumball"] },
    { image: "https://image.tmdb.org/t/p/original/e5YSF0Inv9eL77jv2WQtNOOB3Bg.jpg", answer: "Steven Universe", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/lhg7eA6CTOCL10QNVdKiyxkgPsL.jpg", answer: "Gravity Falls", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5MWFjQ3NuNtNeOE9FdrVLeNMNPs.jpg", answer: "Phineas and Ferb", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/eareuhgO6bQj2N0roSJ7ZxnUtAU.jpg", answer: "Ben 10", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/bIHCUqaapZdRjd2kzSDiwzYyrpC.jpg", answer: "Teen Titans Go!", possibleAnswers: ["Jóvenes Titanes en Acción"] },
    { image: "https://image.tmdb.org/t/p/original/cuGHiBCIS8cUbnsV1TecOg9Z9Nd.jpg", answer: "Scooby-Doo, Where Are You!", possibleAnswers: ["Scooby-Doo, ¿Dónde estás?"] },
    { image: "https://image.tmdb.org/t/p/original/h8tzpd1pqyKCu5V4lw3eUiO6L9Y.jpg", answer: "New Looney Tunes", possibleAnswers: ["Nuevas Looney Tunes"] },
    { image: "https://image.tmdb.org/t/p/original/utqCOvMmjjMTlXNZz6PHOzRM5QP.jpg", answer: "The Tom and Jerry Show", possibleAnswers: ["El Show de Tom y Jerry"] },
    { image: "https://image.tmdb.org/t/p/original/aasp5EmwclAQbwfGABWLTNLhjwB.jpg", answer: "SpongeBob SquarePants", possibleAnswers: ["Bob Esponja Pantalones Cuadrados"] },
    { image: "https://image.tmdb.org/t/p/original/rMKFsYeK3LPJGk9xqUHhGdqA4aB.jpg", answer: "The Fairly OddParents", possibleAnswers: ["Los Padrinos Mágicos"] },
    { image: "https://image.tmdb.org/t/p/original/gnK2nptRXra4RnKgGqAWFSqP5aG.jpg", answer: "The Powerpuff Girls", possibleAnswers: ["Las Chicas Superpoderosas"] },
    { image: "https://image.tmdb.org/t/p/original/ec04M36HKCokAsdJWqx18uKRzoP.jpg", answer: "Dexter's Laboratory", possibleAnswers: ["El Laboratorio de Dexter"] },
    { image: "https://image.tmdb.org/t/p/original/dugFpakDXxjDjEUloukNqAx3cjK.jpg", answer: "Courage the Cowardly Dog", possibleAnswers: ["Coraje, el Perro Cobarde"] },
    { image: "https://image.tmdb.org/t/p/original/iRbNLYmqlxbqkfCuAmHaFwZ9ocY.jpg", answer: "Ed, Edd n Eddy", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/ydf1CeiBLfdxiyNTpskM0802TKl.jpg", answer: "Dragon Ball Z", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/yJAOi2n0VYBEXdPI1NXv5FiOcBX.jpg", answer: "Dragon Ball Super", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5F0HVEgkgP99fEWDjPyikGt9jQi.jpg", answer: "Naruto", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/qD211Hb5XwFxrszzBBe5EUYJerh.jpg", answer: "ONE PIECE", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/o0NsbcIvsllg6CJX0FBFY8wWbsn.jpg", answer: "Bleach", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg", answer: "Attack on Titan", possibleAnswers: ["Ataque a los Titanes"] },
    { image: "https://image.tmdb.org/t/p/original/koBa94NxTaGe2FoDzlXMuJptsv0.jpg", answer: "Death Note", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg", answer: "Demon Slayer: Kimetsu no Yaiba", possibleAnswers: ["Kimetsu no Yaiba: Guardianes de la Noche"] },
    { image: "https://image.tmdb.org/t/p/original/lthkKBLe1rX6iThgVFg22O02sJw.jpg", answer: "JUJUTSU KAISEN", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/575sxZXNNulSlIz7DvtWH5r4lkC.jpg", answer: "Hunter x Hunter", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg", answer: "Fullmetal Alchemist: Brotherhood", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/mLKN1dsimKPiXCZ48KED0X8a02t.jpg", answer: "JoJo's Bizarre Adventure", possibleAnswers: ["Las Bizarras Aventuras de JoJo"] },
    { image: "https://image.tmdb.org/t/p/original/lysUnU6V0VfcthDbviuVlIqgHOR.jpg", answer: "SPY x FAMILY", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg", answer: "Chainsaw Man", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/s0w8JbuNNxL1YgaHeDWih12C3jG.jpg", answer: "One-Punch Man", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/kP5duNJEbTfXpBs6CITsaZ88pQi.jpg", answer: "Mob Psycho 100", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/z2RumCOIZ6HO3oMvfINzZlFnPAw.jpg", answer: "Neon Genesis Evangelion", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/A4PHx94G7mvM3b8vsDJ5HEaQ6uv.jpg", answer: "Cowboy Bebop", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/60TX5aaN7DHZNOEbRdTkag2J5qs.jpg", answer: "Pokémon", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/xsEMAdrDprq3Ldre56Rm0zqbfCA.jpg", answer: "Digimon Adventure:", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/8jgvqyz76ydAwLrntGn3jTaYr7S.jpg", answer: "Yu-Gi-Oh! Zexal", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/sNCpbcCcRadDBMTh6An1dBMakqr.jpg", answer: "Sailor Moon", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/xqi7xzgzed2TyVuoXBmm6neYGee.jpg", answer: "Saint Seiya", possibleAnswers: ["Los Caballeros del Zodiaco"] },
    { image: "https://image.tmdb.org/t/p/original/dSvRkislUYBu8jWpqRpUsfNFNcr.jpg", answer: "Captain Tsubasa", possibleAnswers: ["Súper Campeones"] },
    { image: "https://image.tmdb.org/t/p/original/89BPrKS6BoktBPTfWcHMQrFNo8s.jpg", answer: "Mickey Mouse Clubhouse", possibleAnswers: ["La Casa de Mickey Mouse"] },
    { image: "https://image.tmdb.org/t/p/original/tNi2aJPdCKfielGYzIi3IKxStz9.jpg", answer: "Sesame Street", possibleAnswers: ["Plaza Sésamo"] },
    { image: "https://image.tmdb.org/t/p/original/9UyPl2zR9dckpnmBWP6Xz4E6P3G.jpg", answer: "The Muppet Show", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/wIe1HL7oMNwyltsqqx2sCPwNl4w.jpg", answer: "Thomas & Friends", possibleAnswers: ["Thomas y sus Amigos"] },
    { image: "https://image.tmdb.org/t/p/original/2Ne8sYfnnRVl9BaghudN8bSkMnW.jpg", answer: "Teletubbies", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/ea2Bw6064VpAE7FsLFBlSIb6Qcr.jpg", answer: "Barney & Friends", possibleAnswers: ["Barney y sus Amigos"] },
    { image: "https://image.tmdb.org/t/p/original/fnyS6gOv9tTjhHPl4A1aKEDgWEG.jpg", answer: "Peppa Pig", possibleAnswers: [] },
    { image: "https://image.tmdb.org/t/p/original/7OrV2aAH5Yp7hA9zCCvUloLvZtl.jpg", answer: "PAW Patrol", possibleAnswers: ["Patrulla Canina"] },
    { image: "https://image.tmdb.org/t/p/original/g88VMPtog8sl8riaIRtz4U80dMK.jpg", answer: "Bluey", possibleAnswers: [] },
];
